#ifndef QT_3D_INPUT_C_QVECTOR_H
#define QT_3D_INPUT_C_QVECTOR_H

#include "qt_3d_input_c_global.h"

extern "C" {

QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_append_l(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, const QVector< Qt3DInput::QAbstractActionInput* >* l);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_append_t(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, Qt3DInput::QAbstractActionInput* const * t);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractActionInput* const * qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_at(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractActionInput** qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_back(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractActionInput* const * qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_back_const(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_capacity(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_clear(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractActionInput* const * qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_constData(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractActionInput* const * qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_constFirst(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractActionInput* const * qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_constLast(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_constructor_no_args(QVector< Qt3DInput::QAbstractActionInput* >* output);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_constructor_size(int size, QVector< Qt3DInput::QAbstractActionInput* >* output);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_constructor_size_t(int size, Qt3DInput::QAbstractActionInput* const * t, QVector< Qt3DInput::QAbstractActionInput* >* output);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_constructor_v(const QVector< Qt3DInput::QAbstractActionInput* >* v, QVector< Qt3DInput::QAbstractActionInput* >* output);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_contains(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, Qt3DInput::QAbstractActionInput* const * t);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_count_no_args(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_count_t(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, Qt3DInput::QAbstractActionInput* const * t);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractActionInput** qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_data(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractActionInput* const * qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_data_const(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_destructor(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_empty(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_endsWith(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, Qt3DInput::QAbstractActionInput* const * t);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAbstractActionInput* >* qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_fill_t(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, Qt3DInput::QAbstractActionInput* const * t);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAbstractActionInput* >* qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_fill_t_size(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, Qt3DInput::QAbstractActionInput* const * t, int size);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractActionInput** qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_first(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractActionInput* const * qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_first_const(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractActionInput** qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_front(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractActionInput* const * qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_front_const(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_indexOf_t(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, Qt3DInput::QAbstractActionInput* const * t);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_indexOf_t_from(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, Qt3DInput::QAbstractActionInput* const * t, int from);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_insert_i_n_t(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, int i, int n, Qt3DInput::QAbstractActionInput* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_insert_i_t(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, int i, Qt3DInput::QAbstractActionInput* const * t);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_isEmpty(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractActionInput** qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_last(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_lastIndexOf_t(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, Qt3DInput::QAbstractActionInput* const * t);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_lastIndexOf_t_from(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, Qt3DInput::QAbstractActionInput* const * t, int from);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractActionInput* const * qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_last_const(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_length(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_mid_to_output_pos(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, int pos, QVector< Qt3DInput::QAbstractActionInput* >* output);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_mid_to_output_pos_len(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, int pos, int len, QVector< Qt3DInput::QAbstractActionInput* >* output);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_move(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, int from, int to);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAbstractActionInput* >* qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_operator_add_assign_l(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, const QVector< Qt3DInput::QAbstractActionInput* >* l);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAbstractActionInput* >* qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_operator_add_assign_t(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, Qt3DInput::QAbstractActionInput* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_operator_add_to_output(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, const QVector< Qt3DInput::QAbstractActionInput* >* l, QVector< Qt3DInput::QAbstractActionInput* >* output);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAbstractActionInput* >* qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_operator_assign(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, const QVector< Qt3DInput::QAbstractActionInput* >* v);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_operator_eq(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, const QVector< Qt3DInput::QAbstractActionInput* >* v);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractActionInput** qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_operator_index(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractActionInput* const * qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_operator_index_const(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_operator_neq(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, const QVector< Qt3DInput::QAbstractActionInput* >* v);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAbstractActionInput* >* qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_operator_shl_l(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, const QVector< Qt3DInput::QAbstractActionInput* >* l);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAbstractActionInput* >* qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_operator_shl_t(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, Qt3DInput::QAbstractActionInput* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_pop_back(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_pop_front(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_prepend(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, Qt3DInput::QAbstractActionInput* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_push_back(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, Qt3DInput::QAbstractActionInput* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_push_front(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, Qt3DInput::QAbstractActionInput* const * t);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_removeAll(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, Qt3DInput::QAbstractActionInput* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_removeAt(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_removeFirst(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_removeLast(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_removeOne(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, Qt3DInput::QAbstractActionInput* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_remove_i(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_remove_i_n(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, int i, int n);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_replace(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, int i, Qt3DInput::QAbstractActionInput* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_reserve(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, int size);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_resize(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, int size);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_size(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_squeeze(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_startsWith(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, Qt3DInput::QAbstractActionInput* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_swap(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, QVector< Qt3DInput::QAbstractActionInput* >* other);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractActionInput* qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_takeAt(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractActionInput* qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_takeFirst(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractActionInput* qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_takeLast(QVector< Qt3DInput::QAbstractActionInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractActionInput* qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_value_i(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractActionInput* qt_3d_input_c_QVector_Qt3DInput_QAbstractActionInput_ptr_value_i_defaultValue(const QVector< Qt3DInput::QAbstractActionInput* >* this_ptr, int i, Qt3DInput::QAbstractActionInput* const * defaultValue);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_append_l(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, const QVector< Qt3DInput::QAbstractAxisInput* >* l);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_append_t(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, Qt3DInput::QAbstractAxisInput* const * t);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractAxisInput* const * qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_at(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractAxisInput** qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_back(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractAxisInput* const * qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_back_const(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_capacity(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_clear(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractAxisInput* const * qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_constData(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractAxisInput* const * qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_constFirst(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractAxisInput* const * qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_constLast(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_constructor_no_args(QVector< Qt3DInput::QAbstractAxisInput* >* output);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_constructor_size(int size, QVector< Qt3DInput::QAbstractAxisInput* >* output);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_constructor_size_t(int size, Qt3DInput::QAbstractAxisInput* const * t, QVector< Qt3DInput::QAbstractAxisInput* >* output);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_constructor_v(const QVector< Qt3DInput::QAbstractAxisInput* >* v, QVector< Qt3DInput::QAbstractAxisInput* >* output);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_contains(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, Qt3DInput::QAbstractAxisInput* const * t);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_count_no_args(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_count_t(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, Qt3DInput::QAbstractAxisInput* const * t);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractAxisInput** qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_data(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractAxisInput* const * qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_data_const(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_destructor(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_empty(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_endsWith(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, Qt3DInput::QAbstractAxisInput* const * t);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAbstractAxisInput* >* qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_fill_t(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, Qt3DInput::QAbstractAxisInput* const * t);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAbstractAxisInput* >* qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_fill_t_size(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, Qt3DInput::QAbstractAxisInput* const * t, int size);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractAxisInput** qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_first(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractAxisInput* const * qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_first_const(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractAxisInput** qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_front(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractAxisInput* const * qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_front_const(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_indexOf_t(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, Qt3DInput::QAbstractAxisInput* const * t);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_indexOf_t_from(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, Qt3DInput::QAbstractAxisInput* const * t, int from);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_insert_i_n_t(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, int i, int n, Qt3DInput::QAbstractAxisInput* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_insert_i_t(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, int i, Qt3DInput::QAbstractAxisInput* const * t);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_isEmpty(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractAxisInput** qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_last(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_lastIndexOf_t(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, Qt3DInput::QAbstractAxisInput* const * t);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_lastIndexOf_t_from(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, Qt3DInput::QAbstractAxisInput* const * t, int from);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractAxisInput* const * qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_last_const(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_length(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_mid_to_output_pos(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, int pos, QVector< Qt3DInput::QAbstractAxisInput* >* output);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_mid_to_output_pos_len(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, int pos, int len, QVector< Qt3DInput::QAbstractAxisInput* >* output);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_move(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, int from, int to);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAbstractAxisInput* >* qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_operator_add_assign_l(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, const QVector< Qt3DInput::QAbstractAxisInput* >* l);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAbstractAxisInput* >* qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_operator_add_assign_t(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, Qt3DInput::QAbstractAxisInput* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_operator_add_to_output(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, const QVector< Qt3DInput::QAbstractAxisInput* >* l, QVector< Qt3DInput::QAbstractAxisInput* >* output);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAbstractAxisInput* >* qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_operator_assign(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, const QVector< Qt3DInput::QAbstractAxisInput* >* v);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_operator_eq(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, const QVector< Qt3DInput::QAbstractAxisInput* >* v);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractAxisInput** qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_operator_index(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractAxisInput* const * qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_operator_index_const(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_operator_neq(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, const QVector< Qt3DInput::QAbstractAxisInput* >* v);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAbstractAxisInput* >* qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_operator_shl_l(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, const QVector< Qt3DInput::QAbstractAxisInput* >* l);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAbstractAxisInput* >* qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_operator_shl_t(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, Qt3DInput::QAbstractAxisInput* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_pop_back(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_pop_front(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_prepend(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, Qt3DInput::QAbstractAxisInput* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_push_back(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, Qt3DInput::QAbstractAxisInput* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_push_front(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, Qt3DInput::QAbstractAxisInput* const * t);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_removeAll(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, Qt3DInput::QAbstractAxisInput* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_removeAt(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_removeFirst(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_removeLast(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_removeOne(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, Qt3DInput::QAbstractAxisInput* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_remove_i(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_remove_i_n(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, int i, int n);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_replace(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, int i, Qt3DInput::QAbstractAxisInput* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_reserve(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, int size);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_resize(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, int size);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_size(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_squeeze(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_startsWith(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, Qt3DInput::QAbstractAxisInput* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_swap(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, QVector< Qt3DInput::QAbstractAxisInput* >* other);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractAxisInput* qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_takeAt(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractAxisInput* qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_takeFirst(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractAxisInput* qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_takeLast(QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractAxisInput* qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_value_i(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAbstractAxisInput* qt_3d_input_c_QVector_Qt3DInput_QAbstractAxisInput_ptr_value_i_defaultValue(const QVector< Qt3DInput::QAbstractAxisInput* >* this_ptr, int i, Qt3DInput::QAbstractAxisInput* const * defaultValue);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_append_l(QVector< Qt3DInput::QAction* >* this_ptr, const QVector< Qt3DInput::QAction* >* l);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_append_t(QVector< Qt3DInput::QAction* >* this_ptr, Qt3DInput::QAction* const * t);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAction* const * qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_at(const QVector< Qt3DInput::QAction* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAction** qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_back(QVector< Qt3DInput::QAction* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAction* const * qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_back_const(const QVector< Qt3DInput::QAction* >* this_ptr);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_capacity(const QVector< Qt3DInput::QAction* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_clear(QVector< Qt3DInput::QAction* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAction* const * qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_constData(const QVector< Qt3DInput::QAction* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAction* const * qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_constFirst(const QVector< Qt3DInput::QAction* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAction* const * qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_constLast(const QVector< Qt3DInput::QAction* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_constructor_no_args(QVector< Qt3DInput::QAction* >* output);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_constructor_size(int size, QVector< Qt3DInput::QAction* >* output);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_constructor_size_t(int size, Qt3DInput::QAction* const * t, QVector< Qt3DInput::QAction* >* output);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_constructor_v(const QVector< Qt3DInput::QAction* >* v, QVector< Qt3DInput::QAction* >* output);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_contains(const QVector< Qt3DInput::QAction* >* this_ptr, Qt3DInput::QAction* const * t);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_count_no_args(const QVector< Qt3DInput::QAction* >* this_ptr);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_count_t(const QVector< Qt3DInput::QAction* >* this_ptr, Qt3DInput::QAction* const * t);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAction** qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_data(QVector< Qt3DInput::QAction* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAction* const * qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_data_const(const QVector< Qt3DInput::QAction* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_destructor(QVector< Qt3DInput::QAction* >* this_ptr);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_empty(const QVector< Qt3DInput::QAction* >* this_ptr);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_endsWith(const QVector< Qt3DInput::QAction* >* this_ptr, Qt3DInput::QAction* const * t);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAction* >* qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_fill_t(QVector< Qt3DInput::QAction* >* this_ptr, Qt3DInput::QAction* const * t);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAction* >* qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_fill_t_size(QVector< Qt3DInput::QAction* >* this_ptr, Qt3DInput::QAction* const * t, int size);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAction** qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_first(QVector< Qt3DInput::QAction* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAction* const * qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_first_const(const QVector< Qt3DInput::QAction* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAction** qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_front(QVector< Qt3DInput::QAction* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAction* const * qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_front_const(const QVector< Qt3DInput::QAction* >* this_ptr);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_indexOf_t(const QVector< Qt3DInput::QAction* >* this_ptr, Qt3DInput::QAction* const * t);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_indexOf_t_from(const QVector< Qt3DInput::QAction* >* this_ptr, Qt3DInput::QAction* const * t, int from);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_insert_i_n_t(QVector< Qt3DInput::QAction* >* this_ptr, int i, int n, Qt3DInput::QAction* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_insert_i_t(QVector< Qt3DInput::QAction* >* this_ptr, int i, Qt3DInput::QAction* const * t);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_isEmpty(const QVector< Qt3DInput::QAction* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAction** qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_last(QVector< Qt3DInput::QAction* >* this_ptr);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_lastIndexOf_t(const QVector< Qt3DInput::QAction* >* this_ptr, Qt3DInput::QAction* const * t);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_lastIndexOf_t_from(const QVector< Qt3DInput::QAction* >* this_ptr, Qt3DInput::QAction* const * t, int from);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAction* const * qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_last_const(const QVector< Qt3DInput::QAction* >* this_ptr);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_length(const QVector< Qt3DInput::QAction* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_mid_to_output_pos(const QVector< Qt3DInput::QAction* >* this_ptr, int pos, QVector< Qt3DInput::QAction* >* output);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_mid_to_output_pos_len(const QVector< Qt3DInput::QAction* >* this_ptr, int pos, int len, QVector< Qt3DInput::QAction* >* output);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_move(QVector< Qt3DInput::QAction* >* this_ptr, int from, int to);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAction* >* qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_operator_add_assign_l(QVector< Qt3DInput::QAction* >* this_ptr, const QVector< Qt3DInput::QAction* >* l);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAction* >* qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_operator_add_assign_t(QVector< Qt3DInput::QAction* >* this_ptr, Qt3DInput::QAction* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_operator_add_to_output(const QVector< Qt3DInput::QAction* >* this_ptr, const QVector< Qt3DInput::QAction* >* l, QVector< Qt3DInput::QAction* >* output);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAction* >* qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_operator_assign(QVector< Qt3DInput::QAction* >* this_ptr, const QVector< Qt3DInput::QAction* >* v);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_operator_eq(const QVector< Qt3DInput::QAction* >* this_ptr, const QVector< Qt3DInput::QAction* >* v);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAction** qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_operator_index(QVector< Qt3DInput::QAction* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAction* const * qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_operator_index_const(const QVector< Qt3DInput::QAction* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_operator_neq(const QVector< Qt3DInput::QAction* >* this_ptr, const QVector< Qt3DInput::QAction* >* v);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAction* >* qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_operator_shl_l(QVector< Qt3DInput::QAction* >* this_ptr, const QVector< Qt3DInput::QAction* >* l);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAction* >* qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_operator_shl_t(QVector< Qt3DInput::QAction* >* this_ptr, Qt3DInput::QAction* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_pop_back(QVector< Qt3DInput::QAction* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_pop_front(QVector< Qt3DInput::QAction* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_prepend(QVector< Qt3DInput::QAction* >* this_ptr, Qt3DInput::QAction* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_push_back(QVector< Qt3DInput::QAction* >* this_ptr, Qt3DInput::QAction* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_push_front(QVector< Qt3DInput::QAction* >* this_ptr, Qt3DInput::QAction* const * t);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_removeAll(QVector< Qt3DInput::QAction* >* this_ptr, Qt3DInput::QAction* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_removeAt(QVector< Qt3DInput::QAction* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_removeFirst(QVector< Qt3DInput::QAction* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_removeLast(QVector< Qt3DInput::QAction* >* this_ptr);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_removeOne(QVector< Qt3DInput::QAction* >* this_ptr, Qt3DInput::QAction* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_remove_i(QVector< Qt3DInput::QAction* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_remove_i_n(QVector< Qt3DInput::QAction* >* this_ptr, int i, int n);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_replace(QVector< Qt3DInput::QAction* >* this_ptr, int i, Qt3DInput::QAction* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_reserve(QVector< Qt3DInput::QAction* >* this_ptr, int size);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_resize(QVector< Qt3DInput::QAction* >* this_ptr, int size);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_size(const QVector< Qt3DInput::QAction* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_squeeze(QVector< Qt3DInput::QAction* >* this_ptr);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_startsWith(const QVector< Qt3DInput::QAction* >* this_ptr, Qt3DInput::QAction* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_swap(QVector< Qt3DInput::QAction* >* this_ptr, QVector< Qt3DInput::QAction* >* other);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAction* qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_takeAt(QVector< Qt3DInput::QAction* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAction* qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_takeFirst(QVector< Qt3DInput::QAction* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAction* qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_takeLast(QVector< Qt3DInput::QAction* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAction* qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_value_i(const QVector< Qt3DInput::QAction* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAction* qt_3d_input_c_QVector_Qt3DInput_QAction_ptr_value_i_defaultValue(const QVector< Qt3DInput::QAction* >* this_ptr, int i, Qt3DInput::QAction* const * defaultValue);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_append_l(QVector< Qt3DInput::QAxisSetting* >* this_ptr, const QVector< Qt3DInput::QAxisSetting* >* l);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_append_t(QVector< Qt3DInput::QAxisSetting* >* this_ptr, Qt3DInput::QAxisSetting* const * t);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxisSetting* const * qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_at(const QVector< Qt3DInput::QAxisSetting* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxisSetting** qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_back(QVector< Qt3DInput::QAxisSetting* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxisSetting* const * qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_back_const(const QVector< Qt3DInput::QAxisSetting* >* this_ptr);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_capacity(const QVector< Qt3DInput::QAxisSetting* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_clear(QVector< Qt3DInput::QAxisSetting* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxisSetting* const * qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_constData(const QVector< Qt3DInput::QAxisSetting* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxisSetting* const * qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_constFirst(const QVector< Qt3DInput::QAxisSetting* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxisSetting* const * qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_constLast(const QVector< Qt3DInput::QAxisSetting* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_constructor_no_args(QVector< Qt3DInput::QAxisSetting* >* output);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_constructor_size(int size, QVector< Qt3DInput::QAxisSetting* >* output);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_constructor_size_t(int size, Qt3DInput::QAxisSetting* const * t, QVector< Qt3DInput::QAxisSetting* >* output);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_constructor_v(const QVector< Qt3DInput::QAxisSetting* >* v, QVector< Qt3DInput::QAxisSetting* >* output);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_contains(const QVector< Qt3DInput::QAxisSetting* >* this_ptr, Qt3DInput::QAxisSetting* const * t);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_count_no_args(const QVector< Qt3DInput::QAxisSetting* >* this_ptr);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_count_t(const QVector< Qt3DInput::QAxisSetting* >* this_ptr, Qt3DInput::QAxisSetting* const * t);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxisSetting** qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_data(QVector< Qt3DInput::QAxisSetting* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxisSetting* const * qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_data_const(const QVector< Qt3DInput::QAxisSetting* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_destructor(QVector< Qt3DInput::QAxisSetting* >* this_ptr);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_empty(const QVector< Qt3DInput::QAxisSetting* >* this_ptr);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_endsWith(const QVector< Qt3DInput::QAxisSetting* >* this_ptr, Qt3DInput::QAxisSetting* const * t);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAxisSetting* >* qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_fill_t(QVector< Qt3DInput::QAxisSetting* >* this_ptr, Qt3DInput::QAxisSetting* const * t);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAxisSetting* >* qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_fill_t_size(QVector< Qt3DInput::QAxisSetting* >* this_ptr, Qt3DInput::QAxisSetting* const * t, int size);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxisSetting** qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_first(QVector< Qt3DInput::QAxisSetting* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxisSetting* const * qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_first_const(const QVector< Qt3DInput::QAxisSetting* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxisSetting** qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_front(QVector< Qt3DInput::QAxisSetting* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxisSetting* const * qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_front_const(const QVector< Qt3DInput::QAxisSetting* >* this_ptr);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_indexOf_t(const QVector< Qt3DInput::QAxisSetting* >* this_ptr, Qt3DInput::QAxisSetting* const * t);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_indexOf_t_from(const QVector< Qt3DInput::QAxisSetting* >* this_ptr, Qt3DInput::QAxisSetting* const * t, int from);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_insert_i_n_t(QVector< Qt3DInput::QAxisSetting* >* this_ptr, int i, int n, Qt3DInput::QAxisSetting* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_insert_i_t(QVector< Qt3DInput::QAxisSetting* >* this_ptr, int i, Qt3DInput::QAxisSetting* const * t);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_isEmpty(const QVector< Qt3DInput::QAxisSetting* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxisSetting** qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_last(QVector< Qt3DInput::QAxisSetting* >* this_ptr);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_lastIndexOf_t(const QVector< Qt3DInput::QAxisSetting* >* this_ptr, Qt3DInput::QAxisSetting* const * t);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_lastIndexOf_t_from(const QVector< Qt3DInput::QAxisSetting* >* this_ptr, Qt3DInput::QAxisSetting* const * t, int from);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxisSetting* const * qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_last_const(const QVector< Qt3DInput::QAxisSetting* >* this_ptr);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_length(const QVector< Qt3DInput::QAxisSetting* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_mid_to_output_pos(const QVector< Qt3DInput::QAxisSetting* >* this_ptr, int pos, QVector< Qt3DInput::QAxisSetting* >* output);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_mid_to_output_pos_len(const QVector< Qt3DInput::QAxisSetting* >* this_ptr, int pos, int len, QVector< Qt3DInput::QAxisSetting* >* output);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_move(QVector< Qt3DInput::QAxisSetting* >* this_ptr, int from, int to);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAxisSetting* >* qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_operator_add_assign_l(QVector< Qt3DInput::QAxisSetting* >* this_ptr, const QVector< Qt3DInput::QAxisSetting* >* l);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAxisSetting* >* qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_operator_add_assign_t(QVector< Qt3DInput::QAxisSetting* >* this_ptr, Qt3DInput::QAxisSetting* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_operator_add_to_output(const QVector< Qt3DInput::QAxisSetting* >* this_ptr, const QVector< Qt3DInput::QAxisSetting* >* l, QVector< Qt3DInput::QAxisSetting* >* output);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAxisSetting* >* qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_operator_assign(QVector< Qt3DInput::QAxisSetting* >* this_ptr, const QVector< Qt3DInput::QAxisSetting* >* v);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_operator_eq(const QVector< Qt3DInput::QAxisSetting* >* this_ptr, const QVector< Qt3DInput::QAxisSetting* >* v);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxisSetting** qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_operator_index(QVector< Qt3DInput::QAxisSetting* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxisSetting* const * qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_operator_index_const(const QVector< Qt3DInput::QAxisSetting* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_operator_neq(const QVector< Qt3DInput::QAxisSetting* >* this_ptr, const QVector< Qt3DInput::QAxisSetting* >* v);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAxisSetting* >* qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_operator_shl_l(QVector< Qt3DInput::QAxisSetting* >* this_ptr, const QVector< Qt3DInput::QAxisSetting* >* l);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAxisSetting* >* qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_operator_shl_t(QVector< Qt3DInput::QAxisSetting* >* this_ptr, Qt3DInput::QAxisSetting* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_pop_back(QVector< Qt3DInput::QAxisSetting* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_pop_front(QVector< Qt3DInput::QAxisSetting* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_prepend(QVector< Qt3DInput::QAxisSetting* >* this_ptr, Qt3DInput::QAxisSetting* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_push_back(QVector< Qt3DInput::QAxisSetting* >* this_ptr, Qt3DInput::QAxisSetting* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_push_front(QVector< Qt3DInput::QAxisSetting* >* this_ptr, Qt3DInput::QAxisSetting* const * t);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_removeAll(QVector< Qt3DInput::QAxisSetting* >* this_ptr, Qt3DInput::QAxisSetting* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_removeAt(QVector< Qt3DInput::QAxisSetting* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_removeFirst(QVector< Qt3DInput::QAxisSetting* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_removeLast(QVector< Qt3DInput::QAxisSetting* >* this_ptr);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_removeOne(QVector< Qt3DInput::QAxisSetting* >* this_ptr, Qt3DInput::QAxisSetting* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_remove_i(QVector< Qt3DInput::QAxisSetting* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_remove_i_n(QVector< Qt3DInput::QAxisSetting* >* this_ptr, int i, int n);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_replace(QVector< Qt3DInput::QAxisSetting* >* this_ptr, int i, Qt3DInput::QAxisSetting* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_reserve(QVector< Qt3DInput::QAxisSetting* >* this_ptr, int size);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_resize(QVector< Qt3DInput::QAxisSetting* >* this_ptr, int size);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_size(const QVector< Qt3DInput::QAxisSetting* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_squeeze(QVector< Qt3DInput::QAxisSetting* >* this_ptr);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_startsWith(const QVector< Qt3DInput::QAxisSetting* >* this_ptr, Qt3DInput::QAxisSetting* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_swap(QVector< Qt3DInput::QAxisSetting* >* this_ptr, QVector< Qt3DInput::QAxisSetting* >* other);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxisSetting* qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_takeAt(QVector< Qt3DInput::QAxisSetting* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxisSetting* qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_takeFirst(QVector< Qt3DInput::QAxisSetting* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxisSetting* qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_takeLast(QVector< Qt3DInput::QAxisSetting* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxisSetting* qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_value_i(const QVector< Qt3DInput::QAxisSetting* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxisSetting* qt_3d_input_c_QVector_Qt3DInput_QAxisSetting_ptr_value_i_defaultValue(const QVector< Qt3DInput::QAxisSetting* >* this_ptr, int i, Qt3DInput::QAxisSetting* const * defaultValue);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_append_l(QVector< Qt3DInput::QAxis* >* this_ptr, const QVector< Qt3DInput::QAxis* >* l);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_append_t(QVector< Qt3DInput::QAxis* >* this_ptr, Qt3DInput::QAxis* const * t);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxis* const * qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_at(const QVector< Qt3DInput::QAxis* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxis** qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_back(QVector< Qt3DInput::QAxis* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxis* const * qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_back_const(const QVector< Qt3DInput::QAxis* >* this_ptr);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_capacity(const QVector< Qt3DInput::QAxis* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_clear(QVector< Qt3DInput::QAxis* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxis* const * qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_constData(const QVector< Qt3DInput::QAxis* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxis* const * qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_constFirst(const QVector< Qt3DInput::QAxis* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxis* const * qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_constLast(const QVector< Qt3DInput::QAxis* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_constructor_no_args(QVector< Qt3DInput::QAxis* >* output);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_constructor_size(int size, QVector< Qt3DInput::QAxis* >* output);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_constructor_size_t(int size, Qt3DInput::QAxis* const * t, QVector< Qt3DInput::QAxis* >* output);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_constructor_v(const QVector< Qt3DInput::QAxis* >* v, QVector< Qt3DInput::QAxis* >* output);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_contains(const QVector< Qt3DInput::QAxis* >* this_ptr, Qt3DInput::QAxis* const * t);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_count_no_args(const QVector< Qt3DInput::QAxis* >* this_ptr);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_count_t(const QVector< Qt3DInput::QAxis* >* this_ptr, Qt3DInput::QAxis* const * t);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxis** qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_data(QVector< Qt3DInput::QAxis* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxis* const * qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_data_const(const QVector< Qt3DInput::QAxis* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_destructor(QVector< Qt3DInput::QAxis* >* this_ptr);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_empty(const QVector< Qt3DInput::QAxis* >* this_ptr);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_endsWith(const QVector< Qt3DInput::QAxis* >* this_ptr, Qt3DInput::QAxis* const * t);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAxis* >* qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_fill_t(QVector< Qt3DInput::QAxis* >* this_ptr, Qt3DInput::QAxis* const * t);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAxis* >* qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_fill_t_size(QVector< Qt3DInput::QAxis* >* this_ptr, Qt3DInput::QAxis* const * t, int size);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxis** qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_first(QVector< Qt3DInput::QAxis* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxis* const * qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_first_const(const QVector< Qt3DInput::QAxis* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxis** qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_front(QVector< Qt3DInput::QAxis* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxis* const * qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_front_const(const QVector< Qt3DInput::QAxis* >* this_ptr);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_indexOf_t(const QVector< Qt3DInput::QAxis* >* this_ptr, Qt3DInput::QAxis* const * t);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_indexOf_t_from(const QVector< Qt3DInput::QAxis* >* this_ptr, Qt3DInput::QAxis* const * t, int from);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_insert_i_n_t(QVector< Qt3DInput::QAxis* >* this_ptr, int i, int n, Qt3DInput::QAxis* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_insert_i_t(QVector< Qt3DInput::QAxis* >* this_ptr, int i, Qt3DInput::QAxis* const * t);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_isEmpty(const QVector< Qt3DInput::QAxis* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxis** qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_last(QVector< Qt3DInput::QAxis* >* this_ptr);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_lastIndexOf_t(const QVector< Qt3DInput::QAxis* >* this_ptr, Qt3DInput::QAxis* const * t);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_lastIndexOf_t_from(const QVector< Qt3DInput::QAxis* >* this_ptr, Qt3DInput::QAxis* const * t, int from);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxis* const * qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_last_const(const QVector< Qt3DInput::QAxis* >* this_ptr);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_length(const QVector< Qt3DInput::QAxis* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_mid_to_output_pos(const QVector< Qt3DInput::QAxis* >* this_ptr, int pos, QVector< Qt3DInput::QAxis* >* output);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_mid_to_output_pos_len(const QVector< Qt3DInput::QAxis* >* this_ptr, int pos, int len, QVector< Qt3DInput::QAxis* >* output);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_move(QVector< Qt3DInput::QAxis* >* this_ptr, int from, int to);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAxis* >* qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_operator_add_assign_l(QVector< Qt3DInput::QAxis* >* this_ptr, const QVector< Qt3DInput::QAxis* >* l);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAxis* >* qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_operator_add_assign_t(QVector< Qt3DInput::QAxis* >* this_ptr, Qt3DInput::QAxis* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_operator_add_to_output(const QVector< Qt3DInput::QAxis* >* this_ptr, const QVector< Qt3DInput::QAxis* >* l, QVector< Qt3DInput::QAxis* >* output);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAxis* >* qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_operator_assign(QVector< Qt3DInput::QAxis* >* this_ptr, const QVector< Qt3DInput::QAxis* >* v);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_operator_eq(const QVector< Qt3DInput::QAxis* >* this_ptr, const QVector< Qt3DInput::QAxis* >* v);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxis** qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_operator_index(QVector< Qt3DInput::QAxis* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxis* const * qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_operator_index_const(const QVector< Qt3DInput::QAxis* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_operator_neq(const QVector< Qt3DInput::QAxis* >* this_ptr, const QVector< Qt3DInput::QAxis* >* v);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAxis* >* qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_operator_shl_l(QVector< Qt3DInput::QAxis* >* this_ptr, const QVector< Qt3DInput::QAxis* >* l);
QT_3D_INPUT_C_EXPORT QVector< Qt3DInput::QAxis* >* qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_operator_shl_t(QVector< Qt3DInput::QAxis* >* this_ptr, Qt3DInput::QAxis* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_pop_back(QVector< Qt3DInput::QAxis* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_pop_front(QVector< Qt3DInput::QAxis* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_prepend(QVector< Qt3DInput::QAxis* >* this_ptr, Qt3DInput::QAxis* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_push_back(QVector< Qt3DInput::QAxis* >* this_ptr, Qt3DInput::QAxis* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_push_front(QVector< Qt3DInput::QAxis* >* this_ptr, Qt3DInput::QAxis* const * t);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_removeAll(QVector< Qt3DInput::QAxis* >* this_ptr, Qt3DInput::QAxis* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_removeAt(QVector< Qt3DInput::QAxis* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_removeFirst(QVector< Qt3DInput::QAxis* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_removeLast(QVector< Qt3DInput::QAxis* >* this_ptr);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_removeOne(QVector< Qt3DInput::QAxis* >* this_ptr, Qt3DInput::QAxis* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_remove_i(QVector< Qt3DInput::QAxis* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_remove_i_n(QVector< Qt3DInput::QAxis* >* this_ptr, int i, int n);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_replace(QVector< Qt3DInput::QAxis* >* this_ptr, int i, Qt3DInput::QAxis* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_reserve(QVector< Qt3DInput::QAxis* >* this_ptr, int size);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_resize(QVector< Qt3DInput::QAxis* >* this_ptr, int size);
QT_3D_INPUT_C_EXPORT int qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_size(const QVector< Qt3DInput::QAxis* >* this_ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_squeeze(QVector< Qt3DInput::QAxis* >* this_ptr);
QT_3D_INPUT_C_EXPORT bool qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_startsWith(const QVector< Qt3DInput::QAxis* >* this_ptr, Qt3DInput::QAxis* const * t);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_swap(QVector< Qt3DInput::QAxis* >* this_ptr, QVector< Qt3DInput::QAxis* >* other);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxis* qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_takeAt(QVector< Qt3DInput::QAxis* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxis* qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_takeFirst(QVector< Qt3DInput::QAxis* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxis* qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_takeLast(QVector< Qt3DInput::QAxis* >* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxis* qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_value_i(const QVector< Qt3DInput::QAxis* >* this_ptr, int i);
QT_3D_INPUT_C_EXPORT Qt3DInput::QAxis* qt_3d_input_c_QVector_Qt3DInput_QAxis_ptr_value_i_defaultValue(const QVector< Qt3DInput::QAxis* >* this_ptr, int i, Qt3DInput::QAxis* const * defaultValue);

} // extern "C"

#endif // QT_3D_INPUT_C_QVECTOR_H
