#ifndef QT_3D_INPUT_C_H
#define QT_3D_INPUT_C_H

#include "qt_3d_input_c_QAbstractActionInput.h"
#include "qt_3d_input_c_QAbstractAxisInput.h"
#include "qt_3d_input_c_QAbstractPhysicalDevice.h"
#include "qt_3d_input_c_QAction.h"
#include "qt_3d_input_c_QActionInput.h"
#include "qt_3d_input_c_QAnalogAxisInput.h"
#include "qt_3d_input_c_QAxis.h"
#include "qt_3d_input_c_QAxisAccumulator.h"
#include "qt_3d_input_c_QAxisSetting.h"
#include "qt_3d_input_c_QButtonAxisInput.h"
#include "qt_3d_input_c_QInputAspect.h"
#include "qt_3d_input_c_QInputChord.h"
#include "qt_3d_input_c_QInputSequence.h"
#include "qt_3d_input_c_QInputSettings.h"
#include "qt_3d_input_c_QKeyEvent.h"
#include "qt_3d_input_c_QKeyboardDevice.h"
#include "qt_3d_input_c_QKeyboardHandler.h"
#include "qt_3d_input_c_QLogicalDevice.h"
#include "qt_3d_input_c_QMouseDevice.h"
#include "qt_3d_input_c_QMouseEvent.h"
#include "qt_3d_input_c_QMouseHandler.h"
#include "qt_3d_input_c_QPhysicalDeviceCreatedChange.h"
#include "qt_3d_input_c_QVector.h"
#include "qt_3d_input_c_slots.h"
#endif // QT_3D_INPUT_C_H
