#ifndef QT_3D_INPUT_C_QPHYSICALDEVICECREATEDCHANGE_H
#define QT_3D_INPUT_C_QPHYSICALDEVICECREATEDCHANGE_H

#include "qt_3d_input_c_global.h"

extern "C" {

QT_3D_INPUT_C_EXPORT Qt3DCore::QNodeCreatedChangeBase* qt_3d_input_c_QPhysicalDeviceCreatedChange_G_static_cast_Qt3DCore_QNodeCreatedChangeBase_ptr(Qt3DInput::QPhysicalDeviceCreatedChangeBase* ptr);
QT_3D_INPUT_C_EXPORT Qt3DCore::QSceneChange* qt_3d_input_c_QPhysicalDeviceCreatedChange_G_static_cast_Qt3DCore_QSceneChange_ptr(Qt3DInput::QPhysicalDeviceCreatedChangeBase* ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QPhysicalDeviceCreatedChangeBase* qt_3d_input_c_QPhysicalDeviceCreatedChange_G_static_cast_Qt3DInput_QPhysicalDeviceCreatedChangeBase_ptr_Qt3DCore_QNodeCreatedChangeBase(Qt3DCore::QNodeCreatedChangeBase* ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QPhysicalDeviceCreatedChangeBase* qt_3d_input_c_QPhysicalDeviceCreatedChange_G_static_cast_Qt3DInput_QPhysicalDeviceCreatedChangeBase_ptr_Qt3DCore_QSceneChange(Qt3DCore::QSceneChange* ptr);
QT_3D_INPUT_C_EXPORT void qt_3d_input_c_Qt3DInput_QPhysicalDeviceCreatedChangeBase_delete(Qt3DInput::QPhysicalDeviceCreatedChangeBase* this_ptr);
QT_3D_INPUT_C_EXPORT Qt3DInput::QPhysicalDeviceCreatedChangeBase* qt_3d_input_c_Qt3DInput_QPhysicalDeviceCreatedChangeBase_new(const Qt3DInput::QAbstractPhysicalDevice* device);

} // extern "C"

#endif // QT_3D_INPUT_C_QPHYSICALDEVICECREATEDCHANGE_H
