#ifndef QT_CORE_C_QMETAMETHOD_H
#define QT_CORE_C_QMETAMETHOD_H

#include "qt_core_c_global.h"

extern "C" {

QT_CORE_C_EXPORT QMetaMethod::Access qt_core_c_QMetaMethod_access(const QMetaMethod* this_ptr);
QT_CORE_C_EXPORT int qt_core_c_QMetaMethod_attributes(const QMetaMethod* this_ptr);
QT_CORE_C_EXPORT void qt_core_c_QMetaMethod_constructor(QMetaMethod* output);
QT_CORE_C_EXPORT void qt_core_c_QMetaMethod_destructor(QMetaMethod* this_ptr);
QT_CORE_C_EXPORT const QMetaObject* qt_core_c_QMetaMethod_enclosingMetaObject(const QMetaMethod* this_ptr);
QT_CORE_C_EXPORT void qt_core_c_QMetaMethod_getParameterTypes(const QMetaMethod* this_ptr, int* types);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invokeOnGadget_gadget(const QMetaMethod* this_ptr, void* gadget);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invokeOnGadget_gadget_returnValue(const QMetaMethod* this_ptr, void* gadget, const QGenericReturnArgument* returnValue);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invokeOnGadget_gadget_returnValue_val0(const QMetaMethod* this_ptr, void* gadget, const QGenericReturnArgument* returnValue, const QGenericArgument* val0);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invokeOnGadget_gadget_returnValue_val0_val1(const QMetaMethod* this_ptr, void* gadget, const QGenericReturnArgument* returnValue, const QGenericArgument* val0, const QGenericArgument* val1);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invokeOnGadget_gadget_returnValue_val0_val1_val2(const QMetaMethod* this_ptr, void* gadget, const QGenericReturnArgument* returnValue, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invokeOnGadget_gadget_returnValue_val0_val1_val2_val3(const QMetaMethod* this_ptr, void* gadget, const QGenericReturnArgument* returnValue, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invokeOnGadget_gadget_returnValue_val0_val1_val2_val3_val4(const QMetaMethod* this_ptr, void* gadget, const QGenericReturnArgument* returnValue, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invokeOnGadget_gadget_returnValue_val0_val1_val2_val3_val4_val5(const QMetaMethod* this_ptr, void* gadget, const QGenericReturnArgument* returnValue, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invokeOnGadget_gadget_returnValue_val0_val1_val2_val3_val4_val5_val6(const QMetaMethod* this_ptr, void* gadget, const QGenericReturnArgument* returnValue, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5, const QGenericArgument* val6);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invokeOnGadget_gadget_returnValue_val0_val1_val2_val3_val4_val5_val6_val7(const QMetaMethod* this_ptr, void* gadget, const QGenericReturnArgument* returnValue, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5, const QGenericArgument* val6, const QGenericArgument* val7);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invokeOnGadget_gadget_returnValue_val0_val1_val2_val3_val4_val5_val6_val7_val8(const QMetaMethod* this_ptr, void* gadget, const QGenericReturnArgument* returnValue, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5, const QGenericArgument* val6, const QGenericArgument* val7, const QGenericArgument* val8);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invokeOnGadget_gadget_returnValue_val0_val1_val2_val3_val4_val5_val6_val7_val8_val9(const QMetaMethod* this_ptr, void* gadget, const QGenericReturnArgument* returnValue, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5, const QGenericArgument* val6, const QGenericArgument* val7, const QGenericArgument* val8, const QGenericArgument* val9);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invokeOnGadget_gadget_val0(const QMetaMethod* this_ptr, void* gadget, const QGenericArgument* val0);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invokeOnGadget_gadget_val0_val1(const QMetaMethod* this_ptr, void* gadget, const QGenericArgument* val0, const QGenericArgument* val1);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invokeOnGadget_gadget_val0_val1_val2(const QMetaMethod* this_ptr, void* gadget, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invokeOnGadget_gadget_val0_val1_val2_val3(const QMetaMethod* this_ptr, void* gadget, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invokeOnGadget_gadget_val0_val1_val2_val3_val4(const QMetaMethod* this_ptr, void* gadget, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invokeOnGadget_gadget_val0_val1_val2_val3_val4_val5(const QMetaMethod* this_ptr, void* gadget, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invokeOnGadget_gadget_val0_val1_val2_val3_val4_val5_val6(const QMetaMethod* this_ptr, void* gadget, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5, const QGenericArgument* val6);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invokeOnGadget_gadget_val0_val1_val2_val3_val4_val5_val6_val7(const QMetaMethod* this_ptr, void* gadget, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5, const QGenericArgument* val6, const QGenericArgument* val7);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invokeOnGadget_gadget_val0_val1_val2_val3_val4_val5_val6_val7_val8(const QMetaMethod* this_ptr, void* gadget, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5, const QGenericArgument* val6, const QGenericArgument* val7, const QGenericArgument* val8);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invokeOnGadget_gadget_val0_val1_val2_val3_val4_val5_val6_val7_val8_val9(const QMetaMethod* this_ptr, void* gadget, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5, const QGenericArgument* val6, const QGenericArgument* val7, const QGenericArgument* val8, const QGenericArgument* val9);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object(const QMetaMethod* this_ptr, QObject* object);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_connectionType(const QMetaMethod* this_ptr, QObject* object, const Qt::ConnectionType* connectionType);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_connectionType_returnValue(const QMetaMethod* this_ptr, QObject* object, const Qt::ConnectionType* connectionType, const QGenericReturnArgument* returnValue);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_connectionType_returnValue_val0(const QMetaMethod* this_ptr, QObject* object, const Qt::ConnectionType* connectionType, const QGenericReturnArgument* returnValue, const QGenericArgument* val0);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_connectionType_returnValue_val0_val1(const QMetaMethod* this_ptr, QObject* object, const Qt::ConnectionType* connectionType, const QGenericReturnArgument* returnValue, const QGenericArgument* val0, const QGenericArgument* val1);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_connectionType_returnValue_val0_val1_val2(const QMetaMethod* this_ptr, QObject* object, const Qt::ConnectionType* connectionType, const QGenericReturnArgument* returnValue, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_connectionType_returnValue_val0_val1_val2_val3(const QMetaMethod* this_ptr, QObject* object, const Qt::ConnectionType* connectionType, const QGenericReturnArgument* returnValue, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_connectionType_returnValue_val0_val1_val2_val3_val4(const QMetaMethod* this_ptr, QObject* object, const Qt::ConnectionType* connectionType, const QGenericReturnArgument* returnValue, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_connectionType_returnValue_val0_val1_val2_val3_val4_val5(const QMetaMethod* this_ptr, QObject* object, const Qt::ConnectionType* connectionType, const QGenericReturnArgument* returnValue, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_connectionType_returnValue_val0_val1_val2_val3_val4_val5_val6(const QMetaMethod* this_ptr, QObject* object, const Qt::ConnectionType* connectionType, const QGenericReturnArgument* returnValue, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5, const QGenericArgument* val6);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_connectionType_returnValue_val0_val1_val2_val3_val4_val5_val6_val7(const QMetaMethod* this_ptr, QObject* object, const Qt::ConnectionType* connectionType, const QGenericReturnArgument* returnValue, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5, const QGenericArgument* val6, const QGenericArgument* val7);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_connectionType_returnValue_val0_val1_val2_val3_val4_val5_val6_val7_val8(const QMetaMethod* this_ptr, QObject* object, const Qt::ConnectionType* connectionType, const QGenericReturnArgument* returnValue, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5, const QGenericArgument* val6, const QGenericArgument* val7, const QGenericArgument* val8);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_connectionType_returnValue_val0_val1_val2_val3_val4_val5_val6_val7_val8_val9(const QMetaMethod* this_ptr, QObject* object, const Qt::ConnectionType* connectionType, const QGenericReturnArgument* returnValue, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5, const QGenericArgument* val6, const QGenericArgument* val7, const QGenericArgument* val8, const QGenericArgument* val9);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_connectionType_val0(const QMetaMethod* this_ptr, QObject* object, const Qt::ConnectionType* connectionType, const QGenericArgument* val0);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_connectionType_val0_val1(const QMetaMethod* this_ptr, QObject* object, const Qt::ConnectionType* connectionType, const QGenericArgument* val0, const QGenericArgument* val1);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_connectionType_val0_val1_val2(const QMetaMethod* this_ptr, QObject* object, const Qt::ConnectionType* connectionType, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_connectionType_val0_val1_val2_val3(const QMetaMethod* this_ptr, QObject* object, const Qt::ConnectionType* connectionType, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_connectionType_val0_val1_val2_val3_val4(const QMetaMethod* this_ptr, QObject* object, const Qt::ConnectionType* connectionType, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_connectionType_val0_val1_val2_val3_val4_val5(const QMetaMethod* this_ptr, QObject* object, const Qt::ConnectionType* connectionType, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_connectionType_val0_val1_val2_val3_val4_val5_val6(const QMetaMethod* this_ptr, QObject* object, const Qt::ConnectionType* connectionType, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5, const QGenericArgument* val6);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_connectionType_val0_val1_val2_val3_val4_val5_val6_val7(const QMetaMethod* this_ptr, QObject* object, const Qt::ConnectionType* connectionType, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5, const QGenericArgument* val6, const QGenericArgument* val7);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_connectionType_val0_val1_val2_val3_val4_val5_val6_val7_val8(const QMetaMethod* this_ptr, QObject* object, const Qt::ConnectionType* connectionType, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5, const QGenericArgument* val6, const QGenericArgument* val7, const QGenericArgument* val8);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_connectionType_val0_val1_val2_val3_val4_val5_val6_val7_val8_val9(const QMetaMethod* this_ptr, QObject* object, const Qt::ConnectionType* connectionType, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5, const QGenericArgument* val6, const QGenericArgument* val7, const QGenericArgument* val8, const QGenericArgument* val9);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_returnValue(const QMetaMethod* this_ptr, QObject* object, const QGenericReturnArgument* returnValue);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_returnValue_val0(const QMetaMethod* this_ptr, QObject* object, const QGenericReturnArgument* returnValue, const QGenericArgument* val0);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_returnValue_val0_val1(const QMetaMethod* this_ptr, QObject* object, const QGenericReturnArgument* returnValue, const QGenericArgument* val0, const QGenericArgument* val1);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_returnValue_val0_val1_val2(const QMetaMethod* this_ptr, QObject* object, const QGenericReturnArgument* returnValue, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_returnValue_val0_val1_val2_val3(const QMetaMethod* this_ptr, QObject* object, const QGenericReturnArgument* returnValue, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_returnValue_val0_val1_val2_val3_val4(const QMetaMethod* this_ptr, QObject* object, const QGenericReturnArgument* returnValue, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_returnValue_val0_val1_val2_val3_val4_val5(const QMetaMethod* this_ptr, QObject* object, const QGenericReturnArgument* returnValue, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_returnValue_val0_val1_val2_val3_val4_val5_val6(const QMetaMethod* this_ptr, QObject* object, const QGenericReturnArgument* returnValue, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5, const QGenericArgument* val6);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_returnValue_val0_val1_val2_val3_val4_val5_val6_val7(const QMetaMethod* this_ptr, QObject* object, const QGenericReturnArgument* returnValue, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5, const QGenericArgument* val6, const QGenericArgument* val7);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_returnValue_val0_val1_val2_val3_val4_val5_val6_val7_val8(const QMetaMethod* this_ptr, QObject* object, const QGenericReturnArgument* returnValue, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5, const QGenericArgument* val6, const QGenericArgument* val7, const QGenericArgument* val8);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_returnValue_val0_val1_val2_val3_val4_val5_val6_val7_val8_val9(const QMetaMethod* this_ptr, QObject* object, const QGenericReturnArgument* returnValue, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5, const QGenericArgument* val6, const QGenericArgument* val7, const QGenericArgument* val8, const QGenericArgument* val9);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_val0(const QMetaMethod* this_ptr, QObject* object, const QGenericArgument* val0);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_val0_val1(const QMetaMethod* this_ptr, QObject* object, const QGenericArgument* val0, const QGenericArgument* val1);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_val0_val1_val2(const QMetaMethod* this_ptr, QObject* object, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_val0_val1_val2_val3(const QMetaMethod* this_ptr, QObject* object, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_val0_val1_val2_val3_val4(const QMetaMethod* this_ptr, QObject* object, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_val0_val1_val2_val3_val4_val5(const QMetaMethod* this_ptr, QObject* object, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_val0_val1_val2_val3_val4_val5_val6(const QMetaMethod* this_ptr, QObject* object, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5, const QGenericArgument* val6);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_val0_val1_val2_val3_val4_val5_val6_val7(const QMetaMethod* this_ptr, QObject* object, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5, const QGenericArgument* val6, const QGenericArgument* val7);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_val0_val1_val2_val3_val4_val5_val6_val7_val8(const QMetaMethod* this_ptr, QObject* object, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5, const QGenericArgument* val6, const QGenericArgument* val7, const QGenericArgument* val8);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_invoke_object_val0_val1_val2_val3_val4_val5_val6_val7_val8_val9(const QMetaMethod* this_ptr, QObject* object, const QGenericArgument* val0, const QGenericArgument* val1, const QGenericArgument* val2, const QGenericArgument* val3, const QGenericArgument* val4, const QGenericArgument* val5, const QGenericArgument* val6, const QGenericArgument* val7, const QGenericArgument* val8, const QGenericArgument* val9);
QT_CORE_C_EXPORT bool qt_core_c_QMetaMethod_isValid(const QMetaMethod* this_ptr);
QT_CORE_C_EXPORT int qt_core_c_QMetaMethod_methodIndex(const QMetaMethod* this_ptr);
QT_CORE_C_EXPORT void qt_core_c_QMetaMethod_methodSignature_to_output(const QMetaMethod* this_ptr, QByteArray* output);
QT_CORE_C_EXPORT QMetaMethod::MethodType qt_core_c_QMetaMethod_methodType(const QMetaMethod* this_ptr);
QT_CORE_C_EXPORT void qt_core_c_QMetaMethod_name_to_output(const QMetaMethod* this_ptr, QByteArray* output);
QT_CORE_C_EXPORT int qt_core_c_QMetaMethod_parameterCount(const QMetaMethod* this_ptr);
QT_CORE_C_EXPORT void qt_core_c_QMetaMethod_parameterNames_to_output(const QMetaMethod* this_ptr, QList< QByteArray >* output);
QT_CORE_C_EXPORT int qt_core_c_QMetaMethod_parameterType(const QMetaMethod* this_ptr, int index);
QT_CORE_C_EXPORT void qt_core_c_QMetaMethod_parameterTypes_to_output(const QMetaMethod* this_ptr, QList< QByteArray >* output);
QT_CORE_C_EXPORT int qt_core_c_QMetaMethod_returnType(const QMetaMethod* this_ptr);
QT_CORE_C_EXPORT int qt_core_c_QMetaMethod_revision(const QMetaMethod* this_ptr);
QT_CORE_C_EXPORT const char* qt_core_c_QMetaMethod_tag(const QMetaMethod* this_ptr);
QT_CORE_C_EXPORT const char* qt_core_c_QMetaMethod_typeName(const QMetaMethod* this_ptr);

} // extern "C"

#endif // QT_CORE_C_QMETAMETHOD_H
