#ifndef QT_CORE_C_QPARALLELANIMATIONGROUP_H
#define QT_CORE_C_QPARALLELANIMATIONGROUP_H

#include "qt_core_c_global.h"

extern "C" {

QT_CORE_C_EXPORT QParallelAnimationGroup* qt_core_c_QParallelAnimationGroup_G_dynamic_cast_QParallelAnimationGroup_ptr_QAbstractAnimation(QAbstractAnimation* ptr);
QT_CORE_C_EXPORT QParallelAnimationGroup* qt_core_c_QParallelAnimationGroup_G_dynamic_cast_QParallelAnimationGroup_ptr_QAnimationGroup(QAnimationGroup* ptr);
QT_CORE_C_EXPORT QParallelAnimationGroup* qt_core_c_QParallelAnimationGroup_G_dynamic_cast_QParallelAnimationGroup_ptr_QObject(QObject* ptr);
QT_CORE_C_EXPORT QAbstractAnimation* qt_core_c_QParallelAnimationGroup_G_static_cast_QAbstractAnimation_ptr(QParallelAnimationGroup* ptr);
QT_CORE_C_EXPORT QAnimationGroup* qt_core_c_QParallelAnimationGroup_G_static_cast_QAnimationGroup_ptr(QParallelAnimationGroup* ptr);
QT_CORE_C_EXPORT QObject* qt_core_c_QParallelAnimationGroup_G_static_cast_QObject_ptr(QParallelAnimationGroup* ptr);
QT_CORE_C_EXPORT QParallelAnimationGroup* qt_core_c_QParallelAnimationGroup_G_static_cast_QParallelAnimationGroup_ptr_QAbstractAnimation(QAbstractAnimation* ptr);
QT_CORE_C_EXPORT QParallelAnimationGroup* qt_core_c_QParallelAnimationGroup_G_static_cast_QParallelAnimationGroup_ptr_QAnimationGroup(QAnimationGroup* ptr);
QT_CORE_C_EXPORT QParallelAnimationGroup* qt_core_c_QParallelAnimationGroup_G_static_cast_QParallelAnimationGroup_ptr_QObject(QObject* ptr);
QT_CORE_C_EXPORT void qt_core_c_QParallelAnimationGroup_delete(QParallelAnimationGroup* this_ptr);
QT_CORE_C_EXPORT int qt_core_c_QParallelAnimationGroup_duration(const QParallelAnimationGroup* this_ptr);
QT_CORE_C_EXPORT const QMetaObject* qt_core_c_QParallelAnimationGroup_metaObject(const QParallelAnimationGroup* this_ptr);
QT_CORE_C_EXPORT QParallelAnimationGroup* qt_core_c_QParallelAnimationGroup_new_no_args();
QT_CORE_C_EXPORT QParallelAnimationGroup* qt_core_c_QParallelAnimationGroup_new_parent(QObject* parent);
QT_CORE_C_EXPORT void qt_core_c_QParallelAnimationGroup_trUtf8_to_output(const char* s, const char* c, int n, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QParallelAnimationGroup_tr_to_output(const char* s, const char* c, int n, QString* output);

} // extern "C"

#endif // QT_CORE_C_QPARALLELANIMATIONGROUP_H
