#ifndef QT_CORE_C_QSTRINGREF_H
#define QT_CORE_C_QSTRINGREF_H

#include "qt_core_c_global.h"

extern "C" {

QT_CORE_C_EXPORT void qt_core_c_QStringRef_appendTo_to_output(const QStringRef* this_ptr, QString* string, QStringRef* output);
QT_CORE_C_EXPORT void qt_core_c_QStringRef_at_to_output(const QStringRef* this_ptr, int i, QChar* output);
QT_CORE_C_EXPORT const QChar* qt_core_c_QStringRef_begin(const QStringRef* this_ptr);
QT_CORE_C_EXPORT const QChar* qt_core_c_QStringRef_cbegin(const QStringRef* this_ptr);
QT_CORE_C_EXPORT const QChar* qt_core_c_QStringRef_cend(const QStringRef* this_ptr);
QT_CORE_C_EXPORT void qt_core_c_QStringRef_chop(QStringRef* this_ptr, int n);
QT_CORE_C_EXPORT void qt_core_c_QStringRef_clear(QStringRef* this_ptr);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_compare_QByteArray(const QStringRef* this_ptr, const QByteArray* s);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_compare_QByteArray_Qt_CaseSensitivity(const QStringRef* this_ptr, const QByteArray* s, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_compare_QLatin1String(const QStringRef* this_ptr, const QLatin1String* s);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_compare_QLatin1String_Qt_CaseSensitivity(const QStringRef* this_ptr, const QLatin1String* s, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_compare_QString(const QStringRef* this_ptr, const QString* s);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_compare_QStringRef(const QStringRef* this_ptr, const QStringRef* s);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_compare_QStringRef_QLatin1String(const QStringRef* s1, const QLatin1String* s2);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_compare_QStringRef_QLatin1String_Qt_CaseSensitivity(const QStringRef* s1, const QLatin1String* s2, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_compare_QStringRef_QString(const QStringRef* s1, const QString* s2);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_compare_QStringRef_QStringRef(const QStringRef* s1, const QStringRef* s2);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_compare_QStringRef_QStringRef_Qt_CaseSensitivity(const QStringRef* s1, const QStringRef* s2, const Qt::CaseSensitivity* arg3);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_compare_QStringRef_QString_Qt_CaseSensitivity(const QStringRef* s1, const QString* s2, const Qt::CaseSensitivity* arg3);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_compare_QStringRef_Qt_CaseSensitivity(const QStringRef* this_ptr, const QStringRef* s, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_compare_QString_Qt_CaseSensitivity(const QStringRef* this_ptr, const QString* s, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT const QChar* qt_core_c_QStringRef_constBegin(const QStringRef* this_ptr);
QT_CORE_C_EXPORT const QChar* qt_core_c_QStringRef_constData(const QStringRef* this_ptr);
QT_CORE_C_EXPORT const QChar* qt_core_c_QStringRef_constEnd(const QStringRef* this_ptr);
QT_CORE_C_EXPORT void qt_core_c_QStringRef_constructor_no_args(QStringRef* output);
QT_CORE_C_EXPORT void qt_core_c_QStringRef_constructor_other(const QStringRef* other, QStringRef* output);
QT_CORE_C_EXPORT void qt_core_c_QStringRef_constructor_string(const QString* string, QStringRef* output);
QT_CORE_C_EXPORT void qt_core_c_QStringRef_constructor_string_position_size(const QString* string, int position, int size, QStringRef* output);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_contains_QChar(const QStringRef* this_ptr, const QChar* ch);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_contains_QChar_Qt_CaseSensitivity(const QStringRef* this_ptr, const QChar* ch, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_contains_QLatin1String(const QStringRef* this_ptr, const QLatin1String* str);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_contains_QLatin1String_Qt_CaseSensitivity(const QStringRef* this_ptr, const QLatin1String* str, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_contains_QString(const QStringRef* this_ptr, const QString* str);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_contains_QStringRef(const QStringRef* this_ptr, const QStringRef* str);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_contains_QStringRef_Qt_CaseSensitivity(const QStringRef* this_ptr, const QStringRef* str, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_contains_QString_Qt_CaseSensitivity(const QStringRef* this_ptr, const QString* str, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_count_QChar(const QStringRef* this_ptr, const QChar* c);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_count_QChar_Qt_CaseSensitivity(const QStringRef* this_ptr, const QChar* c, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_count_QString(const QStringRef* this_ptr, const QString* s);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_count_QStringRef(const QStringRef* this_ptr, const QStringRef* s);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_count_QStringRef_Qt_CaseSensitivity(const QStringRef* this_ptr, const QStringRef* s, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_count_QString_Qt_CaseSensitivity(const QStringRef* this_ptr, const QString* s, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_count_no_args(const QStringRef* this_ptr);
QT_CORE_C_EXPORT const QChar* qt_core_c_QStringRef_data(const QStringRef* this_ptr);
QT_CORE_C_EXPORT void qt_core_c_QStringRef_destructor(QStringRef* this_ptr);
QT_CORE_C_EXPORT const QChar* qt_core_c_QStringRef_end(const QStringRef* this_ptr);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_endsWith_QChar(const QStringRef* this_ptr, const QChar* c);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_endsWith_QChar_Qt_CaseSensitivity(const QStringRef* this_ptr, const QChar* c, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_endsWith_QLatin1String(const QStringRef* this_ptr, const QLatin1String* s);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_endsWith_QLatin1String_Qt_CaseSensitivity(const QStringRef* this_ptr, const QLatin1String* s, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_endsWith_QString(const QStringRef* this_ptr, const QString* s);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_endsWith_QStringRef(const QStringRef* this_ptr, const QStringRef* c);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_endsWith_QStringRef_Qt_CaseSensitivity(const QStringRef* this_ptr, const QStringRef* c, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_endsWith_QString_Qt_CaseSensitivity(const QStringRef* this_ptr, const QString* s, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_indexOf_QChar(const QStringRef* this_ptr, const QChar* ch);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_indexOf_QChar_int(const QStringRef* this_ptr, const QChar* ch, int from);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_indexOf_QChar_int_Qt_CaseSensitivity(const QStringRef* this_ptr, const QChar* ch, int from, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_indexOf_QLatin1String(const QStringRef* this_ptr, const QLatin1String* str);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_indexOf_QLatin1String_int(const QStringRef* this_ptr, const QLatin1String* str, int from);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_indexOf_QLatin1String_int_Qt_CaseSensitivity(const QStringRef* this_ptr, const QLatin1String* str, int from, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_indexOf_QString(const QStringRef* this_ptr, const QString* str);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_indexOf_QStringRef(const QStringRef* this_ptr, const QStringRef* str);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_indexOf_QStringRef_int(const QStringRef* this_ptr, const QStringRef* str, int from);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_indexOf_QStringRef_int_Qt_CaseSensitivity(const QStringRef* this_ptr, const QStringRef* str, int from, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_indexOf_QString_int(const QStringRef* this_ptr, const QString* str, int from);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_indexOf_QString_int_Qt_CaseSensitivity(const QStringRef* this_ptr, const QString* str, int from, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_isEmpty(const QStringRef* this_ptr);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_isNull(const QStringRef* this_ptr);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_isRightToLeft(const QStringRef* this_ptr);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_lastIndexOf_QChar(const QStringRef* this_ptr, const QChar* ch);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_lastIndexOf_QChar_int(const QStringRef* this_ptr, const QChar* ch, int from);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_lastIndexOf_QChar_int_Qt_CaseSensitivity(const QStringRef* this_ptr, const QChar* ch, int from, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_lastIndexOf_QLatin1String(const QStringRef* this_ptr, const QLatin1String* str);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_lastIndexOf_QLatin1String_int(const QStringRef* this_ptr, const QLatin1String* str, int from);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_lastIndexOf_QLatin1String_int_Qt_CaseSensitivity(const QStringRef* this_ptr, const QLatin1String* str, int from, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_lastIndexOf_QString(const QStringRef* this_ptr, const QString* str);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_lastIndexOf_QStringRef(const QStringRef* this_ptr, const QStringRef* str);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_lastIndexOf_QStringRef_int(const QStringRef* this_ptr, const QStringRef* str, int from);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_lastIndexOf_QStringRef_int_Qt_CaseSensitivity(const QStringRef* this_ptr, const QStringRef* str, int from, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_lastIndexOf_QString_int(const QStringRef* this_ptr, const QString* str, int from);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_lastIndexOf_QString_int_Qt_CaseSensitivity(const QStringRef* this_ptr, const QString* str, int from, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT void qt_core_c_QStringRef_left_to_output(const QStringRef* this_ptr, int n, QStringRef* output);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_length(const QStringRef* this_ptr);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_localeAwareCompare_QString(const QStringRef* this_ptr, const QString* s);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_localeAwareCompare_QStringRef(const QStringRef* this_ptr, const QStringRef* s);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_localeAwareCompare_QStringRef_QString(const QStringRef* s1, const QString* s2);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_localeAwareCompare_QStringRef_QStringRef(const QStringRef* s1, const QStringRef* s2);
QT_CORE_C_EXPORT void qt_core_c_QStringRef_mid_to_output_pos(const QStringRef* this_ptr, int pos, QStringRef* output);
QT_CORE_C_EXPORT void qt_core_c_QStringRef_mid_to_output_pos_n(const QStringRef* this_ptr, int pos, int n, QStringRef* output);
QT_CORE_C_EXPORT QStringRef* qt_core_c_QStringRef_operator_assign_other(QStringRef* this_ptr, const QStringRef* other);
QT_CORE_C_EXPORT QStringRef* qt_core_c_QStringRef_operator_assign_string(QStringRef* this_ptr, const QString* string);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_operator_eq(const QStringRef* this_ptr, const char* s);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_operator_ge(const QStringRef* this_ptr, const char* s);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_operator_gt(const QStringRef* this_ptr, const char* s);
QT_CORE_C_EXPORT void qt_core_c_QStringRef_operator_index_to_output(const QStringRef* this_ptr, int i, QChar* output);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_operator_le(const QStringRef* this_ptr, const char* s);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_operator_lt(const QStringRef* this_ptr, const char* s);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_operator_neq(const QStringRef* this_ptr, const char* s);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_position(const QStringRef* this_ptr);
QT_CORE_C_EXPORT void qt_core_c_QStringRef_right_to_output(const QStringRef* this_ptr, int n, QStringRef* output);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_size(const QStringRef* this_ptr);
QT_CORE_C_EXPORT void qt_core_c_QStringRef_split_to_output_QChar(const QStringRef* this_ptr, const QChar* sep, QVector< QStringRef >* output);
QT_CORE_C_EXPORT void qt_core_c_QStringRef_split_to_output_QChar_QString_SplitBehavior(const QStringRef* this_ptr, const QChar* sep, const QString::SplitBehavior* behavior, QVector< QStringRef >* output);
QT_CORE_C_EXPORT void qt_core_c_QStringRef_split_to_output_QChar_QString_SplitBehavior_Qt_CaseSensitivity(const QStringRef* this_ptr, const QChar* sep, const QString::SplitBehavior* behavior, const Qt::CaseSensitivity* cs, QVector< QStringRef >* output);
QT_CORE_C_EXPORT void qt_core_c_QStringRef_split_to_output_QString(const QStringRef* this_ptr, const QString* sep, QVector< QStringRef >* output);
QT_CORE_C_EXPORT void qt_core_c_QStringRef_split_to_output_QString_QString_SplitBehavior(const QStringRef* this_ptr, const QString* sep, const QString::SplitBehavior* behavior, QVector< QStringRef >* output);
QT_CORE_C_EXPORT void qt_core_c_QStringRef_split_to_output_QString_QString_SplitBehavior_Qt_CaseSensitivity(const QStringRef* this_ptr, const QString* sep, const QString::SplitBehavior* behavior, const Qt::CaseSensitivity* cs, QVector< QStringRef >* output);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_startsWith_QChar(const QStringRef* this_ptr, const QChar* c);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_startsWith_QChar_Qt_CaseSensitivity(const QStringRef* this_ptr, const QChar* c, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_startsWith_QLatin1String(const QStringRef* this_ptr, const QLatin1String* s);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_startsWith_QLatin1String_Qt_CaseSensitivity(const QStringRef* this_ptr, const QLatin1String* s, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_startsWith_QString(const QStringRef* this_ptr, const QString* s);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_startsWith_QStringRef(const QStringRef* this_ptr, const QStringRef* c);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_startsWith_QStringRef_Qt_CaseSensitivity(const QStringRef* this_ptr, const QStringRef* c, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT bool qt_core_c_QStringRef_startsWith_QString_Qt_CaseSensitivity(const QStringRef* this_ptr, const QString* s, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT const QString* qt_core_c_QStringRef_string(const QStringRef* this_ptr);
QT_CORE_C_EXPORT double qt_core_c_QStringRef_toDouble_no_args(const QStringRef* this_ptr);
QT_CORE_C_EXPORT double qt_core_c_QStringRef_toDouble_ok(const QStringRef* this_ptr, bool* ok);
QT_CORE_C_EXPORT float qt_core_c_QStringRef_toFloat_no_args(const QStringRef* this_ptr);
QT_CORE_C_EXPORT float qt_core_c_QStringRef_toFloat_ok(const QStringRef* this_ptr, bool* ok);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_toInt_no_args(const QStringRef* this_ptr);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_toInt_ok(const QStringRef* this_ptr, bool* ok);
QT_CORE_C_EXPORT int qt_core_c_QStringRef_toInt_ok_base(const QStringRef* this_ptr, bool* ok, int base);
QT_CORE_C_EXPORT void qt_core_c_QStringRef_toLatin1_to_output(const QStringRef* this_ptr, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QStringRef_toLocal8Bit_to_output(const QStringRef* this_ptr, QByteArray* output);
QT_CORE_C_EXPORT qlonglong qt_core_c_QStringRef_toLongLong_no_args(const QStringRef* this_ptr);
QT_CORE_C_EXPORT qlonglong qt_core_c_QStringRef_toLongLong_ok(const QStringRef* this_ptr, bool* ok);
QT_CORE_C_EXPORT qlonglong qt_core_c_QStringRef_toLongLong_ok_base(const QStringRef* this_ptr, bool* ok, int base);
QT_CORE_C_EXPORT long qt_core_c_QStringRef_toLong_no_args(const QStringRef* this_ptr);
QT_CORE_C_EXPORT long qt_core_c_QStringRef_toLong_ok(const QStringRef* this_ptr, bool* ok);
QT_CORE_C_EXPORT long qt_core_c_QStringRef_toLong_ok_base(const QStringRef* this_ptr, bool* ok, int base);
QT_CORE_C_EXPORT short qt_core_c_QStringRef_toShort_no_args(const QStringRef* this_ptr);
QT_CORE_C_EXPORT short qt_core_c_QStringRef_toShort_ok(const QStringRef* this_ptr, bool* ok);
QT_CORE_C_EXPORT short qt_core_c_QStringRef_toShort_ok_base(const QStringRef* this_ptr, bool* ok, int base);
QT_CORE_C_EXPORT void qt_core_c_QStringRef_toString_to_output(const QStringRef* this_ptr, QString* output);
QT_CORE_C_EXPORT unsigned int qt_core_c_QStringRef_toUInt_no_args(const QStringRef* this_ptr);
QT_CORE_C_EXPORT unsigned int qt_core_c_QStringRef_toUInt_ok(const QStringRef* this_ptr, bool* ok);
QT_CORE_C_EXPORT unsigned int qt_core_c_QStringRef_toUInt_ok_base(const QStringRef* this_ptr, bool* ok, int base);
QT_CORE_C_EXPORT qulonglong qt_core_c_QStringRef_toULongLong_no_args(const QStringRef* this_ptr);
QT_CORE_C_EXPORT qulonglong qt_core_c_QStringRef_toULongLong_ok(const QStringRef* this_ptr, bool* ok);
QT_CORE_C_EXPORT qulonglong qt_core_c_QStringRef_toULongLong_ok_base(const QStringRef* this_ptr, bool* ok, int base);
QT_CORE_C_EXPORT unsigned long qt_core_c_QStringRef_toULong_no_args(const QStringRef* this_ptr);
QT_CORE_C_EXPORT unsigned long qt_core_c_QStringRef_toULong_ok(const QStringRef* this_ptr, bool* ok);
QT_CORE_C_EXPORT unsigned long qt_core_c_QStringRef_toULong_ok_base(const QStringRef* this_ptr, bool* ok, int base);
QT_CORE_C_EXPORT unsigned short qt_core_c_QStringRef_toUShort_no_args(const QStringRef* this_ptr);
QT_CORE_C_EXPORT unsigned short qt_core_c_QStringRef_toUShort_ok(const QStringRef* this_ptr, bool* ok);
QT_CORE_C_EXPORT unsigned short qt_core_c_QStringRef_toUShort_ok_base(const QStringRef* this_ptr, bool* ok, int base);
QT_CORE_C_EXPORT void qt_core_c_QStringRef_toUcs4_to_output(const QStringRef* this_ptr, QVector< unsigned int >* output);
QT_CORE_C_EXPORT void qt_core_c_QStringRef_toUtf8_to_output(const QStringRef* this_ptr, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QStringRef_trimmed_to_output(const QStringRef* this_ptr, QStringRef* output);
QT_CORE_C_EXPORT void qt_core_c_QStringRef_truncate(QStringRef* this_ptr, int pos);
QT_CORE_C_EXPORT const QChar* qt_core_c_QStringRef_unicode(const QStringRef* this_ptr);

} // extern "C"

#endif // QT_CORE_C_QSTRINGREF_H
