#ifndef QT_CORE_C_QURLTWOFLAGS_H
#define QT_CORE_C_QURLTWOFLAGS_H

#include "qt_core_c_global.h"

extern "C" {

QT_CORE_C_EXPORT void qt_core_c_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption_constructor_QFlags_QUrl_ComponentFormattingOption(unsigned int f, QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* output);
QT_CORE_C_EXPORT void qt_core_c_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption_constructor_QUrl_ComponentFormattingOption(QUrl::ComponentFormattingOption f, QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* output);
QT_CORE_C_EXPORT void qt_core_c_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption_constructor_QUrl_UrlFormattingOption(QUrl::UrlFormattingOption f, QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* output);
QT_CORE_C_EXPORT unsigned int qt_core_c_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption_convert_to_QFlags_QUrl_ComponentFormattingOption(const QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* this_ptr);
QT_CORE_C_EXPORT int qt_core_c_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption_convert_to_int(const QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* this_ptr);
QT_CORE_C_EXPORT void qt_core_c_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption_destructor(QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* this_ptr);
QT_CORE_C_EXPORT QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* qt_core_c_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption_operator_bit_and_assign_int(QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* this_ptr, int mask);
QT_CORE_C_EXPORT QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* qt_core_c_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption_operator_bit_and_assign_unsigned_int(QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* this_ptr, unsigned int mask);
QT_CORE_C_EXPORT void qt_core_c_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption_operator_bit_and_to_output_QUrl_ComponentFormattingOption(const QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* this_ptr, QUrl::ComponentFormattingOption f, QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* output);
QT_CORE_C_EXPORT void qt_core_c_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption_operator_bit_and_to_output_QUrl_UrlFormattingOption(const QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* this_ptr, QUrl::UrlFormattingOption f, QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* output);
QT_CORE_C_EXPORT void qt_core_c_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption_operator_bit_and_to_output_int(const QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* this_ptr, int mask, QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* output);
QT_CORE_C_EXPORT void qt_core_c_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption_operator_bit_and_to_output_unsigned_int(const QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* this_ptr, unsigned int mask, QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* output);
QT_CORE_C_EXPORT void qt_core_c_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption_operator_bit_not_to_output(const QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* this_ptr, QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* output);
QT_CORE_C_EXPORT QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* qt_core_c_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption_operator_bit_or_assign_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption(QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* this_ptr, const QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* f);
QT_CORE_C_EXPORT QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* qt_core_c_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption_operator_bit_or_assign_QUrl_ComponentFormattingOption(QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* this_ptr, QUrl::ComponentFormattingOption f);
QT_CORE_C_EXPORT QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* qt_core_c_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption_operator_bit_or_assign_QUrl_UrlFormattingOption(QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* this_ptr, QUrl::UrlFormattingOption f);
QT_CORE_C_EXPORT void qt_core_c_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption_operator_bit_or_to_output_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption(const QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* this_ptr, const QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* f, QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* output);
QT_CORE_C_EXPORT void qt_core_c_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption_operator_bit_or_to_output_QUrl_ComponentFormattingOption(const QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* this_ptr, QUrl::ComponentFormattingOption f, QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* output);
QT_CORE_C_EXPORT void qt_core_c_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption_operator_bit_or_to_output_QUrl_UrlFormattingOption(const QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* this_ptr, QUrl::UrlFormattingOption f, QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* output);
QT_CORE_C_EXPORT QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* qt_core_c_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption_operator_bit_xor_assign_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption(QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* this_ptr, const QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* f);
QT_CORE_C_EXPORT QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* qt_core_c_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption_operator_bit_xor_assign_QUrl_ComponentFormattingOption(QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* this_ptr, QUrl::ComponentFormattingOption f);
QT_CORE_C_EXPORT QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* qt_core_c_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption_operator_bit_xor_assign_QUrl_UrlFormattingOption(QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* this_ptr, QUrl::UrlFormattingOption f);
QT_CORE_C_EXPORT void qt_core_c_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption_operator_bit_xor_to_output_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption(const QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* this_ptr, const QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* f, QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* output);
QT_CORE_C_EXPORT void qt_core_c_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption_operator_bit_xor_to_output_QUrl_ComponentFormattingOption(const QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* this_ptr, QUrl::ComponentFormattingOption f, QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* output);
QT_CORE_C_EXPORT void qt_core_c_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption_operator_bit_xor_to_output_QUrl_UrlFormattingOption(const QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* this_ptr, QUrl::UrlFormattingOption f, QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* output);
QT_CORE_C_EXPORT bool qt_core_c_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption_operator_not(const QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* this_ptr);
QT_CORE_C_EXPORT bool qt_core_c_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption_testFlag_QUrl_ComponentFormattingOption(const QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* this_ptr, QUrl::ComponentFormattingOption f);
QT_CORE_C_EXPORT bool qt_core_c_QUrlTwoFlags_QUrl_UrlFormattingOption_QUrl_ComponentFormattingOption_testFlag_QUrl_UrlFormattingOption(const QUrlTwoFlags< QUrl::UrlFormattingOption, QUrl::ComponentFormattingOption >* this_ptr, QUrl::UrlFormattingOption f);

} // extern "C"

#endif // QT_CORE_C_QURLTWOFLAGS_H
