#ifndef QT_CORE_C_QSTRING_H
#define QT_CORE_C_QSTRING_H

#include "qt_core_c_global.h"

extern "C" {

QT_CORE_C_EXPORT void qt_core_c_QString_G_operator_add_to_output_QByteArray_ba_QString_s(const QByteArray* ba, const QString* s, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_G_operator_add_to_output_QChar_s1_QStringRef_s2(const QChar* s1, const QStringRef* s2, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_G_operator_add_to_output_QChar_s1_QString_s2(const QChar* s1, const QString* s2, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_G_operator_add_to_output_QLatin1String_s1_QStringRef_s2(const QLatin1String* s1, const QStringRef* s2, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_G_operator_add_to_output_QStringRef_s1_QChar_s2(const QStringRef* s1, const QChar* s2, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_G_operator_add_to_output_QStringRef_s1_QLatin1String_s2(const QStringRef* s1, const QLatin1String* s2, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_G_operator_add_to_output_QStringRef_s1_QStringRef_s2(const QStringRef* s1, const QStringRef* s2, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_G_operator_add_to_output_QStringRef_s1_QString_s2(const QStringRef* s1, const QString* s2, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_G_operator_add_to_output_QString_s1_QChar_s2(const QString* s1, const QChar* s2, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_G_operator_add_to_output_QString_s1_QStringRef_s2(const QString* s1, const QStringRef* s2, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_G_operator_add_to_output_QString_s1_QString_s2(const QString* s1, const QString* s2, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_G_operator_add_to_output_QString_s1_char_s2(const QString* s1, const char* s2, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_G_operator_add_to_output_QString_s_QByteArray_ba(const QString* s, const QByteArray* ba, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_G_operator_add_to_output_QString_s_char_c(const QString* s, char c, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_G_operator_add_to_output_char_c_QString_s(char c, const QString* s, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_G_operator_add_to_output_char_s1_QString_s2(const char* s1, const QString* s2, QString* output);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_eq_QByteArray_QStringRef(const QByteArray* lhs, const QStringRef* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_eq_QLatin1String_QChar(const QLatin1String* lhs, const QChar* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_eq_QLatin1String_QLatin1String(const QLatin1String* s1, const QLatin1String* s2);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_eq_QLatin1String_QStringRef(const QLatin1String* lhs, const QStringRef* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_eq_QStringRef_QByteArray(const QStringRef* lhs, const QByteArray* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_eq_QStringRef_QChar(const QStringRef* lhs, const QChar* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_eq_QStringRef_QLatin1String(const QStringRef* lhs, const QLatin1String* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_eq_QStringRef_QString(const QStringRef* lhs, const QString* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_eq_QStringRef_QStringRef(const QStringRef* s1, const QStringRef* s2);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_eq_QString_QChar(const QString* lhs, const QChar* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_eq_QString_QStringRef(const QString* lhs, const QStringRef* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_eq_char_QLatin1String(const char* s1, const QLatin1String* s2);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_ge_QByteArray_QStringRef(const QByteArray* lhs, const QStringRef* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_ge_QChar_QLatin1String(const QChar* lhs, const QLatin1String* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_ge_QChar_QString(const QChar* lhs, const QString* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_ge_QChar_QStringRef(const QChar* lhs, const QStringRef* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_ge_QLatin1String_QChar(const QLatin1String* lhs, const QChar* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_ge_QLatin1String_QLatin1String(const QLatin1String* s1, const QLatin1String* s2);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_ge_QLatin1String_QStringRef(const QLatin1String* lhs, const QStringRef* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_ge_QStringRef_QByteArray(const QStringRef* lhs, const QByteArray* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_ge_QStringRef_QChar(const QStringRef* lhs, const QChar* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_ge_QStringRef_QLatin1String(const QStringRef* lhs, const QLatin1String* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_ge_QStringRef_QString(const QStringRef* lhs, const QString* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_ge_QStringRef_QStringRef(const QStringRef* s1, const QStringRef* s2);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_ge_QString_QChar(const QString* lhs, const QChar* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_ge_QString_QStringRef(const QString* lhs, const QStringRef* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_ge_char_QLatin1String(const char* s1, const QLatin1String* s2);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_gt_QByteArray_QStringRef(const QByteArray* lhs, const QStringRef* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_gt_QLatin1String_QChar(const QLatin1String* lhs, const QChar* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_gt_QLatin1String_QLatin1String(const QLatin1String* s1, const QLatin1String* s2);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_gt_QLatin1String_QStringRef(const QLatin1String* lhs, const QStringRef* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_gt_QStringRef_QByteArray(const QStringRef* lhs, const QByteArray* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_gt_QStringRef_QChar(const QStringRef* lhs, const QChar* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_gt_QStringRef_QLatin1String(const QStringRef* lhs, const QLatin1String* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_gt_QStringRef_QString(const QStringRef* lhs, const QString* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_gt_QStringRef_QStringRef(const QStringRef* s1, const QStringRef* s2);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_gt_QString_QChar(const QString* lhs, const QChar* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_gt_QString_QStringRef(const QString* lhs, const QStringRef* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_gt_char_QLatin1String(const char* s1, const QLatin1String* s2);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_le_QByteArray_QStringRef(const QByteArray* lhs, const QStringRef* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_le_QChar_QLatin1String(const QChar* lhs, const QLatin1String* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_le_QChar_QString(const QChar* lhs, const QString* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_le_QChar_QStringRef(const QChar* lhs, const QStringRef* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_le_QLatin1String_QChar(const QLatin1String* lhs, const QChar* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_le_QLatin1String_QLatin1String(const QLatin1String* s1, const QLatin1String* s2);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_le_QLatin1String_QStringRef(const QLatin1String* lhs, const QStringRef* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_le_QStringRef_QByteArray(const QStringRef* lhs, const QByteArray* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_le_QStringRef_QChar(const QStringRef* lhs, const QChar* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_le_QStringRef_QLatin1String(const QStringRef* lhs, const QLatin1String* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_le_QStringRef_QString(const QStringRef* lhs, const QString* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_le_QStringRef_QStringRef(const QStringRef* s1, const QStringRef* s2);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_le_QString_QChar(const QString* lhs, const QChar* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_le_QString_QStringRef(const QString* lhs, const QStringRef* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_le_char_QLatin1String(const char* s1, const QLatin1String* s2);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_lt_QByteArray_QStringRef(const QByteArray* lhs, const QStringRef* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_lt_QLatin1String_QChar(const QLatin1String* lhs, const QChar* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_lt_QLatin1String_QLatin1String(const QLatin1String* s1, const QLatin1String* s2);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_lt_QLatin1String_QStringRef(const QLatin1String* lhs, const QStringRef* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_lt_QStringRef_QByteArray(const QStringRef* lhs, const QByteArray* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_lt_QStringRef_QChar(const QStringRef* lhs, const QChar* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_lt_QStringRef_QLatin1String(const QStringRef* lhs, const QLatin1String* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_lt_QStringRef_QString(const QStringRef* lhs, const QString* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_lt_QStringRef_QStringRef(const QStringRef* s1, const QStringRef* s2);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_lt_QString_QChar(const QString* lhs, const QChar* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_lt_QString_QStringRef(const QString* lhs, const QStringRef* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_lt_char_QLatin1String(const char* s1, const QLatin1String* s2);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_neq_QByteArray_QStringRef(const QByteArray* lhs, const QStringRef* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_neq_QChar_QLatin1String(const QChar* lhs, const QLatin1String* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_neq_QChar_QString(const QChar* lhs, const QString* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_neq_QChar_QStringRef(const QChar* lhs, const QStringRef* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_neq_QLatin1String_QChar(const QLatin1String* lhs, const QChar* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_neq_QLatin1String_QLatin1String(const QLatin1String* s1, const QLatin1String* s2);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_neq_QLatin1String_QStringRef(const QLatin1String* lhs, const QStringRef* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_neq_QStringRef_QByteArray(const QStringRef* lhs, const QByteArray* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_neq_QStringRef_QChar(const QStringRef* lhs, const QChar* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_neq_QStringRef_QLatin1String(const QStringRef* lhs, const QLatin1String* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_neq_QStringRef_QString(const QStringRef* lhs, const QString* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_neq_QStringRef_QStringRef(const QStringRef* s1, const QStringRef* s2);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_neq_QString_QChar(const QString* lhs, const QChar* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_neq_QString_QStringRef(const QString* lhs, const QStringRef* rhs);
QT_CORE_C_EXPORT bool qt_core_c_QString_G_operator_neq_char_QLatin1String(const char* s1, const QLatin1String* s2);
QT_CORE_C_EXPORT QDataStream* qt_core_c_QString_G_operator_shl(QDataStream* arg1, const QString* arg2);
QT_CORE_C_EXPORT QDataStream* qt_core_c_QString_G_operator_shr(QDataStream* arg1, QString* arg2);
QT_CORE_C_EXPORT void qt_core_c_QString_G_swap(QString* value1, QString* value2);
QT_CORE_C_EXPORT QString* qt_core_c_QString_append_QByteArray(QString* this_ptr, const QByteArray* s);
QT_CORE_C_EXPORT QString* qt_core_c_QString_append_QChar(QString* this_ptr, const QChar* c);
QT_CORE_C_EXPORT QString* qt_core_c_QString_append_QChar_int(QString* this_ptr, const QChar* uc, int len);
QT_CORE_C_EXPORT QString* qt_core_c_QString_append_QLatin1String(QString* this_ptr, const QLatin1String* s);
QT_CORE_C_EXPORT QString* qt_core_c_QString_append_QString(QString* this_ptr, const QString* s);
QT_CORE_C_EXPORT QString* qt_core_c_QString_append_QStringRef(QString* this_ptr, const QStringRef* s);
QT_CORE_C_EXPORT QString* qt_core_c_QString_append_char(QString* this_ptr, const char* s);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_QChar(const QString* this_ptr, const QChar* a, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_QChar_int(const QString* this_ptr, const QChar* a, int fieldWidth, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_QChar_int_QChar(const QString* this_ptr, const QChar* a, int fieldWidth, const QChar* fillChar, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_QString(const QString* this_ptr, const QString* a, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_QString_QString(const QString* this_ptr, const QString* a1, const QString* a2, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_QString_QString_QString(const QString* this_ptr, const QString* a1, const QString* a2, const QString* a3, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_QString_QString_QString_QString(const QString* this_ptr, const QString* a1, const QString* a2, const QString* a3, const QString* a4, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_QString_QString_QString_QString_QString(const QString* this_ptr, const QString* a1, const QString* a2, const QString* a3, const QString* a4, const QString* a5, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_QString_QString_QString_QString_QString_QString(const QString* this_ptr, const QString* a1, const QString* a2, const QString* a3, const QString* a4, const QString* a5, const QString* a6, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_QString_QString_QString_QString_QString_QString_QString(const QString* this_ptr, const QString* a1, const QString* a2, const QString* a3, const QString* a4, const QString* a5, const QString* a6, const QString* a7, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_QString_QString_QString_QString_QString_QString_QString_QString(const QString* this_ptr, const QString* a1, const QString* a2, const QString* a3, const QString* a4, const QString* a5, const QString* a6, const QString* a7, const QString* a8, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_QString_QString_QString_QString_QString_QString_QString_QString_QString(const QString* this_ptr, const QString* a1, const QString* a2, const QString* a3, const QString* a4, const QString* a5, const QString* a6, const QString* a7, const QString* a8, const QString* a9, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_QString_int(const QString* this_ptr, const QString* a, int fieldWidth, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_QString_int_QChar(const QString* this_ptr, const QString* a, int fieldWidth, const QChar* fillChar, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_char(const QString* this_ptr, char a, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_char_int(const QString* this_ptr, char a, int fieldWidth, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_char_int_QChar(const QString* this_ptr, char a, int fieldWidth, const QChar* fillChar, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_double(const QString* this_ptr, double a, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_double_int(const QString* this_ptr, double a, int fieldWidth, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_double_int_char(const QString* this_ptr, double a, int fieldWidth, char fmt, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_double_int_char_int(const QString* this_ptr, double a, int fieldWidth, char fmt, int prec, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_double_int_char_int_QChar(const QString* this_ptr, double a, int fieldWidth, char fmt, int prec, const QChar* fillChar, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_int(const QString* this_ptr, int a, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_int_int(const QString* this_ptr, int a, int fieldWidth, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_int_int_int(const QString* this_ptr, int a, int fieldWidth, int base, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_int_int_int_QChar(const QString* this_ptr, int a, int fieldWidth, int base, const QChar* fillChar, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_long(const QString* this_ptr, long a, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_long_int(const QString* this_ptr, long a, int fieldwidth, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_long_int_int(const QString* this_ptr, long a, int fieldwidth, int base, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_long_int_int_QChar(const QString* this_ptr, long a, int fieldwidth, int base, const QChar* fillChar, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_qlonglong(const QString* this_ptr, qlonglong a, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_qlonglong_int(const QString* this_ptr, qlonglong a, int fieldwidth, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_qlonglong_int_int(const QString* this_ptr, qlonglong a, int fieldwidth, int base, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_qlonglong_int_int_QChar(const QString* this_ptr, qlonglong a, int fieldwidth, int base, const QChar* fillChar, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_qulonglong(const QString* this_ptr, qulonglong a, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_qulonglong_int(const QString* this_ptr, qulonglong a, int fieldwidth, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_qulonglong_int_int(const QString* this_ptr, qulonglong a, int fieldwidth, int base, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_qulonglong_int_int_QChar(const QString* this_ptr, qulonglong a, int fieldwidth, int base, const QChar* fillChar, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_short(const QString* this_ptr, short a, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_short_int(const QString* this_ptr, short a, int fieldWidth, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_short_int_int(const QString* this_ptr, short a, int fieldWidth, int base, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_short_int_int_QChar(const QString* this_ptr, short a, int fieldWidth, int base, const QChar* fillChar, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_unsigned_int(const QString* this_ptr, unsigned int a, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_unsigned_int_int(const QString* this_ptr, unsigned int a, int fieldWidth, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_unsigned_int_int_int(const QString* this_ptr, unsigned int a, int fieldWidth, int base, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_unsigned_int_int_int_QChar(const QString* this_ptr, unsigned int a, int fieldWidth, int base, const QChar* fillChar, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_unsigned_long(const QString* this_ptr, unsigned long a, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_unsigned_long_int(const QString* this_ptr, unsigned long a, int fieldwidth, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_unsigned_long_int_int(const QString* this_ptr, unsigned long a, int fieldwidth, int base, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_unsigned_long_int_int_QChar(const QString* this_ptr, unsigned long a, int fieldwidth, int base, const QChar* fillChar, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_unsigned_short(const QString* this_ptr, unsigned short a, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_unsigned_short_int(const QString* this_ptr, unsigned short a, int fieldWidth, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_unsigned_short_int_int(const QString* this_ptr, unsigned short a, int fieldWidth, int base, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_arg_to_output_unsigned_short_int_int_QChar(const QString* this_ptr, unsigned short a, int fieldWidth, int base, const QChar* fillChar, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_at_to_output(const QString* this_ptr, int i, QChar* output);
QT_CORE_C_EXPORT QChar* qt_core_c_QString_begin(QString* this_ptr);
QT_CORE_C_EXPORT const QChar* qt_core_c_QString_begin_const(const QString* this_ptr);
QT_CORE_C_EXPORT int qt_core_c_QString_capacity(const QString* this_ptr);
QT_CORE_C_EXPORT const QChar* qt_core_c_QString_cbegin(const QString* this_ptr);
QT_CORE_C_EXPORT const QChar* qt_core_c_QString_cend(const QString* this_ptr);
QT_CORE_C_EXPORT void qt_core_c_QString_chop(QString* this_ptr, int n);
QT_CORE_C_EXPORT void qt_core_c_QString_clear(QString* this_ptr);
QT_CORE_C_EXPORT int qt_core_c_QString_compare_QLatin1String(const QString* this_ptr, const QLatin1String* other);
QT_CORE_C_EXPORT int qt_core_c_QString_compare_QLatin1String_QString(const QLatin1String* s1, const QString* s2);
QT_CORE_C_EXPORT int qt_core_c_QString_compare_QLatin1String_QString_Qt_CaseSensitivity(const QLatin1String* s1, const QString* s2, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QString_compare_QLatin1String_Qt_CaseSensitivity(const QString* this_ptr, const QLatin1String* other, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QString_compare_QString(const QString* this_ptr, const QString* s);
QT_CORE_C_EXPORT int qt_core_c_QString_compare_QStringRef(const QString* this_ptr, const QStringRef* s);
QT_CORE_C_EXPORT int qt_core_c_QString_compare_QStringRef_Qt_CaseSensitivity(const QString* this_ptr, const QStringRef* s, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QString_compare_QString_QLatin1String(const QString* s1, const QLatin1String* s2);
QT_CORE_C_EXPORT int qt_core_c_QString_compare_QString_QLatin1String_Qt_CaseSensitivity(const QString* s1, const QLatin1String* s2, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QString_compare_QString_QString(const QString* s1, const QString* s2);
QT_CORE_C_EXPORT int qt_core_c_QString_compare_QString_QStringRef(const QString* s1, const QStringRef* s2);
QT_CORE_C_EXPORT int qt_core_c_QString_compare_QString_QStringRef_Qt_CaseSensitivity(const QString* s1, const QStringRef* s2, const Qt::CaseSensitivity* arg3);
QT_CORE_C_EXPORT int qt_core_c_QString_compare_QString_QString_Qt_CaseSensitivity(const QString* s1, const QString* s2, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QString_compare_QString_Qt_CaseSensitivity(const QString* this_ptr, const QString* s, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT const QChar* qt_core_c_QString_constBegin(const QString* this_ptr);
QT_CORE_C_EXPORT const QChar* qt_core_c_QString_constData(const QString* this_ptr);
QT_CORE_C_EXPORT const QChar* qt_core_c_QString_constEnd(const QString* this_ptr);
QT_CORE_C_EXPORT void qt_core_c_QString_constructor_a(const QByteArray* a, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_constructor_arg1(const QString* arg1, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_constructor_c(const QChar* c, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_constructor_ch(const char* ch, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_constructor_latin1(const QLatin1String* latin1, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_constructor_no_args(QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_constructor_size_c(int size, const QChar* c, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_constructor_unicode(const QChar* unicode, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_constructor_unicode_size(const QChar* unicode, int size, QString* output);
QT_CORE_C_EXPORT bool qt_core_c_QString_contains_QChar(const QString* this_ptr, const QChar* c);
QT_CORE_C_EXPORT bool qt_core_c_QString_contains_QChar_Qt_CaseSensitivity(const QString* this_ptr, const QChar* c, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT bool qt_core_c_QString_contains_QLatin1String(const QString* this_ptr, const QLatin1String* s);
QT_CORE_C_EXPORT bool qt_core_c_QString_contains_QLatin1String_Qt_CaseSensitivity(const QString* this_ptr, const QLatin1String* s, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT bool qt_core_c_QString_contains_QRegExp_ref(const QString* this_ptr, QRegExp* rx);
QT_CORE_C_EXPORT bool qt_core_c_QString_contains_const_QRegExp_ref(const QString* this_ptr, const QRegExp* rx);
QT_CORE_C_EXPORT bool qt_core_c_QString_contains_const_QRegularExpression_ref(const QString* this_ptr, const QRegularExpression* re);
QT_CORE_C_EXPORT bool qt_core_c_QString_contains_const_QRegularExpression_ref_QRegularExpressionMatch_ptr(const QString* this_ptr, const QRegularExpression* re, QRegularExpressionMatch* match);
QT_CORE_C_EXPORT bool qt_core_c_QString_contains_const_QStringRef_ref(const QString* this_ptr, const QStringRef* s);
QT_CORE_C_EXPORT bool qt_core_c_QString_contains_const_QStringRef_ref_Qt_CaseSensitivity(const QString* this_ptr, const QStringRef* s, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT bool qt_core_c_QString_contains_const_QString_ref(const QString* this_ptr, const QString* s);
QT_CORE_C_EXPORT bool qt_core_c_QString_contains_const_QString_ref_Qt_CaseSensitivity(const QString* this_ptr, const QString* s, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QString_count_QChar(const QString* this_ptr, const QChar* c);
QT_CORE_C_EXPORT int qt_core_c_QString_count_QChar_Qt_CaseSensitivity(const QString* this_ptr, const QChar* c, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QString_count_QRegExp(const QString* this_ptr, const QRegExp* arg1);
QT_CORE_C_EXPORT int qt_core_c_QString_count_QRegularExpression(const QString* this_ptr, const QRegularExpression* re);
QT_CORE_C_EXPORT int qt_core_c_QString_count_QString(const QString* this_ptr, const QString* s);
QT_CORE_C_EXPORT int qt_core_c_QString_count_QStringRef(const QString* this_ptr, const QStringRef* s);
QT_CORE_C_EXPORT int qt_core_c_QString_count_QStringRef_Qt_CaseSensitivity(const QString* this_ptr, const QStringRef* s, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QString_count_QString_Qt_CaseSensitivity(const QString* this_ptr, const QString* s, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QString_count_no_args(const QString* this_ptr);
QT_CORE_C_EXPORT QChar* qt_core_c_QString_data(QString* this_ptr);
QT_CORE_C_EXPORT const QChar* qt_core_c_QString_data_const(const QString* this_ptr);
QT_CORE_C_EXPORT void qt_core_c_QString_destructor(QString* this_ptr);
QT_CORE_C_EXPORT QChar* qt_core_c_QString_end(QString* this_ptr);
QT_CORE_C_EXPORT const QChar* qt_core_c_QString_end_const(const QString* this_ptr);
QT_CORE_C_EXPORT bool qt_core_c_QString_endsWith_QChar(const QString* this_ptr, const QChar* c);
QT_CORE_C_EXPORT bool qt_core_c_QString_endsWith_QChar_Qt_CaseSensitivity(const QString* this_ptr, const QChar* c, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT bool qt_core_c_QString_endsWith_QLatin1String(const QString* this_ptr, const QLatin1String* s);
QT_CORE_C_EXPORT bool qt_core_c_QString_endsWith_QLatin1String_Qt_CaseSensitivity(const QString* this_ptr, const QLatin1String* s, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT bool qt_core_c_QString_endsWith_QString(const QString* this_ptr, const QString* s);
QT_CORE_C_EXPORT bool qt_core_c_QString_endsWith_QStringRef(const QString* this_ptr, const QStringRef* s);
QT_CORE_C_EXPORT bool qt_core_c_QString_endsWith_QStringRef_Qt_CaseSensitivity(const QString* this_ptr, const QStringRef* s, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT bool qt_core_c_QString_endsWith_QString_Qt_CaseSensitivity(const QString* this_ptr, const QString* s, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT QString* qt_core_c_QString_fill_c(QString* this_ptr, const QChar* c);
QT_CORE_C_EXPORT QString* qt_core_c_QString_fill_c_size(QString* this_ptr, const QChar* c, int size);
QT_CORE_C_EXPORT void qt_core_c_QString_fromLatin1_to_output_QByteArray(const QByteArray* str, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_fromLatin1_to_output_char(const char* str, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_fromLatin1_to_output_char_int(const char* str, int size, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_fromLocal8Bit_to_output_QByteArray(const QByteArray* str, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_fromLocal8Bit_to_output_char(const char* str, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_fromLocal8Bit_to_output_char_int(const char* str, int size, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_fromRawData_to_output(const QChar* arg1, int size, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_fromUcs4_to_output_arg1(const unsigned int* arg1, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_fromUcs4_to_output_arg1_size(const unsigned int* arg1, int size, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_fromUcs4_to_output_str(const char32_t* str, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_fromUcs4_to_output_str_size(const char32_t* str, int size, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_fromUtf16_to_output_arg1(const unsigned short* arg1, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_fromUtf16_to_output_arg1_size(const unsigned short* arg1, int size, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_fromUtf16_to_output_str(const char16_t* str, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_fromUtf16_to_output_str_size(const char16_t* str, int size, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_fromUtf8_to_output_QByteArray(const QByteArray* str, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_fromUtf8_to_output_char(const char* str, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_fromUtf8_to_output_char_int(const char* str, int size, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_fromWCharArray_to_output_string(const wchar_t* string, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_fromWCharArray_to_output_string_size(const wchar_t* string, int size, QString* output);
QT_CORE_C_EXPORT int qt_core_c_QString_indexOf_QChar(const QString* this_ptr, const QChar* c);
QT_CORE_C_EXPORT int qt_core_c_QString_indexOf_QChar_int(const QString* this_ptr, const QChar* c, int from);
QT_CORE_C_EXPORT int qt_core_c_QString_indexOf_QChar_int_Qt_CaseSensitivity(const QString* this_ptr, const QChar* c, int from, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QString_indexOf_QLatin1String(const QString* this_ptr, const QLatin1String* s);
QT_CORE_C_EXPORT int qt_core_c_QString_indexOf_QLatin1String_int(const QString* this_ptr, const QLatin1String* s, int from);
QT_CORE_C_EXPORT int qt_core_c_QString_indexOf_QLatin1String_int_Qt_CaseSensitivity(const QString* this_ptr, const QLatin1String* s, int from, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QString_indexOf_QRegExp_ref(const QString* this_ptr, QRegExp* arg1);
QT_CORE_C_EXPORT int qt_core_c_QString_indexOf_QRegExp_ref_int(const QString* this_ptr, QRegExp* arg1, int from);
QT_CORE_C_EXPORT int qt_core_c_QString_indexOf_const_QRegExp_ref(const QString* this_ptr, const QRegExp* arg1);
QT_CORE_C_EXPORT int qt_core_c_QString_indexOf_const_QRegExp_ref_int(const QString* this_ptr, const QRegExp* arg1, int from);
QT_CORE_C_EXPORT int qt_core_c_QString_indexOf_const_QRegularExpression_ref(const QString* this_ptr, const QRegularExpression* re);
QT_CORE_C_EXPORT int qt_core_c_QString_indexOf_const_QRegularExpression_ref_int(const QString* this_ptr, const QRegularExpression* re, int from);
QT_CORE_C_EXPORT int qt_core_c_QString_indexOf_const_QRegularExpression_ref_int_QRegularExpressionMatch_ptr(const QString* this_ptr, const QRegularExpression* re, int from, QRegularExpressionMatch* rmatch);
QT_CORE_C_EXPORT int qt_core_c_QString_indexOf_const_QStringRef_ref(const QString* this_ptr, const QStringRef* s);
QT_CORE_C_EXPORT int qt_core_c_QString_indexOf_const_QStringRef_ref_int(const QString* this_ptr, const QStringRef* s, int from);
QT_CORE_C_EXPORT int qt_core_c_QString_indexOf_const_QStringRef_ref_int_Qt_CaseSensitivity(const QString* this_ptr, const QStringRef* s, int from, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QString_indexOf_const_QString_ref(const QString* this_ptr, const QString* s);
QT_CORE_C_EXPORT int qt_core_c_QString_indexOf_const_QString_ref_int(const QString* this_ptr, const QString* s, int from);
QT_CORE_C_EXPORT int qt_core_c_QString_indexOf_const_QString_ref_int_Qt_CaseSensitivity(const QString* this_ptr, const QString* s, int from, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT QString* qt_core_c_QString_insert_int_QByteArray(QString* this_ptr, int i, const QByteArray* s);
QT_CORE_C_EXPORT QString* qt_core_c_QString_insert_int_QChar(QString* this_ptr, int i, const QChar* c);
QT_CORE_C_EXPORT QString* qt_core_c_QString_insert_int_QChar_int(QString* this_ptr, int i, const QChar* uc, int len);
QT_CORE_C_EXPORT QString* qt_core_c_QString_insert_int_QLatin1String(QString* this_ptr, int i, const QLatin1String* s);
QT_CORE_C_EXPORT QString* qt_core_c_QString_insert_int_QString(QString* this_ptr, int i, const QString* s);
QT_CORE_C_EXPORT QString* qt_core_c_QString_insert_int_QStringRef(QString* this_ptr, int i, const QStringRef* s);
QT_CORE_C_EXPORT QString* qt_core_c_QString_insert_int_char(QString* this_ptr, int i, const char* s);
QT_CORE_C_EXPORT bool qt_core_c_QString_isEmpty(const QString* this_ptr);
QT_CORE_C_EXPORT bool qt_core_c_QString_isNull(const QString* this_ptr);
QT_CORE_C_EXPORT bool qt_core_c_QString_isRightToLeft(const QString* this_ptr);
QT_CORE_C_EXPORT int qt_core_c_QString_lastIndexOf_QChar(const QString* this_ptr, const QChar* c);
QT_CORE_C_EXPORT int qt_core_c_QString_lastIndexOf_QChar_int(const QString* this_ptr, const QChar* c, int from);
QT_CORE_C_EXPORT int qt_core_c_QString_lastIndexOf_QChar_int_Qt_CaseSensitivity(const QString* this_ptr, const QChar* c, int from, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QString_lastIndexOf_QLatin1String(const QString* this_ptr, const QLatin1String* s);
QT_CORE_C_EXPORT int qt_core_c_QString_lastIndexOf_QLatin1String_int(const QString* this_ptr, const QLatin1String* s, int from);
QT_CORE_C_EXPORT int qt_core_c_QString_lastIndexOf_QLatin1String_int_Qt_CaseSensitivity(const QString* this_ptr, const QLatin1String* s, int from, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QString_lastIndexOf_QRegExp_ref(const QString* this_ptr, QRegExp* arg1);
QT_CORE_C_EXPORT int qt_core_c_QString_lastIndexOf_QRegExp_ref_int(const QString* this_ptr, QRegExp* arg1, int from);
QT_CORE_C_EXPORT int qt_core_c_QString_lastIndexOf_const_QRegExp_ref(const QString* this_ptr, const QRegExp* arg1);
QT_CORE_C_EXPORT int qt_core_c_QString_lastIndexOf_const_QRegExp_ref_int(const QString* this_ptr, const QRegExp* arg1, int from);
QT_CORE_C_EXPORT int qt_core_c_QString_lastIndexOf_const_QRegularExpression_ref(const QString* this_ptr, const QRegularExpression* re);
QT_CORE_C_EXPORT int qt_core_c_QString_lastIndexOf_const_QRegularExpression_ref_int(const QString* this_ptr, const QRegularExpression* re, int from);
QT_CORE_C_EXPORT int qt_core_c_QString_lastIndexOf_const_QRegularExpression_ref_int_QRegularExpressionMatch_ptr(const QString* this_ptr, const QRegularExpression* re, int from, QRegularExpressionMatch* rmatch);
QT_CORE_C_EXPORT int qt_core_c_QString_lastIndexOf_const_QStringRef_ref(const QString* this_ptr, const QStringRef* s);
QT_CORE_C_EXPORT int qt_core_c_QString_lastIndexOf_const_QStringRef_ref_int(const QString* this_ptr, const QStringRef* s, int from);
QT_CORE_C_EXPORT int qt_core_c_QString_lastIndexOf_const_QStringRef_ref_int_Qt_CaseSensitivity(const QString* this_ptr, const QStringRef* s, int from, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT int qt_core_c_QString_lastIndexOf_const_QString_ref(const QString* this_ptr, const QString* s);
QT_CORE_C_EXPORT int qt_core_c_QString_lastIndexOf_const_QString_ref_int(const QString* this_ptr, const QString* s, int from);
QT_CORE_C_EXPORT int qt_core_c_QString_lastIndexOf_const_QString_ref_int_Qt_CaseSensitivity(const QString* this_ptr, const QString* s, int from, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT void qt_core_c_QString_leftJustified_to_output_width(const QString* this_ptr, int width, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_leftJustified_to_output_width_fill(const QString* this_ptr, int width, const QChar* fill, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_leftJustified_to_output_width_fill_trunc(const QString* this_ptr, int width, const QChar* fill, bool trunc, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_leftRef_to_output(const QString* this_ptr, int n, QStringRef* output);
QT_CORE_C_EXPORT void qt_core_c_QString_left_to_output(const QString* this_ptr, int n, QString* output);
QT_CORE_C_EXPORT int qt_core_c_QString_length(const QString* this_ptr);
QT_CORE_C_EXPORT int qt_core_c_QString_localeAwareCompare_QString(const QString* this_ptr, const QString* s);
QT_CORE_C_EXPORT int qt_core_c_QString_localeAwareCompare_QStringRef(const QString* this_ptr, const QStringRef* s);
QT_CORE_C_EXPORT int qt_core_c_QString_localeAwareCompare_QString_QString(const QString* s1, const QString* s2);
QT_CORE_C_EXPORT int qt_core_c_QString_localeAwareCompare_QString_QStringRef(const QString* s1, const QStringRef* s2);
QT_CORE_C_EXPORT void qt_core_c_QString_midRef_to_output_position(const QString* this_ptr, int position, QStringRef* output);
QT_CORE_C_EXPORT void qt_core_c_QString_midRef_to_output_position_n(const QString* this_ptr, int position, int n, QStringRef* output);
QT_CORE_C_EXPORT void qt_core_c_QString_mid_to_output_position(const QString* this_ptr, int position, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_mid_to_output_position_n(const QString* this_ptr, int position, int n, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_normalized_to_output_mode(const QString* this_ptr, QString::NormalizationForm mode, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_normalized_to_output_mode_version(const QString* this_ptr, QString::NormalizationForm mode, const QChar::UnicodeVersion* version, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_number_to_output_double(double arg1, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_number_to_output_double_char(double arg1, char f, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_number_to_output_double_char_int(double arg1, char f, int prec, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_number_to_output_int(int arg1, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_number_to_output_int_int(int arg1, int base, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_number_to_output_long(long arg1, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_number_to_output_long_int(long arg1, int base, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_number_to_output_qlonglong(qlonglong arg1, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_number_to_output_qlonglong_int(qlonglong arg1, int base, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_number_to_output_qulonglong(qulonglong arg1, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_number_to_output_qulonglong_int(qulonglong arg1, int base, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_number_to_output_unsigned_int(unsigned int arg1, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_number_to_output_unsigned_int_int(unsigned int arg1, int base, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_number_to_output_unsigned_long(unsigned long arg1, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_number_to_output_unsigned_long_int(unsigned long arg1, int base, QString* output);
QT_CORE_C_EXPORT QString* qt_core_c_QString_operator_add_assign_QByteArray_s(QString* this_ptr, const QByteArray* s);
QT_CORE_C_EXPORT QString* qt_core_c_QString_operator_add_assign_QChar_SpecialCharacter_c(QString* this_ptr, const QChar::SpecialCharacter* c);
QT_CORE_C_EXPORT QString* qt_core_c_QString_operator_add_assign_QChar_c(QString* this_ptr, const QChar* c);
QT_CORE_C_EXPORT QString* qt_core_c_QString_operator_add_assign_QLatin1String_s(QString* this_ptr, const QLatin1String* s);
QT_CORE_C_EXPORT QString* qt_core_c_QString_operator_add_assign_QStringRef_s(QString* this_ptr, const QStringRef* s);
QT_CORE_C_EXPORT QString* qt_core_c_QString_operator_add_assign_QString_s(QString* this_ptr, const QString* s);
QT_CORE_C_EXPORT QString* qt_core_c_QString_operator_add_assign_char_c(QString* this_ptr, char c);
QT_CORE_C_EXPORT QString* qt_core_c_QString_operator_add_assign_char_s(QString* this_ptr, const char* s);
QT_CORE_C_EXPORT QString* qt_core_c_QString_operator_assign_QByteArray_a(QString* this_ptr, const QByteArray* a);
QT_CORE_C_EXPORT QString* qt_core_c_QString_operator_assign_QChar_c(QString* this_ptr, const QChar* c);
QT_CORE_C_EXPORT QString* qt_core_c_QString_operator_assign_QLatin1String_latin1(QString* this_ptr, const QLatin1String* latin1);
QT_CORE_C_EXPORT QString* qt_core_c_QString_operator_assign_QString_arg1(QString* this_ptr, const QString* arg1);
QT_CORE_C_EXPORT QString* qt_core_c_QString_operator_assign_char_c(QString* this_ptr, char c);
QT_CORE_C_EXPORT QString* qt_core_c_QString_operator_assign_char_ch(QString* this_ptr, const char* ch);
QT_CORE_C_EXPORT bool qt_core_c_QString_operator_eq_QByteArray(const QString* this_ptr, const QByteArray* s);
QT_CORE_C_EXPORT bool qt_core_c_QString_operator_eq_QLatin1String(const QString* this_ptr, const QLatin1String* s);
QT_CORE_C_EXPORT bool qt_core_c_QString_operator_eq_char(const QString* this_ptr, const char* s);
QT_CORE_C_EXPORT bool qt_core_c_QString_operator_ge_QByteArray(const QString* this_ptr, const QByteArray* s);
QT_CORE_C_EXPORT bool qt_core_c_QString_operator_ge_QLatin1String(const QString* this_ptr, const QLatin1String* s);
QT_CORE_C_EXPORT bool qt_core_c_QString_operator_ge_char(const QString* this_ptr, const char* s);
QT_CORE_C_EXPORT bool qt_core_c_QString_operator_gt_QByteArray(const QString* this_ptr, const QByteArray* s);
QT_CORE_C_EXPORT bool qt_core_c_QString_operator_gt_QLatin1String(const QString* this_ptr, const QLatin1String* s);
QT_CORE_C_EXPORT bool qt_core_c_QString_operator_gt_char(const QString* this_ptr, const char* s);
QT_CORE_C_EXPORT void qt_core_c_QString_operator_index_to_output_const_int(const QString* this_ptr, int i, QChar* output);
QT_CORE_C_EXPORT void qt_core_c_QString_operator_index_to_output_const_unsigned_int(const QString* this_ptr, unsigned int i, QChar* output);
QT_CORE_C_EXPORT void qt_core_c_QString_operator_index_to_output_int(QString* this_ptr, int i, QCharRef* output);
QT_CORE_C_EXPORT void qt_core_c_QString_operator_index_to_output_unsigned_int(QString* this_ptr, unsigned int i, QCharRef* output);
QT_CORE_C_EXPORT bool qt_core_c_QString_operator_le_QByteArray(const QString* this_ptr, const QByteArray* s);
QT_CORE_C_EXPORT bool qt_core_c_QString_operator_le_QLatin1String(const QString* this_ptr, const QLatin1String* s);
QT_CORE_C_EXPORT bool qt_core_c_QString_operator_le_char(const QString* this_ptr, const char* s);
QT_CORE_C_EXPORT bool qt_core_c_QString_operator_lt_QByteArray(const QString* this_ptr, const QByteArray* s);
QT_CORE_C_EXPORT bool qt_core_c_QString_operator_lt_QLatin1String(const QString* this_ptr, const QLatin1String* s);
QT_CORE_C_EXPORT bool qt_core_c_QString_operator_lt_char(const QString* this_ptr, const char* s);
QT_CORE_C_EXPORT bool qt_core_c_QString_operator_neq_QByteArray(const QString* this_ptr, const QByteArray* s);
QT_CORE_C_EXPORT bool qt_core_c_QString_operator_neq_QLatin1String(const QString* this_ptr, const QLatin1String* s);
QT_CORE_C_EXPORT bool qt_core_c_QString_operator_neq_char(const QString* this_ptr, const char* s);
QT_CORE_C_EXPORT QString* qt_core_c_QString_prepend_QByteArray(QString* this_ptr, const QByteArray* s);
QT_CORE_C_EXPORT QString* qt_core_c_QString_prepend_QChar(QString* this_ptr, const QChar* c);
QT_CORE_C_EXPORT QString* qt_core_c_QString_prepend_QChar_int(QString* this_ptr, const QChar* uc, int len);
QT_CORE_C_EXPORT QString* qt_core_c_QString_prepend_QLatin1String(QString* this_ptr, const QLatin1String* s);
QT_CORE_C_EXPORT QString* qt_core_c_QString_prepend_QString(QString* this_ptr, const QString* s);
QT_CORE_C_EXPORT QString* qt_core_c_QString_prepend_QStringRef(QString* this_ptr, const QStringRef* s);
QT_CORE_C_EXPORT QString* qt_core_c_QString_prepend_char(QString* this_ptr, const char* s);
QT_CORE_C_EXPORT void qt_core_c_QString_push_back_c(QString* this_ptr, const QChar* c);
QT_CORE_C_EXPORT void qt_core_c_QString_push_back_s(QString* this_ptr, const QString* s);
QT_CORE_C_EXPORT void qt_core_c_QString_push_front_c(QString* this_ptr, const QChar* c);
QT_CORE_C_EXPORT void qt_core_c_QString_push_front_s(QString* this_ptr, const QString* s);
QT_CORE_C_EXPORT QString* qt_core_c_QString_remove_c(QString* this_ptr, const QChar* c);
QT_CORE_C_EXPORT QString* qt_core_c_QString_remove_c_cs(QString* this_ptr, const QChar* c, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT QString* qt_core_c_QString_remove_i_len(QString* this_ptr, int i, int len);
QT_CORE_C_EXPORT QString* qt_core_c_QString_remove_re(QString* this_ptr, const QRegularExpression* re);
QT_CORE_C_EXPORT QString* qt_core_c_QString_remove_rx(QString* this_ptr, const QRegExp* rx);
QT_CORE_C_EXPORT QString* qt_core_c_QString_remove_s(QString* this_ptr, const QString* s);
QT_CORE_C_EXPORT QString* qt_core_c_QString_remove_s_cs(QString* this_ptr, const QString* s, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT void qt_core_c_QString_repeated_to_output(const QString* this_ptr, int times, QString* output);
QT_CORE_C_EXPORT QString* qt_core_c_QString_replace_QChar_QChar(QString* this_ptr, const QChar* before, const QChar* after);
QT_CORE_C_EXPORT QString* qt_core_c_QString_replace_QChar_QChar_Qt_CaseSensitivity(QString* this_ptr, const QChar* before, const QChar* after, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT QString* qt_core_c_QString_replace_QChar_QLatin1String(QString* this_ptr, const QChar* c, const QLatin1String* after);
QT_CORE_C_EXPORT QString* qt_core_c_QString_replace_QChar_QLatin1String_Qt_CaseSensitivity(QString* this_ptr, const QChar* c, const QLatin1String* after, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT QString* qt_core_c_QString_replace_QChar_QString(QString* this_ptr, const QChar* c, const QString* after);
QT_CORE_C_EXPORT QString* qt_core_c_QString_replace_QChar_QString_Qt_CaseSensitivity(QString* this_ptr, const QChar* c, const QString* after, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT QString* qt_core_c_QString_replace_QChar_int_QChar_int(QString* this_ptr, const QChar* before, int blen, const QChar* after, int alen);
QT_CORE_C_EXPORT QString* qt_core_c_QString_replace_QChar_int_QChar_int_Qt_CaseSensitivity(QString* this_ptr, const QChar* before, int blen, const QChar* after, int alen, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT QString* qt_core_c_QString_replace_QLatin1String_QLatin1String(QString* this_ptr, const QLatin1String* before, const QLatin1String* after);
QT_CORE_C_EXPORT QString* qt_core_c_QString_replace_QLatin1String_QLatin1String_Qt_CaseSensitivity(QString* this_ptr, const QLatin1String* before, const QLatin1String* after, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT QString* qt_core_c_QString_replace_QLatin1String_QString(QString* this_ptr, const QLatin1String* before, const QString* after);
QT_CORE_C_EXPORT QString* qt_core_c_QString_replace_QLatin1String_QString_Qt_CaseSensitivity(QString* this_ptr, const QLatin1String* before, const QString* after, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT QString* qt_core_c_QString_replace_QRegExp_QString(QString* this_ptr, const QRegExp* rx, const QString* after);
QT_CORE_C_EXPORT QString* qt_core_c_QString_replace_QRegularExpression_QString(QString* this_ptr, const QRegularExpression* re, const QString* after);
QT_CORE_C_EXPORT QString* qt_core_c_QString_replace_QString_QLatin1String(QString* this_ptr, const QString* before, const QLatin1String* after);
QT_CORE_C_EXPORT QString* qt_core_c_QString_replace_QString_QLatin1String_Qt_CaseSensitivity(QString* this_ptr, const QString* before, const QLatin1String* after, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT QString* qt_core_c_QString_replace_QString_QString(QString* this_ptr, const QString* before, const QString* after);
QT_CORE_C_EXPORT QString* qt_core_c_QString_replace_QString_QString_Qt_CaseSensitivity(QString* this_ptr, const QString* before, const QString* after, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT QString* qt_core_c_QString_replace_int_int_QChar(QString* this_ptr, int i, int len, const QChar* after);
QT_CORE_C_EXPORT QString* qt_core_c_QString_replace_int_int_QChar_int(QString* this_ptr, int i, int len, const QChar* s, int slen);
QT_CORE_C_EXPORT QString* qt_core_c_QString_replace_int_int_QString(QString* this_ptr, int i, int len, const QString* after);
QT_CORE_C_EXPORT void qt_core_c_QString_reserve(QString* this_ptr, int size);
QT_CORE_C_EXPORT void qt_core_c_QString_resize_size(QString* this_ptr, int size);
QT_CORE_C_EXPORT void qt_core_c_QString_resize_size_fillChar(QString* this_ptr, int size, const QChar* fillChar);
QT_CORE_C_EXPORT void qt_core_c_QString_rightJustified_to_output_width(const QString* this_ptr, int width, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_rightJustified_to_output_width_fill(const QString* this_ptr, int width, const QChar* fill, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_rightJustified_to_output_width_fill_trunc(const QString* this_ptr, int width, const QChar* fill, bool trunc, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_rightRef_to_output(const QString* this_ptr, int n, QStringRef* output);
QT_CORE_C_EXPORT void qt_core_c_QString_right_to_output(const QString* this_ptr, int n, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_section_to_output_in_sep_start(const QString* this_ptr, const QString* in_sep, int start, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_section_to_output_in_sep_start_end(const QString* this_ptr, const QString* in_sep, int start, int end, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_section_to_output_in_sep_start_end_flags(const QString* this_ptr, const QString* in_sep, int start, int end, unsigned int flags, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_section_to_output_re_start(const QString* this_ptr, const QRegularExpression* re, int start, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_section_to_output_re_start_end(const QString* this_ptr, const QRegularExpression* re, int start, int end, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_section_to_output_re_start_end_flags(const QString* this_ptr, const QRegularExpression* re, int start, int end, unsigned int flags, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_section_to_output_reg_start(const QString* this_ptr, const QRegExp* reg, int start, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_section_to_output_reg_start_end(const QString* this_ptr, const QRegExp* reg, int start, int end, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_section_to_output_reg_start_end_flags(const QString* this_ptr, const QRegExp* reg, int start, int end, unsigned int flags, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_section_to_output_sep_start(const QString* this_ptr, const QChar* sep, int start, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_section_to_output_sep_start_end(const QString* this_ptr, const QChar* sep, int start, int end, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_section_to_output_sep_start_end_flags(const QString* this_ptr, const QChar* sep, int start, int end, unsigned int flags, QString* output);
QT_CORE_C_EXPORT QString* qt_core_c_QString_setNum_double(QString* this_ptr, double arg1);
QT_CORE_C_EXPORT QString* qt_core_c_QString_setNum_double_char(QString* this_ptr, double arg1, char f);
QT_CORE_C_EXPORT QString* qt_core_c_QString_setNum_double_char_int(QString* this_ptr, double arg1, char f, int prec);
QT_CORE_C_EXPORT QString* qt_core_c_QString_setNum_float(QString* this_ptr, float arg1);
QT_CORE_C_EXPORT QString* qt_core_c_QString_setNum_float_char(QString* this_ptr, float arg1, char f);
QT_CORE_C_EXPORT QString* qt_core_c_QString_setNum_float_char_int(QString* this_ptr, float arg1, char f, int prec);
QT_CORE_C_EXPORT QString* qt_core_c_QString_setNum_int(QString* this_ptr, int arg1);
QT_CORE_C_EXPORT QString* qt_core_c_QString_setNum_int_int(QString* this_ptr, int arg1, int base);
QT_CORE_C_EXPORT QString* qt_core_c_QString_setNum_long(QString* this_ptr, long arg1);
QT_CORE_C_EXPORT QString* qt_core_c_QString_setNum_long_int(QString* this_ptr, long arg1, int base);
QT_CORE_C_EXPORT QString* qt_core_c_QString_setNum_qlonglong(QString* this_ptr, qlonglong arg1);
QT_CORE_C_EXPORT QString* qt_core_c_QString_setNum_qlonglong_int(QString* this_ptr, qlonglong arg1, int base);
QT_CORE_C_EXPORT QString* qt_core_c_QString_setNum_qulonglong(QString* this_ptr, qulonglong arg1);
QT_CORE_C_EXPORT QString* qt_core_c_QString_setNum_qulonglong_int(QString* this_ptr, qulonglong arg1, int base);
QT_CORE_C_EXPORT QString* qt_core_c_QString_setNum_short(QString* this_ptr, short arg1);
QT_CORE_C_EXPORT QString* qt_core_c_QString_setNum_short_int(QString* this_ptr, short arg1, int base);
QT_CORE_C_EXPORT QString* qt_core_c_QString_setNum_unsigned_int(QString* this_ptr, unsigned int arg1);
QT_CORE_C_EXPORT QString* qt_core_c_QString_setNum_unsigned_int_int(QString* this_ptr, unsigned int arg1, int base);
QT_CORE_C_EXPORT QString* qt_core_c_QString_setNum_unsigned_long(QString* this_ptr, unsigned long arg1);
QT_CORE_C_EXPORT QString* qt_core_c_QString_setNum_unsigned_long_int(QString* this_ptr, unsigned long arg1, int base);
QT_CORE_C_EXPORT QString* qt_core_c_QString_setNum_unsigned_short(QString* this_ptr, unsigned short arg1);
QT_CORE_C_EXPORT QString* qt_core_c_QString_setNum_unsigned_short_int(QString* this_ptr, unsigned short arg1, int base);
QT_CORE_C_EXPORT QString* qt_core_c_QString_setRawData(QString* this_ptr, const QChar* unicode, int size);
QT_CORE_C_EXPORT QString* qt_core_c_QString_setUnicode(QString* this_ptr, const QChar* unicode, int size);
QT_CORE_C_EXPORT QString* qt_core_c_QString_setUtf16(QString* this_ptr, const unsigned short* utf16, int size);
QT_CORE_C_EXPORT void qt_core_c_QString_simplified_to_output(QString* this_ptr, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_simplified_to_output_const(const QString* this_ptr, QString* output);
QT_CORE_C_EXPORT int qt_core_c_QString_size(const QString* this_ptr);
QT_CORE_C_EXPORT void qt_core_c_QString_splitRef_to_output_QChar(const QString* this_ptr, const QChar* sep, QVector< QStringRef >* output);
QT_CORE_C_EXPORT void qt_core_c_QString_splitRef_to_output_QChar_QString_SplitBehavior(const QString* this_ptr, const QChar* sep, QString::SplitBehavior behavior, QVector< QStringRef >* output);
QT_CORE_C_EXPORT void qt_core_c_QString_splitRef_to_output_QChar_QString_SplitBehavior_Qt_CaseSensitivity(const QString* this_ptr, const QChar* sep, QString::SplitBehavior behavior, const Qt::CaseSensitivity* cs, QVector< QStringRef >* output);
QT_CORE_C_EXPORT void qt_core_c_QString_splitRef_to_output_QRegExp(const QString* this_ptr, const QRegExp* sep, QVector< QStringRef >* output);
QT_CORE_C_EXPORT void qt_core_c_QString_splitRef_to_output_QRegExp_QString_SplitBehavior(const QString* this_ptr, const QRegExp* sep, QString::SplitBehavior behavior, QVector< QStringRef >* output);
QT_CORE_C_EXPORT void qt_core_c_QString_splitRef_to_output_QRegularExpression(const QString* this_ptr, const QRegularExpression* sep, QVector< QStringRef >* output);
QT_CORE_C_EXPORT void qt_core_c_QString_splitRef_to_output_QRegularExpression_QString_SplitBehavior(const QString* this_ptr, const QRegularExpression* sep, QString::SplitBehavior behavior, QVector< QStringRef >* output);
QT_CORE_C_EXPORT void qt_core_c_QString_splitRef_to_output_QString(const QString* this_ptr, const QString* sep, QVector< QStringRef >* output);
QT_CORE_C_EXPORT void qt_core_c_QString_splitRef_to_output_QString_QString_SplitBehavior(const QString* this_ptr, const QString* sep, QString::SplitBehavior behavior, QVector< QStringRef >* output);
QT_CORE_C_EXPORT void qt_core_c_QString_splitRef_to_output_QString_QString_SplitBehavior_Qt_CaseSensitivity(const QString* this_ptr, const QString* sep, QString::SplitBehavior behavior, const Qt::CaseSensitivity* cs, QVector< QStringRef >* output);
QT_CORE_C_EXPORT void qt_core_c_QString_split_to_output_QChar(const QString* this_ptr, const QChar* sep, QStringList* output);
QT_CORE_C_EXPORT void qt_core_c_QString_split_to_output_QChar_QString_SplitBehavior(const QString* this_ptr, const QChar* sep, QString::SplitBehavior behavior, QStringList* output);
QT_CORE_C_EXPORT void qt_core_c_QString_split_to_output_QChar_QString_SplitBehavior_Qt_CaseSensitivity(const QString* this_ptr, const QChar* sep, QString::SplitBehavior behavior, const Qt::CaseSensitivity* cs, QStringList* output);
QT_CORE_C_EXPORT void qt_core_c_QString_split_to_output_QRegExp(const QString* this_ptr, const QRegExp* sep, QStringList* output);
QT_CORE_C_EXPORT void qt_core_c_QString_split_to_output_QRegExp_QString_SplitBehavior(const QString* this_ptr, const QRegExp* sep, QString::SplitBehavior behavior, QStringList* output);
QT_CORE_C_EXPORT void qt_core_c_QString_split_to_output_QRegularExpression(const QString* this_ptr, const QRegularExpression* sep, QStringList* output);
QT_CORE_C_EXPORT void qt_core_c_QString_split_to_output_QRegularExpression_QString_SplitBehavior(const QString* this_ptr, const QRegularExpression* sep, QString::SplitBehavior behavior, QStringList* output);
QT_CORE_C_EXPORT void qt_core_c_QString_split_to_output_QString(const QString* this_ptr, const QString* sep, QStringList* output);
QT_CORE_C_EXPORT void qt_core_c_QString_split_to_output_QString_QString_SplitBehavior(const QString* this_ptr, const QString* sep, QString::SplitBehavior behavior, QStringList* output);
QT_CORE_C_EXPORT void qt_core_c_QString_split_to_output_QString_QString_SplitBehavior_Qt_CaseSensitivity(const QString* this_ptr, const QString* sep, QString::SplitBehavior behavior, const Qt::CaseSensitivity* cs, QStringList* output);
QT_CORE_C_EXPORT void qt_core_c_QString_squeeze(QString* this_ptr);
QT_CORE_C_EXPORT bool qt_core_c_QString_startsWith_QChar(const QString* this_ptr, const QChar* c);
QT_CORE_C_EXPORT bool qt_core_c_QString_startsWith_QChar_Qt_CaseSensitivity(const QString* this_ptr, const QChar* c, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT bool qt_core_c_QString_startsWith_QLatin1String(const QString* this_ptr, const QLatin1String* s);
QT_CORE_C_EXPORT bool qt_core_c_QString_startsWith_QLatin1String_Qt_CaseSensitivity(const QString* this_ptr, const QLatin1String* s, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT bool qt_core_c_QString_startsWith_QString(const QString* this_ptr, const QString* s);
QT_CORE_C_EXPORT bool qt_core_c_QString_startsWith_QStringRef(const QString* this_ptr, const QStringRef* s);
QT_CORE_C_EXPORT bool qt_core_c_QString_startsWith_QStringRef_Qt_CaseSensitivity(const QString* this_ptr, const QStringRef* s, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT bool qt_core_c_QString_startsWith_QString_Qt_CaseSensitivity(const QString* this_ptr, const QString* s, const Qt::CaseSensitivity* cs);
QT_CORE_C_EXPORT void qt_core_c_QString_swap(QString* this_ptr, QString* other);
QT_CORE_C_EXPORT void qt_core_c_QString_toCaseFolded_to_output(QString* this_ptr, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_toCaseFolded_to_output_const(const QString* this_ptr, QString* output);
QT_CORE_C_EXPORT double qt_core_c_QString_toDouble_no_args(const QString* this_ptr);
QT_CORE_C_EXPORT double qt_core_c_QString_toDouble_ok(const QString* this_ptr, bool* ok);
QT_CORE_C_EXPORT float qt_core_c_QString_toFloat_no_args(const QString* this_ptr);
QT_CORE_C_EXPORT float qt_core_c_QString_toFloat_ok(const QString* this_ptr, bool* ok);
QT_CORE_C_EXPORT void qt_core_c_QString_toHtmlEscaped_to_output(const QString* this_ptr, QString* output);
QT_CORE_C_EXPORT int qt_core_c_QString_toInt_no_args(const QString* this_ptr);
QT_CORE_C_EXPORT int qt_core_c_QString_toInt_ok(const QString* this_ptr, bool* ok);
QT_CORE_C_EXPORT int qt_core_c_QString_toInt_ok_base(const QString* this_ptr, bool* ok, int base);
QT_CORE_C_EXPORT void qt_core_c_QString_toLatin1_to_output(const QString* this_ptr, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QString_toLocal8Bit_to_output(const QString* this_ptr, QByteArray* output);
QT_CORE_C_EXPORT qlonglong qt_core_c_QString_toLongLong_no_args(const QString* this_ptr);
QT_CORE_C_EXPORT qlonglong qt_core_c_QString_toLongLong_ok(const QString* this_ptr, bool* ok);
QT_CORE_C_EXPORT qlonglong qt_core_c_QString_toLongLong_ok_base(const QString* this_ptr, bool* ok, int base);
QT_CORE_C_EXPORT long qt_core_c_QString_toLong_no_args(const QString* this_ptr);
QT_CORE_C_EXPORT long qt_core_c_QString_toLong_ok(const QString* this_ptr, bool* ok);
QT_CORE_C_EXPORT long qt_core_c_QString_toLong_ok_base(const QString* this_ptr, bool* ok, int base);
QT_CORE_C_EXPORT void qt_core_c_QString_toLower_to_output(QString* this_ptr, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_toLower_to_output_const(const QString* this_ptr, QString* output);
QT_CORE_C_EXPORT short qt_core_c_QString_toShort_no_args(const QString* this_ptr);
QT_CORE_C_EXPORT short qt_core_c_QString_toShort_ok(const QString* this_ptr, bool* ok);
QT_CORE_C_EXPORT short qt_core_c_QString_toShort_ok_base(const QString* this_ptr, bool* ok, int base);
QT_CORE_C_EXPORT unsigned int qt_core_c_QString_toUInt_no_args(const QString* this_ptr);
QT_CORE_C_EXPORT unsigned int qt_core_c_QString_toUInt_ok(const QString* this_ptr, bool* ok);
QT_CORE_C_EXPORT unsigned int qt_core_c_QString_toUInt_ok_base(const QString* this_ptr, bool* ok, int base);
QT_CORE_C_EXPORT qulonglong qt_core_c_QString_toULongLong_no_args(const QString* this_ptr);
QT_CORE_C_EXPORT qulonglong qt_core_c_QString_toULongLong_ok(const QString* this_ptr, bool* ok);
QT_CORE_C_EXPORT qulonglong qt_core_c_QString_toULongLong_ok_base(const QString* this_ptr, bool* ok, int base);
QT_CORE_C_EXPORT unsigned long qt_core_c_QString_toULong_no_args(const QString* this_ptr);
QT_CORE_C_EXPORT unsigned long qt_core_c_QString_toULong_ok(const QString* this_ptr, bool* ok);
QT_CORE_C_EXPORT unsigned long qt_core_c_QString_toULong_ok_base(const QString* this_ptr, bool* ok, int base);
QT_CORE_C_EXPORT unsigned short qt_core_c_QString_toUShort_no_args(const QString* this_ptr);
QT_CORE_C_EXPORT unsigned short qt_core_c_QString_toUShort_ok(const QString* this_ptr, bool* ok);
QT_CORE_C_EXPORT unsigned short qt_core_c_QString_toUShort_ok_base(const QString* this_ptr, bool* ok, int base);
QT_CORE_C_EXPORT void qt_core_c_QString_toUcs4_to_output(const QString* this_ptr, QVector< unsigned int >* output);
QT_CORE_C_EXPORT void qt_core_c_QString_toUpper_to_output(QString* this_ptr, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_toUpper_to_output_const(const QString* this_ptr, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_toUtf8_to_output(const QString* this_ptr, QByteArray* output);
QT_CORE_C_EXPORT int qt_core_c_QString_toWCharArray(const QString* this_ptr, wchar_t* array);
QT_CORE_C_EXPORT void qt_core_c_QString_trimmed_to_output(QString* this_ptr, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_trimmed_to_output_const(const QString* this_ptr, QString* output);
QT_CORE_C_EXPORT void qt_core_c_QString_truncate(QString* this_ptr, int pos);
QT_CORE_C_EXPORT const QChar* qt_core_c_QString_unicode(const QString* this_ptr);
QT_CORE_C_EXPORT const unsigned short* qt_core_c_QString_utf16(const QString* this_ptr);

} // extern "C"

#endif // QT_CORE_C_QSTRING_H
