#ifndef QT_CORE_C_QBYTEARRAY_H
#define QT_CORE_C_QBYTEARRAY_H

#include "qt_core_c_global.h"

extern "C" {

QT_CORE_C_EXPORT void qt_core_c_QByteArray_G_operator_add_to_output_char_const_QByteArray_ref(char a1, const QByteArray* a2, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_G_operator_add_to_output_const_QByteArray_ref_char(const QByteArray* a1, char a2, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_G_operator_add_to_output_const_QByteArray_ref_const_QByteArray_ref(const QByteArray* a1, const QByteArray* a2, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_G_operator_add_to_output_const_QByteArray_ref_const_char_ptr(const QByteArray* a1, const char* a2, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_G_operator_add_to_output_const_char_ptr_const_QByteArray_ref(const char* a1, const QByteArray* a2, QByteArray* output);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_G_operator_eq_QByteArray_QByteArray(const QByteArray* a1, const QByteArray* a2);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_G_operator_eq_QByteArray_char(const QByteArray* a1, const char* a2);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_G_operator_eq_char_QByteArray(const char* a1, const QByteArray* a2);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_G_operator_ge_QByteArray_QByteArray(const QByteArray* a1, const QByteArray* a2);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_G_operator_ge_QByteArray_char(const QByteArray* a1, const char* a2);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_G_operator_ge_char_QByteArray(const char* a1, const QByteArray* a2);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_G_operator_gt_QByteArray_QByteArray(const QByteArray* a1, const QByteArray* a2);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_G_operator_gt_QByteArray_char(const QByteArray* a1, const char* a2);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_G_operator_gt_char_QByteArray(const char* a1, const QByteArray* a2);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_G_operator_le_QByteArray_QByteArray(const QByteArray* a1, const QByteArray* a2);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_G_operator_le_QByteArray_char(const QByteArray* a1, const char* a2);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_G_operator_le_char_QByteArray(const char* a1, const QByteArray* a2);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_G_operator_lt_QByteArray_QByteArray(const QByteArray* a1, const QByteArray* a2);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_G_operator_lt_QByteArray_char(const QByteArray* a1, const char* a2);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_G_operator_lt_char_QByteArray(const char* a1, const QByteArray* a2);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_G_operator_neq_QByteArray_QByteArray(const QByteArray* a1, const QByteArray* a2);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_G_operator_neq_QByteArray_char(const QByteArray* a1, const char* a2);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_G_operator_neq_char_QByteArray(const char* a1, const QByteArray* a2);
QT_CORE_C_EXPORT QDataStream* qt_core_c_QByteArray_G_operator_shl(QDataStream* arg1, const QByteArray* arg2);
QT_CORE_C_EXPORT QDataStream* qt_core_c_QByteArray_G_operator_shr(QDataStream* arg1, QByteArray* arg2);
QT_CORE_C_EXPORT quint16 qt_core_c_QByteArray_G_qChecksum_s_len(const char* s, unsigned int len);
QT_CORE_C_EXPORT quint16 qt_core_c_QByteArray_G_qChecksum_s_len_standard(const char* s, unsigned int len, const Qt::ChecksumType* standard);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_G_qCompress_to_output_data(const QByteArray* data, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_G_qCompress_to_output_data_compressionLevel(const QByteArray* data, int compressionLevel, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_G_qCompress_to_output_data_nbytes(const unsigned char* data, int nbytes, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_G_qCompress_to_output_data_nbytes_compressionLevel(const unsigned char* data, int nbytes, int compressionLevel, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_G_qUncompress_to_output(const QByteArray* data, QByteArray* output);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_G_qstrcmp_QByteArray_QByteArray(const QByteArray* str1, const QByteArray* str2);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_G_qstrcmp_QByteArray_char(const QByteArray* str1, const char* str2);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_G_qstrcmp_char_QByteArray(const char* str1, const QByteArray* str2);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_G_qstrcmp_char_char(const char* str1, const char* str2);
QT_CORE_C_EXPORT char* qt_core_c_QByteArray_G_qstrcpy(char* dst, const char* src);
QT_CORE_C_EXPORT char* qt_core_c_QByteArray_G_qstrdup(const char* arg1);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_G_qstricmp(const char* arg1, const char* arg2);
QT_CORE_C_EXPORT unsigned int qt_core_c_QByteArray_G_qstrlen(const char* str);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_G_qstrncmp(const char* str1, const char* str2, unsigned int len);
QT_CORE_C_EXPORT char* qt_core_c_QByteArray_G_qstrncpy(char* dst, const char* src, unsigned int len);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_G_qstrnicmp(const char* arg1, const char* arg2, unsigned int len);
QT_CORE_C_EXPORT unsigned int qt_core_c_QByteArray_G_qstrnlen(const char* str, unsigned int maxlen);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_G_swap(QByteArray* value1, QByteArray* value2);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_append_QByteArray_a(QByteArray* this_ptr, const QByteArray* a);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_append_QString_s(QByteArray* this_ptr, const QString* s);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_append_char_c(QByteArray* this_ptr, char c);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_append_char_s(QByteArray* this_ptr, const char* s);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_append_char_s_int_len(QByteArray* this_ptr, const char* s, int len);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_append_int_count_char_c(QByteArray* this_ptr, int count, char c);
QT_CORE_C_EXPORT char qt_core_c_QByteArray_at(const QByteArray* this_ptr, int i);
QT_CORE_C_EXPORT char* qt_core_c_QByteArray_begin(QByteArray* this_ptr);
QT_CORE_C_EXPORT const char* qt_core_c_QByteArray_begin_const(const QByteArray* this_ptr);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_capacity(const QByteArray* this_ptr);
QT_CORE_C_EXPORT const char* qt_core_c_QByteArray_cbegin(const QByteArray* this_ptr);
QT_CORE_C_EXPORT const char* qt_core_c_QByteArray_cend(const QByteArray* this_ptr);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_chop(QByteArray* this_ptr, int n);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_clear(QByteArray* this_ptr);
QT_CORE_C_EXPORT const char* qt_core_c_QByteArray_constBegin(const QByteArray* this_ptr);
QT_CORE_C_EXPORT const char* qt_core_c_QByteArray_constData(const QByteArray* this_ptr);
QT_CORE_C_EXPORT const char* qt_core_c_QByteArray_constEnd(const QByteArray* this_ptr);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_constructor_QByteArray(const QByteArray* arg1, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_constructor_char(const char* arg1, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_constructor_char_int(const char* arg1, int size, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_constructor_int_char(int size, char c, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_constructor_no_args(QByteArray* output);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_contains_QByteArray_a(const QByteArray* this_ptr, const QByteArray* a);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_contains_char_a(const QByteArray* this_ptr, const char* a);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_contains_char_c(const QByteArray* this_ptr, char c);
QT_CORE_C_EXPORT const char* qt_core_c_QByteArray_convert_to_const_char_ptr(const QByteArray* this_ptr);
QT_CORE_C_EXPORT const void* qt_core_c_QByteArray_convert_to_const_void_ptr(const QByteArray* this_ptr);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_count_QByteArray_a(const QByteArray* this_ptr, const QByteArray* a);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_count_char_a(const QByteArray* this_ptr, const char* a);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_count_char_c(const QByteArray* this_ptr, char c);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_count_no_args(const QByteArray* this_ptr);
QT_CORE_C_EXPORT char* qt_core_c_QByteArray_data(QByteArray* this_ptr);
QT_CORE_C_EXPORT const char* qt_core_c_QByteArray_data_const(const QByteArray* this_ptr);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_destructor(QByteArray* this_ptr);
QT_CORE_C_EXPORT char* qt_core_c_QByteArray_end(QByteArray* this_ptr);
QT_CORE_C_EXPORT const char* qt_core_c_QByteArray_end_const(const QByteArray* this_ptr);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_endsWith_char(const QByteArray* this_ptr, char c);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_endsWith_const_QByteArray_ref(const QByteArray* this_ptr, const QByteArray* a);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_endsWith_const_char_ptr(const QByteArray* this_ptr, const char* c);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_fill_c(QByteArray* this_ptr, char c);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_fill_c_size(QByteArray* this_ptr, char c, int size);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_fromBase64_to_output_base64(const QByteArray* base64, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_fromBase64_to_output_base64_options(const QByteArray* base64, unsigned int options, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_fromHex_to_output(const QByteArray* hexEncoded, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_fromPercentEncoding_to_output_pctEncoded(const QByteArray* pctEncoded, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_fromPercentEncoding_to_output_pctEncoded_percent(const QByteArray* pctEncoded, char percent, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_fromRawData_to_output(const char* arg1, int size, QByteArray* output);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_indexOf_char(const QByteArray* this_ptr, char c);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_indexOf_char_int(const QByteArray* this_ptr, char c, int from);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_indexOf_const_QByteArray_ref(const QByteArray* this_ptr, const QByteArray* a);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_indexOf_const_QByteArray_ref_int(const QByteArray* this_ptr, const QByteArray* a, int from);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_indexOf_const_QString_ref(const QByteArray* this_ptr, const QString* s);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_indexOf_const_QString_ref_int(const QByteArray* this_ptr, const QString* s, int from);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_indexOf_const_char_ptr(const QByteArray* this_ptr, const char* c);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_indexOf_const_char_ptr_int(const QByteArray* this_ptr, const char* c, int from);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_insert_int_i_QByteArray_a(QByteArray* this_ptr, int i, const QByteArray* a);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_insert_int_i_QString_s(QByteArray* this_ptr, int i, const QString* s);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_insert_int_i_char_c(QByteArray* this_ptr, int i, char c);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_insert_int_i_char_s(QByteArray* this_ptr, int i, const char* s);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_insert_int_i_char_s_int_len(QByteArray* this_ptr, int i, const char* s, int len);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_insert_int_i_int_count_char_c(QByteArray* this_ptr, int i, int count, char c);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_isEmpty(const QByteArray* this_ptr);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_isNull(const QByteArray* this_ptr);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_lastIndexOf_char(const QByteArray* this_ptr, char c);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_lastIndexOf_char_int(const QByteArray* this_ptr, char c, int from);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_lastIndexOf_const_QByteArray_ref(const QByteArray* this_ptr, const QByteArray* a);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_lastIndexOf_const_QByteArray_ref_int(const QByteArray* this_ptr, const QByteArray* a, int from);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_lastIndexOf_const_QString_ref(const QByteArray* this_ptr, const QString* s);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_lastIndexOf_const_QString_ref_int(const QByteArray* this_ptr, const QString* s, int from);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_lastIndexOf_const_char_ptr(const QByteArray* this_ptr, const char* c);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_lastIndexOf_const_char_ptr_int(const QByteArray* this_ptr, const char* c, int from);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_leftJustified_to_output_width(const QByteArray* this_ptr, int width, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_leftJustified_to_output_width_fill(const QByteArray* this_ptr, int width, char fill, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_leftJustified_to_output_width_fill_truncate(const QByteArray* this_ptr, int width, char fill, bool truncate, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_left_to_output(const QByteArray* this_ptr, int len, QByteArray* output);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_length(const QByteArray* this_ptr);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_mid_to_output_index(const QByteArray* this_ptr, int index, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_mid_to_output_index_len(const QByteArray* this_ptr, int index, int len, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_number_to_output_double(double arg1, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_number_to_output_double_char(double arg1, char f, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_number_to_output_double_char_int(double arg1, char f, int prec, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_number_to_output_int(int arg1, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_number_to_output_int_int(int arg1, int base, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_number_to_output_qlonglong(qlonglong arg1, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_number_to_output_qlonglong_int(qlonglong arg1, int base, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_number_to_output_qulonglong(qulonglong arg1, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_number_to_output_qulonglong_int(qulonglong arg1, int base, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_number_to_output_unsigned_int(unsigned int arg1, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_number_to_output_unsigned_int_int(unsigned int arg1, int base, QByteArray* output);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_operator_add_assign_QByteArray_a(QByteArray* this_ptr, const QByteArray* a);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_operator_add_assign_QString_s(QByteArray* this_ptr, const QString* s);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_operator_add_assign_char_c(QByteArray* this_ptr, char c);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_operator_add_assign_char_s(QByteArray* this_ptr, const char* s);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_operator_assign_arg1(QByteArray* this_ptr, const QByteArray* arg1);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_operator_assign_str(QByteArray* this_ptr, const char* str);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_operator_eq(const QByteArray* this_ptr, const QString* s2);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_operator_ge(const QByteArray* this_ptr, const QString* s2);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_operator_gt(const QByteArray* this_ptr, const QString* s2);
QT_CORE_C_EXPORT char qt_core_c_QByteArray_operator_index_int(const QByteArray* this_ptr, int i);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_operator_index_to_output_int(QByteArray* this_ptr, int i, QByteRef* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_operator_index_to_output_unsigned_int(QByteArray* this_ptr, unsigned int i, QByteRef* output);
QT_CORE_C_EXPORT char qt_core_c_QByteArray_operator_index_unsigned_int(const QByteArray* this_ptr, unsigned int i);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_operator_le(const QByteArray* this_ptr, const QString* s2);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_operator_lt(const QByteArray* this_ptr, const QString* s2);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_operator_neq(const QByteArray* this_ptr, const QString* s2);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_prepend_a(QByteArray* this_ptr, const QByteArray* a);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_prepend_c(QByteArray* this_ptr, char c);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_prepend_count_c(QByteArray* this_ptr, int count, char c);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_prepend_s(QByteArray* this_ptr, const char* s);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_prepend_s_len(QByteArray* this_ptr, const char* s, int len);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_push_back_char(QByteArray* this_ptr, char c);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_push_back_const_QByteArray_ref(QByteArray* this_ptr, const QByteArray* a);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_push_back_const_char_ptr(QByteArray* this_ptr, const char* c);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_push_front_char(QByteArray* this_ptr, char c);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_push_front_const_QByteArray_ref(QByteArray* this_ptr, const QByteArray* a);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_push_front_const_char_ptr(QByteArray* this_ptr, const char* c);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_remove(QByteArray* this_ptr, int index, int len);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_repeated_to_output(const QByteArray* this_ptr, int times, QByteArray* output);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_replace_char_char(QByteArray* this_ptr, char before, char after);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_replace_char_const_QByteArray_ref(QByteArray* this_ptr, char before, const QByteArray* after);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_replace_char_const_QString_ref(QByteArray* this_ptr, char c, const QString* after);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_replace_char_const_char_ptr(QByteArray* this_ptr, char before, const char* after);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_replace_const_QByteArray_ref_const_QByteArray_ref(QByteArray* this_ptr, const QByteArray* before, const QByteArray* after);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_replace_const_QByteArray_ref_const_char_ptr(QByteArray* this_ptr, const QByteArray* before, const char* after);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_replace_const_QString_ref_const_QByteArray_ref(QByteArray* this_ptr, const QString* before, const QByteArray* after);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_replace_const_QString_ref_const_char_ptr(QByteArray* this_ptr, const QString* before, const char* after);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_replace_const_char_ptr_const_QByteArray_ref(QByteArray* this_ptr, const char* before, const QByteArray* after);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_replace_const_char_ptr_const_char_ptr(QByteArray* this_ptr, const char* before, const char* after);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_replace_const_char_ptr_int_const_char_ptr_int(QByteArray* this_ptr, const char* before, int bsize, const char* after, int asize);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_replace_int_int_const_QByteArray_ref(QByteArray* this_ptr, int index, int len, const QByteArray* s);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_replace_int_int_const_char_ptr(QByteArray* this_ptr, int index, int len, const char* s);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_replace_int_int_const_char_ptr_int(QByteArray* this_ptr, int index, int len, const char* s, int alen);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_reserve(QByteArray* this_ptr, int size);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_resize(QByteArray* this_ptr, int size);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_rightJustified_to_output_width(const QByteArray* this_ptr, int width, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_rightJustified_to_output_width_fill(const QByteArray* this_ptr, int width, char fill, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_rightJustified_to_output_width_fill_truncate(const QByteArray* this_ptr, int width, char fill, bool truncate, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_right_to_output(const QByteArray* this_ptr, int len, QByteArray* output);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_setNum_double(QByteArray* this_ptr, double arg1);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_setNum_double_char(QByteArray* this_ptr, double arg1, char f);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_setNum_double_char_int(QByteArray* this_ptr, double arg1, char f, int prec);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_setNum_float(QByteArray* this_ptr, float arg1);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_setNum_float_char(QByteArray* this_ptr, float arg1, char f);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_setNum_float_char_int(QByteArray* this_ptr, float arg1, char f, int prec);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_setNum_int(QByteArray* this_ptr, int arg1);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_setNum_int_int(QByteArray* this_ptr, int arg1, int base);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_setNum_qlonglong(QByteArray* this_ptr, qlonglong arg1);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_setNum_qlonglong_int(QByteArray* this_ptr, qlonglong arg1, int base);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_setNum_qulonglong(QByteArray* this_ptr, qulonglong arg1);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_setNum_qulonglong_int(QByteArray* this_ptr, qulonglong arg1, int base);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_setNum_short(QByteArray* this_ptr, short arg1);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_setNum_short_int(QByteArray* this_ptr, short arg1, int base);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_setNum_unsigned_int(QByteArray* this_ptr, unsigned int arg1);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_setNum_unsigned_int_int(QByteArray* this_ptr, unsigned int arg1, int base);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_setNum_unsigned_short(QByteArray* this_ptr, unsigned short arg1);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_setNum_unsigned_short_int(QByteArray* this_ptr, unsigned short arg1, int base);
QT_CORE_C_EXPORT QByteArray* qt_core_c_QByteArray_setRawData(QByteArray* this_ptr, const char* a, unsigned int n);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_simplified_to_output(QByteArray* this_ptr, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_simplified_to_output_const(const QByteArray* this_ptr, QByteArray* output);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_size(const QByteArray* this_ptr);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_split_to_output(const QByteArray* this_ptr, char sep, QList< QByteArray >* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_squeeze(QByteArray* this_ptr);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_startsWith_char(const QByteArray* this_ptr, char c);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_startsWith_const_QByteArray_ref(const QByteArray* this_ptr, const QByteArray* a);
QT_CORE_C_EXPORT bool qt_core_c_QByteArray_startsWith_const_char_ptr(const QByteArray* this_ptr, const char* c);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_swap(QByteArray* this_ptr, QByteArray* other);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_toBase64_to_output_no_args(const QByteArray* this_ptr, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_toBase64_to_output_options(const QByteArray* this_ptr, unsigned int options, QByteArray* output);
QT_CORE_C_EXPORT double qt_core_c_QByteArray_toDouble_no_args(const QByteArray* this_ptr);
QT_CORE_C_EXPORT double qt_core_c_QByteArray_toDouble_ok(const QByteArray* this_ptr, bool* ok);
QT_CORE_C_EXPORT float qt_core_c_QByteArray_toFloat_no_args(const QByteArray* this_ptr);
QT_CORE_C_EXPORT float qt_core_c_QByteArray_toFloat_ok(const QByteArray* this_ptr, bool* ok);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_toHex_to_output_no_args(const QByteArray* this_ptr, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_toHex_to_output_separator(const QByteArray* this_ptr, char separator, QByteArray* output);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_toInt_no_args(const QByteArray* this_ptr);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_toInt_ok(const QByteArray* this_ptr, bool* ok);
QT_CORE_C_EXPORT int qt_core_c_QByteArray_toInt_ok_base(const QByteArray* this_ptr, bool* ok, int base);
QT_CORE_C_EXPORT qlonglong qt_core_c_QByteArray_toLongLong_no_args(const QByteArray* this_ptr);
QT_CORE_C_EXPORT qlonglong qt_core_c_QByteArray_toLongLong_ok(const QByteArray* this_ptr, bool* ok);
QT_CORE_C_EXPORT qlonglong qt_core_c_QByteArray_toLongLong_ok_base(const QByteArray* this_ptr, bool* ok, int base);
QT_CORE_C_EXPORT long qt_core_c_QByteArray_toLong_no_args(const QByteArray* this_ptr);
QT_CORE_C_EXPORT long qt_core_c_QByteArray_toLong_ok(const QByteArray* this_ptr, bool* ok);
QT_CORE_C_EXPORT long qt_core_c_QByteArray_toLong_ok_base(const QByteArray* this_ptr, bool* ok, int base);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_toLower_to_output(QByteArray* this_ptr, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_toLower_to_output_const(const QByteArray* this_ptr, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_toPercentEncoding_to_output_exclude(const QByteArray* this_ptr, const QByteArray* exclude, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_toPercentEncoding_to_output_exclude_include(const QByteArray* this_ptr, const QByteArray* exclude, const QByteArray* include, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_toPercentEncoding_to_output_exclude_include_percent(const QByteArray* this_ptr, const QByteArray* exclude, const QByteArray* include, char percent, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_toPercentEncoding_to_output_no_args(const QByteArray* this_ptr, QByteArray* output);
QT_CORE_C_EXPORT short qt_core_c_QByteArray_toShort_no_args(const QByteArray* this_ptr);
QT_CORE_C_EXPORT short qt_core_c_QByteArray_toShort_ok(const QByteArray* this_ptr, bool* ok);
QT_CORE_C_EXPORT short qt_core_c_QByteArray_toShort_ok_base(const QByteArray* this_ptr, bool* ok, int base);
QT_CORE_C_EXPORT unsigned int qt_core_c_QByteArray_toUInt_no_args(const QByteArray* this_ptr);
QT_CORE_C_EXPORT unsigned int qt_core_c_QByteArray_toUInt_ok(const QByteArray* this_ptr, bool* ok);
QT_CORE_C_EXPORT unsigned int qt_core_c_QByteArray_toUInt_ok_base(const QByteArray* this_ptr, bool* ok, int base);
QT_CORE_C_EXPORT qulonglong qt_core_c_QByteArray_toULongLong_no_args(const QByteArray* this_ptr);
QT_CORE_C_EXPORT qulonglong qt_core_c_QByteArray_toULongLong_ok(const QByteArray* this_ptr, bool* ok);
QT_CORE_C_EXPORT qulonglong qt_core_c_QByteArray_toULongLong_ok_base(const QByteArray* this_ptr, bool* ok, int base);
QT_CORE_C_EXPORT unsigned long qt_core_c_QByteArray_toULong_no_args(const QByteArray* this_ptr);
QT_CORE_C_EXPORT unsigned long qt_core_c_QByteArray_toULong_ok(const QByteArray* this_ptr, bool* ok);
QT_CORE_C_EXPORT unsigned long qt_core_c_QByteArray_toULong_ok_base(const QByteArray* this_ptr, bool* ok, int base);
QT_CORE_C_EXPORT unsigned short qt_core_c_QByteArray_toUShort_no_args(const QByteArray* this_ptr);
QT_CORE_C_EXPORT unsigned short qt_core_c_QByteArray_toUShort_ok(const QByteArray* this_ptr, bool* ok);
QT_CORE_C_EXPORT unsigned short qt_core_c_QByteArray_toUShort_ok_base(const QByteArray* this_ptr, bool* ok, int base);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_toUpper_to_output(QByteArray* this_ptr, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_toUpper_to_output_const(const QByteArray* this_ptr, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_trimmed_to_output(QByteArray* this_ptr, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_trimmed_to_output_const(const QByteArray* this_ptr, QByteArray* output);
QT_CORE_C_EXPORT void qt_core_c_QByteArray_truncate(QByteArray* this_ptr, int pos);

} // extern "C"

#endif // QT_CORE_C_QBYTEARRAY_H
