#ifndef QT_GUI_C_QACCESSIBLETEXTINSERTEVENT_H
#define QT_GUI_C_QACCESSIBLETEXTINSERTEVENT_H

#include "qt_gui_c_global.h"

extern "C" {

QT_GUI_C_EXPORT QAccessibleTextInsertEvent* qt_gui_c_QAccessibleTextInsertEvent_G_dynamic_cast_QAccessibleTextInsertEvent_ptr_QAccessibleEvent(QAccessibleEvent* ptr);
QT_GUI_C_EXPORT QAccessibleTextInsertEvent* qt_gui_c_QAccessibleTextInsertEvent_G_dynamic_cast_QAccessibleTextInsertEvent_ptr_QAccessibleTextCursorEvent(QAccessibleTextCursorEvent* ptr);
QT_GUI_C_EXPORT QAccessibleEvent* qt_gui_c_QAccessibleTextInsertEvent_G_static_cast_QAccessibleEvent_ptr(QAccessibleTextInsertEvent* ptr);
QT_GUI_C_EXPORT QAccessibleTextCursorEvent* qt_gui_c_QAccessibleTextInsertEvent_G_static_cast_QAccessibleTextCursorEvent_ptr(QAccessibleTextInsertEvent* ptr);
QT_GUI_C_EXPORT QAccessibleTextInsertEvent* qt_gui_c_QAccessibleTextInsertEvent_G_static_cast_QAccessibleTextInsertEvent_ptr_QAccessibleEvent(QAccessibleEvent* ptr);
QT_GUI_C_EXPORT QAccessibleTextInsertEvent* qt_gui_c_QAccessibleTextInsertEvent_G_static_cast_QAccessibleTextInsertEvent_ptr_QAccessibleTextCursorEvent(QAccessibleTextCursorEvent* ptr);
QT_GUI_C_EXPORT int qt_gui_c_QAccessibleTextInsertEvent_changePosition(const QAccessibleTextInsertEvent* this_ptr);
QT_GUI_C_EXPORT void qt_gui_c_QAccessibleTextInsertEvent_delete(QAccessibleTextInsertEvent* this_ptr);
QT_GUI_C_EXPORT QAccessibleTextInsertEvent* qt_gui_c_QAccessibleTextInsertEvent_new_iface_position_text(QAccessibleInterface* iface, int position, const QString* text);
QT_GUI_C_EXPORT QAccessibleTextInsertEvent* qt_gui_c_QAccessibleTextInsertEvent_new_obj_position_text(QObject* obj, int position, const QString* text);
QT_GUI_C_EXPORT void qt_gui_c_QAccessibleTextInsertEvent_textInserted_to_output(const QAccessibleTextInsertEvent* this_ptr, QString* output);

} // extern "C"

#endif // QT_GUI_C_QACCESSIBLETEXTINSERTEVENT_H
