#ifndef QT_GUI_C_QACCESSIBLETEXTSELECTIONEVENT_H
#define QT_GUI_C_QACCESSIBLETEXTSELECTIONEVENT_H

#include "qt_gui_c_global.h"

extern "C" {

QT_GUI_C_EXPORT QAccessibleTextSelectionEvent* qt_gui_c_QAccessibleTextSelectionEvent_G_dynamic_cast_QAccessibleTextSelectionEvent_ptr_QAccessibleEvent(QAccessibleEvent* ptr);
QT_GUI_C_EXPORT QAccessibleTextSelectionEvent* qt_gui_c_QAccessibleTextSelectionEvent_G_dynamic_cast_QAccessibleTextSelectionEvent_ptr_QAccessibleTextCursorEvent(QAccessibleTextCursorEvent* ptr);
QT_GUI_C_EXPORT QAccessibleEvent* qt_gui_c_QAccessibleTextSelectionEvent_G_static_cast_QAccessibleEvent_ptr(QAccessibleTextSelectionEvent* ptr);
QT_GUI_C_EXPORT QAccessibleTextCursorEvent* qt_gui_c_QAccessibleTextSelectionEvent_G_static_cast_QAccessibleTextCursorEvent_ptr(QAccessibleTextSelectionEvent* ptr);
QT_GUI_C_EXPORT QAccessibleTextSelectionEvent* qt_gui_c_QAccessibleTextSelectionEvent_G_static_cast_QAccessibleTextSelectionEvent_ptr_QAccessibleEvent(QAccessibleEvent* ptr);
QT_GUI_C_EXPORT QAccessibleTextSelectionEvent* qt_gui_c_QAccessibleTextSelectionEvent_G_static_cast_QAccessibleTextSelectionEvent_ptr_QAccessibleTextCursorEvent(QAccessibleTextCursorEvent* ptr);
QT_GUI_C_EXPORT void qt_gui_c_QAccessibleTextSelectionEvent_delete(QAccessibleTextSelectionEvent* this_ptr);
QT_GUI_C_EXPORT QAccessibleTextSelectionEvent* qt_gui_c_QAccessibleTextSelectionEvent_new_iface_start_end(QAccessibleInterface* iface, int start, int end);
QT_GUI_C_EXPORT QAccessibleTextSelectionEvent* qt_gui_c_QAccessibleTextSelectionEvent_new_obj_start_end(QObject* obj, int start, int end);
QT_GUI_C_EXPORT int qt_gui_c_QAccessibleTextSelectionEvent_selectionEnd(const QAccessibleTextSelectionEvent* this_ptr);
QT_GUI_C_EXPORT int qt_gui_c_QAccessibleTextSelectionEvent_selectionStart(const QAccessibleTextSelectionEvent* this_ptr);
QT_GUI_C_EXPORT void qt_gui_c_QAccessibleTextSelectionEvent_setSelection(QAccessibleTextSelectionEvent* this_ptr, int start, int end);

} // extern "C"

#endif // QT_GUI_C_QACCESSIBLETEXTSELECTIONEVENT_H
