#ifndef QT_GUI_C_QIMAGE_H
#define QT_GUI_C_QIMAGE_H

#include "qt_gui_c_global.h"

extern "C" {

QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_G_dynamic_cast_QImage_ptr(QPaintDevice* ptr);
QT_GUI_C_EXPORT QDataStream* qt_gui_c_QImage_G_operator_shl(QDataStream* arg1, const QImage* arg2);
QT_GUI_C_EXPORT void qt_gui_c_QImage_G_operator_shl_to_output(const QDebug* arg1, const QImage* arg2, QDebug* output);
QT_GUI_C_EXPORT QDataStream* qt_gui_c_QImage_G_operator_shr(QDataStream* arg1, QImage* arg2);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_G_static_cast_QImage_ptr(QPaintDevice* ptr);
QT_GUI_C_EXPORT QPaintDevice* qt_gui_c_QImage_G_static_cast_QPaintDevice_ptr(QImage* ptr);
QT_GUI_C_EXPORT void qt_gui_c_QImage_G_swap(QImage* value1, QImage* value2);
QT_GUI_C_EXPORT bool qt_gui_c_QImage_allGray(const QImage* this_ptr);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_alphaChannel_as_ptr(const QImage* this_ptr);
QT_GUI_C_EXPORT int qt_gui_c_QImage_bitPlaneCount(const QImage* this_ptr);
QT_GUI_C_EXPORT unsigned char* qt_gui_c_QImage_bits(QImage* this_ptr);
QT_GUI_C_EXPORT const unsigned char* qt_gui_c_QImage_bits_const(const QImage* this_ptr);
QT_GUI_C_EXPORT int qt_gui_c_QImage_byteCount(const QImage* this_ptr);
QT_GUI_C_EXPORT int qt_gui_c_QImage_bytesPerLine(const QImage* this_ptr);
QT_GUI_C_EXPORT qint64 qt_gui_c_QImage_cacheKey(const QImage* this_ptr);
QT_GUI_C_EXPORT unsigned int qt_gui_c_QImage_color(const QImage* this_ptr, int i);
QT_GUI_C_EXPORT int qt_gui_c_QImage_colorCount(const QImage* this_ptr);
QT_GUI_C_EXPORT void qt_gui_c_QImage_colorTable_to_output(const QImage* this_ptr, QVector< unsigned int >* output);
QT_GUI_C_EXPORT const unsigned char* qt_gui_c_QImage_constBits(const QImage* this_ptr);
QT_GUI_C_EXPORT const unsigned char* qt_gui_c_QImage_constScanLine(const QImage* this_ptr, int arg1);
QT_GUI_C_EXPORT void qt_gui_c_QImage_convert_to_QVariant_to_output(const QImage* this_ptr, QVariant* output);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_copy_as_ptr_no_args(const QImage* this_ptr);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_copy_as_ptr_rect(const QImage* this_ptr, const QRect* rect);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_copy_as_ptr_x_y_w_h(const QImage* this_ptr, int x, int y, int w, int h);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_createHeuristicMask_as_ptr_clipTight(const QImage* this_ptr, bool clipTight);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_createHeuristicMask_as_ptr_no_args(const QImage* this_ptr);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_createMaskFromColor_as_ptr_color(const QImage* this_ptr, unsigned int color);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_createMaskFromColor_as_ptr_color_mode(const QImage* this_ptr, unsigned int color, const Qt::MaskMode* mode);
QT_GUI_C_EXPORT void qt_gui_c_QImage_delete(QImage* this_ptr);
QT_GUI_C_EXPORT int qt_gui_c_QImage_depth(const QImage* this_ptr);
QT_GUI_C_EXPORT void qt_gui_c_QImage_detach(QImage* this_ptr);
QT_GUI_C_EXPORT int qt_gui_c_QImage_devType(const QImage* this_ptr);
QT_GUI_C_EXPORT double qt_gui_c_QImage_devicePixelRatio(const QImage* this_ptr);
QT_GUI_C_EXPORT int qt_gui_c_QImage_dotsPerMeterX(const QImage* this_ptr);
QT_GUI_C_EXPORT int qt_gui_c_QImage_dotsPerMeterY(const QImage* this_ptr);
QT_GUI_C_EXPORT void qt_gui_c_QImage_fill_QColor(QImage* this_ptr, const QColor* color);
QT_GUI_C_EXPORT void qt_gui_c_QImage_fill_Qt_GlobalColor(QImage* this_ptr, const Qt::GlobalColor* color);
QT_GUI_C_EXPORT void qt_gui_c_QImage_fill_unsigned_int(QImage* this_ptr, unsigned int pixel);
QT_GUI_C_EXPORT QImage::Format qt_gui_c_QImage_format(const QImage* this_ptr);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_fromData_as_ptr_data(const QByteArray* data);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_fromData_as_ptr_data_format(const QByteArray* data, const char* format);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_fromData_as_ptr_data_size(const unsigned char* data, int size);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_fromData_as_ptr_data_size_format(const unsigned char* data, int size, const char* format);
QT_GUI_C_EXPORT bool qt_gui_c_QImage_hasAlphaChannel(const QImage* this_ptr);
QT_GUI_C_EXPORT int qt_gui_c_QImage_height(const QImage* this_ptr);
QT_GUI_C_EXPORT void qt_gui_c_QImage_invertPixels_arg1(QImage* this_ptr, QImage::InvertMode arg1);
QT_GUI_C_EXPORT void qt_gui_c_QImage_invertPixels_no_args(QImage* this_ptr);
QT_GUI_C_EXPORT bool qt_gui_c_QImage_isDetached(const QImage* this_ptr);
QT_GUI_C_EXPORT bool qt_gui_c_QImage_isGrayscale(const QImage* this_ptr);
QT_GUI_C_EXPORT bool qt_gui_c_QImage_isNull(const QImage* this_ptr);
QT_GUI_C_EXPORT bool qt_gui_c_QImage_loadFromData_buf_len(QImage* this_ptr, const unsigned char* buf, int len);
QT_GUI_C_EXPORT bool qt_gui_c_QImage_loadFromData_buf_len_format(QImage* this_ptr, const unsigned char* buf, int len, const char* format);
QT_GUI_C_EXPORT bool qt_gui_c_QImage_loadFromData_data(QImage* this_ptr, const QByteArray* data);
QT_GUI_C_EXPORT bool qt_gui_c_QImage_loadFromData_data_aformat(QImage* this_ptr, const QByteArray* data, const char* aformat);
QT_GUI_C_EXPORT bool qt_gui_c_QImage_load_device_format(QImage* this_ptr, QIODevice* device, const char* format);
QT_GUI_C_EXPORT bool qt_gui_c_QImage_load_fileName(QImage* this_ptr, const QString* fileName);
QT_GUI_C_EXPORT bool qt_gui_c_QImage_load_fileName_format(QImage* this_ptr, const QString* fileName, const char* format);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_mirrored_as_ptr_horizontally(const QImage* this_ptr, bool horizontally);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_mirrored_as_ptr_horizontally_vertically(const QImage* this_ptr, bool horizontally, bool vertically);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_mirrored_as_ptr_no_args(const QImage* this_ptr);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_new_const_QImage_ref(const QImage* arg1);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_new_const_QSize_ref_QImage_Format(const QSize* size, QImage::Format format);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_new_const_QString_ref(const QString* fileName);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_new_const_QString_ref_const_char_ptr(const QString* fileName, const char* format);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_new_const_unsigned_char_ptr_int_int_QImage_Format(const unsigned char* data, int width, int height, QImage::Format format);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_new_const_unsigned_char_ptr_int_int_QImage_Format_void_func_void_ptr(const unsigned char* data, int width, int height, QImage::Format format, void (*cleanupFunction)(void*));
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_new_const_unsigned_char_ptr_int_int_QImage_Format_void_func_void_ptr_void_ptr(const unsigned char* data, int width, int height, QImage::Format format, void (*cleanupFunction)(void*), void* cleanupInfo);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_new_const_unsigned_char_ptr_int_int_int_QImage_Format(const unsigned char* data, int width, int height, int bytesPerLine, QImage::Format format);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_new_const_unsigned_char_ptr_int_int_int_QImage_Format_void_func_void_ptr(const unsigned char* data, int width, int height, int bytesPerLine, QImage::Format format, void (*cleanupFunction)(void*));
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_new_const_unsigned_char_ptr_int_int_int_QImage_Format_void_func_void_ptr_void_ptr(const unsigned char* data, int width, int height, int bytesPerLine, QImage::Format format, void (*cleanupFunction)(void*), void* cleanupInfo);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_new_int_int_QImage_Format(int width, int height, QImage::Format format);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_new_no_args();
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_new_unsigned_char_ptr_int_int_QImage_Format(unsigned char* data, int width, int height, QImage::Format format);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_new_unsigned_char_ptr_int_int_QImage_Format_void_func_void_ptr(unsigned char* data, int width, int height, QImage::Format format, void (*cleanupFunction)(void*));
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_new_unsigned_char_ptr_int_int_QImage_Format_void_func_void_ptr_void_ptr(unsigned char* data, int width, int height, QImage::Format format, void (*cleanupFunction)(void*), void* cleanupInfo);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_new_unsigned_char_ptr_int_int_int_QImage_Format(unsigned char* data, int width, int height, int bytesPerLine, QImage::Format format);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_new_unsigned_char_ptr_int_int_int_QImage_Format_void_func_void_ptr(unsigned char* data, int width, int height, int bytesPerLine, QImage::Format format, void (*cleanupFunction)(void*));
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_new_unsigned_char_ptr_int_int_int_QImage_Format_void_func_void_ptr_void_ptr(unsigned char* data, int width, int height, int bytesPerLine, QImage::Format format, void (*cleanupFunction)(void*), void* cleanupInfo);
QT_GUI_C_EXPORT void qt_gui_c_QImage_offset_to_output(const QImage* this_ptr, QPoint* output);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_operator_assign(QImage* this_ptr, const QImage* arg1);
QT_GUI_C_EXPORT bool qt_gui_c_QImage_operator_eq(const QImage* this_ptr, const QImage* arg1);
QT_GUI_C_EXPORT bool qt_gui_c_QImage_operator_neq(const QImage* this_ptr, const QImage* arg1);
QT_GUI_C_EXPORT QPaintEngine* qt_gui_c_QImage_paintEngine(const QImage* this_ptr);
QT_GUI_C_EXPORT void qt_gui_c_QImage_pixelColor_to_output_pt(const QImage* this_ptr, const QPoint* pt, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QImage_pixelColor_to_output_x_y(const QImage* this_ptr, int x, int y, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QImage_pixelFormat_to_output(const QImage* this_ptr, QPixelFormat* output);
QT_GUI_C_EXPORT int qt_gui_c_QImage_pixelIndex_pt(const QImage* this_ptr, const QPoint* pt);
QT_GUI_C_EXPORT int qt_gui_c_QImage_pixelIndex_x_y(const QImage* this_ptr, int x, int y);
QT_GUI_C_EXPORT unsigned int qt_gui_c_QImage_pixel_pt(const QImage* this_ptr, const QPoint* pt);
QT_GUI_C_EXPORT unsigned int qt_gui_c_QImage_pixel_x_y(const QImage* this_ptr, int x, int y);
QT_GUI_C_EXPORT void qt_gui_c_QImage_rect_to_output(const QImage* this_ptr, QRect* output);
QT_GUI_C_EXPORT bool qt_gui_c_QImage_reinterpretAsFormat(QImage* this_ptr, QImage::Format f);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_rgbSwapped_as_ptr(const QImage* this_ptr);
QT_GUI_C_EXPORT bool qt_gui_c_QImage_save_device(const QImage* this_ptr, QIODevice* device);
QT_GUI_C_EXPORT bool qt_gui_c_QImage_save_device_format(const QImage* this_ptr, QIODevice* device, const char* format);
QT_GUI_C_EXPORT bool qt_gui_c_QImage_save_device_format_quality(const QImage* this_ptr, QIODevice* device, const char* format, int quality);
QT_GUI_C_EXPORT bool qt_gui_c_QImage_save_fileName(const QImage* this_ptr, const QString* fileName);
QT_GUI_C_EXPORT bool qt_gui_c_QImage_save_fileName_format(const QImage* this_ptr, const QString* fileName, const char* format);
QT_GUI_C_EXPORT bool qt_gui_c_QImage_save_fileName_format_quality(const QImage* this_ptr, const QString* fileName, const char* format, int quality);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_scaledToHeight_as_ptr_h(const QImage* this_ptr, int h);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_scaledToHeight_as_ptr_h_mode(const QImage* this_ptr, int h, const Qt::TransformationMode* mode);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_scaledToWidth_as_ptr_w(const QImage* this_ptr, int w);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_scaledToWidth_as_ptr_w_mode(const QImage* this_ptr, int w, const Qt::TransformationMode* mode);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_scaled_as_ptr_s(const QImage* this_ptr, const QSize* s);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_scaled_as_ptr_s_aspectMode(const QImage* this_ptr, const QSize* s, const Qt::AspectRatioMode* aspectMode);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_scaled_as_ptr_s_aspectMode_mode(const QImage* this_ptr, const QSize* s, const Qt::AspectRatioMode* aspectMode, const Qt::TransformationMode* mode);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_scaled_as_ptr_w_h(const QImage* this_ptr, int w, int h);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_scaled_as_ptr_w_h_aspectMode(const QImage* this_ptr, int w, int h, const Qt::AspectRatioMode* aspectMode);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_scaled_as_ptr_w_h_aspectMode_mode(const QImage* this_ptr, int w, int h, const Qt::AspectRatioMode* aspectMode, const Qt::TransformationMode* mode);
QT_GUI_C_EXPORT unsigned char* qt_gui_c_QImage_scanLine(QImage* this_ptr, int arg1);
QT_GUI_C_EXPORT const unsigned char* qt_gui_c_QImage_scanLine_const(const QImage* this_ptr, int arg1);
QT_GUI_C_EXPORT void qt_gui_c_QImage_setAlphaChannel(QImage* this_ptr, const QImage* alphaChannel);
QT_GUI_C_EXPORT void qt_gui_c_QImage_setColor(QImage* this_ptr, int i, unsigned int c);
QT_GUI_C_EXPORT void qt_gui_c_QImage_setColorCount(QImage* this_ptr, int arg1);
QT_GUI_C_EXPORT void qt_gui_c_QImage_setColorTable(QImage* this_ptr, const QVector< unsigned int >* colors);
QT_GUI_C_EXPORT void qt_gui_c_QImage_setDevicePixelRatio(QImage* this_ptr, double scaleFactor);
QT_GUI_C_EXPORT void qt_gui_c_QImage_setDotsPerMeterX(QImage* this_ptr, int arg1);
QT_GUI_C_EXPORT void qt_gui_c_QImage_setDotsPerMeterY(QImage* this_ptr, int arg1);
QT_GUI_C_EXPORT void qt_gui_c_QImage_setOffset(QImage* this_ptr, const QPoint* arg1);
QT_GUI_C_EXPORT void qt_gui_c_QImage_setPixelColor_pt_c(QImage* this_ptr, const QPoint* pt, const QColor* c);
QT_GUI_C_EXPORT void qt_gui_c_QImage_setPixelColor_x_y_c(QImage* this_ptr, int x, int y, const QColor* c);
QT_GUI_C_EXPORT void qt_gui_c_QImage_setPixel_pt_index_or_rgb(QImage* this_ptr, const QPoint* pt, unsigned int index_or_rgb);
QT_GUI_C_EXPORT void qt_gui_c_QImage_setPixel_x_y_index_or_rgb(QImage* this_ptr, int x, int y, unsigned int index_or_rgb);
QT_GUI_C_EXPORT void qt_gui_c_QImage_setText(QImage* this_ptr, const QString* key, const QString* value);
QT_GUI_C_EXPORT void qt_gui_c_QImage_size_to_output(const QImage* this_ptr, QSize* output);
QT_GUI_C_EXPORT void qt_gui_c_QImage_swap(QImage* this_ptr, QImage* other);
QT_GUI_C_EXPORT void qt_gui_c_QImage_textKeys_to_output(const QImage* this_ptr, QStringList* output);
QT_GUI_C_EXPORT void qt_gui_c_QImage_text_to_output_key(const QImage* this_ptr, const QString* key, QString* output);
QT_GUI_C_EXPORT void qt_gui_c_QImage_text_to_output_no_args(const QImage* this_ptr, QString* output);
QT_GUI_C_EXPORT void qt_gui_c_QImage_toPixelFormat_to_output(const QImage::Format* format, QPixelFormat* output);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_transformed_as_ptr_QMatrix(const QImage* this_ptr, const QMatrix* matrix);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_transformed_as_ptr_QMatrix_Qt_TransformationMode(const QImage* this_ptr, const QMatrix* matrix, const Qt::TransformationMode* mode);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_transformed_as_ptr_QTransform(const QImage* this_ptr, const QTransform* matrix);
QT_GUI_C_EXPORT QImage* qt_gui_c_QImage_transformed_as_ptr_QTransform_Qt_TransformationMode(const QImage* this_ptr, const QTransform* matrix, const Qt::TransformationMode* mode);
QT_GUI_C_EXPORT void qt_gui_c_QImage_trueMatrix_to_output_QMatrix_int_int(const QMatrix* arg1, int w, int h, QMatrix* output);
QT_GUI_C_EXPORT void qt_gui_c_QImage_trueMatrix_to_output_QTransform_int_int(const QTransform* arg1, int w, int h, QTransform* output);
QT_GUI_C_EXPORT bool qt_gui_c_QImage_valid_pt(const QImage* this_ptr, const QPoint* pt);
QT_GUI_C_EXPORT bool qt_gui_c_QImage_valid_x_y(const QImage* this_ptr, int x, int y);
QT_GUI_C_EXPORT int qt_gui_c_QImage_width(const QImage* this_ptr);

} // extern "C"

#endif // QT_GUI_C_QIMAGE_H
