#ifndef QT_GUI_C_QOPENGLSHADERPROGRAM_H
#define QT_GUI_C_QOPENGLSHADERPROGRAM_H

#include "qt_gui_c_global.h"

extern "C" {

QT_GUI_C_EXPORT QObject* qt_gui_c_QOpenGLShaderProgram_G_static_cast_QObject_ptr(QOpenGLShaderProgram* ptr);
QT_GUI_C_EXPORT QOpenGLShaderProgram* qt_gui_c_QOpenGLShaderProgram_G_static_cast_QOpenGLShaderProgram_ptr(QObject* ptr);
QT_GUI_C_EXPORT bool qt_gui_c_QOpenGLShaderProgram_addShader(QOpenGLShaderProgram* this_ptr, QOpenGLShader* shader);
QT_GUI_C_EXPORT int qt_gui_c_QOpenGLShaderProgram_attributeLocation_QByteArray(const QOpenGLShaderProgram* this_ptr, const QByteArray* name);
QT_GUI_C_EXPORT int qt_gui_c_QOpenGLShaderProgram_attributeLocation_QString(const QOpenGLShaderProgram* this_ptr, const QString* name);
QT_GUI_C_EXPORT int qt_gui_c_QOpenGLShaderProgram_attributeLocation_char(const QOpenGLShaderProgram* this_ptr, const char* name);
QT_GUI_C_EXPORT bool qt_gui_c_QOpenGLShaderProgram_bind(QOpenGLShaderProgram* this_ptr);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_bindAttributeLocation_QByteArray_int(QOpenGLShaderProgram* this_ptr, const QByteArray* name, int location);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_bindAttributeLocation_QString_int(QOpenGLShaderProgram* this_ptr, const QString* name, int location);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_bindAttributeLocation_char_int(QOpenGLShaderProgram* this_ptr, const char* name, int location);
QT_GUI_C_EXPORT bool qt_gui_c_QOpenGLShaderProgram_create(QOpenGLShaderProgram* this_ptr);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_defaultInnerTessellationLevels_to_output(const QOpenGLShaderProgram* this_ptr, QVector< float >* output);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_defaultOuterTessellationLevels_to_output(const QOpenGLShaderProgram* this_ptr, QVector< float >* output);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_delete(QOpenGLShaderProgram* this_ptr);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_disableAttributeArray_location(QOpenGLShaderProgram* this_ptr, int location);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_disableAttributeArray_name(QOpenGLShaderProgram* this_ptr, const char* name);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_enableAttributeArray_location(QOpenGLShaderProgram* this_ptr, int location);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_enableAttributeArray_name(QOpenGLShaderProgram* this_ptr, const char* name);
QT_GUI_C_EXPORT bool qt_gui_c_QOpenGLShaderProgram_hasOpenGLShaderPrograms_context(QOpenGLContext* context);
QT_GUI_C_EXPORT bool qt_gui_c_QOpenGLShaderProgram_hasOpenGLShaderPrograms_no_args();
QT_GUI_C_EXPORT bool qt_gui_c_QOpenGLShaderProgram_isLinked(const QOpenGLShaderProgram* this_ptr);
QT_GUI_C_EXPORT bool qt_gui_c_QOpenGLShaderProgram_link(QOpenGLShaderProgram* this_ptr);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_log_to_output(const QOpenGLShaderProgram* this_ptr, QString* output);
QT_GUI_C_EXPORT int qt_gui_c_QOpenGLShaderProgram_maxGeometryOutputVertices(const QOpenGLShaderProgram* this_ptr);
QT_GUI_C_EXPORT const QMetaObject* qt_gui_c_QOpenGLShaderProgram_metaObject(const QOpenGLShaderProgram* this_ptr);
QT_GUI_C_EXPORT QOpenGLShaderProgram* qt_gui_c_QOpenGLShaderProgram_new_no_args();
QT_GUI_C_EXPORT QOpenGLShaderProgram* qt_gui_c_QOpenGLShaderProgram_new_parent(QObject* parent);
QT_GUI_C_EXPORT int qt_gui_c_QOpenGLShaderProgram_patchVertexCount(const QOpenGLShaderProgram* this_ptr);
QT_GUI_C_EXPORT GLuint qt_gui_c_QOpenGLShaderProgram_programId(const QOpenGLShaderProgram* this_ptr);
QT_GUI_C_EXPORT int qt_gui_c_QOpenGLShaderProgram_qt_metacall(QOpenGLShaderProgram* this_ptr, const QMetaObject::Call* arg1, int arg2, void** arg3);
QT_GUI_C_EXPORT void* qt_gui_c_QOpenGLShaderProgram_qt_metacast(QOpenGLShaderProgram* this_ptr, const char* arg1);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_release(QOpenGLShaderProgram* this_ptr);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_removeAllShaders(QOpenGLShaderProgram* this_ptr);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_removeShader(QOpenGLShaderProgram* this_ptr, QOpenGLShader* shader);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeArray_char_QVector2D(QOpenGLShaderProgram* this_ptr, const char* name, const QVector2D* values);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeArray_char_QVector2D_int(QOpenGLShaderProgram* this_ptr, const char* name, const QVector2D* values, int stride);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeArray_char_QVector3D(QOpenGLShaderProgram* this_ptr, const char* name, const QVector3D* values);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeArray_char_QVector3D_int(QOpenGLShaderProgram* this_ptr, const char* name, const QVector3D* values, int stride);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeArray_char_QVector4D(QOpenGLShaderProgram* this_ptr, const char* name, const QVector4D* values);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeArray_char_QVector4D_int(QOpenGLShaderProgram* this_ptr, const char* name, const QVector4D* values, int stride);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeArray_char_float_int(QOpenGLShaderProgram* this_ptr, const char* name, const float* values, int tupleSize);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeArray_char_float_int_int(QOpenGLShaderProgram* this_ptr, const char* name, const float* values, int tupleSize, int stride);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeArray_char_unsigned_int_void_int(QOpenGLShaderProgram* this_ptr, const char* name, unsigned int type, const void* values, int tupleSize);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeArray_char_unsigned_int_void_int_int(QOpenGLShaderProgram* this_ptr, const char* name, unsigned int type, const void* values, int tupleSize, int stride);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeArray_int_QVector2D(QOpenGLShaderProgram* this_ptr, int location, const QVector2D* values);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeArray_int_QVector2D_int(QOpenGLShaderProgram* this_ptr, int location, const QVector2D* values, int stride);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeArray_int_QVector3D(QOpenGLShaderProgram* this_ptr, int location, const QVector3D* values);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeArray_int_QVector3D_int(QOpenGLShaderProgram* this_ptr, int location, const QVector3D* values, int stride);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeArray_int_QVector4D(QOpenGLShaderProgram* this_ptr, int location, const QVector4D* values);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeArray_int_QVector4D_int(QOpenGLShaderProgram* this_ptr, int location, const QVector4D* values, int stride);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeArray_int_float_int(QOpenGLShaderProgram* this_ptr, int location, const float* values, int tupleSize);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeArray_int_float_int_int(QOpenGLShaderProgram* this_ptr, int location, const float* values, int tupleSize, int stride);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeArray_int_unsigned_int_void_int(QOpenGLShaderProgram* this_ptr, int location, unsigned int type, const void* values, int tupleSize);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeArray_int_unsigned_int_void_int_int(QOpenGLShaderProgram* this_ptr, int location, unsigned int type, const void* values, int tupleSize, int stride);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeBuffer_location_type_offset_tupleSize(QOpenGLShaderProgram* this_ptr, int location, unsigned int type, int offset, int tupleSize);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeBuffer_location_type_offset_tupleSize_stride(QOpenGLShaderProgram* this_ptr, int location, unsigned int type, int offset, int tupleSize, int stride);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeBuffer_name_type_offset_tupleSize(QOpenGLShaderProgram* this_ptr, const char* name, unsigned int type, int offset, int tupleSize);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeBuffer_name_type_offset_tupleSize_stride(QOpenGLShaderProgram* this_ptr, const char* name, unsigned int type, int offset, int tupleSize, int stride);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeValue_char_QColor(QOpenGLShaderProgram* this_ptr, const char* name, const QColor* value);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeValue_char_QVector2D(QOpenGLShaderProgram* this_ptr, const char* name, const QVector2D* value);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeValue_char_QVector3D(QOpenGLShaderProgram* this_ptr, const char* name, const QVector3D* value);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeValue_char_QVector4D(QOpenGLShaderProgram* this_ptr, const char* name, const QVector4D* value);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeValue_char_float(QOpenGLShaderProgram* this_ptr, const char* name, float value);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeValue_char_float_float(QOpenGLShaderProgram* this_ptr, const char* name, float x, float y);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeValue_char_float_float_float(QOpenGLShaderProgram* this_ptr, const char* name, float x, float y, float z);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeValue_char_float_float_float_float(QOpenGLShaderProgram* this_ptr, const char* name, float x, float y, float z, float w);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeValue_char_float_int_int(QOpenGLShaderProgram* this_ptr, const char* name, const float* values, int columns, int rows);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeValue_int_QColor(QOpenGLShaderProgram* this_ptr, int location, const QColor* value);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeValue_int_QVector2D(QOpenGLShaderProgram* this_ptr, int location, const QVector2D* value);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeValue_int_QVector3D(QOpenGLShaderProgram* this_ptr, int location, const QVector3D* value);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeValue_int_QVector4D(QOpenGLShaderProgram* this_ptr, int location, const QVector4D* value);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeValue_int_float(QOpenGLShaderProgram* this_ptr, int location, float value);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeValue_int_float_float(QOpenGLShaderProgram* this_ptr, int location, float x, float y);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeValue_int_float_float_float(QOpenGLShaderProgram* this_ptr, int location, float x, float y, float z);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeValue_int_float_float_float_float(QOpenGLShaderProgram* this_ptr, int location, float x, float y, float z, float w);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setAttributeValue_int_float_int_int(QOpenGLShaderProgram* this_ptr, int location, const float* values, int columns, int rows);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setDefaultInnerTessellationLevels(QOpenGLShaderProgram* this_ptr, const QVector< float >* levels);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setDefaultOuterTessellationLevels(QOpenGLShaderProgram* this_ptr, const QVector< float >* levels);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setPatchVertexCount(QOpenGLShaderProgram* this_ptr, int count);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValueArray_char_GLint_int(QOpenGLShaderProgram* this_ptr, const char* name, const GLint* values, int count);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValueArray_char_GLuint_int(QOpenGLShaderProgram* this_ptr, const char* name, const GLuint* values, int count);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValueArray_char_QMatrix4x4_int(QOpenGLShaderProgram* this_ptr, const char* name, const QMatrix4x4* values, int count);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValueArray_char_QVector2D_int(QOpenGLShaderProgram* this_ptr, const char* name, const QVector2D* values, int count);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValueArray_char_QVector3D_int(QOpenGLShaderProgram* this_ptr, const char* name, const QVector3D* values, int count);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValueArray_char_QVector4D_int(QOpenGLShaderProgram* this_ptr, const char* name, const QVector4D* values, int count);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValueArray_char_float_int_int(QOpenGLShaderProgram* this_ptr, const char* name, const float* values, int count, int tupleSize);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValueArray_int_GLint_int(QOpenGLShaderProgram* this_ptr, int location, const GLint* values, int count);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValueArray_int_GLuint_int(QOpenGLShaderProgram* this_ptr, int location, const GLuint* values, int count);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValueArray_int_QMatrix4x4_int(QOpenGLShaderProgram* this_ptr, int location, const QMatrix4x4* values, int count);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValueArray_int_QVector2D_int(QOpenGLShaderProgram* this_ptr, int location, const QVector2D* values, int count);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValueArray_int_QVector3D_int(QOpenGLShaderProgram* this_ptr, int location, const QVector3D* values, int count);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValueArray_int_QVector4D_int(QOpenGLShaderProgram* this_ptr, int location, const QVector4D* values, int count);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValueArray_int_float_int_int(QOpenGLShaderProgram* this_ptr, int location, const float* values, int count, int tupleSize);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_char_GLint(QOpenGLShaderProgram* this_ptr, const char* name, GLint value);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_char_GLuint(QOpenGLShaderProgram* this_ptr, const char* name, GLuint value);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_char_QColor(QOpenGLShaderProgram* this_ptr, const char* name, const QColor* color);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_char_QMatrix4x4(QOpenGLShaderProgram* this_ptr, const char* name, const QMatrix4x4* value);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_char_QPoint(QOpenGLShaderProgram* this_ptr, const char* name, const QPoint* point);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_char_QPointF(QOpenGLShaderProgram* this_ptr, const char* name, const QPointF* point);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_char_QSize(QOpenGLShaderProgram* this_ptr, const char* name, const QSize* size);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_char_QSizeF(QOpenGLShaderProgram* this_ptr, const char* name, const QSizeF* size);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_char_QTransform(QOpenGLShaderProgram* this_ptr, const char* name, const QTransform* value);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_char_QVector2D(QOpenGLShaderProgram* this_ptr, const char* name, const QVector2D* value);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_char_QVector3D(QOpenGLShaderProgram* this_ptr, const char* name, const QVector3D* value);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_char_QVector4D(QOpenGLShaderProgram* this_ptr, const char* name, const QVector4D* value);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_char_float(QOpenGLShaderProgram* this_ptr, const char* name, float value);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_char_float_float(QOpenGLShaderProgram* this_ptr, const char* name, float x, float y);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_char_float_float_float(QOpenGLShaderProgram* this_ptr, const char* name, float x, float y, float z);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_char_float_float_float_float(QOpenGLShaderProgram* this_ptr, const char* name, float x, float y, float z, float w);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_int_GLint(QOpenGLShaderProgram* this_ptr, int location, GLint value);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_int_GLuint(QOpenGLShaderProgram* this_ptr, int location, GLuint value);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_int_QColor(QOpenGLShaderProgram* this_ptr, int location, const QColor* color);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_int_QMatrix4x4(QOpenGLShaderProgram* this_ptr, int location, const QMatrix4x4* value);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_int_QPoint(QOpenGLShaderProgram* this_ptr, int location, const QPoint* point);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_int_QPointF(QOpenGLShaderProgram* this_ptr, int location, const QPointF* point);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_int_QSize(QOpenGLShaderProgram* this_ptr, int location, const QSize* size);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_int_QSizeF(QOpenGLShaderProgram* this_ptr, int location, const QSizeF* size);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_int_QTransform(QOpenGLShaderProgram* this_ptr, int location, const QTransform* value);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_int_QVector2D(QOpenGLShaderProgram* this_ptr, int location, const QVector2D* value);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_int_QVector3D(QOpenGLShaderProgram* this_ptr, int location, const QVector3D* value);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_int_QVector4D(QOpenGLShaderProgram* this_ptr, int location, const QVector4D* value);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_int_float(QOpenGLShaderProgram* this_ptr, int location, float value);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_int_float_float(QOpenGLShaderProgram* this_ptr, int location, float x, float y);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_int_float_float_float(QOpenGLShaderProgram* this_ptr, int location, float x, float y, float z);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_setUniformValue_int_float_float_float_float(QOpenGLShaderProgram* this_ptr, int location, float x, float y, float z, float w);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_shaders_to_output(const QOpenGLShaderProgram* this_ptr, QList< QOpenGLShader* >* output);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_trUtf8_to_output(const char* s, const char* c, int n, QString* output);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLShaderProgram_tr_to_output(const char* s, const char* c, int n, QString* output);
QT_GUI_C_EXPORT int qt_gui_c_QOpenGLShaderProgram_uniformLocation_QByteArray(const QOpenGLShaderProgram* this_ptr, const QByteArray* name);
QT_GUI_C_EXPORT int qt_gui_c_QOpenGLShaderProgram_uniformLocation_QString(const QOpenGLShaderProgram* this_ptr, const QString* name);
QT_GUI_C_EXPORT int qt_gui_c_QOpenGLShaderProgram_uniformLocation_char(const QOpenGLShaderProgram* this_ptr, const char* name);

} // extern "C"

#endif // QT_GUI_C_QOPENGLSHADERPROGRAM_H
