#ifndef QT_GUI_C_QACCESSIBLETABLEMODELCHANGEEVENT_H
#define QT_GUI_C_QACCESSIBLETABLEMODELCHANGEEVENT_H

#include "qt_gui_c_global.h"

extern "C" {

QT_GUI_C_EXPORT QAccessibleTableModelChangeEvent* qt_gui_c_QAccessibleTableModelChangeEvent_G_dynamic_cast_QAccessibleTableModelChangeEvent_ptr(QAccessibleEvent* ptr);
QT_GUI_C_EXPORT QAccessibleEvent* qt_gui_c_QAccessibleTableModelChangeEvent_G_static_cast_QAccessibleEvent_ptr(QAccessibleTableModelChangeEvent* ptr);
QT_GUI_C_EXPORT QAccessibleTableModelChangeEvent* qt_gui_c_QAccessibleTableModelChangeEvent_G_static_cast_QAccessibleTableModelChangeEvent_ptr(QAccessibleEvent* ptr);
QT_GUI_C_EXPORT void qt_gui_c_QAccessibleTableModelChangeEvent_delete(QAccessibleTableModelChangeEvent* this_ptr);
QT_GUI_C_EXPORT int qt_gui_c_QAccessibleTableModelChangeEvent_firstColumn(const QAccessibleTableModelChangeEvent* this_ptr);
QT_GUI_C_EXPORT int qt_gui_c_QAccessibleTableModelChangeEvent_firstRow(const QAccessibleTableModelChangeEvent* this_ptr);
QT_GUI_C_EXPORT int qt_gui_c_QAccessibleTableModelChangeEvent_lastColumn(const QAccessibleTableModelChangeEvent* this_ptr);
QT_GUI_C_EXPORT int qt_gui_c_QAccessibleTableModelChangeEvent_lastRow(const QAccessibleTableModelChangeEvent* this_ptr);
QT_GUI_C_EXPORT QAccessibleTableModelChangeEvent::ModelChangeType qt_gui_c_QAccessibleTableModelChangeEvent_modelChangeType(const QAccessibleTableModelChangeEvent* this_ptr);
QT_GUI_C_EXPORT QAccessibleTableModelChangeEvent* qt_gui_c_QAccessibleTableModelChangeEvent_new_iface_changeType(QAccessibleInterface* iface, QAccessibleTableModelChangeEvent::ModelChangeType changeType);
QT_GUI_C_EXPORT QAccessibleTableModelChangeEvent* qt_gui_c_QAccessibleTableModelChangeEvent_new_obj_changeType(QObject* obj, QAccessibleTableModelChangeEvent::ModelChangeType changeType);
QT_GUI_C_EXPORT void qt_gui_c_QAccessibleTableModelChangeEvent_setFirstColumn(QAccessibleTableModelChangeEvent* this_ptr, int col);
QT_GUI_C_EXPORT void qt_gui_c_QAccessibleTableModelChangeEvent_setFirstRow(QAccessibleTableModelChangeEvent* this_ptr, int row);
QT_GUI_C_EXPORT void qt_gui_c_QAccessibleTableModelChangeEvent_setLastColumn(QAccessibleTableModelChangeEvent* this_ptr, int col);
QT_GUI_C_EXPORT void qt_gui_c_QAccessibleTableModelChangeEvent_setLastRow(QAccessibleTableModelChangeEvent* this_ptr, int row);
QT_GUI_C_EXPORT void qt_gui_c_QAccessibleTableModelChangeEvent_setModelChangeType(QAccessibleTableModelChangeEvent* this_ptr, QAccessibleTableModelChangeEvent::ModelChangeType changeType);

} // extern "C"

#endif // QT_GUI_C_QACCESSIBLETABLEMODELCHANGEEVENT_H
