#ifndef QT_GUI_C_QCOLOR_H
#define QT_GUI_C_QCOLOR_H

#include "qt_gui_c_global.h"

extern "C" {

QT_GUI_C_EXPORT QDataStream* qt_gui_c_QColor_G_operator_shl(QDataStream* arg1, const QColor* arg2);
QT_GUI_C_EXPORT void qt_gui_c_QColor_G_operator_shl_to_output(const QDebug* arg1, const QColor* arg2, QDebug* output);
QT_GUI_C_EXPORT QDataStream* qt_gui_c_QColor_G_operator_shr(QDataStream* arg1, QColor* arg2);
QT_GUI_C_EXPORT int qt_gui_c_QColor_alpha(const QColor* this_ptr);
QT_GUI_C_EXPORT double qt_gui_c_QColor_alphaF(const QColor* this_ptr);
QT_GUI_C_EXPORT int qt_gui_c_QColor_black(const QColor* this_ptr);
QT_GUI_C_EXPORT double qt_gui_c_QColor_blackF(const QColor* this_ptr);
QT_GUI_C_EXPORT int qt_gui_c_QColor_blue(const QColor* this_ptr);
QT_GUI_C_EXPORT double qt_gui_c_QColor_blueF(const QColor* this_ptr);
QT_GUI_C_EXPORT void qt_gui_c_QColor_colorNames_to_output(QStringList* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_constructor_QColor(const QColor* color, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_constructor_QColor_Spec(QColor::Spec spec, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_constructor_QLatin1String(const QLatin1String* name, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_constructor_QRgba64(const QRgba64* rgba64, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_constructor_QString(const QString* name, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_constructor_Qt_GlobalColor(const Qt::GlobalColor* color, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_constructor_char(const char* aname, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_constructor_int_int_int(int r, int g, int b, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_constructor_int_int_int_int(int r, int g, int b, int a, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_constructor_no_args(QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_constructor_unsigned_int(unsigned int rgb, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_convertTo_to_output(const QColor* this_ptr, QColor::Spec colorSpec, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_convert_to_QVariant_to_output(const QColor* this_ptr, QVariant* output);
QT_GUI_C_EXPORT int qt_gui_c_QColor_cyan(const QColor* this_ptr);
QT_GUI_C_EXPORT double qt_gui_c_QColor_cyanF(const QColor* this_ptr);
QT_GUI_C_EXPORT void qt_gui_c_QColor_dark_to_output_f(const QColor* this_ptr, int f, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_dark_to_output_no_args(const QColor* this_ptr, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_darker_to_output_f(const QColor* this_ptr, int f, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_darker_to_output_no_args(const QColor* this_ptr, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_destructor(QColor* this_ptr);
QT_GUI_C_EXPORT void qt_gui_c_QColor_fromCmykF_to_output_c_m_y_k(double c, double m, double y, double k, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_fromCmykF_to_output_c_m_y_k_a(double c, double m, double y, double k, double a, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_fromCmyk_to_output_c_m_y_k(int c, int m, int y, int k, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_fromCmyk_to_output_c_m_y_k_a(int c, int m, int y, int k, int a, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_fromHslF_to_output_h_s_l(double h, double s, double l, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_fromHslF_to_output_h_s_l_a(double h, double s, double l, double a, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_fromHsl_to_output_h_s_l(int h, int s, int l, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_fromHsl_to_output_h_s_l_a(int h, int s, int l, int a, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_fromHsvF_to_output_h_s_v(double h, double s, double v, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_fromHsvF_to_output_h_s_v_a(double h, double s, double v, double a, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_fromHsv_to_output_h_s_v(int h, int s, int v, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_fromHsv_to_output_h_s_v_a(int h, int s, int v, int a, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_fromRgbF_to_output_r_g_b(double r, double g, double b, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_fromRgbF_to_output_r_g_b_a(double r, double g, double b, double a, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_fromRgb_to_output_r_g_b(int r, int g, int b, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_fromRgb_to_output_r_g_b_a(int r, int g, int b, int a, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_fromRgb_to_output_rgb(unsigned int rgb, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_fromRgba64_to_output_r_g_b(unsigned short r, unsigned short g, unsigned short b, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_fromRgba64_to_output_r_g_b_a(unsigned short r, unsigned short g, unsigned short b, unsigned short a, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_fromRgba64_to_output_rgba(const QRgba64* rgba, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_fromRgba_to_output(unsigned int rgba, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_getCmykF_c_m_y_k(QColor* this_ptr, double* c, double* m, double* y, double* k);
QT_GUI_C_EXPORT void qt_gui_c_QColor_getCmykF_c_m_y_k_a(QColor* this_ptr, double* c, double* m, double* y, double* k, double* a);
QT_GUI_C_EXPORT void qt_gui_c_QColor_getCmyk_c_m_y_k(QColor* this_ptr, int* c, int* m, int* y, int* k);
QT_GUI_C_EXPORT void qt_gui_c_QColor_getCmyk_c_m_y_k_a(QColor* this_ptr, int* c, int* m, int* y, int* k, int* a);
QT_GUI_C_EXPORT void qt_gui_c_QColor_getHslF_h_s_l(const QColor* this_ptr, double* h, double* s, double* l);
QT_GUI_C_EXPORT void qt_gui_c_QColor_getHslF_h_s_l_a(const QColor* this_ptr, double* h, double* s, double* l, double* a);
QT_GUI_C_EXPORT void qt_gui_c_QColor_getHsl_h_s_l(const QColor* this_ptr, int* h, int* s, int* l);
QT_GUI_C_EXPORT void qt_gui_c_QColor_getHsl_h_s_l_a(const QColor* this_ptr, int* h, int* s, int* l, int* a);
QT_GUI_C_EXPORT void qt_gui_c_QColor_getHsvF_h_s_v(const QColor* this_ptr, double* h, double* s, double* v);
QT_GUI_C_EXPORT void qt_gui_c_QColor_getHsvF_h_s_v_a(const QColor* this_ptr, double* h, double* s, double* v, double* a);
QT_GUI_C_EXPORT void qt_gui_c_QColor_getHsv_h_s_v(const QColor* this_ptr, int* h, int* s, int* v);
QT_GUI_C_EXPORT void qt_gui_c_QColor_getHsv_h_s_v_a(const QColor* this_ptr, int* h, int* s, int* v, int* a);
QT_GUI_C_EXPORT void qt_gui_c_QColor_getRgbF_r_g_b(const QColor* this_ptr, double* r, double* g, double* b);
QT_GUI_C_EXPORT void qt_gui_c_QColor_getRgbF_r_g_b_a(const QColor* this_ptr, double* r, double* g, double* b, double* a);
QT_GUI_C_EXPORT void qt_gui_c_QColor_getRgb_r_g_b(const QColor* this_ptr, int* r, int* g, int* b);
QT_GUI_C_EXPORT void qt_gui_c_QColor_getRgb_r_g_b_a(const QColor* this_ptr, int* r, int* g, int* b, int* a);
QT_GUI_C_EXPORT int qt_gui_c_QColor_green(const QColor* this_ptr);
QT_GUI_C_EXPORT double qt_gui_c_QColor_greenF(const QColor* this_ptr);
QT_GUI_C_EXPORT int qt_gui_c_QColor_hslHue(const QColor* this_ptr);
QT_GUI_C_EXPORT double qt_gui_c_QColor_hslHueF(const QColor* this_ptr);
QT_GUI_C_EXPORT int qt_gui_c_QColor_hslSaturation(const QColor* this_ptr);
QT_GUI_C_EXPORT double qt_gui_c_QColor_hslSaturationF(const QColor* this_ptr);
QT_GUI_C_EXPORT int qt_gui_c_QColor_hsvHue(const QColor* this_ptr);
QT_GUI_C_EXPORT double qt_gui_c_QColor_hsvHueF(const QColor* this_ptr);
QT_GUI_C_EXPORT int qt_gui_c_QColor_hsvSaturation(const QColor* this_ptr);
QT_GUI_C_EXPORT double qt_gui_c_QColor_hsvSaturationF(const QColor* this_ptr);
QT_GUI_C_EXPORT int qt_gui_c_QColor_hue(const QColor* this_ptr);
QT_GUI_C_EXPORT double qt_gui_c_QColor_hueF(const QColor* this_ptr);
QT_GUI_C_EXPORT bool qt_gui_c_QColor_isValid(const QColor* this_ptr);
QT_GUI_C_EXPORT bool qt_gui_c_QColor_isValidColor_arg1(const QLatin1String* arg1);
QT_GUI_C_EXPORT bool qt_gui_c_QColor_isValidColor_name(const QString* name);
QT_GUI_C_EXPORT void qt_gui_c_QColor_light_to_output_f(const QColor* this_ptr, int f, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_light_to_output_no_args(const QColor* this_ptr, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_lighter_to_output_f(const QColor* this_ptr, int f, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_lighter_to_output_no_args(const QColor* this_ptr, QColor* output);
QT_GUI_C_EXPORT int qt_gui_c_QColor_lightness(const QColor* this_ptr);
QT_GUI_C_EXPORT double qt_gui_c_QColor_lightnessF(const QColor* this_ptr);
QT_GUI_C_EXPORT int qt_gui_c_QColor_magenta(const QColor* this_ptr);
QT_GUI_C_EXPORT double qt_gui_c_QColor_magentaF(const QColor* this_ptr);
QT_GUI_C_EXPORT void qt_gui_c_QColor_name_to_output_format(const QColor* this_ptr, QColor::NameFormat format, QString* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_name_to_output_no_args(const QColor* this_ptr, QString* output);
QT_GUI_C_EXPORT QColor* qt_gui_c_QColor_operator_assign_arg1(QColor* this_ptr, const QColor* arg1);
QT_GUI_C_EXPORT QColor* qt_gui_c_QColor_operator_assign_color(QColor* this_ptr, const Qt::GlobalColor* color);
QT_GUI_C_EXPORT bool qt_gui_c_QColor_operator_eq(const QColor* this_ptr, const QColor* c);
QT_GUI_C_EXPORT bool qt_gui_c_QColor_operator_neq(const QColor* this_ptr, const QColor* c);
QT_GUI_C_EXPORT int qt_gui_c_QColor_red(const QColor* this_ptr);
QT_GUI_C_EXPORT double qt_gui_c_QColor_redF(const QColor* this_ptr);
QT_GUI_C_EXPORT unsigned int qt_gui_c_QColor_rgb(const QColor* this_ptr);
QT_GUI_C_EXPORT unsigned int qt_gui_c_QColor_rgba(const QColor* this_ptr);
QT_GUI_C_EXPORT void qt_gui_c_QColor_rgba64_to_output(const QColor* this_ptr, QRgba64* output);
QT_GUI_C_EXPORT int qt_gui_c_QColor_saturation(const QColor* this_ptr);
QT_GUI_C_EXPORT double qt_gui_c_QColor_saturationF(const QColor* this_ptr);
QT_GUI_C_EXPORT void qt_gui_c_QColor_setAlpha(QColor* this_ptr, int alpha);
QT_GUI_C_EXPORT void qt_gui_c_QColor_setAlphaF(QColor* this_ptr, double alpha);
QT_GUI_C_EXPORT void qt_gui_c_QColor_setBlue(QColor* this_ptr, int blue);
QT_GUI_C_EXPORT void qt_gui_c_QColor_setBlueF(QColor* this_ptr, double blue);
QT_GUI_C_EXPORT void qt_gui_c_QColor_setCmykF_c_m_y_k(QColor* this_ptr, double c, double m, double y, double k);
QT_GUI_C_EXPORT void qt_gui_c_QColor_setCmykF_c_m_y_k_a(QColor* this_ptr, double c, double m, double y, double k, double a);
QT_GUI_C_EXPORT void qt_gui_c_QColor_setCmyk_c_m_y_k(QColor* this_ptr, int c, int m, int y, int k);
QT_GUI_C_EXPORT void qt_gui_c_QColor_setCmyk_c_m_y_k_a(QColor* this_ptr, int c, int m, int y, int k, int a);
QT_GUI_C_EXPORT void qt_gui_c_QColor_setGreen(QColor* this_ptr, int green);
QT_GUI_C_EXPORT void qt_gui_c_QColor_setGreenF(QColor* this_ptr, double green);
QT_GUI_C_EXPORT void qt_gui_c_QColor_setHslF_h_s_l(QColor* this_ptr, double h, double s, double l);
QT_GUI_C_EXPORT void qt_gui_c_QColor_setHslF_h_s_l_a(QColor* this_ptr, double h, double s, double l, double a);
QT_GUI_C_EXPORT void qt_gui_c_QColor_setHsl_h_s_l(QColor* this_ptr, int h, int s, int l);
QT_GUI_C_EXPORT void qt_gui_c_QColor_setHsl_h_s_l_a(QColor* this_ptr, int h, int s, int l, int a);
QT_GUI_C_EXPORT void qt_gui_c_QColor_setHsvF_h_s_v(QColor* this_ptr, double h, double s, double v);
QT_GUI_C_EXPORT void qt_gui_c_QColor_setHsvF_h_s_v_a(QColor* this_ptr, double h, double s, double v, double a);
QT_GUI_C_EXPORT void qt_gui_c_QColor_setHsv_h_s_v(QColor* this_ptr, int h, int s, int v);
QT_GUI_C_EXPORT void qt_gui_c_QColor_setHsv_h_s_v_a(QColor* this_ptr, int h, int s, int v, int a);
QT_GUI_C_EXPORT void qt_gui_c_QColor_setNamedColor_QLatin1String(QColor* this_ptr, const QLatin1String* name);
QT_GUI_C_EXPORT void qt_gui_c_QColor_setNamedColor_QString(QColor* this_ptr, const QString* name);
QT_GUI_C_EXPORT void qt_gui_c_QColor_setRed(QColor* this_ptr, int red);
QT_GUI_C_EXPORT void qt_gui_c_QColor_setRedF(QColor* this_ptr, double red);
QT_GUI_C_EXPORT void qt_gui_c_QColor_setRgbF_r_g_b(QColor* this_ptr, double r, double g, double b);
QT_GUI_C_EXPORT void qt_gui_c_QColor_setRgbF_r_g_b_a(QColor* this_ptr, double r, double g, double b, double a);
QT_GUI_C_EXPORT void qt_gui_c_QColor_setRgb_r_g_b(QColor* this_ptr, int r, int g, int b);
QT_GUI_C_EXPORT void qt_gui_c_QColor_setRgb_r_g_b_a(QColor* this_ptr, int r, int g, int b, int a);
QT_GUI_C_EXPORT void qt_gui_c_QColor_setRgb_rgb(QColor* this_ptr, unsigned int rgb);
QT_GUI_C_EXPORT void qt_gui_c_QColor_setRgba(QColor* this_ptr, unsigned int rgba);
QT_GUI_C_EXPORT void qt_gui_c_QColor_setRgba64(QColor* this_ptr, const QRgba64* rgba);
QT_GUI_C_EXPORT QColor::Spec qt_gui_c_QColor_spec(const QColor* this_ptr);
QT_GUI_C_EXPORT void qt_gui_c_QColor_toCmyk_to_output(const QColor* this_ptr, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_toHsl_to_output(const QColor* this_ptr, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_toHsv_to_output(const QColor* this_ptr, QColor* output);
QT_GUI_C_EXPORT void qt_gui_c_QColor_toRgb_to_output(const QColor* this_ptr, QColor* output);
QT_GUI_C_EXPORT int qt_gui_c_QColor_value(const QColor* this_ptr);
QT_GUI_C_EXPORT double qt_gui_c_QColor_valueF(const QColor* this_ptr);
QT_GUI_C_EXPORT int qt_gui_c_QColor_yellow(const QColor* this_ptr);
QT_GUI_C_EXPORT double qt_gui_c_QColor_yellowF(const QColor* this_ptr);

} // extern "C"

#endif // QT_GUI_C_QCOLOR_H
