#ifndef QT_GUI_C_QOPENGLFUNCTIONS_H
#define QT_GUI_C_QOPENGLFUNCTIONS_H

#include "qt_gui_c_global.h"

extern "C" {

QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_delete(QOpenGLFunctions* this_ptr);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glActiveTexture(QOpenGLFunctions* this_ptr, unsigned int texture);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glAttachShader(QOpenGLFunctions* this_ptr, GLuint program, GLuint shader);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glBindAttribLocation(QOpenGLFunctions* this_ptr, GLuint program, GLuint index, const char* name);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glBindBuffer(QOpenGLFunctions* this_ptr, unsigned int target, GLuint buffer);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glBindFramebuffer(QOpenGLFunctions* this_ptr, unsigned int target, GLuint framebuffer);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glBindRenderbuffer(QOpenGLFunctions* this_ptr, unsigned int target, GLuint renderbuffer);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glBindTexture(QOpenGLFunctions* this_ptr, unsigned int target, GLuint texture);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glBlendColor(QOpenGLFunctions* this_ptr, float red, float green, float blue, float alpha);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glBlendEquation(QOpenGLFunctions* this_ptr, unsigned int mode);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glBlendEquationSeparate(QOpenGLFunctions* this_ptr, unsigned int modeRGB, unsigned int modeAlpha);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glBlendFunc(QOpenGLFunctions* this_ptr, unsigned int sfactor, unsigned int dfactor);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glBlendFuncSeparate(QOpenGLFunctions* this_ptr, unsigned int srcRGB, unsigned int dstRGB, unsigned int srcAlpha, unsigned int dstAlpha);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glBufferData(QOpenGLFunctions* this_ptr, unsigned int target, long size, const void* data, unsigned int usage);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glBufferSubData(QOpenGLFunctions* this_ptr, unsigned int target, long offset, long size, const void* data);
QT_GUI_C_EXPORT unsigned int qt_gui_c_QOpenGLFunctions_glCheckFramebufferStatus(QOpenGLFunctions* this_ptr, unsigned int target);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glClear(QOpenGLFunctions* this_ptr, unsigned int mask);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glClearColor(QOpenGLFunctions* this_ptr, float red, float green, float blue, float alpha);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glClearDepthf(QOpenGLFunctions* this_ptr, float depth);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glClearStencil(QOpenGLFunctions* this_ptr, GLint s);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glColorMask(QOpenGLFunctions* this_ptr, unsigned char red, unsigned char green, unsigned char blue, unsigned char alpha);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glCompileShader(QOpenGLFunctions* this_ptr, GLuint shader);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glCompressedTexImage2D(QOpenGLFunctions* this_ptr, unsigned int target, GLint level, unsigned int internalformat, int width, int height, GLint border, int imageSize, const void* data);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glCompressedTexSubImage2D(QOpenGLFunctions* this_ptr, unsigned int target, GLint level, GLint xoffset, GLint yoffset, int width, int height, unsigned int format, int imageSize, const void* data);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glCopyTexImage2D(QOpenGLFunctions* this_ptr, unsigned int target, GLint level, unsigned int internalformat, GLint x, GLint y, int width, int height, GLint border);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glCopyTexSubImage2D(QOpenGLFunctions* this_ptr, unsigned int target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, int width, int height);
QT_GUI_C_EXPORT GLuint qt_gui_c_QOpenGLFunctions_glCreateProgram(QOpenGLFunctions* this_ptr);
QT_GUI_C_EXPORT GLuint qt_gui_c_QOpenGLFunctions_glCreateShader(QOpenGLFunctions* this_ptr, unsigned int type);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glCullFace(QOpenGLFunctions* this_ptr, unsigned int mode);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glDeleteBuffers(QOpenGLFunctions* this_ptr, int n, const GLuint* buffers);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glDeleteFramebuffers(QOpenGLFunctions* this_ptr, int n, const GLuint* framebuffers);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glDeleteProgram(QOpenGLFunctions* this_ptr, GLuint program);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glDeleteRenderbuffers(QOpenGLFunctions* this_ptr, int n, const GLuint* renderbuffers);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glDeleteShader(QOpenGLFunctions* this_ptr, GLuint shader);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glDeleteTextures(QOpenGLFunctions* this_ptr, int n, const GLuint* textures);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glDepthFunc(QOpenGLFunctions* this_ptr, unsigned int func);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glDepthMask(QOpenGLFunctions* this_ptr, unsigned char flag);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glDepthRangef(QOpenGLFunctions* this_ptr, float zNear, float zFar);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glDetachShader(QOpenGLFunctions* this_ptr, GLuint program, GLuint shader);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glDisable(QOpenGLFunctions* this_ptr, unsigned int cap);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glDisableVertexAttribArray(QOpenGLFunctions* this_ptr, GLuint index);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glDrawArrays(QOpenGLFunctions* this_ptr, unsigned int mode, GLint first, int count);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glDrawElements(QOpenGLFunctions* this_ptr, unsigned int mode, int count, unsigned int type, const void* indices);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glEnable(QOpenGLFunctions* this_ptr, unsigned int cap);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glEnableVertexAttribArray(QOpenGLFunctions* this_ptr, GLuint index);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glFinish(QOpenGLFunctions* this_ptr);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glFlush(QOpenGLFunctions* this_ptr);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glFramebufferRenderbuffer(QOpenGLFunctions* this_ptr, unsigned int target, unsigned int attachment, unsigned int renderbuffertarget, GLuint renderbuffer);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glFramebufferTexture2D(QOpenGLFunctions* this_ptr, unsigned int target, unsigned int attachment, unsigned int textarget, GLuint texture, GLint level);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glFrontFace(QOpenGLFunctions* this_ptr, unsigned int mode);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glGenBuffers(QOpenGLFunctions* this_ptr, int n, GLuint* buffers);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glGenFramebuffers(QOpenGLFunctions* this_ptr, int n, GLuint* framebuffers);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glGenRenderbuffers(QOpenGLFunctions* this_ptr, int n, GLuint* renderbuffers);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glGenTextures(QOpenGLFunctions* this_ptr, int n, GLuint* textures);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glGenerateMipmap(QOpenGLFunctions* this_ptr, unsigned int target);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glGetActiveAttrib(QOpenGLFunctions* this_ptr, GLuint program, GLuint index, int bufsize, int* length, GLint* size, unsigned int* type, char* name);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glGetActiveUniform(QOpenGLFunctions* this_ptr, GLuint program, GLuint index, int bufsize, int* length, GLint* size, unsigned int* type, char* name);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glGetAttachedShaders(QOpenGLFunctions* this_ptr, GLuint program, int maxcount, int* count, GLuint* shaders);
QT_GUI_C_EXPORT GLint qt_gui_c_QOpenGLFunctions_glGetAttribLocation(QOpenGLFunctions* this_ptr, GLuint program, const char* name);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glGetBooleanv(QOpenGLFunctions* this_ptr, unsigned int pname, unsigned char* params);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glGetBufferParameteriv(QOpenGLFunctions* this_ptr, unsigned int target, unsigned int pname, GLint* params);
QT_GUI_C_EXPORT unsigned int qt_gui_c_QOpenGLFunctions_glGetError(QOpenGLFunctions* this_ptr);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glGetFloatv(QOpenGLFunctions* this_ptr, unsigned int pname, float* params);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glGetFramebufferAttachmentParameteriv(QOpenGLFunctions* this_ptr, unsigned int target, unsigned int attachment, unsigned int pname, GLint* params);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glGetIntegerv(QOpenGLFunctions* this_ptr, unsigned int pname, GLint* params);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glGetProgramInfoLog(QOpenGLFunctions* this_ptr, GLuint program, int bufsize, int* length, char* infolog);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glGetProgramiv(QOpenGLFunctions* this_ptr, GLuint program, unsigned int pname, GLint* params);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glGetRenderbufferParameteriv(QOpenGLFunctions* this_ptr, unsigned int target, unsigned int pname, GLint* params);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glGetShaderInfoLog(QOpenGLFunctions* this_ptr, GLuint shader, int bufsize, int* length, char* infolog);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glGetShaderPrecisionFormat(QOpenGLFunctions* this_ptr, unsigned int shadertype, unsigned int precisiontype, GLint* range, GLint* precision);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glGetShaderSource(QOpenGLFunctions* this_ptr, GLuint shader, int bufsize, int* length, char* source);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glGetShaderiv(QOpenGLFunctions* this_ptr, GLuint shader, unsigned int pname, GLint* params);
QT_GUI_C_EXPORT const GLubyte* qt_gui_c_QOpenGLFunctions_glGetString(QOpenGLFunctions* this_ptr, unsigned int name);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glGetTexParameterfv(QOpenGLFunctions* this_ptr, unsigned int target, unsigned int pname, float* params);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glGetTexParameteriv(QOpenGLFunctions* this_ptr, unsigned int target, unsigned int pname, GLint* params);
QT_GUI_C_EXPORT GLint qt_gui_c_QOpenGLFunctions_glGetUniformLocation(QOpenGLFunctions* this_ptr, GLuint program, const char* name);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glGetUniformfv(QOpenGLFunctions* this_ptr, GLuint program, GLint location, float* params);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glGetUniformiv(QOpenGLFunctions* this_ptr, GLuint program, GLint location, GLint* params);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glGetVertexAttribPointerv(QOpenGLFunctions* this_ptr, GLuint index, unsigned int pname, void** pointer);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glGetVertexAttribfv(QOpenGLFunctions* this_ptr, GLuint index, unsigned int pname, float* params);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glGetVertexAttribiv(QOpenGLFunctions* this_ptr, GLuint index, unsigned int pname, GLint* params);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glHint(QOpenGLFunctions* this_ptr, unsigned int target, unsigned int mode);
QT_GUI_C_EXPORT unsigned char qt_gui_c_QOpenGLFunctions_glIsBuffer(QOpenGLFunctions* this_ptr, GLuint buffer);
QT_GUI_C_EXPORT unsigned char qt_gui_c_QOpenGLFunctions_glIsEnabled(QOpenGLFunctions* this_ptr, unsigned int cap);
QT_GUI_C_EXPORT unsigned char qt_gui_c_QOpenGLFunctions_glIsFramebuffer(QOpenGLFunctions* this_ptr, GLuint framebuffer);
QT_GUI_C_EXPORT unsigned char qt_gui_c_QOpenGLFunctions_glIsProgram(QOpenGLFunctions* this_ptr, GLuint program);
QT_GUI_C_EXPORT unsigned char qt_gui_c_QOpenGLFunctions_glIsRenderbuffer(QOpenGLFunctions* this_ptr, GLuint renderbuffer);
QT_GUI_C_EXPORT unsigned char qt_gui_c_QOpenGLFunctions_glIsShader(QOpenGLFunctions* this_ptr, GLuint shader);
QT_GUI_C_EXPORT unsigned char qt_gui_c_QOpenGLFunctions_glIsTexture(QOpenGLFunctions* this_ptr, GLuint texture);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glLineWidth(QOpenGLFunctions* this_ptr, float width);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glLinkProgram(QOpenGLFunctions* this_ptr, GLuint program);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glPixelStorei(QOpenGLFunctions* this_ptr, unsigned int pname, GLint param);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glPolygonOffset(QOpenGLFunctions* this_ptr, float factor, float units);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glReadPixels(QOpenGLFunctions* this_ptr, GLint x, GLint y, int width, int height, unsigned int format, unsigned int type, void* pixels);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glReleaseShaderCompiler(QOpenGLFunctions* this_ptr);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glRenderbufferStorage(QOpenGLFunctions* this_ptr, unsigned int target, unsigned int internalformat, int width, int height);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glSampleCoverage(QOpenGLFunctions* this_ptr, float value, unsigned char invert);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glScissor(QOpenGLFunctions* this_ptr, GLint x, GLint y, int width, int height);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glShaderBinary(QOpenGLFunctions* this_ptr, GLint n, const GLuint* shaders, unsigned int binaryformat, const void* binary, GLint length);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glShaderSource(QOpenGLFunctions* this_ptr, GLuint shader, int count, const char** string, const GLint* length);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glStencilFunc(QOpenGLFunctions* this_ptr, unsigned int func, GLint ref, GLuint mask);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glStencilFuncSeparate(QOpenGLFunctions* this_ptr, unsigned int face, unsigned int func, GLint ref, GLuint mask);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glStencilMask(QOpenGLFunctions* this_ptr, GLuint mask);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glStencilMaskSeparate(QOpenGLFunctions* this_ptr, unsigned int face, GLuint mask);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glStencilOp(QOpenGLFunctions* this_ptr, unsigned int fail, unsigned int zfail, unsigned int zpass);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glStencilOpSeparate(QOpenGLFunctions* this_ptr, unsigned int face, unsigned int fail, unsigned int zfail, unsigned int zpass);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glTexImage2D(QOpenGLFunctions* this_ptr, unsigned int target, GLint level, GLint internalformat, int width, int height, GLint border, unsigned int format, unsigned int type, const void* pixels);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glTexParameterf(QOpenGLFunctions* this_ptr, unsigned int target, unsigned int pname, float param);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glTexParameterfv(QOpenGLFunctions* this_ptr, unsigned int target, unsigned int pname, const float* params);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glTexParameteri(QOpenGLFunctions* this_ptr, unsigned int target, unsigned int pname, GLint param);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glTexParameteriv(QOpenGLFunctions* this_ptr, unsigned int target, unsigned int pname, const GLint* params);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glTexSubImage2D(QOpenGLFunctions* this_ptr, unsigned int target, GLint level, GLint xoffset, GLint yoffset, int width, int height, unsigned int format, unsigned int type, const void* pixels);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glUniform1f(QOpenGLFunctions* this_ptr, GLint location, float x);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glUniform1fv(QOpenGLFunctions* this_ptr, GLint location, int count, const float* v);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glUniform1i(QOpenGLFunctions* this_ptr, GLint location, GLint x);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glUniform1iv(QOpenGLFunctions* this_ptr, GLint location, int count, const GLint* v);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glUniform2f(QOpenGLFunctions* this_ptr, GLint location, float x, float y);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glUniform2fv(QOpenGLFunctions* this_ptr, GLint location, int count, const float* v);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glUniform2i(QOpenGLFunctions* this_ptr, GLint location, GLint x, GLint y);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glUniform2iv(QOpenGLFunctions* this_ptr, GLint location, int count, const GLint* v);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glUniform3f(QOpenGLFunctions* this_ptr, GLint location, float x, float y, float z);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glUniform3fv(QOpenGLFunctions* this_ptr, GLint location, int count, const float* v);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glUniform3i(QOpenGLFunctions* this_ptr, GLint location, GLint x, GLint y, GLint z);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glUniform3iv(QOpenGLFunctions* this_ptr, GLint location, int count, const GLint* v);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glUniform4f(QOpenGLFunctions* this_ptr, GLint location, float x, float y, float z, float w);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glUniform4fv(QOpenGLFunctions* this_ptr, GLint location, int count, const float* v);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glUniform4i(QOpenGLFunctions* this_ptr, GLint location, GLint x, GLint y, GLint z, GLint w);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glUniform4iv(QOpenGLFunctions* this_ptr, GLint location, int count, const GLint* v);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glUniformMatrix2fv(QOpenGLFunctions* this_ptr, GLint location, int count, unsigned char transpose, const float* value);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glUniformMatrix3fv(QOpenGLFunctions* this_ptr, GLint location, int count, unsigned char transpose, const float* value);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glUniformMatrix4fv(QOpenGLFunctions* this_ptr, GLint location, int count, unsigned char transpose, const float* value);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glUseProgram(QOpenGLFunctions* this_ptr, GLuint program);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glValidateProgram(QOpenGLFunctions* this_ptr, GLuint program);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glVertexAttrib1f(QOpenGLFunctions* this_ptr, GLuint indx, float x);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glVertexAttrib1fv(QOpenGLFunctions* this_ptr, GLuint indx, const float* values);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glVertexAttrib2f(QOpenGLFunctions* this_ptr, GLuint indx, float x, float y);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glVertexAttrib2fv(QOpenGLFunctions* this_ptr, GLuint indx, const float* values);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glVertexAttrib3f(QOpenGLFunctions* this_ptr, GLuint indx, float x, float y, float z);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glVertexAttrib3fv(QOpenGLFunctions* this_ptr, GLuint indx, const float* values);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glVertexAttrib4f(QOpenGLFunctions* this_ptr, GLuint indx, float x, float y, float z, float w);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glVertexAttrib4fv(QOpenGLFunctions* this_ptr, GLuint indx, const float* values);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glVertexAttribPointer(QOpenGLFunctions* this_ptr, GLuint indx, GLint size, unsigned int type, unsigned char normalized, int stride, const void* ptr);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_glViewport(QOpenGLFunctions* this_ptr, GLint x, GLint y, int width, int height);
QT_GUI_C_EXPORT bool qt_gui_c_QOpenGLFunctions_hasOpenGLFeature(const QOpenGLFunctions* this_ptr, const QOpenGLFunctions::OpenGLFeature* feature);
QT_GUI_C_EXPORT void qt_gui_c_QOpenGLFunctions_initializeOpenGLFunctions(QOpenGLFunctions* this_ptr);
QT_GUI_C_EXPORT QOpenGLFunctions* qt_gui_c_QOpenGLFunctions_new_context(QOpenGLContext* context);
QT_GUI_C_EXPORT QOpenGLFunctions* qt_gui_c_QOpenGLFunctions_new_no_args();

} // extern "C"

#endif // QT_GUI_C_QOPENGLFUNCTIONS_H
