#ifndef QT_3D_CORE_C_QSTATICPROPERTYVALUEREMOVEDCHANGEBASE_H
#define QT_3D_CORE_C_QSTATICPROPERTYVALUEREMOVEDCHANGEBASE_H

#include "qt_3d_core_c_global.h"

extern "C" {

QT_3D_CORE_C_EXPORT Qt3DCore::QStaticPropertyValueRemovedChangeBase* qt_3d_core_c_QStaticPropertyValueRemovedChangeBase_G_dynamic_cast_Qt3DCore_QStaticPropertyValueRemovedChangeBase_ptr_Qt3DCore_QPropertyValueRemovedChangeBase(Qt3DCore::QPropertyValueRemovedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QStaticPropertyValueRemovedChangeBase* qt_3d_core_c_QStaticPropertyValueRemovedChangeBase_G_dynamic_cast_Qt3DCore_QStaticPropertyValueRemovedChangeBase_ptr_Qt3DCore_QSceneChange(Qt3DCore::QSceneChange* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyValueRemovedChangeBase* qt_3d_core_c_QStaticPropertyValueRemovedChangeBase_G_static_cast_Qt3DCore_QPropertyValueRemovedChangeBase_ptr(Qt3DCore::QStaticPropertyValueRemovedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QSceneChange* qt_3d_core_c_QStaticPropertyValueRemovedChangeBase_G_static_cast_Qt3DCore_QSceneChange_ptr(Qt3DCore::QStaticPropertyValueRemovedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QStaticPropertyValueRemovedChangeBase* qt_3d_core_c_QStaticPropertyValueRemovedChangeBase_G_static_cast_Qt3DCore_QStaticPropertyValueRemovedChangeBase_ptr_Qt3DCore_QPropertyValueRemovedChangeBase(Qt3DCore::QPropertyValueRemovedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QStaticPropertyValueRemovedChangeBase* qt_3d_core_c_QStaticPropertyValueRemovedChangeBase_G_static_cast_Qt3DCore_QStaticPropertyValueRemovedChangeBase_ptr_Qt3DCore_QSceneChange(Qt3DCore::QSceneChange* ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_Qt3DCore_QStaticPropertyValueRemovedChangeBase_delete(Qt3DCore::QStaticPropertyValueRemovedChangeBase* this_ptr);
QT_3D_CORE_C_EXPORT const char* qt_3d_core_c_Qt3DCore_QStaticPropertyValueRemovedChangeBase_propertyName(const Qt3DCore::QStaticPropertyValueRemovedChangeBase* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_Qt3DCore_QStaticPropertyValueRemovedChangeBase_setPropertyName(Qt3DCore::QStaticPropertyValueRemovedChangeBase* this_ptr, const char* name);

} // extern "C"

#endif // QT_3D_CORE_C_QSTATICPROPERTYVALUEREMOVEDCHANGEBASE_H
