#ifndef QT_3D_CORE_C_QPROPERTYNODEREMOVEDCHANGE_H
#define QT_3D_CORE_C_QPROPERTYNODEREMOVEDCHANGE_H

#include "qt_3d_core_c_global.h"

extern "C" {

QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyNodeRemovedChange* qt_3d_core_c_QPropertyNodeRemovedChange_G_dynamic_cast_Qt3DCore_QPropertyNodeRemovedChange_ptr_Qt3DCore_QPropertyValueRemovedChangeBase(Qt3DCore::QPropertyValueRemovedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyNodeRemovedChange* qt_3d_core_c_QPropertyNodeRemovedChange_G_dynamic_cast_Qt3DCore_QPropertyNodeRemovedChange_ptr_Qt3DCore_QSceneChange(Qt3DCore::QSceneChange* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyNodeRemovedChange* qt_3d_core_c_QPropertyNodeRemovedChange_G_dynamic_cast_Qt3DCore_QPropertyNodeRemovedChange_ptr_Qt3DCore_QStaticPropertyValueRemovedChangeBase(Qt3DCore::QStaticPropertyValueRemovedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyNodeRemovedChange* qt_3d_core_c_QPropertyNodeRemovedChange_G_static_cast_Qt3DCore_QPropertyNodeRemovedChange_ptr_Qt3DCore_QPropertyValueRemovedChangeBase(Qt3DCore::QPropertyValueRemovedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyNodeRemovedChange* qt_3d_core_c_QPropertyNodeRemovedChange_G_static_cast_Qt3DCore_QPropertyNodeRemovedChange_ptr_Qt3DCore_QSceneChange(Qt3DCore::QSceneChange* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyNodeRemovedChange* qt_3d_core_c_QPropertyNodeRemovedChange_G_static_cast_Qt3DCore_QPropertyNodeRemovedChange_ptr_Qt3DCore_QStaticPropertyValueRemovedChangeBase(Qt3DCore::QStaticPropertyValueRemovedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyValueRemovedChangeBase* qt_3d_core_c_QPropertyNodeRemovedChange_G_static_cast_Qt3DCore_QPropertyValueRemovedChangeBase_ptr(Qt3DCore::QPropertyNodeRemovedChange* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QSceneChange* qt_3d_core_c_QPropertyNodeRemovedChange_G_static_cast_Qt3DCore_QSceneChange_ptr(Qt3DCore::QPropertyNodeRemovedChange* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QStaticPropertyValueRemovedChangeBase* qt_3d_core_c_QPropertyNodeRemovedChange_G_static_cast_Qt3DCore_QStaticPropertyValueRemovedChangeBase_ptr(Qt3DCore::QPropertyNodeRemovedChange* ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_Qt3DCore_QPropertyNodeRemovedChange_delete(Qt3DCore::QPropertyNodeRemovedChange* this_ptr);
QT_3D_CORE_C_EXPORT const QMetaObject* qt_3d_core_c_Qt3DCore_QPropertyNodeRemovedChange_metaObject(const Qt3DCore::QPropertyNodeRemovedChange* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyNodeRemovedChange* qt_3d_core_c_Qt3DCore_QPropertyNodeRemovedChange_new(const Qt3DCore::QNodeId* subjectId, Qt3DCore::QNode* node);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_Qt3DCore_QPropertyNodeRemovedChange_removedNodeId_to_output(const Qt3DCore::QPropertyNodeRemovedChange* this_ptr, Qt3DCore::QNodeId* output);

} // extern "C"

#endif // QT_3D_CORE_C_QPROPERTYNODEREMOVEDCHANGE_H
