#ifndef QT_3D_CORE_C_QVECTOR_H
#define QT_3D_CORE_C_QVECTOR_H

#include "qt_3d_core_c_global.h"

extern "C" {

QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_append_l(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* l);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_append_t(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, const QSharedPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT const QSharedPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_at(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, int i);
QT_3D_CORE_C_EXPORT QSharedPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_back(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT const QSharedPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_back_const(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_capacity(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_clear(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT const QSharedPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_constData(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT const QSharedPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_constFirst(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT const QSharedPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_constLast(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_constructor_no_args(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_constructor_size(int size, QVector< QSharedPointer< Qt3DCore::QAspectJob > >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_constructor_size_t(int size, const QSharedPointer< Qt3DCore::QAspectJob >* t, QVector< QSharedPointer< Qt3DCore::QAspectJob > >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_constructor_v(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* v, QVector< QSharedPointer< Qt3DCore::QAspectJob > >* output);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_contains(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, const QSharedPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_count_no_args(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_count_t(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, const QSharedPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT QSharedPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_data(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT const QSharedPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_data_const(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_destructor(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_empty(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_endsWith(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, const QSharedPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT QVector< QSharedPointer< Qt3DCore::QAspectJob > >* qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_fill_t(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, const QSharedPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT QVector< QSharedPointer< Qt3DCore::QAspectJob > >* qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_fill_t_size(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, const QSharedPointer< Qt3DCore::QAspectJob >* t, int size);
QT_3D_CORE_C_EXPORT QSharedPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_first(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT const QSharedPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_first_const(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT QSharedPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_front(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT const QSharedPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_front_const(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_indexOf_t(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, const QSharedPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_indexOf_t_from(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, const QSharedPointer< Qt3DCore::QAspectJob >* t, int from);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_insert_i_n_t(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, int i, int n, const QSharedPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_insert_i_t(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, int i, const QSharedPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_isEmpty(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT QSharedPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_last(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_lastIndexOf_t(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, const QSharedPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_lastIndexOf_t_from(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, const QSharedPointer< Qt3DCore::QAspectJob >* t, int from);
QT_3D_CORE_C_EXPORT const QSharedPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_last_const(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_length(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_mid_to_output_pos(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, int pos, QVector< QSharedPointer< Qt3DCore::QAspectJob > >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_mid_to_output_pos_len(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, int pos, int len, QVector< QSharedPointer< Qt3DCore::QAspectJob > >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_move(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, int from, int to);
QT_3D_CORE_C_EXPORT QVector< QSharedPointer< Qt3DCore::QAspectJob > >* qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_operator_add_assign_l(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* l);
QT_3D_CORE_C_EXPORT QVector< QSharedPointer< Qt3DCore::QAspectJob > >* qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_operator_add_assign_t(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, const QSharedPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_operator_add_to_output(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* l, QVector< QSharedPointer< Qt3DCore::QAspectJob > >* output);
QT_3D_CORE_C_EXPORT QVector< QSharedPointer< Qt3DCore::QAspectJob > >* qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_operator_assign(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* v);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_operator_eq(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* v);
QT_3D_CORE_C_EXPORT QSharedPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_operator_index(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, int i);
QT_3D_CORE_C_EXPORT const QSharedPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_operator_index_const(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, int i);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_operator_neq(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* v);
QT_3D_CORE_C_EXPORT QVector< QSharedPointer< Qt3DCore::QAspectJob > >* qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_operator_shl_l(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* l);
QT_3D_CORE_C_EXPORT QVector< QSharedPointer< Qt3DCore::QAspectJob > >* qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_operator_shl_t(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, const QSharedPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_pop_back(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_pop_front(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_prepend(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, const QSharedPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_push_back(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, const QSharedPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_push_front(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, const QSharedPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_removeAll(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, const QSharedPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_removeAt(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, int i);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_removeFirst(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_removeLast(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_removeOne(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, const QSharedPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_remove_i(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, int i);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_remove_i_n(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, int i, int n);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_replace(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, int i, const QSharedPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_reserve(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, int size);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_resize(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, int size);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_size(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_squeeze(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_startsWith(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, const QSharedPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_swap(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, QVector< QSharedPointer< Qt3DCore::QAspectJob > >* other);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_takeAt_to_output(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, int i, QSharedPointer< Qt3DCore::QAspectJob >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_takeFirst_to_output(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, QSharedPointer< Qt3DCore::QAspectJob >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_takeLast_to_output(QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, QSharedPointer< Qt3DCore::QAspectJob >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_value_to_output_i(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, int i, QSharedPointer< Qt3DCore::QAspectJob >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QSharedPointer_Qt3DCore_QAspectJob_value_to_output_i_defaultValue(const QVector< QSharedPointer< Qt3DCore::QAspectJob > >* this_ptr, int i, const QSharedPointer< Qt3DCore::QAspectJob >* defaultValue, QSharedPointer< Qt3DCore::QAspectJob >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_append_l(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* l);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_append_t(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, const QWeakPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT const QWeakPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_at(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, int i);
QT_3D_CORE_C_EXPORT QWeakPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_back(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT const QWeakPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_back_const(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_capacity(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_clear(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT const QWeakPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_constData(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT const QWeakPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_constFirst(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT const QWeakPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_constLast(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_constructor_no_args(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_constructor_size(int size, QVector< QWeakPointer< Qt3DCore::QAspectJob > >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_constructor_size_t(int size, const QWeakPointer< Qt3DCore::QAspectJob >* t, QVector< QWeakPointer< Qt3DCore::QAspectJob > >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_constructor_v(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* v, QVector< QWeakPointer< Qt3DCore::QAspectJob > >* output);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_contains(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, const QWeakPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_count_no_args(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_count_t(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, const QWeakPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT QWeakPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_data(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT const QWeakPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_data_const(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_destructor(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_empty(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_endsWith(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, const QWeakPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT QVector< QWeakPointer< Qt3DCore::QAspectJob > >* qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_fill_t(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, const QWeakPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT QVector< QWeakPointer< Qt3DCore::QAspectJob > >* qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_fill_t_size(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, const QWeakPointer< Qt3DCore::QAspectJob >* t, int size);
QT_3D_CORE_C_EXPORT QWeakPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_first(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT const QWeakPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_first_const(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT QWeakPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_front(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT const QWeakPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_front_const(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_indexOf_t(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, const QWeakPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_indexOf_t_from(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, const QWeakPointer< Qt3DCore::QAspectJob >* t, int from);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_insert_i_n_t(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, int i, int n, const QWeakPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_insert_i_t(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, int i, const QWeakPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_isEmpty(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT QWeakPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_last(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_lastIndexOf_t(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, const QWeakPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_lastIndexOf_t_from(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, const QWeakPointer< Qt3DCore::QAspectJob >* t, int from);
QT_3D_CORE_C_EXPORT const QWeakPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_last_const(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_length(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_mid_to_output_pos(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, int pos, QVector< QWeakPointer< Qt3DCore::QAspectJob > >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_mid_to_output_pos_len(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, int pos, int len, QVector< QWeakPointer< Qt3DCore::QAspectJob > >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_move(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, int from, int to);
QT_3D_CORE_C_EXPORT QVector< QWeakPointer< Qt3DCore::QAspectJob > >* qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_operator_add_assign_l(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* l);
QT_3D_CORE_C_EXPORT QVector< QWeakPointer< Qt3DCore::QAspectJob > >* qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_operator_add_assign_t(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, const QWeakPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_operator_add_to_output(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* l, QVector< QWeakPointer< Qt3DCore::QAspectJob > >* output);
QT_3D_CORE_C_EXPORT QVector< QWeakPointer< Qt3DCore::QAspectJob > >* qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_operator_assign(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* v);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_operator_eq(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* v);
QT_3D_CORE_C_EXPORT QWeakPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_operator_index(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, int i);
QT_3D_CORE_C_EXPORT const QWeakPointer< Qt3DCore::QAspectJob >* qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_operator_index_const(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, int i);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_operator_neq(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* v);
QT_3D_CORE_C_EXPORT QVector< QWeakPointer< Qt3DCore::QAspectJob > >* qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_operator_shl_l(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* l);
QT_3D_CORE_C_EXPORT QVector< QWeakPointer< Qt3DCore::QAspectJob > >* qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_operator_shl_t(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, const QWeakPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_pop_back(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_pop_front(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_prepend(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, const QWeakPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_push_back(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, const QWeakPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_push_front(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, const QWeakPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_removeAll(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, const QWeakPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_removeAt(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, int i);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_removeFirst(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_removeLast(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_removeOne(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, const QWeakPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_remove_i(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, int i);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_remove_i_n(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, int i, int n);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_replace(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, int i, const QWeakPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_reserve(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, int size);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_resize(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, int size);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_size(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_squeeze(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_startsWith(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, const QWeakPointer< Qt3DCore::QAspectJob >* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_swap(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, QVector< QWeakPointer< Qt3DCore::QAspectJob > >* other);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_takeAt_to_output(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, int i, QWeakPointer< Qt3DCore::QAspectJob >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_takeFirst_to_output(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, QWeakPointer< Qt3DCore::QAspectJob >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_takeLast_to_output(QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, QWeakPointer< Qt3DCore::QAspectJob >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_value_to_output_i(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, int i, QWeakPointer< Qt3DCore::QAspectJob >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_QWeakPointer_Qt3DCore_QAspectJob_value_to_output_i_defaultValue(const QVector< QWeakPointer< Qt3DCore::QAspectJob > >* this_ptr, int i, const QWeakPointer< Qt3DCore::QAspectJob >* defaultValue, QWeakPointer< Qt3DCore::QAspectJob >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_append_l(QVector< Qt3DCore::QAbstractAspect* >* this_ptr, const QVector< Qt3DCore::QAbstractAspect* >* l);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_append_t(QVector< Qt3DCore::QAbstractAspect* >* this_ptr, Qt3DCore::QAbstractAspect* const * t);
QT_3D_CORE_C_EXPORT Qt3DCore::QAbstractAspect* const * qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_at(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr, int i);
QT_3D_CORE_C_EXPORT Qt3DCore::QAbstractAspect** qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_back(QVector< Qt3DCore::QAbstractAspect* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QAbstractAspect* const * qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_back_const(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_capacity(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_clear(QVector< Qt3DCore::QAbstractAspect* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QAbstractAspect* const * qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_constData(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QAbstractAspect* const * qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_constFirst(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QAbstractAspect* const * qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_constLast(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_constructor_no_args(QVector< Qt3DCore::QAbstractAspect* >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_constructor_size(int size, QVector< Qt3DCore::QAbstractAspect* >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_constructor_size_t(int size, Qt3DCore::QAbstractAspect* const * t, QVector< Qt3DCore::QAbstractAspect* >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_constructor_v(const QVector< Qt3DCore::QAbstractAspect* >* v, QVector< Qt3DCore::QAbstractAspect* >* output);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_contains(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr, Qt3DCore::QAbstractAspect* const * t);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_count_no_args(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_count_t(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr, Qt3DCore::QAbstractAspect* const * t);
QT_3D_CORE_C_EXPORT Qt3DCore::QAbstractAspect** qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_data(QVector< Qt3DCore::QAbstractAspect* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QAbstractAspect* const * qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_data_const(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_destructor(QVector< Qt3DCore::QAbstractAspect* >* this_ptr);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_empty(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_endsWith(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr, Qt3DCore::QAbstractAspect* const * t);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QAbstractAspect* >* qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_fill_t(QVector< Qt3DCore::QAbstractAspect* >* this_ptr, Qt3DCore::QAbstractAspect* const * t);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QAbstractAspect* >* qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_fill_t_size(QVector< Qt3DCore::QAbstractAspect* >* this_ptr, Qt3DCore::QAbstractAspect* const * t, int size);
QT_3D_CORE_C_EXPORT Qt3DCore::QAbstractAspect** qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_first(QVector< Qt3DCore::QAbstractAspect* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QAbstractAspect* const * qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_first_const(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QAbstractAspect** qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_front(QVector< Qt3DCore::QAbstractAspect* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QAbstractAspect* const * qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_front_const(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_indexOf_t(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr, Qt3DCore::QAbstractAspect* const * t);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_indexOf_t_from(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr, Qt3DCore::QAbstractAspect* const * t, int from);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_insert_i_n_t(QVector< Qt3DCore::QAbstractAspect* >* this_ptr, int i, int n, Qt3DCore::QAbstractAspect* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_insert_i_t(QVector< Qt3DCore::QAbstractAspect* >* this_ptr, int i, Qt3DCore::QAbstractAspect* const * t);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_isEmpty(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QAbstractAspect** qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_last(QVector< Qt3DCore::QAbstractAspect* >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_lastIndexOf_t(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr, Qt3DCore::QAbstractAspect* const * t);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_lastIndexOf_t_from(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr, Qt3DCore::QAbstractAspect* const * t, int from);
QT_3D_CORE_C_EXPORT Qt3DCore::QAbstractAspect* const * qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_last_const(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_length(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_mid_to_output_pos(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr, int pos, QVector< Qt3DCore::QAbstractAspect* >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_mid_to_output_pos_len(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr, int pos, int len, QVector< Qt3DCore::QAbstractAspect* >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_move(QVector< Qt3DCore::QAbstractAspect* >* this_ptr, int from, int to);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QAbstractAspect* >* qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_operator_add_assign_l(QVector< Qt3DCore::QAbstractAspect* >* this_ptr, const QVector< Qt3DCore::QAbstractAspect* >* l);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QAbstractAspect* >* qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_operator_add_assign_t(QVector< Qt3DCore::QAbstractAspect* >* this_ptr, Qt3DCore::QAbstractAspect* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_operator_add_to_output(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr, const QVector< Qt3DCore::QAbstractAspect* >* l, QVector< Qt3DCore::QAbstractAspect* >* output);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QAbstractAspect* >* qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_operator_assign(QVector< Qt3DCore::QAbstractAspect* >* this_ptr, const QVector< Qt3DCore::QAbstractAspect* >* v);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_operator_eq(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr, const QVector< Qt3DCore::QAbstractAspect* >* v);
QT_3D_CORE_C_EXPORT Qt3DCore::QAbstractAspect** qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_operator_index(QVector< Qt3DCore::QAbstractAspect* >* this_ptr, int i);
QT_3D_CORE_C_EXPORT Qt3DCore::QAbstractAspect* const * qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_operator_index_const(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr, int i);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_operator_neq(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr, const QVector< Qt3DCore::QAbstractAspect* >* v);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QAbstractAspect* >* qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_operator_shl_l(QVector< Qt3DCore::QAbstractAspect* >* this_ptr, const QVector< Qt3DCore::QAbstractAspect* >* l);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QAbstractAspect* >* qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_operator_shl_t(QVector< Qt3DCore::QAbstractAspect* >* this_ptr, Qt3DCore::QAbstractAspect* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_pop_back(QVector< Qt3DCore::QAbstractAspect* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_pop_front(QVector< Qt3DCore::QAbstractAspect* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_prepend(QVector< Qt3DCore::QAbstractAspect* >* this_ptr, Qt3DCore::QAbstractAspect* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_push_back(QVector< Qt3DCore::QAbstractAspect* >* this_ptr, Qt3DCore::QAbstractAspect* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_push_front(QVector< Qt3DCore::QAbstractAspect* >* this_ptr, Qt3DCore::QAbstractAspect* const * t);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_removeAll(QVector< Qt3DCore::QAbstractAspect* >* this_ptr, Qt3DCore::QAbstractAspect* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_removeAt(QVector< Qt3DCore::QAbstractAspect* >* this_ptr, int i);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_removeFirst(QVector< Qt3DCore::QAbstractAspect* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_removeLast(QVector< Qt3DCore::QAbstractAspect* >* this_ptr);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_removeOne(QVector< Qt3DCore::QAbstractAspect* >* this_ptr, Qt3DCore::QAbstractAspect* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_remove_i(QVector< Qt3DCore::QAbstractAspect* >* this_ptr, int i);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_remove_i_n(QVector< Qt3DCore::QAbstractAspect* >* this_ptr, int i, int n);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_replace(QVector< Qt3DCore::QAbstractAspect* >* this_ptr, int i, Qt3DCore::QAbstractAspect* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_reserve(QVector< Qt3DCore::QAbstractAspect* >* this_ptr, int size);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_resize(QVector< Qt3DCore::QAbstractAspect* >* this_ptr, int size);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_size(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_squeeze(QVector< Qt3DCore::QAbstractAspect* >* this_ptr);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_startsWith(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr, Qt3DCore::QAbstractAspect* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_swap(QVector< Qt3DCore::QAbstractAspect* >* this_ptr, QVector< Qt3DCore::QAbstractAspect* >* other);
QT_3D_CORE_C_EXPORT Qt3DCore::QAbstractAspect* qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_takeAt(QVector< Qt3DCore::QAbstractAspect* >* this_ptr, int i);
QT_3D_CORE_C_EXPORT Qt3DCore::QAbstractAspect* qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_takeFirst(QVector< Qt3DCore::QAbstractAspect* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QAbstractAspect* qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_takeLast(QVector< Qt3DCore::QAbstractAspect* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QAbstractAspect* qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_value_i(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr, int i);
QT_3D_CORE_C_EXPORT Qt3DCore::QAbstractAspect* qt_3d_core_c_QVector_Qt3DCore_QAbstractAspect_ptr_value_i_defaultValue(const QVector< Qt3DCore::QAbstractAspect* >* this_ptr, int i, Qt3DCore::QAbstractAspect* const * defaultValue);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_append_l(QVector< Qt3DCore::QComponent* >* this_ptr, const QVector< Qt3DCore::QComponent* >* l);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_append_t(QVector< Qt3DCore::QComponent* >* this_ptr, Qt3DCore::QComponent* const * t);
QT_3D_CORE_C_EXPORT Qt3DCore::QComponent* const * qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_at(const QVector< Qt3DCore::QComponent* >* this_ptr, int i);
QT_3D_CORE_C_EXPORT Qt3DCore::QComponent** qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_back(QVector< Qt3DCore::QComponent* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QComponent* const * qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_back_const(const QVector< Qt3DCore::QComponent* >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_capacity(const QVector< Qt3DCore::QComponent* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_clear(QVector< Qt3DCore::QComponent* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QComponent* const * qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_constData(const QVector< Qt3DCore::QComponent* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QComponent* const * qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_constFirst(const QVector< Qt3DCore::QComponent* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QComponent* const * qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_constLast(const QVector< Qt3DCore::QComponent* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_constructor_no_args(QVector< Qt3DCore::QComponent* >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_constructor_size(int size, QVector< Qt3DCore::QComponent* >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_constructor_size_t(int size, Qt3DCore::QComponent* const * t, QVector< Qt3DCore::QComponent* >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_constructor_v(const QVector< Qt3DCore::QComponent* >* v, QVector< Qt3DCore::QComponent* >* output);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_contains(const QVector< Qt3DCore::QComponent* >* this_ptr, Qt3DCore::QComponent* const * t);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_count_no_args(const QVector< Qt3DCore::QComponent* >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_count_t(const QVector< Qt3DCore::QComponent* >* this_ptr, Qt3DCore::QComponent* const * t);
QT_3D_CORE_C_EXPORT Qt3DCore::QComponent** qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_data(QVector< Qt3DCore::QComponent* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QComponent* const * qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_data_const(const QVector< Qt3DCore::QComponent* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_destructor(QVector< Qt3DCore::QComponent* >* this_ptr);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_empty(const QVector< Qt3DCore::QComponent* >* this_ptr);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_endsWith(const QVector< Qt3DCore::QComponent* >* this_ptr, Qt3DCore::QComponent* const * t);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QComponent* >* qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_fill_t(QVector< Qt3DCore::QComponent* >* this_ptr, Qt3DCore::QComponent* const * t);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QComponent* >* qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_fill_t_size(QVector< Qt3DCore::QComponent* >* this_ptr, Qt3DCore::QComponent* const * t, int size);
QT_3D_CORE_C_EXPORT Qt3DCore::QComponent** qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_first(QVector< Qt3DCore::QComponent* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QComponent* const * qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_first_const(const QVector< Qt3DCore::QComponent* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QComponent** qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_front(QVector< Qt3DCore::QComponent* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QComponent* const * qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_front_const(const QVector< Qt3DCore::QComponent* >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_indexOf_t(const QVector< Qt3DCore::QComponent* >* this_ptr, Qt3DCore::QComponent* const * t);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_indexOf_t_from(const QVector< Qt3DCore::QComponent* >* this_ptr, Qt3DCore::QComponent* const * t, int from);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_insert_i_n_t(QVector< Qt3DCore::QComponent* >* this_ptr, int i, int n, Qt3DCore::QComponent* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_insert_i_t(QVector< Qt3DCore::QComponent* >* this_ptr, int i, Qt3DCore::QComponent* const * t);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_isEmpty(const QVector< Qt3DCore::QComponent* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QComponent** qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_last(QVector< Qt3DCore::QComponent* >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_lastIndexOf_t(const QVector< Qt3DCore::QComponent* >* this_ptr, Qt3DCore::QComponent* const * t);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_lastIndexOf_t_from(const QVector< Qt3DCore::QComponent* >* this_ptr, Qt3DCore::QComponent* const * t, int from);
QT_3D_CORE_C_EXPORT Qt3DCore::QComponent* const * qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_last_const(const QVector< Qt3DCore::QComponent* >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_length(const QVector< Qt3DCore::QComponent* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_mid_to_output_pos(const QVector< Qt3DCore::QComponent* >* this_ptr, int pos, QVector< Qt3DCore::QComponent* >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_mid_to_output_pos_len(const QVector< Qt3DCore::QComponent* >* this_ptr, int pos, int len, QVector< Qt3DCore::QComponent* >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_move(QVector< Qt3DCore::QComponent* >* this_ptr, int from, int to);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QComponent* >* qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_operator_add_assign_l(QVector< Qt3DCore::QComponent* >* this_ptr, const QVector< Qt3DCore::QComponent* >* l);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QComponent* >* qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_operator_add_assign_t(QVector< Qt3DCore::QComponent* >* this_ptr, Qt3DCore::QComponent* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_operator_add_to_output(const QVector< Qt3DCore::QComponent* >* this_ptr, const QVector< Qt3DCore::QComponent* >* l, QVector< Qt3DCore::QComponent* >* output);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QComponent* >* qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_operator_assign(QVector< Qt3DCore::QComponent* >* this_ptr, const QVector< Qt3DCore::QComponent* >* v);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_operator_eq(const QVector< Qt3DCore::QComponent* >* this_ptr, const QVector< Qt3DCore::QComponent* >* v);
QT_3D_CORE_C_EXPORT Qt3DCore::QComponent** qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_operator_index(QVector< Qt3DCore::QComponent* >* this_ptr, int i);
QT_3D_CORE_C_EXPORT Qt3DCore::QComponent* const * qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_operator_index_const(const QVector< Qt3DCore::QComponent* >* this_ptr, int i);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_operator_neq(const QVector< Qt3DCore::QComponent* >* this_ptr, const QVector< Qt3DCore::QComponent* >* v);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QComponent* >* qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_operator_shl_l(QVector< Qt3DCore::QComponent* >* this_ptr, const QVector< Qt3DCore::QComponent* >* l);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QComponent* >* qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_operator_shl_t(QVector< Qt3DCore::QComponent* >* this_ptr, Qt3DCore::QComponent* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_pop_back(QVector< Qt3DCore::QComponent* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_pop_front(QVector< Qt3DCore::QComponent* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_prepend(QVector< Qt3DCore::QComponent* >* this_ptr, Qt3DCore::QComponent* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_push_back(QVector< Qt3DCore::QComponent* >* this_ptr, Qt3DCore::QComponent* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_push_front(QVector< Qt3DCore::QComponent* >* this_ptr, Qt3DCore::QComponent* const * t);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_removeAll(QVector< Qt3DCore::QComponent* >* this_ptr, Qt3DCore::QComponent* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_removeAt(QVector< Qt3DCore::QComponent* >* this_ptr, int i);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_removeFirst(QVector< Qt3DCore::QComponent* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_removeLast(QVector< Qt3DCore::QComponent* >* this_ptr);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_removeOne(QVector< Qt3DCore::QComponent* >* this_ptr, Qt3DCore::QComponent* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_remove_i(QVector< Qt3DCore::QComponent* >* this_ptr, int i);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_remove_i_n(QVector< Qt3DCore::QComponent* >* this_ptr, int i, int n);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_replace(QVector< Qt3DCore::QComponent* >* this_ptr, int i, Qt3DCore::QComponent* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_reserve(QVector< Qt3DCore::QComponent* >* this_ptr, int size);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_resize(QVector< Qt3DCore::QComponent* >* this_ptr, int size);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_size(const QVector< Qt3DCore::QComponent* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_squeeze(QVector< Qt3DCore::QComponent* >* this_ptr);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_startsWith(const QVector< Qt3DCore::QComponent* >* this_ptr, Qt3DCore::QComponent* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_swap(QVector< Qt3DCore::QComponent* >* this_ptr, QVector< Qt3DCore::QComponent* >* other);
QT_3D_CORE_C_EXPORT Qt3DCore::QComponent* qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_takeAt(QVector< Qt3DCore::QComponent* >* this_ptr, int i);
QT_3D_CORE_C_EXPORT Qt3DCore::QComponent* qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_takeFirst(QVector< Qt3DCore::QComponent* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QComponent* qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_takeLast(QVector< Qt3DCore::QComponent* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QComponent* qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_value_i(const QVector< Qt3DCore::QComponent* >* this_ptr, int i);
QT_3D_CORE_C_EXPORT Qt3DCore::QComponent* qt_3d_core_c_QVector_Qt3DCore_QComponent_ptr_value_i_defaultValue(const QVector< Qt3DCore::QComponent* >* this_ptr, int i, Qt3DCore::QComponent* const * defaultValue);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_append_l(QVector< Qt3DCore::QEntity* >* this_ptr, const QVector< Qt3DCore::QEntity* >* l);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_append_t(QVector< Qt3DCore::QEntity* >* this_ptr, Qt3DCore::QEntity* const * t);
QT_3D_CORE_C_EXPORT Qt3DCore::QEntity* const * qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_at(const QVector< Qt3DCore::QEntity* >* this_ptr, int i);
QT_3D_CORE_C_EXPORT Qt3DCore::QEntity** qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_back(QVector< Qt3DCore::QEntity* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QEntity* const * qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_back_const(const QVector< Qt3DCore::QEntity* >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_capacity(const QVector< Qt3DCore::QEntity* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_clear(QVector< Qt3DCore::QEntity* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QEntity* const * qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_constData(const QVector< Qt3DCore::QEntity* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QEntity* const * qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_constFirst(const QVector< Qt3DCore::QEntity* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QEntity* const * qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_constLast(const QVector< Qt3DCore::QEntity* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_constructor_no_args(QVector< Qt3DCore::QEntity* >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_constructor_size(int size, QVector< Qt3DCore::QEntity* >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_constructor_size_t(int size, Qt3DCore::QEntity* const * t, QVector< Qt3DCore::QEntity* >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_constructor_v(const QVector< Qt3DCore::QEntity* >* v, QVector< Qt3DCore::QEntity* >* output);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_contains(const QVector< Qt3DCore::QEntity* >* this_ptr, Qt3DCore::QEntity* const * t);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_count_no_args(const QVector< Qt3DCore::QEntity* >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_count_t(const QVector< Qt3DCore::QEntity* >* this_ptr, Qt3DCore::QEntity* const * t);
QT_3D_CORE_C_EXPORT Qt3DCore::QEntity** qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_data(QVector< Qt3DCore::QEntity* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QEntity* const * qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_data_const(const QVector< Qt3DCore::QEntity* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_destructor(QVector< Qt3DCore::QEntity* >* this_ptr);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_empty(const QVector< Qt3DCore::QEntity* >* this_ptr);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_endsWith(const QVector< Qt3DCore::QEntity* >* this_ptr, Qt3DCore::QEntity* const * t);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QEntity* >* qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_fill_t(QVector< Qt3DCore::QEntity* >* this_ptr, Qt3DCore::QEntity* const * t);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QEntity* >* qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_fill_t_size(QVector< Qt3DCore::QEntity* >* this_ptr, Qt3DCore::QEntity* const * t, int size);
QT_3D_CORE_C_EXPORT Qt3DCore::QEntity** qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_first(QVector< Qt3DCore::QEntity* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QEntity* const * qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_first_const(const QVector< Qt3DCore::QEntity* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QEntity** qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_front(QVector< Qt3DCore::QEntity* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QEntity* const * qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_front_const(const QVector< Qt3DCore::QEntity* >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_indexOf_t(const QVector< Qt3DCore::QEntity* >* this_ptr, Qt3DCore::QEntity* const * t);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_indexOf_t_from(const QVector< Qt3DCore::QEntity* >* this_ptr, Qt3DCore::QEntity* const * t, int from);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_insert_i_n_t(QVector< Qt3DCore::QEntity* >* this_ptr, int i, int n, Qt3DCore::QEntity* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_insert_i_t(QVector< Qt3DCore::QEntity* >* this_ptr, int i, Qt3DCore::QEntity* const * t);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_isEmpty(const QVector< Qt3DCore::QEntity* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QEntity** qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_last(QVector< Qt3DCore::QEntity* >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_lastIndexOf_t(const QVector< Qt3DCore::QEntity* >* this_ptr, Qt3DCore::QEntity* const * t);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_lastIndexOf_t_from(const QVector< Qt3DCore::QEntity* >* this_ptr, Qt3DCore::QEntity* const * t, int from);
QT_3D_CORE_C_EXPORT Qt3DCore::QEntity* const * qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_last_const(const QVector< Qt3DCore::QEntity* >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_length(const QVector< Qt3DCore::QEntity* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_mid_to_output_pos(const QVector< Qt3DCore::QEntity* >* this_ptr, int pos, QVector< Qt3DCore::QEntity* >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_mid_to_output_pos_len(const QVector< Qt3DCore::QEntity* >* this_ptr, int pos, int len, QVector< Qt3DCore::QEntity* >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_move(QVector< Qt3DCore::QEntity* >* this_ptr, int from, int to);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QEntity* >* qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_operator_add_assign_l(QVector< Qt3DCore::QEntity* >* this_ptr, const QVector< Qt3DCore::QEntity* >* l);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QEntity* >* qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_operator_add_assign_t(QVector< Qt3DCore::QEntity* >* this_ptr, Qt3DCore::QEntity* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_operator_add_to_output(const QVector< Qt3DCore::QEntity* >* this_ptr, const QVector< Qt3DCore::QEntity* >* l, QVector< Qt3DCore::QEntity* >* output);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QEntity* >* qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_operator_assign(QVector< Qt3DCore::QEntity* >* this_ptr, const QVector< Qt3DCore::QEntity* >* v);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_operator_eq(const QVector< Qt3DCore::QEntity* >* this_ptr, const QVector< Qt3DCore::QEntity* >* v);
QT_3D_CORE_C_EXPORT Qt3DCore::QEntity** qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_operator_index(QVector< Qt3DCore::QEntity* >* this_ptr, int i);
QT_3D_CORE_C_EXPORT Qt3DCore::QEntity* const * qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_operator_index_const(const QVector< Qt3DCore::QEntity* >* this_ptr, int i);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_operator_neq(const QVector< Qt3DCore::QEntity* >* this_ptr, const QVector< Qt3DCore::QEntity* >* v);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QEntity* >* qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_operator_shl_l(QVector< Qt3DCore::QEntity* >* this_ptr, const QVector< Qt3DCore::QEntity* >* l);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QEntity* >* qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_operator_shl_t(QVector< Qt3DCore::QEntity* >* this_ptr, Qt3DCore::QEntity* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_pop_back(QVector< Qt3DCore::QEntity* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_pop_front(QVector< Qt3DCore::QEntity* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_prepend(QVector< Qt3DCore::QEntity* >* this_ptr, Qt3DCore::QEntity* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_push_back(QVector< Qt3DCore::QEntity* >* this_ptr, Qt3DCore::QEntity* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_push_front(QVector< Qt3DCore::QEntity* >* this_ptr, Qt3DCore::QEntity* const * t);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_removeAll(QVector< Qt3DCore::QEntity* >* this_ptr, Qt3DCore::QEntity* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_removeAt(QVector< Qt3DCore::QEntity* >* this_ptr, int i);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_removeFirst(QVector< Qt3DCore::QEntity* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_removeLast(QVector< Qt3DCore::QEntity* >* this_ptr);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_removeOne(QVector< Qt3DCore::QEntity* >* this_ptr, Qt3DCore::QEntity* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_remove_i(QVector< Qt3DCore::QEntity* >* this_ptr, int i);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_remove_i_n(QVector< Qt3DCore::QEntity* >* this_ptr, int i, int n);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_replace(QVector< Qt3DCore::QEntity* >* this_ptr, int i, Qt3DCore::QEntity* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_reserve(QVector< Qt3DCore::QEntity* >* this_ptr, int size);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_resize(QVector< Qt3DCore::QEntity* >* this_ptr, int size);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_size(const QVector< Qt3DCore::QEntity* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_squeeze(QVector< Qt3DCore::QEntity* >* this_ptr);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_startsWith(const QVector< Qt3DCore::QEntity* >* this_ptr, Qt3DCore::QEntity* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_swap(QVector< Qt3DCore::QEntity* >* this_ptr, QVector< Qt3DCore::QEntity* >* other);
QT_3D_CORE_C_EXPORT Qt3DCore::QEntity* qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_takeAt(QVector< Qt3DCore::QEntity* >* this_ptr, int i);
QT_3D_CORE_C_EXPORT Qt3DCore::QEntity* qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_takeFirst(QVector< Qt3DCore::QEntity* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QEntity* qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_takeLast(QVector< Qt3DCore::QEntity* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QEntity* qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_value_i(const QVector< Qt3DCore::QEntity* >* this_ptr, int i);
QT_3D_CORE_C_EXPORT Qt3DCore::QEntity* qt_3d_core_c_QVector_Qt3DCore_QEntity_ptr_value_i_defaultValue(const QVector< Qt3DCore::QEntity* >* this_ptr, int i, Qt3DCore::QEntity* const * defaultValue);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_append_l(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, const QVector< Qt3DCore::QNodeIdTypePair >* l);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_append_t(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, const Qt3DCore::QNodeIdTypePair* t);
QT_3D_CORE_C_EXPORT const Qt3DCore::QNodeIdTypePair* qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_at(const QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, int i);
QT_3D_CORE_C_EXPORT Qt3DCore::QNodeIdTypePair* qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_back(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr);
QT_3D_CORE_C_EXPORT const Qt3DCore::QNodeIdTypePair* qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_back_const(const QVector< Qt3DCore::QNodeIdTypePair >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_capacity(const QVector< Qt3DCore::QNodeIdTypePair >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_clear(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr);
QT_3D_CORE_C_EXPORT const Qt3DCore::QNodeIdTypePair* qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_constData(const QVector< Qt3DCore::QNodeIdTypePair >* this_ptr);
QT_3D_CORE_C_EXPORT const Qt3DCore::QNodeIdTypePair* qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_constFirst(const QVector< Qt3DCore::QNodeIdTypePair >* this_ptr);
QT_3D_CORE_C_EXPORT const Qt3DCore::QNodeIdTypePair* qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_constLast(const QVector< Qt3DCore::QNodeIdTypePair >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_constructor_no_args(QVector< Qt3DCore::QNodeIdTypePair >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_constructor_size(int size, QVector< Qt3DCore::QNodeIdTypePair >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_constructor_size_t(int size, const Qt3DCore::QNodeIdTypePair* t, QVector< Qt3DCore::QNodeIdTypePair >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_constructor_v(const QVector< Qt3DCore::QNodeIdTypePair >* v, QVector< Qt3DCore::QNodeIdTypePair >* output);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_count(const QVector< Qt3DCore::QNodeIdTypePair >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QNodeIdTypePair* qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_data(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr);
QT_3D_CORE_C_EXPORT const Qt3DCore::QNodeIdTypePair* qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_data_const(const QVector< Qt3DCore::QNodeIdTypePair >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_destructor(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_empty(const QVector< Qt3DCore::QNodeIdTypePair >* this_ptr);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QNodeIdTypePair >* qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_fill_t(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, const Qt3DCore::QNodeIdTypePair* t);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QNodeIdTypePair >* qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_fill_t_size(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, const Qt3DCore::QNodeIdTypePair* t, int size);
QT_3D_CORE_C_EXPORT Qt3DCore::QNodeIdTypePair* qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_first(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr);
QT_3D_CORE_C_EXPORT const Qt3DCore::QNodeIdTypePair* qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_first_const(const QVector< Qt3DCore::QNodeIdTypePair >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QNodeIdTypePair* qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_front(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr);
QT_3D_CORE_C_EXPORT const Qt3DCore::QNodeIdTypePair* qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_front_const(const QVector< Qt3DCore::QNodeIdTypePair >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_insert_i_n_t(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, int i, int n, const Qt3DCore::QNodeIdTypePair* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_insert_i_t(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, int i, const Qt3DCore::QNodeIdTypePair* t);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_isEmpty(const QVector< Qt3DCore::QNodeIdTypePair >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QNodeIdTypePair* qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_last(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr);
QT_3D_CORE_C_EXPORT const Qt3DCore::QNodeIdTypePair* qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_last_const(const QVector< Qt3DCore::QNodeIdTypePair >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_length(const QVector< Qt3DCore::QNodeIdTypePair >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_mid_to_output_pos(const QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, int pos, QVector< Qt3DCore::QNodeIdTypePair >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_mid_to_output_pos_len(const QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, int pos, int len, QVector< Qt3DCore::QNodeIdTypePair >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_move(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, int from, int to);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QNodeIdTypePair >* qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_operator_add_assign_l(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, const QVector< Qt3DCore::QNodeIdTypePair >* l);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QNodeIdTypePair >* qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_operator_add_assign_t(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, const Qt3DCore::QNodeIdTypePair* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_operator_add_to_output(const QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, const QVector< Qt3DCore::QNodeIdTypePair >* l, QVector< Qt3DCore::QNodeIdTypePair >* output);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QNodeIdTypePair >* qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_operator_assign(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, const QVector< Qt3DCore::QNodeIdTypePair >* v);
QT_3D_CORE_C_EXPORT Qt3DCore::QNodeIdTypePair* qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_operator_index(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, int i);
QT_3D_CORE_C_EXPORT const Qt3DCore::QNodeIdTypePair* qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_operator_index_const(const QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, int i);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QNodeIdTypePair >* qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_operator_shl_l(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, const QVector< Qt3DCore::QNodeIdTypePair >* l);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QNodeIdTypePair >* qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_operator_shl_t(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, const Qt3DCore::QNodeIdTypePair* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_pop_back(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_pop_front(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_prepend(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, const Qt3DCore::QNodeIdTypePair* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_push_back(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, const Qt3DCore::QNodeIdTypePair* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_push_front(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, const Qt3DCore::QNodeIdTypePair* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_removeAt(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, int i);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_removeFirst(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_removeLast(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_remove_i(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, int i);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_remove_i_n(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, int i, int n);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_replace(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, int i, const Qt3DCore::QNodeIdTypePair* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_reserve(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, int size);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_resize(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, int size);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_size(const QVector< Qt3DCore::QNodeIdTypePair >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_squeeze(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_swap(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, QVector< Qt3DCore::QNodeIdTypePair >* other);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_takeAt_to_output(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, int i, Qt3DCore::QNodeIdTypePair* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_takeFirst_to_output(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, Qt3DCore::QNodeIdTypePair* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_takeLast_to_output(QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, Qt3DCore::QNodeIdTypePair* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_value_to_output_i(const QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, int i, Qt3DCore::QNodeIdTypePair* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeIdTypePair_value_to_output_i_defaultValue(const QVector< Qt3DCore::QNodeIdTypePair >* this_ptr, int i, const Qt3DCore::QNodeIdTypePair* defaultValue, Qt3DCore::QNodeIdTypePair* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_append_l(QVector< Qt3DCore::QNodeId >* this_ptr, const QVector< Qt3DCore::QNodeId >* l);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_append_t(QVector< Qt3DCore::QNodeId >* this_ptr, const Qt3DCore::QNodeId* t);
QT_3D_CORE_C_EXPORT const Qt3DCore::QNodeId* qt_3d_core_c_QVector_Qt3DCore_QNodeId_at(const QVector< Qt3DCore::QNodeId >* this_ptr, int i);
QT_3D_CORE_C_EXPORT Qt3DCore::QNodeId* qt_3d_core_c_QVector_Qt3DCore_QNodeId_back(QVector< Qt3DCore::QNodeId >* this_ptr);
QT_3D_CORE_C_EXPORT const Qt3DCore::QNodeId* qt_3d_core_c_QVector_Qt3DCore_QNodeId_back_const(const QVector< Qt3DCore::QNodeId >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QNodeId_capacity(const QVector< Qt3DCore::QNodeId >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_clear(QVector< Qt3DCore::QNodeId >* this_ptr);
QT_3D_CORE_C_EXPORT const Qt3DCore::QNodeId* qt_3d_core_c_QVector_Qt3DCore_QNodeId_constData(const QVector< Qt3DCore::QNodeId >* this_ptr);
QT_3D_CORE_C_EXPORT const Qt3DCore::QNodeId* qt_3d_core_c_QVector_Qt3DCore_QNodeId_constFirst(const QVector< Qt3DCore::QNodeId >* this_ptr);
QT_3D_CORE_C_EXPORT const Qt3DCore::QNodeId* qt_3d_core_c_QVector_Qt3DCore_QNodeId_constLast(const QVector< Qt3DCore::QNodeId >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_constructor_no_args(QVector< Qt3DCore::QNodeId >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_constructor_size(int size, QVector< Qt3DCore::QNodeId >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_constructor_size_t(int size, const Qt3DCore::QNodeId* t, QVector< Qt3DCore::QNodeId >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_constructor_v(const QVector< Qt3DCore::QNodeId >* v, QVector< Qt3DCore::QNodeId >* output);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QNodeId_contains(const QVector< Qt3DCore::QNodeId >* this_ptr, const Qt3DCore::QNodeId* t);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QNodeId_count_no_args(const QVector< Qt3DCore::QNodeId >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QNodeId_count_t(const QVector< Qt3DCore::QNodeId >* this_ptr, const Qt3DCore::QNodeId* t);
QT_3D_CORE_C_EXPORT Qt3DCore::QNodeId* qt_3d_core_c_QVector_Qt3DCore_QNodeId_data(QVector< Qt3DCore::QNodeId >* this_ptr);
QT_3D_CORE_C_EXPORT const Qt3DCore::QNodeId* qt_3d_core_c_QVector_Qt3DCore_QNodeId_data_const(const QVector< Qt3DCore::QNodeId >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_destructor(QVector< Qt3DCore::QNodeId >* this_ptr);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QNodeId_empty(const QVector< Qt3DCore::QNodeId >* this_ptr);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QNodeId_endsWith(const QVector< Qt3DCore::QNodeId >* this_ptr, const Qt3DCore::QNodeId* t);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QNodeId >* qt_3d_core_c_QVector_Qt3DCore_QNodeId_fill_t(QVector< Qt3DCore::QNodeId >* this_ptr, const Qt3DCore::QNodeId* t);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QNodeId >* qt_3d_core_c_QVector_Qt3DCore_QNodeId_fill_t_size(QVector< Qt3DCore::QNodeId >* this_ptr, const Qt3DCore::QNodeId* t, int size);
QT_3D_CORE_C_EXPORT Qt3DCore::QNodeId* qt_3d_core_c_QVector_Qt3DCore_QNodeId_first(QVector< Qt3DCore::QNodeId >* this_ptr);
QT_3D_CORE_C_EXPORT const Qt3DCore::QNodeId* qt_3d_core_c_QVector_Qt3DCore_QNodeId_first_const(const QVector< Qt3DCore::QNodeId >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QNodeId* qt_3d_core_c_QVector_Qt3DCore_QNodeId_front(QVector< Qt3DCore::QNodeId >* this_ptr);
QT_3D_CORE_C_EXPORT const Qt3DCore::QNodeId* qt_3d_core_c_QVector_Qt3DCore_QNodeId_front_const(const QVector< Qt3DCore::QNodeId >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QNodeId_indexOf_t(const QVector< Qt3DCore::QNodeId >* this_ptr, const Qt3DCore::QNodeId* t);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QNodeId_indexOf_t_from(const QVector< Qt3DCore::QNodeId >* this_ptr, const Qt3DCore::QNodeId* t, int from);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_insert_i_n_t(QVector< Qt3DCore::QNodeId >* this_ptr, int i, int n, const Qt3DCore::QNodeId* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_insert_i_t(QVector< Qt3DCore::QNodeId >* this_ptr, int i, const Qt3DCore::QNodeId* t);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QNodeId_isEmpty(const QVector< Qt3DCore::QNodeId >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QNodeId* qt_3d_core_c_QVector_Qt3DCore_QNodeId_last(QVector< Qt3DCore::QNodeId >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QNodeId_lastIndexOf_t(const QVector< Qt3DCore::QNodeId >* this_ptr, const Qt3DCore::QNodeId* t);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QNodeId_lastIndexOf_t_from(const QVector< Qt3DCore::QNodeId >* this_ptr, const Qt3DCore::QNodeId* t, int from);
QT_3D_CORE_C_EXPORT const Qt3DCore::QNodeId* qt_3d_core_c_QVector_Qt3DCore_QNodeId_last_const(const QVector< Qt3DCore::QNodeId >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QNodeId_length(const QVector< Qt3DCore::QNodeId >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_mid_to_output_pos(const QVector< Qt3DCore::QNodeId >* this_ptr, int pos, QVector< Qt3DCore::QNodeId >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_mid_to_output_pos_len(const QVector< Qt3DCore::QNodeId >* this_ptr, int pos, int len, QVector< Qt3DCore::QNodeId >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_move(QVector< Qt3DCore::QNodeId >* this_ptr, int from, int to);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QNodeId >* qt_3d_core_c_QVector_Qt3DCore_QNodeId_operator_add_assign_l(QVector< Qt3DCore::QNodeId >* this_ptr, const QVector< Qt3DCore::QNodeId >* l);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QNodeId >* qt_3d_core_c_QVector_Qt3DCore_QNodeId_operator_add_assign_t(QVector< Qt3DCore::QNodeId >* this_ptr, const Qt3DCore::QNodeId* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_operator_add_to_output(const QVector< Qt3DCore::QNodeId >* this_ptr, const QVector< Qt3DCore::QNodeId >* l, QVector< Qt3DCore::QNodeId >* output);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QNodeId >* qt_3d_core_c_QVector_Qt3DCore_QNodeId_operator_assign(QVector< Qt3DCore::QNodeId >* this_ptr, const QVector< Qt3DCore::QNodeId >* v);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QNodeId_operator_eq(const QVector< Qt3DCore::QNodeId >* this_ptr, const QVector< Qt3DCore::QNodeId >* v);
QT_3D_CORE_C_EXPORT Qt3DCore::QNodeId* qt_3d_core_c_QVector_Qt3DCore_QNodeId_operator_index(QVector< Qt3DCore::QNodeId >* this_ptr, int i);
QT_3D_CORE_C_EXPORT const Qt3DCore::QNodeId* qt_3d_core_c_QVector_Qt3DCore_QNodeId_operator_index_const(const QVector< Qt3DCore::QNodeId >* this_ptr, int i);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QNodeId_operator_neq(const QVector< Qt3DCore::QNodeId >* this_ptr, const QVector< Qt3DCore::QNodeId >* v);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QNodeId >* qt_3d_core_c_QVector_Qt3DCore_QNodeId_operator_shl_l(QVector< Qt3DCore::QNodeId >* this_ptr, const QVector< Qt3DCore::QNodeId >* l);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QNodeId >* qt_3d_core_c_QVector_Qt3DCore_QNodeId_operator_shl_t(QVector< Qt3DCore::QNodeId >* this_ptr, const Qt3DCore::QNodeId* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_pop_back(QVector< Qt3DCore::QNodeId >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_pop_front(QVector< Qt3DCore::QNodeId >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_prepend(QVector< Qt3DCore::QNodeId >* this_ptr, const Qt3DCore::QNodeId* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_push_back(QVector< Qt3DCore::QNodeId >* this_ptr, const Qt3DCore::QNodeId* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_push_front(QVector< Qt3DCore::QNodeId >* this_ptr, const Qt3DCore::QNodeId* t);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QNodeId_removeAll(QVector< Qt3DCore::QNodeId >* this_ptr, const Qt3DCore::QNodeId* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_removeAt(QVector< Qt3DCore::QNodeId >* this_ptr, int i);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_removeFirst(QVector< Qt3DCore::QNodeId >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_removeLast(QVector< Qt3DCore::QNodeId >* this_ptr);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QNodeId_removeOne(QVector< Qt3DCore::QNodeId >* this_ptr, const Qt3DCore::QNodeId* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_remove_i(QVector< Qt3DCore::QNodeId >* this_ptr, int i);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_remove_i_n(QVector< Qt3DCore::QNodeId >* this_ptr, int i, int n);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_replace(QVector< Qt3DCore::QNodeId >* this_ptr, int i, const Qt3DCore::QNodeId* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_reserve(QVector< Qt3DCore::QNodeId >* this_ptr, int size);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_resize(QVector< Qt3DCore::QNodeId >* this_ptr, int size);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QNodeId_size(const QVector< Qt3DCore::QNodeId >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_squeeze(QVector< Qt3DCore::QNodeId >* this_ptr);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QNodeId_startsWith(const QVector< Qt3DCore::QNodeId >* this_ptr, const Qt3DCore::QNodeId* t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_swap(QVector< Qt3DCore::QNodeId >* this_ptr, QVector< Qt3DCore::QNodeId >* other);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_takeAt_to_output(QVector< Qt3DCore::QNodeId >* this_ptr, int i, Qt3DCore::QNodeId* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_takeFirst_to_output(QVector< Qt3DCore::QNodeId >* this_ptr, Qt3DCore::QNodeId* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_takeLast_to_output(QVector< Qt3DCore::QNodeId >* this_ptr, Qt3DCore::QNodeId* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_value_to_output_i(const QVector< Qt3DCore::QNodeId >* this_ptr, int i, Qt3DCore::QNodeId* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNodeId_value_to_output_i_defaultValue(const QVector< Qt3DCore::QNodeId >* this_ptr, int i, const Qt3DCore::QNodeId* defaultValue, Qt3DCore::QNodeId* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_append_l(QVector< Qt3DCore::QNode* >* this_ptr, const QVector< Qt3DCore::QNode* >* l);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_append_t(QVector< Qt3DCore::QNode* >* this_ptr, Qt3DCore::QNode* const * t);
QT_3D_CORE_C_EXPORT Qt3DCore::QNode* const * qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_at(const QVector< Qt3DCore::QNode* >* this_ptr, int i);
QT_3D_CORE_C_EXPORT Qt3DCore::QNode** qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_back(QVector< Qt3DCore::QNode* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QNode* const * qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_back_const(const QVector< Qt3DCore::QNode* >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_capacity(const QVector< Qt3DCore::QNode* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_clear(QVector< Qt3DCore::QNode* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QNode* const * qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_constData(const QVector< Qt3DCore::QNode* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QNode* const * qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_constFirst(const QVector< Qt3DCore::QNode* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QNode* const * qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_constLast(const QVector< Qt3DCore::QNode* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_constructor_no_args(QVector< Qt3DCore::QNode* >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_constructor_size(int size, QVector< Qt3DCore::QNode* >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_constructor_size_t(int size, Qt3DCore::QNode* const * t, QVector< Qt3DCore::QNode* >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_constructor_v(const QVector< Qt3DCore::QNode* >* v, QVector< Qt3DCore::QNode* >* output);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_contains(const QVector< Qt3DCore::QNode* >* this_ptr, Qt3DCore::QNode* const * t);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_count_no_args(const QVector< Qt3DCore::QNode* >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_count_t(const QVector< Qt3DCore::QNode* >* this_ptr, Qt3DCore::QNode* const * t);
QT_3D_CORE_C_EXPORT Qt3DCore::QNode** qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_data(QVector< Qt3DCore::QNode* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QNode* const * qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_data_const(const QVector< Qt3DCore::QNode* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_destructor(QVector< Qt3DCore::QNode* >* this_ptr);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_empty(const QVector< Qt3DCore::QNode* >* this_ptr);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_endsWith(const QVector< Qt3DCore::QNode* >* this_ptr, Qt3DCore::QNode* const * t);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QNode* >* qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_fill_t(QVector< Qt3DCore::QNode* >* this_ptr, Qt3DCore::QNode* const * t);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QNode* >* qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_fill_t_size(QVector< Qt3DCore::QNode* >* this_ptr, Qt3DCore::QNode* const * t, int size);
QT_3D_CORE_C_EXPORT Qt3DCore::QNode** qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_first(QVector< Qt3DCore::QNode* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QNode* const * qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_first_const(const QVector< Qt3DCore::QNode* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QNode** qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_front(QVector< Qt3DCore::QNode* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QNode* const * qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_front_const(const QVector< Qt3DCore::QNode* >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_indexOf_t(const QVector< Qt3DCore::QNode* >* this_ptr, Qt3DCore::QNode* const * t);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_indexOf_t_from(const QVector< Qt3DCore::QNode* >* this_ptr, Qt3DCore::QNode* const * t, int from);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_insert_i_n_t(QVector< Qt3DCore::QNode* >* this_ptr, int i, int n, Qt3DCore::QNode* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_insert_i_t(QVector< Qt3DCore::QNode* >* this_ptr, int i, Qt3DCore::QNode* const * t);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_isEmpty(const QVector< Qt3DCore::QNode* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QNode** qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_last(QVector< Qt3DCore::QNode* >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_lastIndexOf_t(const QVector< Qt3DCore::QNode* >* this_ptr, Qt3DCore::QNode* const * t);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_lastIndexOf_t_from(const QVector< Qt3DCore::QNode* >* this_ptr, Qt3DCore::QNode* const * t, int from);
QT_3D_CORE_C_EXPORT Qt3DCore::QNode* const * qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_last_const(const QVector< Qt3DCore::QNode* >* this_ptr);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_length(const QVector< Qt3DCore::QNode* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_mid_to_output_pos(const QVector< Qt3DCore::QNode* >* this_ptr, int pos, QVector< Qt3DCore::QNode* >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_mid_to_output_pos_len(const QVector< Qt3DCore::QNode* >* this_ptr, int pos, int len, QVector< Qt3DCore::QNode* >* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_move(QVector< Qt3DCore::QNode* >* this_ptr, int from, int to);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QNode* >* qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_operator_add_assign_l(QVector< Qt3DCore::QNode* >* this_ptr, const QVector< Qt3DCore::QNode* >* l);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QNode* >* qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_operator_add_assign_t(QVector< Qt3DCore::QNode* >* this_ptr, Qt3DCore::QNode* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_operator_add_to_output(const QVector< Qt3DCore::QNode* >* this_ptr, const QVector< Qt3DCore::QNode* >* l, QVector< Qt3DCore::QNode* >* output);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QNode* >* qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_operator_assign(QVector< Qt3DCore::QNode* >* this_ptr, const QVector< Qt3DCore::QNode* >* v);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_operator_eq(const QVector< Qt3DCore::QNode* >* this_ptr, const QVector< Qt3DCore::QNode* >* v);
QT_3D_CORE_C_EXPORT Qt3DCore::QNode** qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_operator_index(QVector< Qt3DCore::QNode* >* this_ptr, int i);
QT_3D_CORE_C_EXPORT Qt3DCore::QNode* const * qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_operator_index_const(const QVector< Qt3DCore::QNode* >* this_ptr, int i);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_operator_neq(const QVector< Qt3DCore::QNode* >* this_ptr, const QVector< Qt3DCore::QNode* >* v);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QNode* >* qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_operator_shl_l(QVector< Qt3DCore::QNode* >* this_ptr, const QVector< Qt3DCore::QNode* >* l);
QT_3D_CORE_C_EXPORT QVector< Qt3DCore::QNode* >* qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_operator_shl_t(QVector< Qt3DCore::QNode* >* this_ptr, Qt3DCore::QNode* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_pop_back(QVector< Qt3DCore::QNode* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_pop_front(QVector< Qt3DCore::QNode* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_prepend(QVector< Qt3DCore::QNode* >* this_ptr, Qt3DCore::QNode* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_push_back(QVector< Qt3DCore::QNode* >* this_ptr, Qt3DCore::QNode* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_push_front(QVector< Qt3DCore::QNode* >* this_ptr, Qt3DCore::QNode* const * t);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_removeAll(QVector< Qt3DCore::QNode* >* this_ptr, Qt3DCore::QNode* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_removeAt(QVector< Qt3DCore::QNode* >* this_ptr, int i);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_removeFirst(QVector< Qt3DCore::QNode* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_removeLast(QVector< Qt3DCore::QNode* >* this_ptr);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_removeOne(QVector< Qt3DCore::QNode* >* this_ptr, Qt3DCore::QNode* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_remove_i(QVector< Qt3DCore::QNode* >* this_ptr, int i);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_remove_i_n(QVector< Qt3DCore::QNode* >* this_ptr, int i, int n);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_replace(QVector< Qt3DCore::QNode* >* this_ptr, int i, Qt3DCore::QNode* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_reserve(QVector< Qt3DCore::QNode* >* this_ptr, int size);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_resize(QVector< Qt3DCore::QNode* >* this_ptr, int size);
QT_3D_CORE_C_EXPORT int qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_size(const QVector< Qt3DCore::QNode* >* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_squeeze(QVector< Qt3DCore::QNode* >* this_ptr);
QT_3D_CORE_C_EXPORT bool qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_startsWith(const QVector< Qt3DCore::QNode* >* this_ptr, Qt3DCore::QNode* const * t);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_swap(QVector< Qt3DCore::QNode* >* this_ptr, QVector< Qt3DCore::QNode* >* other);
QT_3D_CORE_C_EXPORT Qt3DCore::QNode* qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_takeAt(QVector< Qt3DCore::QNode* >* this_ptr, int i);
QT_3D_CORE_C_EXPORT Qt3DCore::QNode* qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_takeFirst(QVector< Qt3DCore::QNode* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QNode* qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_takeLast(QVector< Qt3DCore::QNode* >* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QNode* qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_value_i(const QVector< Qt3DCore::QNode* >* this_ptr, int i);
QT_3D_CORE_C_EXPORT Qt3DCore::QNode* qt_3d_core_c_QVector_Qt3DCore_QNode_ptr_value_i_defaultValue(const QVector< Qt3DCore::QNode* >* this_ptr, int i, Qt3DCore::QNode* const * defaultValue);

} // extern "C"

#endif // QT_3D_CORE_C_QVECTOR_H
