#ifndef QT_3D_CORE_C_QPROPERTYVALUEADDEDCHANGE_H
#define QT_3D_CORE_C_QPROPERTYVALUEADDEDCHANGE_H

#include "qt_3d_core_c_global.h"

extern "C" {

QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyValueAddedChange* qt_3d_core_c_QPropertyValueAddedChange_G_dynamic_cast_Qt3DCore_QPropertyValueAddedChange_ptr_Qt3DCore_QPropertyValueAddedChangeBase(Qt3DCore::QPropertyValueAddedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyValueAddedChange* qt_3d_core_c_QPropertyValueAddedChange_G_dynamic_cast_Qt3DCore_QPropertyValueAddedChange_ptr_Qt3DCore_QSceneChange(Qt3DCore::QSceneChange* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyValueAddedChange* qt_3d_core_c_QPropertyValueAddedChange_G_dynamic_cast_Qt3DCore_QPropertyValueAddedChange_ptr_Qt3DCore_QStaticPropertyValueAddedChangeBase(Qt3DCore::QStaticPropertyValueAddedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyValueAddedChangeBase* qt_3d_core_c_QPropertyValueAddedChange_G_static_cast_Qt3DCore_QPropertyValueAddedChangeBase_ptr(Qt3DCore::QPropertyValueAddedChange* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyValueAddedChange* qt_3d_core_c_QPropertyValueAddedChange_G_static_cast_Qt3DCore_QPropertyValueAddedChange_ptr_Qt3DCore_QPropertyValueAddedChangeBase(Qt3DCore::QPropertyValueAddedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyValueAddedChange* qt_3d_core_c_QPropertyValueAddedChange_G_static_cast_Qt3DCore_QPropertyValueAddedChange_ptr_Qt3DCore_QSceneChange(Qt3DCore::QSceneChange* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyValueAddedChange* qt_3d_core_c_QPropertyValueAddedChange_G_static_cast_Qt3DCore_QPropertyValueAddedChange_ptr_Qt3DCore_QStaticPropertyValueAddedChangeBase(Qt3DCore::QStaticPropertyValueAddedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QSceneChange* qt_3d_core_c_QPropertyValueAddedChange_G_static_cast_Qt3DCore_QSceneChange_ptr(Qt3DCore::QPropertyValueAddedChange* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QStaticPropertyValueAddedChangeBase* qt_3d_core_c_QPropertyValueAddedChange_G_static_cast_Qt3DCore_QStaticPropertyValueAddedChangeBase_ptr(Qt3DCore::QPropertyValueAddedChange* ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_Qt3DCore_QPropertyValueAddedChange_addedValue_to_output(const Qt3DCore::QPropertyValueAddedChange* this_ptr, QVariant* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_Qt3DCore_QPropertyValueAddedChange_delete(Qt3DCore::QPropertyValueAddedChange* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyValueAddedChange* qt_3d_core_c_Qt3DCore_QPropertyValueAddedChange_new(const Qt3DCore::QNodeId* subjectId);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_Qt3DCore_QPropertyValueAddedChange_setAddedValue(Qt3DCore::QPropertyValueAddedChange* this_ptr, const QVariant* value);

} // extern "C"

#endif // QT_3D_CORE_C_QPROPERTYVALUEADDEDCHANGE_H
