#ifndef QT_3D_CORE_C_QSTATICPROPERTYVALUEADDEDCHANGEBASE_H
#define QT_3D_CORE_C_QSTATICPROPERTYVALUEADDEDCHANGEBASE_H

#include "qt_3d_core_c_global.h"

extern "C" {

QT_3D_CORE_C_EXPORT Qt3DCore::QStaticPropertyValueAddedChangeBase* qt_3d_core_c_QStaticPropertyValueAddedChangeBase_G_dynamic_cast_Qt3DCore_QStaticPropertyValueAddedChangeBase_ptr_Qt3DCore_QPropertyValueAddedChangeBase(Qt3DCore::QPropertyValueAddedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QStaticPropertyValueAddedChangeBase* qt_3d_core_c_QStaticPropertyValueAddedChangeBase_G_dynamic_cast_Qt3DCore_QStaticPropertyValueAddedChangeBase_ptr_Qt3DCore_QSceneChange(Qt3DCore::QSceneChange* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyValueAddedChangeBase* qt_3d_core_c_QStaticPropertyValueAddedChangeBase_G_static_cast_Qt3DCore_QPropertyValueAddedChangeBase_ptr(Qt3DCore::QStaticPropertyValueAddedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QSceneChange* qt_3d_core_c_QStaticPropertyValueAddedChangeBase_G_static_cast_Qt3DCore_QSceneChange_ptr(Qt3DCore::QStaticPropertyValueAddedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QStaticPropertyValueAddedChangeBase* qt_3d_core_c_QStaticPropertyValueAddedChangeBase_G_static_cast_Qt3DCore_QStaticPropertyValueAddedChangeBase_ptr_Qt3DCore_QPropertyValueAddedChangeBase(Qt3DCore::QPropertyValueAddedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QStaticPropertyValueAddedChangeBase* qt_3d_core_c_QStaticPropertyValueAddedChangeBase_G_static_cast_Qt3DCore_QStaticPropertyValueAddedChangeBase_ptr_Qt3DCore_QSceneChange(Qt3DCore::QSceneChange* ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_Qt3DCore_QStaticPropertyValueAddedChangeBase_delete(Qt3DCore::QStaticPropertyValueAddedChangeBase* this_ptr);
QT_3D_CORE_C_EXPORT const char* qt_3d_core_c_Qt3DCore_QStaticPropertyValueAddedChangeBase_propertyName(const Qt3DCore::QStaticPropertyValueAddedChangeBase* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_Qt3DCore_QStaticPropertyValueAddedChangeBase_setPropertyName(Qt3DCore::QStaticPropertyValueAddedChangeBase* this_ptr, const char* name);

} // extern "C"

#endif // QT_3D_CORE_C_QSTATICPROPERTYVALUEADDEDCHANGEBASE_H
