#ifndef QT_3D_CORE_C_QSTATICPROPERTYUPDATEDCHANGEBASE_H
#define QT_3D_CORE_C_QSTATICPROPERTYUPDATEDCHANGEBASE_H

#include "qt_3d_core_c_global.h"

extern "C" {

QT_3D_CORE_C_EXPORT Qt3DCore::QStaticPropertyUpdatedChangeBase* qt_3d_core_c_QStaticPropertyUpdatedChangeBase_G_dynamic_cast_Qt3DCore_QStaticPropertyUpdatedChangeBase_ptr_Qt3DCore_QPropertyUpdatedChangeBase(Qt3DCore::QPropertyUpdatedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QStaticPropertyUpdatedChangeBase* qt_3d_core_c_QStaticPropertyUpdatedChangeBase_G_dynamic_cast_Qt3DCore_QStaticPropertyUpdatedChangeBase_ptr_Qt3DCore_QSceneChange(Qt3DCore::QSceneChange* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyUpdatedChangeBase* qt_3d_core_c_QStaticPropertyUpdatedChangeBase_G_static_cast_Qt3DCore_QPropertyUpdatedChangeBase_ptr(Qt3DCore::QStaticPropertyUpdatedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QSceneChange* qt_3d_core_c_QStaticPropertyUpdatedChangeBase_G_static_cast_Qt3DCore_QSceneChange_ptr(Qt3DCore::QStaticPropertyUpdatedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QStaticPropertyUpdatedChangeBase* qt_3d_core_c_QStaticPropertyUpdatedChangeBase_G_static_cast_Qt3DCore_QStaticPropertyUpdatedChangeBase_ptr_Qt3DCore_QPropertyUpdatedChangeBase(Qt3DCore::QPropertyUpdatedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QStaticPropertyUpdatedChangeBase* qt_3d_core_c_QStaticPropertyUpdatedChangeBase_G_static_cast_Qt3DCore_QStaticPropertyUpdatedChangeBase_ptr_Qt3DCore_QSceneChange(Qt3DCore::QSceneChange* ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_Qt3DCore_QStaticPropertyUpdatedChangeBase_delete(Qt3DCore::QStaticPropertyUpdatedChangeBase* this_ptr);
QT_3D_CORE_C_EXPORT const char* qt_3d_core_c_Qt3DCore_QStaticPropertyUpdatedChangeBase_propertyName(const Qt3DCore::QStaticPropertyUpdatedChangeBase* this_ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_Qt3DCore_QStaticPropertyUpdatedChangeBase_setPropertyName(Qt3DCore::QStaticPropertyUpdatedChangeBase* this_ptr, const char* name);

} // extern "C"

#endif // QT_3D_CORE_C_QSTATICPROPERTYUPDATEDCHANGEBASE_H
