#ifndef QT_3D_CORE_C_QPROPERTYUPDATEDCHANGEBASE_H
#define QT_3D_CORE_C_QPROPERTYUPDATEDCHANGEBASE_H

#include "qt_3d_core_c_global.h"

extern "C" {

QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyUpdatedChangeBase* qt_3d_core_c_QPropertyUpdatedChangeBase_G_dynamic_cast_Qt3DCore_QPropertyUpdatedChangeBase_ptr(Qt3DCore::QSceneChange* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyUpdatedChangeBase* qt_3d_core_c_QPropertyUpdatedChangeBase_G_static_cast_Qt3DCore_QPropertyUpdatedChangeBase_ptr(Qt3DCore::QSceneChange* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QSceneChange* qt_3d_core_c_QPropertyUpdatedChangeBase_G_static_cast_Qt3DCore_QSceneChange_ptr(Qt3DCore::QPropertyUpdatedChangeBase* ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_Qt3DCore_QPropertyUpdatedChangeBase_delete(Qt3DCore::QPropertyUpdatedChangeBase* this_ptr);

} // extern "C"

#endif // QT_3D_CORE_C_QPROPERTYUPDATEDCHANGEBASE_H
