#ifndef QT_3D_CORE_C_QPROPERTYUPDATEDCHANGE_H
#define QT_3D_CORE_C_QPROPERTYUPDATEDCHANGE_H

#include "qt_3d_core_c_global.h"

extern "C" {

QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyUpdatedChange* qt_3d_core_c_QPropertyUpdatedChange_G_dynamic_cast_Qt3DCore_QPropertyUpdatedChange_ptr_Qt3DCore_QPropertyUpdatedChangeBase(Qt3DCore::QPropertyUpdatedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyUpdatedChange* qt_3d_core_c_QPropertyUpdatedChange_G_dynamic_cast_Qt3DCore_QPropertyUpdatedChange_ptr_Qt3DCore_QSceneChange(Qt3DCore::QSceneChange* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyUpdatedChange* qt_3d_core_c_QPropertyUpdatedChange_G_dynamic_cast_Qt3DCore_QPropertyUpdatedChange_ptr_Qt3DCore_QStaticPropertyUpdatedChangeBase(Qt3DCore::QStaticPropertyUpdatedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyUpdatedChangeBase* qt_3d_core_c_QPropertyUpdatedChange_G_static_cast_Qt3DCore_QPropertyUpdatedChangeBase_ptr(Qt3DCore::QPropertyUpdatedChange* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyUpdatedChange* qt_3d_core_c_QPropertyUpdatedChange_G_static_cast_Qt3DCore_QPropertyUpdatedChange_ptr_Qt3DCore_QPropertyUpdatedChangeBase(Qt3DCore::QPropertyUpdatedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyUpdatedChange* qt_3d_core_c_QPropertyUpdatedChange_G_static_cast_Qt3DCore_QPropertyUpdatedChange_ptr_Qt3DCore_QSceneChange(Qt3DCore::QSceneChange* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyUpdatedChange* qt_3d_core_c_QPropertyUpdatedChange_G_static_cast_Qt3DCore_QPropertyUpdatedChange_ptr_Qt3DCore_QStaticPropertyUpdatedChangeBase(Qt3DCore::QStaticPropertyUpdatedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QSceneChange* qt_3d_core_c_QPropertyUpdatedChange_G_static_cast_Qt3DCore_QSceneChange_ptr(Qt3DCore::QPropertyUpdatedChange* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QStaticPropertyUpdatedChangeBase* qt_3d_core_c_QPropertyUpdatedChange_G_static_cast_Qt3DCore_QStaticPropertyUpdatedChangeBase_ptr(Qt3DCore::QPropertyUpdatedChange* ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_Qt3DCore_QPropertyUpdatedChange_delete(Qt3DCore::QPropertyUpdatedChange* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyUpdatedChange* qt_3d_core_c_Qt3DCore_QPropertyUpdatedChange_new(const Qt3DCore::QNodeId* subjectId);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_Qt3DCore_QPropertyUpdatedChange_setValue(Qt3DCore::QPropertyUpdatedChange* this_ptr, const QVariant* value);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_Qt3DCore_QPropertyUpdatedChange_value_to_output(const Qt3DCore::QPropertyUpdatedChange* this_ptr, QVariant* output);

} // extern "C"

#endif // QT_3D_CORE_C_QPROPERTYUPDATEDCHANGE_H
