#ifndef QT_3D_CORE_C_QPROPERTYNODEADDEDCHANGE_H
#define QT_3D_CORE_C_QPROPERTYNODEADDEDCHANGE_H

#include "qt_3d_core_c_global.h"

extern "C" {

QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyNodeAddedChange* qt_3d_core_c_QPropertyNodeAddedChange_G_dynamic_cast_Qt3DCore_QPropertyNodeAddedChange_ptr_Qt3DCore_QPropertyValueAddedChangeBase(Qt3DCore::QPropertyValueAddedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyNodeAddedChange* qt_3d_core_c_QPropertyNodeAddedChange_G_dynamic_cast_Qt3DCore_QPropertyNodeAddedChange_ptr_Qt3DCore_QSceneChange(Qt3DCore::QSceneChange* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyNodeAddedChange* qt_3d_core_c_QPropertyNodeAddedChange_G_dynamic_cast_Qt3DCore_QPropertyNodeAddedChange_ptr_Qt3DCore_QStaticPropertyValueAddedChangeBase(Qt3DCore::QStaticPropertyValueAddedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyNodeAddedChange* qt_3d_core_c_QPropertyNodeAddedChange_G_static_cast_Qt3DCore_QPropertyNodeAddedChange_ptr_Qt3DCore_QPropertyValueAddedChangeBase(Qt3DCore::QPropertyValueAddedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyNodeAddedChange* qt_3d_core_c_QPropertyNodeAddedChange_G_static_cast_Qt3DCore_QPropertyNodeAddedChange_ptr_Qt3DCore_QSceneChange(Qt3DCore::QSceneChange* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyNodeAddedChange* qt_3d_core_c_QPropertyNodeAddedChange_G_static_cast_Qt3DCore_QPropertyNodeAddedChange_ptr_Qt3DCore_QStaticPropertyValueAddedChangeBase(Qt3DCore::QStaticPropertyValueAddedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyValueAddedChangeBase* qt_3d_core_c_QPropertyNodeAddedChange_G_static_cast_Qt3DCore_QPropertyValueAddedChangeBase_ptr(Qt3DCore::QPropertyNodeAddedChange* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QSceneChange* qt_3d_core_c_QPropertyNodeAddedChange_G_static_cast_Qt3DCore_QSceneChange_ptr(Qt3DCore::QPropertyNodeAddedChange* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QStaticPropertyValueAddedChangeBase* qt_3d_core_c_QPropertyNodeAddedChange_G_static_cast_Qt3DCore_QStaticPropertyValueAddedChangeBase_ptr(Qt3DCore::QPropertyNodeAddedChange* ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_Qt3DCore_QPropertyNodeAddedChange_addedNodeId_to_output(const Qt3DCore::QPropertyNodeAddedChange* this_ptr, Qt3DCore::QNodeId* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_Qt3DCore_QPropertyNodeAddedChange_delete(Qt3DCore::QPropertyNodeAddedChange* this_ptr);
QT_3D_CORE_C_EXPORT const QMetaObject* qt_3d_core_c_Qt3DCore_QPropertyNodeAddedChange_metaObject(const Qt3DCore::QPropertyNodeAddedChange* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyNodeAddedChange* qt_3d_core_c_Qt3DCore_QPropertyNodeAddedChange_new(const Qt3DCore::QNodeId* subjectId, Qt3DCore::QNode* node);

} // extern "C"

#endif // QT_3D_CORE_C_QPROPERTYNODEADDEDCHANGE_H
