#ifndef QT_3D_CORE_C_QPROPERTYVALUEREMOVEDCHANGE_H
#define QT_3D_CORE_C_QPROPERTYVALUEREMOVEDCHANGE_H

#include "qt_3d_core_c_global.h"

extern "C" {

QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyValueRemovedChange* qt_3d_core_c_QPropertyValueRemovedChange_G_dynamic_cast_Qt3DCore_QPropertyValueRemovedChange_ptr_Qt3DCore_QPropertyValueRemovedChangeBase(Qt3DCore::QPropertyValueRemovedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyValueRemovedChange* qt_3d_core_c_QPropertyValueRemovedChange_G_dynamic_cast_Qt3DCore_QPropertyValueRemovedChange_ptr_Qt3DCore_QSceneChange(Qt3DCore::QSceneChange* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyValueRemovedChange* qt_3d_core_c_QPropertyValueRemovedChange_G_dynamic_cast_Qt3DCore_QPropertyValueRemovedChange_ptr_Qt3DCore_QStaticPropertyValueRemovedChangeBase(Qt3DCore::QStaticPropertyValueRemovedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyValueRemovedChangeBase* qt_3d_core_c_QPropertyValueRemovedChange_G_static_cast_Qt3DCore_QPropertyValueRemovedChangeBase_ptr(Qt3DCore::QPropertyValueRemovedChange* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyValueRemovedChange* qt_3d_core_c_QPropertyValueRemovedChange_G_static_cast_Qt3DCore_QPropertyValueRemovedChange_ptr_Qt3DCore_QPropertyValueRemovedChangeBase(Qt3DCore::QPropertyValueRemovedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyValueRemovedChange* qt_3d_core_c_QPropertyValueRemovedChange_G_static_cast_Qt3DCore_QPropertyValueRemovedChange_ptr_Qt3DCore_QSceneChange(Qt3DCore::QSceneChange* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyValueRemovedChange* qt_3d_core_c_QPropertyValueRemovedChange_G_static_cast_Qt3DCore_QPropertyValueRemovedChange_ptr_Qt3DCore_QStaticPropertyValueRemovedChangeBase(Qt3DCore::QStaticPropertyValueRemovedChangeBase* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QSceneChange* qt_3d_core_c_QPropertyValueRemovedChange_G_static_cast_Qt3DCore_QSceneChange_ptr(Qt3DCore::QPropertyValueRemovedChange* ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QStaticPropertyValueRemovedChangeBase* qt_3d_core_c_QPropertyValueRemovedChange_G_static_cast_Qt3DCore_QStaticPropertyValueRemovedChangeBase_ptr(Qt3DCore::QPropertyValueRemovedChange* ptr);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_Qt3DCore_QPropertyValueRemovedChange_delete(Qt3DCore::QPropertyValueRemovedChange* this_ptr);
QT_3D_CORE_C_EXPORT Qt3DCore::QPropertyValueRemovedChange* qt_3d_core_c_Qt3DCore_QPropertyValueRemovedChange_new(const Qt3DCore::QNodeId* subjectId);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_Qt3DCore_QPropertyValueRemovedChange_removedValue_to_output(const Qt3DCore::QPropertyValueRemovedChange* this_ptr, QVariant* output);
QT_3D_CORE_C_EXPORT void qt_3d_core_c_Qt3DCore_QPropertyValueRemovedChange_setRemovedValue(Qt3DCore::QPropertyValueRemovedChange* this_ptr, const QVariant* value);

} // extern "C"

#endif // QT_3D_CORE_C_QPROPERTYVALUEREMOVEDCHANGE_H
