#ifndef QT_3D_RENDER_C_QRENDERTARGETSELECTOR_H
#define QT_3D_RENDER_C_QRENDERTARGETSELECTOR_H

#include "qt_3d_render_c_global.h"

extern "C" {

QT_3D_RENDER_C_EXPORT Qt3DRender::QRenderTargetSelector* qt_3d_render_c_QRenderTargetSelector_G_dynamic_cast_Qt3DRender_QRenderTargetSelector_ptr(Qt3DRender::QFrameGraphNode* ptr);
QT_3D_RENDER_C_EXPORT QObject* qt_3d_render_c_QRenderTargetSelector_G_static_cast_QObject_ptr(Qt3DRender::QRenderTargetSelector* ptr);
QT_3D_RENDER_C_EXPORT Qt3DCore::QNode* qt_3d_render_c_QRenderTargetSelector_G_static_cast_Qt3DCore_QNode_ptr(Qt3DRender::QRenderTargetSelector* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QFrameGraphNode* qt_3d_render_c_QRenderTargetSelector_G_static_cast_Qt3DRender_QFrameGraphNode_ptr(Qt3DRender::QRenderTargetSelector* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QRenderTargetSelector* qt_3d_render_c_QRenderTargetSelector_G_static_cast_Qt3DRender_QRenderTargetSelector_ptr_QObject(QObject* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QRenderTargetSelector* qt_3d_render_c_QRenderTargetSelector_G_static_cast_Qt3DRender_QRenderTargetSelector_ptr_Qt3DCore_QNode(Qt3DCore::QNode* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QRenderTargetSelector* qt_3d_render_c_QRenderTargetSelector_G_static_cast_Qt3DRender_QRenderTargetSelector_ptr_Qt3DRender_QFrameGraphNode(Qt3DRender::QFrameGraphNode* ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QRenderTargetSelector_delete(Qt3DRender::QRenderTargetSelector* this_ptr);
QT_3D_RENDER_C_EXPORT const QMetaObject* qt_3d_render_c_Qt3DRender_QRenderTargetSelector_metaObject(const Qt3DRender::QRenderTargetSelector* this_ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QRenderTargetSelector* qt_3d_render_c_Qt3DRender_QRenderTargetSelector_new_no_args();
QT_3D_RENDER_C_EXPORT Qt3DRender::QRenderTargetSelector* qt_3d_render_c_Qt3DRender_QRenderTargetSelector_new_parent(Qt3DCore::QNode* parent);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QRenderTargetSelector_outputs_to_output(const Qt3DRender::QRenderTargetSelector* this_ptr, QVector< Qt3DRender::QRenderTargetOutput::AttachmentPoint >* output);
QT_3D_RENDER_C_EXPORT int qt_3d_render_c_Qt3DRender_QRenderTargetSelector_qt_metacall(Qt3DRender::QRenderTargetSelector* this_ptr, const QMetaObject::Call* arg1, int arg2, void** arg3);
QT_3D_RENDER_C_EXPORT void* qt_3d_render_c_Qt3DRender_QRenderTargetSelector_qt_metacast(Qt3DRender::QRenderTargetSelector* this_ptr, const char* arg1);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QRenderTargetSelector_setOutputs(Qt3DRender::QRenderTargetSelector* this_ptr, const QVector< Qt3DRender::QRenderTargetOutput::AttachmentPoint >* buffers);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QRenderTargetSelector_setTarget(Qt3DRender::QRenderTargetSelector* this_ptr, Qt3DRender::QRenderTarget* target);
QT_3D_RENDER_C_EXPORT Qt3DRender::QRenderTarget* qt_3d_render_c_Qt3DRender_QRenderTargetSelector_target(const Qt3DRender::QRenderTargetSelector* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QRenderTargetSelector_trUtf8_to_output(const char* s, const char* c, int n, QString* output);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QRenderTargetSelector_tr_to_output(const char* s, const char* c, int n, QString* output);

} // extern "C"

#endif // QT_3D_RENDER_C_QRENDERTARGETSELECTOR_H
