#ifndef QT_3D_RENDER_C_QBLENDEQUATIONARGUMENTS_H
#define QT_3D_RENDER_C_QBLENDEQUATIONARGUMENTS_H

#include "qt_3d_render_c_global.h"

extern "C" {

QT_3D_RENDER_C_EXPORT Qt3DRender::QBlendEquationArguments* qt_3d_render_c_QBlendEquationArguments_G_dynamic_cast_Qt3DRender_QBlendEquationArguments_ptr(Qt3DRender::QRenderState* ptr);
QT_3D_RENDER_C_EXPORT QObject* qt_3d_render_c_QBlendEquationArguments_G_static_cast_QObject_ptr(Qt3DRender::QBlendEquationArguments* ptr);
QT_3D_RENDER_C_EXPORT Qt3DCore::QNode* qt_3d_render_c_QBlendEquationArguments_G_static_cast_Qt3DCore_QNode_ptr(Qt3DRender::QBlendEquationArguments* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QBlendEquationArguments* qt_3d_render_c_QBlendEquationArguments_G_static_cast_Qt3DRender_QBlendEquationArguments_ptr_QObject(QObject* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QBlendEquationArguments* qt_3d_render_c_QBlendEquationArguments_G_static_cast_Qt3DRender_QBlendEquationArguments_ptr_Qt3DCore_QNode(Qt3DCore::QNode* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QBlendEquationArguments* qt_3d_render_c_QBlendEquationArguments_G_static_cast_Qt3DRender_QBlendEquationArguments_ptr_Qt3DRender_QRenderState(Qt3DRender::QRenderState* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QRenderState* qt_3d_render_c_QBlendEquationArguments_G_static_cast_Qt3DRender_QRenderState_ptr(Qt3DRender::QBlendEquationArguments* ptr);
QT_3D_RENDER_C_EXPORT int qt_3d_render_c_Qt3DRender_QBlendEquationArguments_bufferIndex(const Qt3DRender::QBlendEquationArguments* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QBlendEquationArguments_delete(Qt3DRender::QBlendEquationArguments* this_ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QBlendEquationArguments::Blending qt_3d_render_c_Qt3DRender_QBlendEquationArguments_destinationAlpha(const Qt3DRender::QBlendEquationArguments* this_ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QBlendEquationArguments::Blending qt_3d_render_c_Qt3DRender_QBlendEquationArguments_destinationRgb(const Qt3DRender::QBlendEquationArguments* this_ptr);
QT_3D_RENDER_C_EXPORT const QMetaObject* qt_3d_render_c_Qt3DRender_QBlendEquationArguments_metaObject(const Qt3DRender::QBlendEquationArguments* this_ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QBlendEquationArguments* qt_3d_render_c_Qt3DRender_QBlendEquationArguments_new_no_args();
QT_3D_RENDER_C_EXPORT Qt3DRender::QBlendEquationArguments* qt_3d_render_c_Qt3DRender_QBlendEquationArguments_new_parent(Qt3DCore::QNode* parent);
QT_3D_RENDER_C_EXPORT int qt_3d_render_c_Qt3DRender_QBlendEquationArguments_qt_metacall(Qt3DRender::QBlendEquationArguments* this_ptr, const QMetaObject::Call* arg1, int arg2, void** arg3);
QT_3D_RENDER_C_EXPORT void* qt_3d_render_c_Qt3DRender_QBlendEquationArguments_qt_metacast(Qt3DRender::QBlendEquationArguments* this_ptr, const char* arg1);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QBlendEquationArguments_setBufferIndex(Qt3DRender::QBlendEquationArguments* this_ptr, int index);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QBlendEquationArguments_setDestinationAlpha(Qt3DRender::QBlendEquationArguments* this_ptr, Qt3DRender::QBlendEquationArguments::Blending destinationAlpha);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QBlendEquationArguments_setDestinationRgb(Qt3DRender::QBlendEquationArguments* this_ptr, Qt3DRender::QBlendEquationArguments::Blending destinationRgb);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QBlendEquationArguments_setDestinationRgba(Qt3DRender::QBlendEquationArguments* this_ptr, Qt3DRender::QBlendEquationArguments::Blending destinationRgba);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QBlendEquationArguments_setSourceAlpha(Qt3DRender::QBlendEquationArguments* this_ptr, Qt3DRender::QBlendEquationArguments::Blending sourceAlpha);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QBlendEquationArguments_setSourceRgb(Qt3DRender::QBlendEquationArguments* this_ptr, Qt3DRender::QBlendEquationArguments::Blending sourceRgb);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QBlendEquationArguments_setSourceRgba(Qt3DRender::QBlendEquationArguments* this_ptr, Qt3DRender::QBlendEquationArguments::Blending sourceRgba);
QT_3D_RENDER_C_EXPORT Qt3DRender::QBlendEquationArguments::Blending qt_3d_render_c_Qt3DRender_QBlendEquationArguments_sourceAlpha(const Qt3DRender::QBlendEquationArguments* this_ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QBlendEquationArguments::Blending qt_3d_render_c_Qt3DRender_QBlendEquationArguments_sourceRgb(const Qt3DRender::QBlendEquationArguments* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QBlendEquationArguments_trUtf8_to_output(const char* s, const char* c, int n, QString* output);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QBlendEquationArguments_tr_to_output(const char* s, const char* c, int n, QString* output);

} // extern "C"

#endif // QT_3D_RENDER_C_QBLENDEQUATIONARGUMENTS_H
