#ifndef QT_3D_RENDER_C_QTEXTUREIMAGEDATAGENERATOR_H
#define QT_3D_RENDER_C_QTEXTUREIMAGEDATAGENERATOR_H

#include "qt_3d_render_c_global.h"

extern "C" {

QT_3D_RENDER_C_EXPORT Qt3DRender::QTextureImageDataGenerator* qt_3d_render_c_QTextureImageDataGenerator_G_dynamic_cast_Qt3DRender_QTextureImageDataGenerator_ptr(Qt3DRender::QAbstractFunctor* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QAbstractFunctor* qt_3d_render_c_QTextureImageDataGenerator_G_static_cast_Qt3DRender_QAbstractFunctor_ptr(Qt3DRender::QTextureImageDataGenerator* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QTextureImageDataGenerator* qt_3d_render_c_QTextureImageDataGenerator_G_static_cast_Qt3DRender_QTextureImageDataGenerator_ptr(Qt3DRender::QAbstractFunctor* ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QTextureImageDataGenerator_delete(Qt3DRender::QTextureImageDataGenerator* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QTextureImageDataGenerator_operator_call_to_output(Qt3DRender::QTextureImageDataGenerator* this_ptr, QSharedPointer< Qt3DRender::QTextureImageData >* output);
QT_3D_RENDER_C_EXPORT bool qt_3d_render_c_Qt3DRender_QTextureImageDataGenerator_operator_eq(const Qt3DRender::QTextureImageDataGenerator* this_ptr, const Qt3DRender::QTextureImageDataGenerator* other);

} // extern "C"

#endif // QT_3D_RENDER_C_QTEXTUREIMAGEDATAGENERATOR_H
