#ifndef QT_3D_RENDER_C_QBUFFERDATAGENERATOR_H
#define QT_3D_RENDER_C_QBUFFERDATAGENERATOR_H

#include "qt_3d_render_c_global.h"

extern "C" {

QT_3D_RENDER_C_EXPORT Qt3DRender::QBufferDataGenerator* qt_3d_render_c_QBufferDataGenerator_G_dynamic_cast_Qt3DRender_QBufferDataGenerator_ptr(Qt3DRender::QAbstractFunctor* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QAbstractFunctor* qt_3d_render_c_QBufferDataGenerator_G_static_cast_Qt3DRender_QAbstractFunctor_ptr(Qt3DRender::QBufferDataGenerator* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QBufferDataGenerator* qt_3d_render_c_QBufferDataGenerator_G_static_cast_Qt3DRender_QBufferDataGenerator_ptr(Qt3DRender::QAbstractFunctor* ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QBufferDataGenerator_delete(Qt3DRender::QBufferDataGenerator* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QBufferDataGenerator_operator_call_to_output(Qt3DRender::QBufferDataGenerator* this_ptr, QByteArray* output);
QT_3D_RENDER_C_EXPORT bool qt_3d_render_c_Qt3DRender_QBufferDataGenerator_operator_eq(const Qt3DRender::QBufferDataGenerator* this_ptr, const Qt3DRender::QBufferDataGenerator* other);

} // extern "C"

#endif // QT_3D_RENDER_C_QBUFFERDATAGENERATOR_H
