#ifndef QT_3D_RENDER_C_QFRAMEGRAPHNODECREATEDCHANGE_H
#define QT_3D_RENDER_C_QFRAMEGRAPHNODECREATEDCHANGE_H

#include "qt_3d_render_c_global.h"

extern "C" {

QT_3D_RENDER_C_EXPORT Qt3DCore::QNodeCreatedChangeBase* qt_3d_render_c_QFrameGraphNodeCreatedChange_G_static_cast_Qt3DCore_QNodeCreatedChangeBase_ptr(Qt3DRender::QFrameGraphNodeCreatedChangeBase* ptr);
QT_3D_RENDER_C_EXPORT Qt3DCore::QSceneChange* qt_3d_render_c_QFrameGraphNodeCreatedChange_G_static_cast_Qt3DCore_QSceneChange_ptr(Qt3DRender::QFrameGraphNodeCreatedChangeBase* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QFrameGraphNodeCreatedChangeBase* qt_3d_render_c_QFrameGraphNodeCreatedChange_G_static_cast_Qt3DRender_QFrameGraphNodeCreatedChangeBase_ptr_Qt3DCore_QNodeCreatedChangeBase(Qt3DCore::QNodeCreatedChangeBase* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QFrameGraphNodeCreatedChangeBase* qt_3d_render_c_QFrameGraphNodeCreatedChange_G_static_cast_Qt3DRender_QFrameGraphNodeCreatedChangeBase_ptr_Qt3DCore_QSceneChange(Qt3DCore::QSceneChange* ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QFrameGraphNodeCreatedChangeBase_delete(Qt3DRender::QFrameGraphNodeCreatedChangeBase* this_ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QFrameGraphNodeCreatedChangeBase* qt_3d_render_c_Qt3DRender_QFrameGraphNodeCreatedChangeBase_new(const Qt3DRender::QFrameGraphNode* node);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QFrameGraphNodeCreatedChangeBase_parentFrameGraphNodeId_to_output(const Qt3DRender::QFrameGraphNodeCreatedChangeBase* this_ptr, Qt3DCore::QNodeId* output);

} // extern "C"

#endif // QT_3D_RENDER_C_QFRAMEGRAPHNODECREATEDCHANGE_H
