#ifndef QT_3D_RENDER_C_QRENDERSURFACESELECTOR_H
#define QT_3D_RENDER_C_QRENDERSURFACESELECTOR_H

#include "qt_3d_render_c_global.h"

extern "C" {

QT_3D_RENDER_C_EXPORT Qt3DRender::QRenderSurfaceSelector* qt_3d_render_c_QRenderSurfaceSelector_G_dynamic_cast_Qt3DRender_QRenderSurfaceSelector_ptr(Qt3DRender::QFrameGraphNode* ptr);
QT_3D_RENDER_C_EXPORT QObject* qt_3d_render_c_QRenderSurfaceSelector_G_static_cast_QObject_ptr(Qt3DRender::QRenderSurfaceSelector* ptr);
QT_3D_RENDER_C_EXPORT Qt3DCore::QNode* qt_3d_render_c_QRenderSurfaceSelector_G_static_cast_Qt3DCore_QNode_ptr(Qt3DRender::QRenderSurfaceSelector* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QFrameGraphNode* qt_3d_render_c_QRenderSurfaceSelector_G_static_cast_Qt3DRender_QFrameGraphNode_ptr(Qt3DRender::QRenderSurfaceSelector* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QRenderSurfaceSelector* qt_3d_render_c_QRenderSurfaceSelector_G_static_cast_Qt3DRender_QRenderSurfaceSelector_ptr_QObject(QObject* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QRenderSurfaceSelector* qt_3d_render_c_QRenderSurfaceSelector_G_static_cast_Qt3DRender_QRenderSurfaceSelector_ptr_Qt3DCore_QNode(Qt3DCore::QNode* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QRenderSurfaceSelector* qt_3d_render_c_QRenderSurfaceSelector_G_static_cast_Qt3DRender_QRenderSurfaceSelector_ptr_Qt3DRender_QFrameGraphNode(Qt3DRender::QFrameGraphNode* ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QRenderSurfaceSelector_delete(Qt3DRender::QRenderSurfaceSelector* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QRenderSurfaceSelector_externalRenderTargetSize_to_output(const Qt3DRender::QRenderSurfaceSelector* this_ptr, QSize* output);
QT_3D_RENDER_C_EXPORT const QMetaObject* qt_3d_render_c_Qt3DRender_QRenderSurfaceSelector_metaObject(const Qt3DRender::QRenderSurfaceSelector* this_ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QRenderSurfaceSelector* qt_3d_render_c_Qt3DRender_QRenderSurfaceSelector_new_no_args();
QT_3D_RENDER_C_EXPORT Qt3DRender::QRenderSurfaceSelector* qt_3d_render_c_Qt3DRender_QRenderSurfaceSelector_new_parent(Qt3DCore::QNode* parent);
QT_3D_RENDER_C_EXPORT int qt_3d_render_c_Qt3DRender_QRenderSurfaceSelector_qt_metacall(Qt3DRender::QRenderSurfaceSelector* this_ptr, const QMetaObject::Call* arg1, int arg2, void** arg3);
QT_3D_RENDER_C_EXPORT void* qt_3d_render_c_Qt3DRender_QRenderSurfaceSelector_qt_metacast(Qt3DRender::QRenderSurfaceSelector* this_ptr, const char* arg1);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QRenderSurfaceSelector_setExternalRenderTargetSize(Qt3DRender::QRenderSurfaceSelector* this_ptr, const QSize* size);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QRenderSurfaceSelector_setSurface(Qt3DRender::QRenderSurfaceSelector* this_ptr, QObject* surfaceObject);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QRenderSurfaceSelector_setSurfacePixelRatio(Qt3DRender::QRenderSurfaceSelector* this_ptr, float ratio);
QT_3D_RENDER_C_EXPORT QObject* qt_3d_render_c_Qt3DRender_QRenderSurfaceSelector_surface(const Qt3DRender::QRenderSurfaceSelector* this_ptr);
QT_3D_RENDER_C_EXPORT float qt_3d_render_c_Qt3DRender_QRenderSurfaceSelector_surfacePixelRatio(const Qt3DRender::QRenderSurfaceSelector* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QRenderSurfaceSelector_trUtf8_to_output(const char* s, const char* c, int n, QString* output);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QRenderSurfaceSelector_tr_to_output(const char* s, const char* c, int n, QString* output);

} // extern "C"

#endif // QT_3D_RENDER_C_QRENDERSURFACESELECTOR_H
