#ifndef QT_3D_RENDER_C_QPAINTEDTEXTUREIMAGE_H
#define QT_3D_RENDER_C_QPAINTEDTEXTUREIMAGE_H

#include "qt_3d_render_c_global.h"

extern "C" {

QT_3D_RENDER_C_EXPORT Qt3DRender::QPaintedTextureImage* qt_3d_render_c_QPaintedTextureImage_G_dynamic_cast_Qt3DRender_QPaintedTextureImage_ptr(Qt3DRender::QAbstractTextureImage* ptr);
QT_3D_RENDER_C_EXPORT QObject* qt_3d_render_c_QPaintedTextureImage_G_static_cast_QObject_ptr(Qt3DRender::QPaintedTextureImage* ptr);
QT_3D_RENDER_C_EXPORT Qt3DCore::QNode* qt_3d_render_c_QPaintedTextureImage_G_static_cast_Qt3DCore_QNode_ptr(Qt3DRender::QPaintedTextureImage* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QAbstractTextureImage* qt_3d_render_c_QPaintedTextureImage_G_static_cast_Qt3DRender_QAbstractTextureImage_ptr(Qt3DRender::QPaintedTextureImage* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QPaintedTextureImage* qt_3d_render_c_QPaintedTextureImage_G_static_cast_Qt3DRender_QPaintedTextureImage_ptr_QObject(QObject* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QPaintedTextureImage* qt_3d_render_c_QPaintedTextureImage_G_static_cast_Qt3DRender_QPaintedTextureImage_ptr_Qt3DCore_QNode(Qt3DCore::QNode* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QPaintedTextureImage* qt_3d_render_c_QPaintedTextureImage_G_static_cast_Qt3DRender_QPaintedTextureImage_ptr_Qt3DRender_QAbstractTextureImage(Qt3DRender::QAbstractTextureImage* ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QPaintedTextureImage_delete(Qt3DRender::QPaintedTextureImage* this_ptr);
QT_3D_RENDER_C_EXPORT int qt_3d_render_c_Qt3DRender_QPaintedTextureImage_height(const Qt3DRender::QPaintedTextureImage* this_ptr);
QT_3D_RENDER_C_EXPORT const QMetaObject* qt_3d_render_c_Qt3DRender_QPaintedTextureImage_metaObject(const Qt3DRender::QPaintedTextureImage* this_ptr);
QT_3D_RENDER_C_EXPORT int qt_3d_render_c_Qt3DRender_QPaintedTextureImage_qt_metacall(Qt3DRender::QPaintedTextureImage* this_ptr, const QMetaObject::Call* arg1, int arg2, void** arg3);
QT_3D_RENDER_C_EXPORT void* qt_3d_render_c_Qt3DRender_QPaintedTextureImage_qt_metacast(Qt3DRender::QPaintedTextureImage* this_ptr, const char* arg1);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QPaintedTextureImage_setHeight(Qt3DRender::QPaintedTextureImage* this_ptr, int h);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QPaintedTextureImage_setSize(Qt3DRender::QPaintedTextureImage* this_ptr, const QSize* size);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QPaintedTextureImage_setWidth(Qt3DRender::QPaintedTextureImage* this_ptr, int w);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QPaintedTextureImage_size_to_output(const Qt3DRender::QPaintedTextureImage* this_ptr, QSize* output);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QPaintedTextureImage_trUtf8_to_output(const char* s, const char* c, int n, QString* output);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QPaintedTextureImage_tr_to_output(const char* s, const char* c, int n, QString* output);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QPaintedTextureImage_update_no_args(Qt3DRender::QPaintedTextureImage* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QPaintedTextureImage_update_rect(Qt3DRender::QPaintedTextureImage* this_ptr, const QRect* rect);
QT_3D_RENDER_C_EXPORT int qt_3d_render_c_Qt3DRender_QPaintedTextureImage_width(const Qt3DRender::QPaintedTextureImage* this_ptr);

} // extern "C"

#endif // QT_3D_RENDER_C_QPAINTEDTEXTUREIMAGE_H
