#ifndef QT_3D_RENDER_C_QLEVELOFDETAILSWITCH_H
#define QT_3D_RENDER_C_QLEVELOFDETAILSWITCH_H

#include "qt_3d_render_c_global.h"

extern "C" {

QT_3D_RENDER_C_EXPORT Qt3DRender::QLevelOfDetailSwitch* qt_3d_render_c_QLevelOfDetailSwitch_G_dynamic_cast_Qt3DRender_QLevelOfDetailSwitch_ptr(Qt3DRender::QLevelOfDetail* ptr);
QT_3D_RENDER_C_EXPORT QObject* qt_3d_render_c_QLevelOfDetailSwitch_G_static_cast_QObject_ptr(Qt3DRender::QLevelOfDetailSwitch* ptr);
QT_3D_RENDER_C_EXPORT Qt3DCore::QComponent* qt_3d_render_c_QLevelOfDetailSwitch_G_static_cast_Qt3DCore_QComponent_ptr(Qt3DRender::QLevelOfDetailSwitch* ptr);
QT_3D_RENDER_C_EXPORT Qt3DCore::QNode* qt_3d_render_c_QLevelOfDetailSwitch_G_static_cast_Qt3DCore_QNode_ptr(Qt3DRender::QLevelOfDetailSwitch* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QLevelOfDetailSwitch* qt_3d_render_c_QLevelOfDetailSwitch_G_static_cast_Qt3DRender_QLevelOfDetailSwitch_ptr_QObject(QObject* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QLevelOfDetailSwitch* qt_3d_render_c_QLevelOfDetailSwitch_G_static_cast_Qt3DRender_QLevelOfDetailSwitch_ptr_Qt3DCore_QComponent(Qt3DCore::QComponent* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QLevelOfDetailSwitch* qt_3d_render_c_QLevelOfDetailSwitch_G_static_cast_Qt3DRender_QLevelOfDetailSwitch_ptr_Qt3DCore_QNode(Qt3DCore::QNode* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QLevelOfDetailSwitch* qt_3d_render_c_QLevelOfDetailSwitch_G_static_cast_Qt3DRender_QLevelOfDetailSwitch_ptr_Qt3DRender_QLevelOfDetail(Qt3DRender::QLevelOfDetail* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QLevelOfDetail* qt_3d_render_c_QLevelOfDetailSwitch_G_static_cast_Qt3DRender_QLevelOfDetail_ptr(Qt3DRender::QLevelOfDetailSwitch* ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QLevelOfDetailSwitch_delete(Qt3DRender::QLevelOfDetailSwitch* this_ptr);
QT_3D_RENDER_C_EXPORT const QMetaObject* qt_3d_render_c_Qt3DRender_QLevelOfDetailSwitch_metaObject(const Qt3DRender::QLevelOfDetailSwitch* this_ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QLevelOfDetailSwitch* qt_3d_render_c_Qt3DRender_QLevelOfDetailSwitch_new_no_args();
QT_3D_RENDER_C_EXPORT Qt3DRender::QLevelOfDetailSwitch* qt_3d_render_c_Qt3DRender_QLevelOfDetailSwitch_new_parent(Qt3DCore::QNode* parent);
QT_3D_RENDER_C_EXPORT int qt_3d_render_c_Qt3DRender_QLevelOfDetailSwitch_qt_metacall(Qt3DRender::QLevelOfDetailSwitch* this_ptr, const QMetaObject::Call* arg1, int arg2, void** arg3);
QT_3D_RENDER_C_EXPORT void* qt_3d_render_c_Qt3DRender_QLevelOfDetailSwitch_qt_metacast(Qt3DRender::QLevelOfDetailSwitch* this_ptr, const char* arg1);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QLevelOfDetailSwitch_trUtf8_to_output(const char* s, const char* c, int n, QString* output);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QLevelOfDetailSwitch_tr_to_output(const char* s, const char* c, int n, QString* output);

} // extern "C"

#endif // QT_3D_RENDER_C_QLEVELOFDETAILSWITCH_H
