#ifndef QT_3D_RENDER_C_QSHAREDPOINTER_H
#define QT_3D_RENDER_C_QSHAREDPOINTER_H

#include "qt_3d_render_c_global.h"

extern "C" {

QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_PropertyReaderInterface_clear(QSharedPointer< Qt3DRender::PropertyReaderInterface >* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_PropertyReaderInterface_constructor_no_args(QSharedPointer< Qt3DRender::PropertyReaderInterface >* output);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_PropertyReaderInterface_constructor_other(const QSharedPointer< Qt3DRender::PropertyReaderInterface >* other, QSharedPointer< Qt3DRender::PropertyReaderInterface >* output);
QT_3D_RENDER_C_EXPORT Qt3DRender::PropertyReaderInterface* qt_3d_render_c_QSharedPointer_Qt3DRender_PropertyReaderInterface_data(const QSharedPointer< Qt3DRender::PropertyReaderInterface >* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_PropertyReaderInterface_destructor(QSharedPointer< Qt3DRender::PropertyReaderInterface >* this_ptr);
QT_3D_RENDER_C_EXPORT bool qt_3d_render_c_QSharedPointer_Qt3DRender_PropertyReaderInterface_isNull(const QSharedPointer< Qt3DRender::PropertyReaderInterface >* this_ptr);
QT_3D_RENDER_C_EXPORT QSharedPointer< Qt3DRender::PropertyReaderInterface >* qt_3d_render_c_QSharedPointer_Qt3DRender_PropertyReaderInterface_operator_assign(QSharedPointer< Qt3DRender::PropertyReaderInterface >* this_ptr, const QSharedPointer< Qt3DRender::PropertyReaderInterface >* other);
QT_3D_RENDER_C_EXPORT Qt3DRender::PropertyReaderInterface* qt_3d_render_c_QSharedPointer_Qt3DRender_PropertyReaderInterface_operator_indirection(const QSharedPointer< Qt3DRender::PropertyReaderInterface >* this_ptr);
QT_3D_RENDER_C_EXPORT bool qt_3d_render_c_QSharedPointer_Qt3DRender_PropertyReaderInterface_operator_not(const QSharedPointer< Qt3DRender::PropertyReaderInterface >* this_ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::PropertyReaderInterface* qt_3d_render_c_QSharedPointer_Qt3DRender_PropertyReaderInterface_operator_struct_deref(const QSharedPointer< Qt3DRender::PropertyReaderInterface >* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_PropertyReaderInterface_reset_no_args(QSharedPointer< Qt3DRender::PropertyReaderInterface >* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_PropertyReaderInterface_reset_t(QSharedPointer< Qt3DRender::PropertyReaderInterface >* this_ptr, Qt3DRender::PropertyReaderInterface* t);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_PropertyReaderInterface_swap(QSharedPointer< Qt3DRender::PropertyReaderInterface >* this_ptr, QSharedPointer< Qt3DRender::PropertyReaderInterface >* other);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QBufferDataGenerator_clear(QSharedPointer< Qt3DRender::QBufferDataGenerator >* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QBufferDataGenerator_constructor_no_args(QSharedPointer< Qt3DRender::QBufferDataGenerator >* output);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QBufferDataGenerator_constructor_other(const QSharedPointer< Qt3DRender::QBufferDataGenerator >* other, QSharedPointer< Qt3DRender::QBufferDataGenerator >* output);
QT_3D_RENDER_C_EXPORT Qt3DRender::QBufferDataGenerator* qt_3d_render_c_QSharedPointer_Qt3DRender_QBufferDataGenerator_data(const QSharedPointer< Qt3DRender::QBufferDataGenerator >* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QBufferDataGenerator_destructor(QSharedPointer< Qt3DRender::QBufferDataGenerator >* this_ptr);
QT_3D_RENDER_C_EXPORT bool qt_3d_render_c_QSharedPointer_Qt3DRender_QBufferDataGenerator_isNull(const QSharedPointer< Qt3DRender::QBufferDataGenerator >* this_ptr);
QT_3D_RENDER_C_EXPORT QSharedPointer< Qt3DRender::QBufferDataGenerator >* qt_3d_render_c_QSharedPointer_Qt3DRender_QBufferDataGenerator_operator_assign(QSharedPointer< Qt3DRender::QBufferDataGenerator >* this_ptr, const QSharedPointer< Qt3DRender::QBufferDataGenerator >* other);
QT_3D_RENDER_C_EXPORT Qt3DRender::QBufferDataGenerator* qt_3d_render_c_QSharedPointer_Qt3DRender_QBufferDataGenerator_operator_indirection(const QSharedPointer< Qt3DRender::QBufferDataGenerator >* this_ptr);
QT_3D_RENDER_C_EXPORT bool qt_3d_render_c_QSharedPointer_Qt3DRender_QBufferDataGenerator_operator_not(const QSharedPointer< Qt3DRender::QBufferDataGenerator >* this_ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QBufferDataGenerator* qt_3d_render_c_QSharedPointer_Qt3DRender_QBufferDataGenerator_operator_struct_deref(const QSharedPointer< Qt3DRender::QBufferDataGenerator >* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QBufferDataGenerator_reset_no_args(QSharedPointer< Qt3DRender::QBufferDataGenerator >* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QBufferDataGenerator_reset_t(QSharedPointer< Qt3DRender::QBufferDataGenerator >* this_ptr, Qt3DRender::QBufferDataGenerator* t);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QBufferDataGenerator_swap(QSharedPointer< Qt3DRender::QBufferDataGenerator >* this_ptr, QSharedPointer< Qt3DRender::QBufferDataGenerator >* other);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QGeometryFactory_clear(QSharedPointer< Qt3DRender::QGeometryFactory >* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QGeometryFactory_constructor_no_args(QSharedPointer< Qt3DRender::QGeometryFactory >* output);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QGeometryFactory_constructor_other(const QSharedPointer< Qt3DRender::QGeometryFactory >* other, QSharedPointer< Qt3DRender::QGeometryFactory >* output);
QT_3D_RENDER_C_EXPORT Qt3DRender::QGeometryFactory* qt_3d_render_c_QSharedPointer_Qt3DRender_QGeometryFactory_data(const QSharedPointer< Qt3DRender::QGeometryFactory >* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QGeometryFactory_destructor(QSharedPointer< Qt3DRender::QGeometryFactory >* this_ptr);
QT_3D_RENDER_C_EXPORT bool qt_3d_render_c_QSharedPointer_Qt3DRender_QGeometryFactory_isNull(const QSharedPointer< Qt3DRender::QGeometryFactory >* this_ptr);
QT_3D_RENDER_C_EXPORT QSharedPointer< Qt3DRender::QGeometryFactory >* qt_3d_render_c_QSharedPointer_Qt3DRender_QGeometryFactory_operator_assign(QSharedPointer< Qt3DRender::QGeometryFactory >* this_ptr, const QSharedPointer< Qt3DRender::QGeometryFactory >* other);
QT_3D_RENDER_C_EXPORT Qt3DRender::QGeometryFactory* qt_3d_render_c_QSharedPointer_Qt3DRender_QGeometryFactory_operator_indirection(const QSharedPointer< Qt3DRender::QGeometryFactory >* this_ptr);
QT_3D_RENDER_C_EXPORT bool qt_3d_render_c_QSharedPointer_Qt3DRender_QGeometryFactory_operator_not(const QSharedPointer< Qt3DRender::QGeometryFactory >* this_ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QGeometryFactory* qt_3d_render_c_QSharedPointer_Qt3DRender_QGeometryFactory_operator_struct_deref(const QSharedPointer< Qt3DRender::QGeometryFactory >* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QGeometryFactory_reset_no_args(QSharedPointer< Qt3DRender::QGeometryFactory >* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QGeometryFactory_reset_t(QSharedPointer< Qt3DRender::QGeometryFactory >* this_ptr, Qt3DRender::QGeometryFactory* t);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QGeometryFactory_swap(QSharedPointer< Qt3DRender::QGeometryFactory >* this_ptr, QSharedPointer< Qt3DRender::QGeometryFactory >* other);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureData_clear(QSharedPointer< Qt3DRender::QTextureData >* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureData_constructor_no_args(QSharedPointer< Qt3DRender::QTextureData >* output);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureData_constructor_other(const QSharedPointer< Qt3DRender::QTextureData >* other, QSharedPointer< Qt3DRender::QTextureData >* output);
QT_3D_RENDER_C_EXPORT Qt3DRender::QTextureData* qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureData_data(const QSharedPointer< Qt3DRender::QTextureData >* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureData_destructor(QSharedPointer< Qt3DRender::QTextureData >* this_ptr);
QT_3D_RENDER_C_EXPORT bool qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureData_isNull(const QSharedPointer< Qt3DRender::QTextureData >* this_ptr);
QT_3D_RENDER_C_EXPORT QSharedPointer< Qt3DRender::QTextureData >* qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureData_operator_assign(QSharedPointer< Qt3DRender::QTextureData >* this_ptr, const QSharedPointer< Qt3DRender::QTextureData >* other);
QT_3D_RENDER_C_EXPORT Qt3DRender::QTextureData* qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureData_operator_indirection(const QSharedPointer< Qt3DRender::QTextureData >* this_ptr);
QT_3D_RENDER_C_EXPORT bool qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureData_operator_not(const QSharedPointer< Qt3DRender::QTextureData >* this_ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QTextureData* qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureData_operator_struct_deref(const QSharedPointer< Qt3DRender::QTextureData >* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureData_reset_no_args(QSharedPointer< Qt3DRender::QTextureData >* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureData_reset_t(QSharedPointer< Qt3DRender::QTextureData >* this_ptr, Qt3DRender::QTextureData* t);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureData_swap(QSharedPointer< Qt3DRender::QTextureData >* this_ptr, QSharedPointer< Qt3DRender::QTextureData >* other);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureGenerator_clear(QSharedPointer< Qt3DRender::QTextureGenerator >* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureGenerator_constructor_no_args(QSharedPointer< Qt3DRender::QTextureGenerator >* output);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureGenerator_constructor_other(const QSharedPointer< Qt3DRender::QTextureGenerator >* other, QSharedPointer< Qt3DRender::QTextureGenerator >* output);
QT_3D_RENDER_C_EXPORT Qt3DRender::QTextureGenerator* qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureGenerator_data(const QSharedPointer< Qt3DRender::QTextureGenerator >* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureGenerator_destructor(QSharedPointer< Qt3DRender::QTextureGenerator >* this_ptr);
QT_3D_RENDER_C_EXPORT bool qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureGenerator_isNull(const QSharedPointer< Qt3DRender::QTextureGenerator >* this_ptr);
QT_3D_RENDER_C_EXPORT QSharedPointer< Qt3DRender::QTextureGenerator >* qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureGenerator_operator_assign(QSharedPointer< Qt3DRender::QTextureGenerator >* this_ptr, const QSharedPointer< Qt3DRender::QTextureGenerator >* other);
QT_3D_RENDER_C_EXPORT Qt3DRender::QTextureGenerator* qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureGenerator_operator_indirection(const QSharedPointer< Qt3DRender::QTextureGenerator >* this_ptr);
QT_3D_RENDER_C_EXPORT bool qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureGenerator_operator_not(const QSharedPointer< Qt3DRender::QTextureGenerator >* this_ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QTextureGenerator* qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureGenerator_operator_struct_deref(const QSharedPointer< Qt3DRender::QTextureGenerator >* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureGenerator_reset_no_args(QSharedPointer< Qt3DRender::QTextureGenerator >* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureGenerator_reset_t(QSharedPointer< Qt3DRender::QTextureGenerator >* this_ptr, Qt3DRender::QTextureGenerator* t);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureGenerator_swap(QSharedPointer< Qt3DRender::QTextureGenerator >* this_ptr, QSharedPointer< Qt3DRender::QTextureGenerator >* other);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureImageDataGenerator_clear(QSharedPointer< Qt3DRender::QTextureImageDataGenerator >* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureImageDataGenerator_constructor_no_args(QSharedPointer< Qt3DRender::QTextureImageDataGenerator >* output);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureImageDataGenerator_constructor_other(const QSharedPointer< Qt3DRender::QTextureImageDataGenerator >* other, QSharedPointer< Qt3DRender::QTextureImageDataGenerator >* output);
QT_3D_RENDER_C_EXPORT Qt3DRender::QTextureImageDataGenerator* qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureImageDataGenerator_data(const QSharedPointer< Qt3DRender::QTextureImageDataGenerator >* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureImageDataGenerator_destructor(QSharedPointer< Qt3DRender::QTextureImageDataGenerator >* this_ptr);
QT_3D_RENDER_C_EXPORT bool qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureImageDataGenerator_isNull(const QSharedPointer< Qt3DRender::QTextureImageDataGenerator >* this_ptr);
QT_3D_RENDER_C_EXPORT QSharedPointer< Qt3DRender::QTextureImageDataGenerator >* qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureImageDataGenerator_operator_assign(QSharedPointer< Qt3DRender::QTextureImageDataGenerator >* this_ptr, const QSharedPointer< Qt3DRender::QTextureImageDataGenerator >* other);
QT_3D_RENDER_C_EXPORT Qt3DRender::QTextureImageDataGenerator* qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureImageDataGenerator_operator_indirection(const QSharedPointer< Qt3DRender::QTextureImageDataGenerator >* this_ptr);
QT_3D_RENDER_C_EXPORT bool qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureImageDataGenerator_operator_not(const QSharedPointer< Qt3DRender::QTextureImageDataGenerator >* this_ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QTextureImageDataGenerator* qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureImageDataGenerator_operator_struct_deref(const QSharedPointer< Qt3DRender::QTextureImageDataGenerator >* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureImageDataGenerator_reset_no_args(QSharedPointer< Qt3DRender::QTextureImageDataGenerator >* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureImageDataGenerator_reset_t(QSharedPointer< Qt3DRender::QTextureImageDataGenerator >* this_ptr, Qt3DRender::QTextureImageDataGenerator* t);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureImageDataGenerator_swap(QSharedPointer< Qt3DRender::QTextureImageDataGenerator >* this_ptr, QSharedPointer< Qt3DRender::QTextureImageDataGenerator >* other);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureImageData_clear(QSharedPointer< Qt3DRender::QTextureImageData >* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureImageData_constructor_no_args(QSharedPointer< Qt3DRender::QTextureImageData >* output);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureImageData_constructor_other(const QSharedPointer< Qt3DRender::QTextureImageData >* other, QSharedPointer< Qt3DRender::QTextureImageData >* output);
QT_3D_RENDER_C_EXPORT Qt3DRender::QTextureImageData* qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureImageData_data(const QSharedPointer< Qt3DRender::QTextureImageData >* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureImageData_destructor(QSharedPointer< Qt3DRender::QTextureImageData >* this_ptr);
QT_3D_RENDER_C_EXPORT bool qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureImageData_isNull(const QSharedPointer< Qt3DRender::QTextureImageData >* this_ptr);
QT_3D_RENDER_C_EXPORT QSharedPointer< Qt3DRender::QTextureImageData >* qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureImageData_operator_assign(QSharedPointer< Qt3DRender::QTextureImageData >* this_ptr, const QSharedPointer< Qt3DRender::QTextureImageData >* other);
QT_3D_RENDER_C_EXPORT Qt3DRender::QTextureImageData* qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureImageData_operator_indirection(const QSharedPointer< Qt3DRender::QTextureImageData >* this_ptr);
QT_3D_RENDER_C_EXPORT bool qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureImageData_operator_not(const QSharedPointer< Qt3DRender::QTextureImageData >* this_ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QTextureImageData* qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureImageData_operator_struct_deref(const QSharedPointer< Qt3DRender::QTextureImageData >* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureImageData_reset_no_args(QSharedPointer< Qt3DRender::QTextureImageData >* this_ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureImageData_reset_t(QSharedPointer< Qt3DRender::QTextureImageData >* this_ptr, Qt3DRender::QTextureImageData* t);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_QSharedPointer_Qt3DRender_QTextureImageData_swap(QSharedPointer< Qt3DRender::QTextureImageData >* this_ptr, QSharedPointer< Qt3DRender::QTextureImageData >* other);

} // extern "C"

#endif // QT_3D_RENDER_C_QSHAREDPOINTER_H
