#ifndef QT_3D_RENDER_C_QDIRECTIONALLIGHT_H
#define QT_3D_RENDER_C_QDIRECTIONALLIGHT_H

#include "qt_3d_render_c_global.h"

extern "C" {

QT_3D_RENDER_C_EXPORT Qt3DRender::QDirectionalLight* qt_3d_render_c_QDirectionalLight_G_dynamic_cast_Qt3DRender_QDirectionalLight_ptr(Qt3DRender::QAbstractLight* ptr);
QT_3D_RENDER_C_EXPORT QObject* qt_3d_render_c_QDirectionalLight_G_static_cast_QObject_ptr(Qt3DRender::QDirectionalLight* ptr);
QT_3D_RENDER_C_EXPORT Qt3DCore::QComponent* qt_3d_render_c_QDirectionalLight_G_static_cast_Qt3DCore_QComponent_ptr(Qt3DRender::QDirectionalLight* ptr);
QT_3D_RENDER_C_EXPORT Qt3DCore::QNode* qt_3d_render_c_QDirectionalLight_G_static_cast_Qt3DCore_QNode_ptr(Qt3DRender::QDirectionalLight* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QAbstractLight* qt_3d_render_c_QDirectionalLight_G_static_cast_Qt3DRender_QAbstractLight_ptr(Qt3DRender::QDirectionalLight* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QDirectionalLight* qt_3d_render_c_QDirectionalLight_G_static_cast_Qt3DRender_QDirectionalLight_ptr_QObject(QObject* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QDirectionalLight* qt_3d_render_c_QDirectionalLight_G_static_cast_Qt3DRender_QDirectionalLight_ptr_Qt3DCore_QComponent(Qt3DCore::QComponent* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QDirectionalLight* qt_3d_render_c_QDirectionalLight_G_static_cast_Qt3DRender_QDirectionalLight_ptr_Qt3DCore_QNode(Qt3DCore::QNode* ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QDirectionalLight* qt_3d_render_c_QDirectionalLight_G_static_cast_Qt3DRender_QDirectionalLight_ptr_Qt3DRender_QAbstractLight(Qt3DRender::QAbstractLight* ptr);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QDirectionalLight_delete(Qt3DRender::QDirectionalLight* this_ptr);
QT_3D_RENDER_C_EXPORT const QMetaObject* qt_3d_render_c_Qt3DRender_QDirectionalLight_metaObject(const Qt3DRender::QDirectionalLight* this_ptr);
QT_3D_RENDER_C_EXPORT Qt3DRender::QDirectionalLight* qt_3d_render_c_Qt3DRender_QDirectionalLight_new_no_args();
QT_3D_RENDER_C_EXPORT Qt3DRender::QDirectionalLight* qt_3d_render_c_Qt3DRender_QDirectionalLight_new_parent(Qt3DCore::QNode* parent);
QT_3D_RENDER_C_EXPORT int qt_3d_render_c_Qt3DRender_QDirectionalLight_qt_metacall(Qt3DRender::QDirectionalLight* this_ptr, const QMetaObject::Call* arg1, int arg2, void** arg3);
QT_3D_RENDER_C_EXPORT void* qt_3d_render_c_Qt3DRender_QDirectionalLight_qt_metacast(Qt3DRender::QDirectionalLight* this_ptr, const char* arg1);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QDirectionalLight_setWorldDirection(Qt3DRender::QDirectionalLight* this_ptr, const QVector3D* worldDirection);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QDirectionalLight_trUtf8_to_output(const char* s, const char* c, int n, QString* output);
QT_3D_RENDER_C_EXPORT void qt_3d_render_c_Qt3DRender_QDirectionalLight_tr_to_output(const char* s, const char* c, int n, QString* output);
QT_3D_RENDER_C_EXPORT QVector3D* qt_3d_render_c_Qt3DRender_QDirectionalLight_worldDirection_as_ptr(const Qt3DRender::QDirectionalLight* this_ptr);

} // extern "C"

#endif // QT_3D_RENDER_C_QDIRECTIONALLIGHT_H
