#ifndef QT_WIDGETS_C_QGRAPHICSSCENECONTEXTMENUEVENT_H
#define QT_WIDGETS_C_QGRAPHICSSCENECONTEXTMENUEVENT_H

#include "qt_widgets_c_global.h"

extern "C" {

QT_WIDGETS_C_EXPORT QGraphicsSceneContextMenuEvent* qt_widgets_c_QGraphicsSceneContextMenuEvent_G_dynamic_cast_QGraphicsSceneContextMenuEvent_ptr(QGraphicsSceneEvent* ptr);
QT_WIDGETS_C_EXPORT QEvent* qt_widgets_c_QGraphicsSceneContextMenuEvent_G_static_cast_QEvent_ptr(QGraphicsSceneContextMenuEvent* ptr);
QT_WIDGETS_C_EXPORT QGraphicsSceneContextMenuEvent* qt_widgets_c_QGraphicsSceneContextMenuEvent_G_static_cast_QGraphicsSceneContextMenuEvent_ptr_QEvent(QEvent* ptr);
QT_WIDGETS_C_EXPORT QGraphicsSceneContextMenuEvent* qt_widgets_c_QGraphicsSceneContextMenuEvent_G_static_cast_QGraphicsSceneContextMenuEvent_ptr_QGraphicsSceneEvent(QGraphicsSceneEvent* ptr);
QT_WIDGETS_C_EXPORT QGraphicsSceneEvent* qt_widgets_c_QGraphicsSceneContextMenuEvent_G_static_cast_QGraphicsSceneEvent_ptr(QGraphicsSceneContextMenuEvent* ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsSceneContextMenuEvent_delete(QGraphicsSceneContextMenuEvent* this_ptr);
QT_WIDGETS_C_EXPORT QGraphicsSceneContextMenuEvent* qt_widgets_c_QGraphicsSceneContextMenuEvent_new_no_args();
QT_WIDGETS_C_EXPORT QGraphicsSceneContextMenuEvent* qt_widgets_c_QGraphicsSceneContextMenuEvent_new_type(QEvent::Type type);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsSceneContextMenuEvent_pos_to_output(const QGraphicsSceneContextMenuEvent* this_ptr, QPointF* output);
QT_WIDGETS_C_EXPORT QGraphicsSceneContextMenuEvent::Reason qt_widgets_c_QGraphicsSceneContextMenuEvent_reason(const QGraphicsSceneContextMenuEvent* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsSceneContextMenuEvent_scenePos_to_output(const QGraphicsSceneContextMenuEvent* this_ptr, QPointF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsSceneContextMenuEvent_screenPos_to_output(const QGraphicsSceneContextMenuEvent* this_ptr, QPoint* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsSceneContextMenuEvent_setPos(QGraphicsSceneContextMenuEvent* this_ptr, const QPointF* pos);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsSceneContextMenuEvent_setReason(QGraphicsSceneContextMenuEvent* this_ptr, QGraphicsSceneContextMenuEvent::Reason reason);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsSceneContextMenuEvent_setScenePos(QGraphicsSceneContextMenuEvent* this_ptr, const QPointF* pos);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsSceneContextMenuEvent_setScreenPos(QGraphicsSceneContextMenuEvent* this_ptr, const QPoint* pos);

} // extern "C"

#endif // QT_WIDGETS_C_QGRAPHICSSCENECONTEXTMENUEVENT_H
