#ifndef QT_WIDGETS_C_QSTYLEOPTIONTOOLBUTTON_H
#define QT_WIDGETS_C_QSTYLEOPTIONTOOLBUTTON_H

#include "qt_widgets_c_global.h"

extern "C" {

QT_WIDGETS_C_EXPORT QStyleOptionComplex* qt_widgets_c_QStyleOptionToolButton_G_static_cast_QStyleOptionComplex_ptr(QStyleOptionToolButton* ptr);
QT_WIDGETS_C_EXPORT QStyleOptionToolButton* qt_widgets_c_QStyleOptionToolButton_G_static_cast_QStyleOptionToolButton_ptr_QStyleOption(QStyleOption* ptr);
QT_WIDGETS_C_EXPORT QStyleOptionToolButton* qt_widgets_c_QStyleOptionToolButton_G_static_cast_QStyleOptionToolButton_ptr_QStyleOptionComplex(QStyleOptionComplex* ptr);
QT_WIDGETS_C_EXPORT QStyleOption* qt_widgets_c_QStyleOptionToolButton_G_static_cast_QStyleOption_ptr(QStyleOptionToolButton* ptr);
QT_WIDGETS_C_EXPORT const Qt::ArrowType* qt_widgets_c_QStyleOptionToolButton_arrowType(const QStyleOptionToolButton* this_ptr);
QT_WIDGETS_C_EXPORT Qt::ArrowType* qt_widgets_c_QStyleOptionToolButton_arrowType_mut(QStyleOptionToolButton* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QStyleOptionToolButton_delete(QStyleOptionToolButton* this_ptr);
QT_WIDGETS_C_EXPORT unsigned int qt_widgets_c_QStyleOptionToolButton_features(const QStyleOptionToolButton* this_ptr);
QT_WIDGETS_C_EXPORT const QFont* qt_widgets_c_QStyleOptionToolButton_font(const QStyleOptionToolButton* this_ptr);
QT_WIDGETS_C_EXPORT QFont* qt_widgets_c_QStyleOptionToolButton_font_mut(QStyleOptionToolButton* this_ptr);
QT_WIDGETS_C_EXPORT const QIcon* qt_widgets_c_QStyleOptionToolButton_icon(const QStyleOptionToolButton* this_ptr);
QT_WIDGETS_C_EXPORT const QSize* qt_widgets_c_QStyleOptionToolButton_iconSize(const QStyleOptionToolButton* this_ptr);
QT_WIDGETS_C_EXPORT QSize* qt_widgets_c_QStyleOptionToolButton_iconSize_mut(QStyleOptionToolButton* this_ptr);
QT_WIDGETS_C_EXPORT QIcon* qt_widgets_c_QStyleOptionToolButton_icon_mut(QStyleOptionToolButton* this_ptr);
QT_WIDGETS_C_EXPORT QStyleOptionToolButton* qt_widgets_c_QStyleOptionToolButton_new_no_args();
QT_WIDGETS_C_EXPORT QStyleOptionToolButton* qt_widgets_c_QStyleOptionToolButton_new_other(const QStyleOptionToolButton* other);
QT_WIDGETS_C_EXPORT const QPoint* qt_widgets_c_QStyleOptionToolButton_pos(const QStyleOptionToolButton* this_ptr);
QT_WIDGETS_C_EXPORT QPoint* qt_widgets_c_QStyleOptionToolButton_pos_mut(QStyleOptionToolButton* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QStyleOptionToolButton_set_arrowType(QStyleOptionToolButton* this_ptr, const Qt::ArrowType* value);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QStyleOptionToolButton_set_features(QStyleOptionToolButton* this_ptr, unsigned int value);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QStyleOptionToolButton_set_font(QStyleOptionToolButton* this_ptr, const QFont* value);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QStyleOptionToolButton_set_icon(QStyleOptionToolButton* this_ptr, const QIcon* value);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QStyleOptionToolButton_set_iconSize(QStyleOptionToolButton* this_ptr, const QSize* value);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QStyleOptionToolButton_set_pos(QStyleOptionToolButton* this_ptr, const QPoint* value);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QStyleOptionToolButton_set_text(QStyleOptionToolButton* this_ptr, const QString* value);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QStyleOptionToolButton_set_toolButtonStyle(QStyleOptionToolButton* this_ptr, const Qt::ToolButtonStyle* value);
QT_WIDGETS_C_EXPORT const QString* qt_widgets_c_QStyleOptionToolButton_text(const QStyleOptionToolButton* this_ptr);
QT_WIDGETS_C_EXPORT QString* qt_widgets_c_QStyleOptionToolButton_text_mut(QStyleOptionToolButton* this_ptr);
QT_WIDGETS_C_EXPORT const Qt::ToolButtonStyle* qt_widgets_c_QStyleOptionToolButton_toolButtonStyle(const QStyleOptionToolButton* this_ptr);
QT_WIDGETS_C_EXPORT Qt::ToolButtonStyle* qt_widgets_c_QStyleOptionToolButton_toolButtonStyle_mut(QStyleOptionToolButton* this_ptr);

} // extern "C"

#endif // QT_WIDGETS_C_QSTYLEOPTIONTOOLBUTTON_H
