#ifndef QT_WIDGETS_C_QSTYLEOPTIONTABWIDGETFRAME_H
#define QT_WIDGETS_C_QSTYLEOPTIONTABWIDGETFRAME_H

#include "qt_widgets_c_global.h"

extern "C" {

QT_WIDGETS_C_EXPORT QStyleOptionTabWidgetFrame* qt_widgets_c_QStyleOptionTabWidgetFrame_G_static_cast_QStyleOptionTabWidgetFrame_ptr(QStyleOption* ptr);
QT_WIDGETS_C_EXPORT QStyleOption* qt_widgets_c_QStyleOptionTabWidgetFrame_G_static_cast_QStyleOption_ptr(QStyleOptionTabWidgetFrame* ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QStyleOptionTabWidgetFrame_delete(QStyleOptionTabWidgetFrame* this_ptr);
QT_WIDGETS_C_EXPORT const QSize* qt_widgets_c_QStyleOptionTabWidgetFrame_leftCornerWidgetSize(const QStyleOptionTabWidgetFrame* this_ptr);
QT_WIDGETS_C_EXPORT QSize* qt_widgets_c_QStyleOptionTabWidgetFrame_leftCornerWidgetSize_mut(QStyleOptionTabWidgetFrame* this_ptr);
QT_WIDGETS_C_EXPORT int qt_widgets_c_QStyleOptionTabWidgetFrame_lineWidth(const QStyleOptionTabWidgetFrame* this_ptr);
QT_WIDGETS_C_EXPORT int qt_widgets_c_QStyleOptionTabWidgetFrame_midLineWidth(const QStyleOptionTabWidgetFrame* this_ptr);
QT_WIDGETS_C_EXPORT QStyleOptionTabWidgetFrame* qt_widgets_c_QStyleOptionTabWidgetFrame_new_no_args();
QT_WIDGETS_C_EXPORT QStyleOptionTabWidgetFrame* qt_widgets_c_QStyleOptionTabWidgetFrame_new_other(const QStyleOptionTabWidgetFrame* other);
QT_WIDGETS_C_EXPORT const QSize* qt_widgets_c_QStyleOptionTabWidgetFrame_rightCornerWidgetSize(const QStyleOptionTabWidgetFrame* this_ptr);
QT_WIDGETS_C_EXPORT QSize* qt_widgets_c_QStyleOptionTabWidgetFrame_rightCornerWidgetSize_mut(QStyleOptionTabWidgetFrame* this_ptr);
QT_WIDGETS_C_EXPORT const QRect* qt_widgets_c_QStyleOptionTabWidgetFrame_selectedTabRect(const QStyleOptionTabWidgetFrame* this_ptr);
QT_WIDGETS_C_EXPORT QRect* qt_widgets_c_QStyleOptionTabWidgetFrame_selectedTabRect_mut(QStyleOptionTabWidgetFrame* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QStyleOptionTabWidgetFrame_set_leftCornerWidgetSize(QStyleOptionTabWidgetFrame* this_ptr, const QSize* value);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QStyleOptionTabWidgetFrame_set_lineWidth(QStyleOptionTabWidgetFrame* this_ptr, int value);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QStyleOptionTabWidgetFrame_set_midLineWidth(QStyleOptionTabWidgetFrame* this_ptr, int value);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QStyleOptionTabWidgetFrame_set_rightCornerWidgetSize(QStyleOptionTabWidgetFrame* this_ptr, const QSize* value);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QStyleOptionTabWidgetFrame_set_selectedTabRect(QStyleOptionTabWidgetFrame* this_ptr, const QRect* value);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QStyleOptionTabWidgetFrame_set_shape(QStyleOptionTabWidgetFrame* this_ptr, const QTabBar::Shape* value);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QStyleOptionTabWidgetFrame_set_tabBarRect(QStyleOptionTabWidgetFrame* this_ptr, const QRect* value);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QStyleOptionTabWidgetFrame_set_tabBarSize(QStyleOptionTabWidgetFrame* this_ptr, const QSize* value);
QT_WIDGETS_C_EXPORT const QTabBar::Shape* qt_widgets_c_QStyleOptionTabWidgetFrame_shape(const QStyleOptionTabWidgetFrame* this_ptr);
QT_WIDGETS_C_EXPORT QTabBar::Shape* qt_widgets_c_QStyleOptionTabWidgetFrame_shape_mut(QStyleOptionTabWidgetFrame* this_ptr);
QT_WIDGETS_C_EXPORT const QRect* qt_widgets_c_QStyleOptionTabWidgetFrame_tabBarRect(const QStyleOptionTabWidgetFrame* this_ptr);
QT_WIDGETS_C_EXPORT QRect* qt_widgets_c_QStyleOptionTabWidgetFrame_tabBarRect_mut(QStyleOptionTabWidgetFrame* this_ptr);
QT_WIDGETS_C_EXPORT const QSize* qt_widgets_c_QStyleOptionTabWidgetFrame_tabBarSize(const QStyleOptionTabWidgetFrame* this_ptr);
QT_WIDGETS_C_EXPORT QSize* qt_widgets_c_QStyleOptionTabWidgetFrame_tabBarSize_mut(QStyleOptionTabWidgetFrame* this_ptr);

} // extern "C"

#endif // QT_WIDGETS_C_QSTYLEOPTIONTABWIDGETFRAME_H
