#ifndef QT_WIDGETS_C_QGRAPHICSSCENE_H
#define QT_WIDGETS_C_QGRAPHICSSCENE_H

#include "qt_widgets_c_global.h"

extern "C" {

QT_WIDGETS_C_EXPORT QGraphicsScene* qt_widgets_c_QGraphicsScene_G_static_cast_QGraphicsScene_ptr(QObject* ptr);
QT_WIDGETS_C_EXPORT QObject* qt_widgets_c_QGraphicsScene_G_static_cast_QObject_ptr(QGraphicsScene* ptr);
QT_WIDGETS_C_EXPORT QGraphicsItem* qt_widgets_c_QGraphicsScene_activePanel(const QGraphicsScene* this_ptr);
QT_WIDGETS_C_EXPORT QGraphicsWidget* qt_widgets_c_QGraphicsScene_activeWindow(const QGraphicsScene* this_ptr);
QT_WIDGETS_C_EXPORT QGraphicsEllipseItem* qt_widgets_c_QGraphicsScene_addEllipse_rect(QGraphicsScene* this_ptr, const QRectF* rect);
QT_WIDGETS_C_EXPORT QGraphicsEllipseItem* qt_widgets_c_QGraphicsScene_addEllipse_rect_pen(QGraphicsScene* this_ptr, const QRectF* rect, const QPen* pen);
QT_WIDGETS_C_EXPORT QGraphicsEllipseItem* qt_widgets_c_QGraphicsScene_addEllipse_rect_pen_brush(QGraphicsScene* this_ptr, const QRectF* rect, const QPen* pen, const QBrush* brush);
QT_WIDGETS_C_EXPORT QGraphicsEllipseItem* qt_widgets_c_QGraphicsScene_addEllipse_x_y_w_h(QGraphicsScene* this_ptr, double x, double y, double w, double h);
QT_WIDGETS_C_EXPORT QGraphicsEllipseItem* qt_widgets_c_QGraphicsScene_addEllipse_x_y_w_h_pen(QGraphicsScene* this_ptr, double x, double y, double w, double h, const QPen* pen);
QT_WIDGETS_C_EXPORT QGraphicsEllipseItem* qt_widgets_c_QGraphicsScene_addEllipse_x_y_w_h_pen_brush(QGraphicsScene* this_ptr, double x, double y, double w, double h, const QPen* pen, const QBrush* brush);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_addItem(QGraphicsScene* this_ptr, QGraphicsItem* item);
QT_WIDGETS_C_EXPORT QGraphicsLineItem* qt_widgets_c_QGraphicsScene_addLine_line(QGraphicsScene* this_ptr, const QLineF* line);
QT_WIDGETS_C_EXPORT QGraphicsLineItem* qt_widgets_c_QGraphicsScene_addLine_line_pen(QGraphicsScene* this_ptr, const QLineF* line, const QPen* pen);
QT_WIDGETS_C_EXPORT QGraphicsLineItem* qt_widgets_c_QGraphicsScene_addLine_x1_y1_x2_y2(QGraphicsScene* this_ptr, double x1, double y1, double x2, double y2);
QT_WIDGETS_C_EXPORT QGraphicsLineItem* qt_widgets_c_QGraphicsScene_addLine_x1_y1_x2_y2_pen(QGraphicsScene* this_ptr, double x1, double y1, double x2, double y2, const QPen* pen);
QT_WIDGETS_C_EXPORT QGraphicsPathItem* qt_widgets_c_QGraphicsScene_addPath_path(QGraphicsScene* this_ptr, const QPainterPath* path);
QT_WIDGETS_C_EXPORT QGraphicsPathItem* qt_widgets_c_QGraphicsScene_addPath_path_pen(QGraphicsScene* this_ptr, const QPainterPath* path, const QPen* pen);
QT_WIDGETS_C_EXPORT QGraphicsPathItem* qt_widgets_c_QGraphicsScene_addPath_path_pen_brush(QGraphicsScene* this_ptr, const QPainterPath* path, const QPen* pen, const QBrush* brush);
QT_WIDGETS_C_EXPORT QGraphicsPixmapItem* qt_widgets_c_QGraphicsScene_addPixmap(QGraphicsScene* this_ptr, const QPixmap* pixmap);
QT_WIDGETS_C_EXPORT QGraphicsPolygonItem* qt_widgets_c_QGraphicsScene_addPolygon_polygon(QGraphicsScene* this_ptr, const QPolygonF* polygon);
QT_WIDGETS_C_EXPORT QGraphicsPolygonItem* qt_widgets_c_QGraphicsScene_addPolygon_polygon_pen(QGraphicsScene* this_ptr, const QPolygonF* polygon, const QPen* pen);
QT_WIDGETS_C_EXPORT QGraphicsPolygonItem* qt_widgets_c_QGraphicsScene_addPolygon_polygon_pen_brush(QGraphicsScene* this_ptr, const QPolygonF* polygon, const QPen* pen, const QBrush* brush);
QT_WIDGETS_C_EXPORT QGraphicsRectItem* qt_widgets_c_QGraphicsScene_addRect_rect(QGraphicsScene* this_ptr, const QRectF* rect);
QT_WIDGETS_C_EXPORT QGraphicsRectItem* qt_widgets_c_QGraphicsScene_addRect_rect_pen(QGraphicsScene* this_ptr, const QRectF* rect, const QPen* pen);
QT_WIDGETS_C_EXPORT QGraphicsRectItem* qt_widgets_c_QGraphicsScene_addRect_rect_pen_brush(QGraphicsScene* this_ptr, const QRectF* rect, const QPen* pen, const QBrush* brush);
QT_WIDGETS_C_EXPORT QGraphicsRectItem* qt_widgets_c_QGraphicsScene_addRect_x_y_w_h(QGraphicsScene* this_ptr, double x, double y, double w, double h);
QT_WIDGETS_C_EXPORT QGraphicsRectItem* qt_widgets_c_QGraphicsScene_addRect_x_y_w_h_pen(QGraphicsScene* this_ptr, double x, double y, double w, double h, const QPen* pen);
QT_WIDGETS_C_EXPORT QGraphicsRectItem* qt_widgets_c_QGraphicsScene_addRect_x_y_w_h_pen_brush(QGraphicsScene* this_ptr, double x, double y, double w, double h, const QPen* pen, const QBrush* brush);
QT_WIDGETS_C_EXPORT QGraphicsSimpleTextItem* qt_widgets_c_QGraphicsScene_addSimpleText_text(QGraphicsScene* this_ptr, const QString* text);
QT_WIDGETS_C_EXPORT QGraphicsSimpleTextItem* qt_widgets_c_QGraphicsScene_addSimpleText_text_font(QGraphicsScene* this_ptr, const QString* text, const QFont* font);
QT_WIDGETS_C_EXPORT QGraphicsTextItem* qt_widgets_c_QGraphicsScene_addText_text(QGraphicsScene* this_ptr, const QString* text);
QT_WIDGETS_C_EXPORT QGraphicsTextItem* qt_widgets_c_QGraphicsScene_addText_text_font(QGraphicsScene* this_ptr, const QString* text, const QFont* font);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_advance(QGraphicsScene* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_backgroundBrush_to_output(const QGraphicsScene* this_ptr, QBrush* output);
QT_WIDGETS_C_EXPORT int qt_widgets_c_QGraphicsScene_bspTreeDepth(const QGraphicsScene* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_clear(QGraphicsScene* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_clearFocus(QGraphicsScene* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_clearSelection(QGraphicsScene* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_collidingItems_to_output_item(const QGraphicsScene* this_ptr, const QGraphicsItem* item, QList< QGraphicsItem* >* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_collidingItems_to_output_item_mode(const QGraphicsScene* this_ptr, const QGraphicsItem* item, const Qt::ItemSelectionMode* mode, QList< QGraphicsItem* >* output);
QT_WIDGETS_C_EXPORT QGraphicsItemGroup* qt_widgets_c_QGraphicsScene_createItemGroup(QGraphicsScene* this_ptr, const QList< QGraphicsItem* >* items);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_delete(QGraphicsScene* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_destroyItemGroup(QGraphicsScene* this_ptr, QGraphicsItemGroup* group);
QT_WIDGETS_C_EXPORT QGraphicsItem* qt_widgets_c_QGraphicsScene_focusItem(const QGraphicsScene* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_font_to_output(const QGraphicsScene* this_ptr, QFont* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_foregroundBrush_to_output(const QGraphicsScene* this_ptr, QBrush* output);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsScene_hasFocus(const QGraphicsScene* this_ptr);
QT_WIDGETS_C_EXPORT double qt_widgets_c_QGraphicsScene_height(const QGraphicsScene* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_inputMethodQuery_to_output(const QGraphicsScene* this_ptr, const Qt::InputMethodQuery* query, QVariant* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_invalidate_no_args(QGraphicsScene* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_invalidate_rect(QGraphicsScene* this_ptr, const QRectF* rect);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_invalidate_rect_layers(QGraphicsScene* this_ptr, const QRectF* rect, unsigned int layers);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_invalidate_x_y_w_h(QGraphicsScene* this_ptr, double x, double y, double w, double h);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_invalidate_x_y_w_h_layers(QGraphicsScene* this_ptr, double x, double y, double w, double h, unsigned int layers);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsScene_isActive(const QGraphicsScene* this_ptr);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsScene_isSortCacheEnabled(const QGraphicsScene* this_ptr);
QT_WIDGETS_C_EXPORT QGraphicsItem* qt_widgets_c_QGraphicsScene_itemAt_pos_deviceTransform(const QGraphicsScene* this_ptr, const QPointF* pos, const QTransform* deviceTransform);
QT_WIDGETS_C_EXPORT QGraphicsItem* qt_widgets_c_QGraphicsScene_itemAt_x_y_deviceTransform(const QGraphicsScene* this_ptr, double x, double y, const QTransform* deviceTransform);
QT_WIDGETS_C_EXPORT QGraphicsScene::ItemIndexMethod qt_widgets_c_QGraphicsScene_itemIndexMethod(const QGraphicsScene* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_itemsBoundingRect_to_output(const QGraphicsScene* this_ptr, QRectF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_items_to_output_no_args(const QGraphicsScene* this_ptr, QList< QGraphicsItem* >* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_items_to_output_order(const QGraphicsScene* this_ptr, const Qt::SortOrder* order, QList< QGraphicsItem* >* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_items_to_output_path(const QGraphicsScene* this_ptr, const QPainterPath* path, QList< QGraphicsItem* >* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_items_to_output_path_mode(const QGraphicsScene* this_ptr, const QPainterPath* path, const Qt::ItemSelectionMode* mode, QList< QGraphicsItem* >* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_items_to_output_path_mode_order(const QGraphicsScene* this_ptr, const QPainterPath* path, const Qt::ItemSelectionMode* mode, const Qt::SortOrder* order, QList< QGraphicsItem* >* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_items_to_output_path_mode_order_deviceTransform(const QGraphicsScene* this_ptr, const QPainterPath* path, const Qt::ItemSelectionMode* mode, const Qt::SortOrder* order, const QTransform* deviceTransform, QList< QGraphicsItem* >* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_items_to_output_polygon(const QGraphicsScene* this_ptr, const QPolygonF* polygon, QList< QGraphicsItem* >* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_items_to_output_polygon_mode(const QGraphicsScene* this_ptr, const QPolygonF* polygon, const Qt::ItemSelectionMode* mode, QList< QGraphicsItem* >* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_items_to_output_polygon_mode_order(const QGraphicsScene* this_ptr, const QPolygonF* polygon, const Qt::ItemSelectionMode* mode, const Qt::SortOrder* order, QList< QGraphicsItem* >* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_items_to_output_polygon_mode_order_deviceTransform(const QGraphicsScene* this_ptr, const QPolygonF* polygon, const Qt::ItemSelectionMode* mode, const Qt::SortOrder* order, const QTransform* deviceTransform, QList< QGraphicsItem* >* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_items_to_output_pos(const QGraphicsScene* this_ptr, const QPointF* pos, QList< QGraphicsItem* >* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_items_to_output_pos_mode(const QGraphicsScene* this_ptr, const QPointF* pos, const Qt::ItemSelectionMode* mode, QList< QGraphicsItem* >* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_items_to_output_pos_mode_order(const QGraphicsScene* this_ptr, const QPointF* pos, const Qt::ItemSelectionMode* mode, const Qt::SortOrder* order, QList< QGraphicsItem* >* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_items_to_output_pos_mode_order_deviceTransform(const QGraphicsScene* this_ptr, const QPointF* pos, const Qt::ItemSelectionMode* mode, const Qt::SortOrder* order, const QTransform* deviceTransform, QList< QGraphicsItem* >* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_items_to_output_rect(const QGraphicsScene* this_ptr, const QRectF* rect, QList< QGraphicsItem* >* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_items_to_output_rect_mode(const QGraphicsScene* this_ptr, const QRectF* rect, const Qt::ItemSelectionMode* mode, QList< QGraphicsItem* >* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_items_to_output_rect_mode_order(const QGraphicsScene* this_ptr, const QRectF* rect, const Qt::ItemSelectionMode* mode, const Qt::SortOrder* order, QList< QGraphicsItem* >* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_items_to_output_rect_mode_order_deviceTransform(const QGraphicsScene* this_ptr, const QRectF* rect, const Qt::ItemSelectionMode* mode, const Qt::SortOrder* order, const QTransform* deviceTransform, QList< QGraphicsItem* >* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_items_to_output_x_y_w_h_mode_order(const QGraphicsScene* this_ptr, double x, double y, double w, double h, const Qt::ItemSelectionMode* mode, const Qt::SortOrder* order, QList< QGraphicsItem* >* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_items_to_output_x_y_w_h_mode_order_deviceTransform(const QGraphicsScene* this_ptr, double x, double y, double w, double h, const Qt::ItemSelectionMode* mode, const Qt::SortOrder* order, const QTransform* deviceTransform, QList< QGraphicsItem* >* output);
QT_WIDGETS_C_EXPORT const QMetaObject* qt_widgets_c_QGraphicsScene_metaObject(const QGraphicsScene* this_ptr);
QT_WIDGETS_C_EXPORT double qt_widgets_c_QGraphicsScene_minimumRenderSize(const QGraphicsScene* this_ptr);
QT_WIDGETS_C_EXPORT QGraphicsItem* qt_widgets_c_QGraphicsScene_mouseGrabberItem(const QGraphicsScene* this_ptr);
QT_WIDGETS_C_EXPORT QGraphicsScene* qt_widgets_c_QGraphicsScene_new_no_args();
QT_WIDGETS_C_EXPORT QGraphicsScene* qt_widgets_c_QGraphicsScene_new_parent(QObject* parent);
QT_WIDGETS_C_EXPORT QGraphicsScene* qt_widgets_c_QGraphicsScene_new_sceneRect(const QRectF* sceneRect);
QT_WIDGETS_C_EXPORT QGraphicsScene* qt_widgets_c_QGraphicsScene_new_sceneRect_parent(const QRectF* sceneRect, QObject* parent);
QT_WIDGETS_C_EXPORT QGraphicsScene* qt_widgets_c_QGraphicsScene_new_x_y_width_height(double x, double y, double width, double height);
QT_WIDGETS_C_EXPORT QGraphicsScene* qt_widgets_c_QGraphicsScene_new_x_y_width_height_parent(double x, double y, double width, double height, QObject* parent);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_palette_to_output(const QGraphicsScene* this_ptr, QPalette* output);
QT_WIDGETS_C_EXPORT int qt_widgets_c_QGraphicsScene_qt_metacall(QGraphicsScene* this_ptr, const QMetaObject::Call* arg1, int arg2, void** arg3);
QT_WIDGETS_C_EXPORT void* qt_widgets_c_QGraphicsScene_qt_metacast(QGraphicsScene* this_ptr, const char* arg1);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_removeItem(QGraphicsScene* this_ptr, QGraphicsItem* item);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_render_painter(QGraphicsScene* this_ptr, QPainter* painter);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_render_painter_target(QGraphicsScene* this_ptr, QPainter* painter, const QRectF* target);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_render_painter_target_source(QGraphicsScene* this_ptr, QPainter* painter, const QRectF* target, const QRectF* source);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_render_painter_target_source_aspectRatioMode(QGraphicsScene* this_ptr, QPainter* painter, const QRectF* target, const QRectF* source, const Qt::AspectRatioMode* aspectRatioMode);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_sceneRect_to_output(const QGraphicsScene* this_ptr, QRectF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_selectedItems_to_output(const QGraphicsScene* this_ptr, QList< QGraphicsItem* >* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_selectionArea_to_output(const QGraphicsScene* this_ptr, QPainterPath* output);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsScene_sendEvent(QGraphicsScene* this_ptr, QGraphicsItem* item, QEvent* event);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_setActivePanel(QGraphicsScene* this_ptr, QGraphicsItem* item);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_setActiveWindow(QGraphicsScene* this_ptr, QGraphicsWidget* widget);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_setBackgroundBrush(QGraphicsScene* this_ptr, const QBrush* brush);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_setBspTreeDepth(QGraphicsScene* this_ptr, int depth);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_setFocusItem_item(QGraphicsScene* this_ptr, QGraphicsItem* item);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_setFocusItem_item_focusReason(QGraphicsScene* this_ptr, QGraphicsItem* item, const Qt::FocusReason* focusReason);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_setFocus_focusReason(QGraphicsScene* this_ptr, const Qt::FocusReason* focusReason);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_setFocus_no_args(QGraphicsScene* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_setFont(QGraphicsScene* this_ptr, const QFont* font);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_setForegroundBrush(QGraphicsScene* this_ptr, const QBrush* brush);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_setItemIndexMethod(QGraphicsScene* this_ptr, QGraphicsScene::ItemIndexMethod method);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_setMinimumRenderSize(QGraphicsScene* this_ptr, double minSize);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_setPalette(QGraphicsScene* this_ptr, const QPalette* palette);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_setSceneRect_rect(QGraphicsScene* this_ptr, const QRectF* rect);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_setSceneRect_x_y_w_h(QGraphicsScene* this_ptr, double x, double y, double w, double h);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_setSelectionArea_path(QGraphicsScene* this_ptr, const QPainterPath* path);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_setSelectionArea_path_deviceTransform(QGraphicsScene* this_ptr, const QPainterPath* path, const QTransform* deviceTransform);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_setSelectionArea_path_mode(QGraphicsScene* this_ptr, const QPainterPath* path, const Qt::ItemSelectionMode* mode);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_setSelectionArea_path_mode_deviceTransform(QGraphicsScene* this_ptr, const QPainterPath* path, const Qt::ItemSelectionMode* mode, const QTransform* deviceTransform);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_setSelectionArea_path_selectionOperation(QGraphicsScene* this_ptr, const QPainterPath* path, const Qt::ItemSelectionOperation* selectionOperation);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_setSelectionArea_path_selectionOperation_mode(QGraphicsScene* this_ptr, const QPainterPath* path, const Qt::ItemSelectionOperation* selectionOperation, const Qt::ItemSelectionMode* mode);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_setSelectionArea_path_selectionOperation_mode_deviceTransform(QGraphicsScene* this_ptr, const QPainterPath* path, const Qt::ItemSelectionOperation* selectionOperation, const Qt::ItemSelectionMode* mode, const QTransform* deviceTransform);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_setSortCacheEnabled(QGraphicsScene* this_ptr, bool enabled);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_setStickyFocus(QGraphicsScene* this_ptr, bool enabled);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_setStyle(QGraphicsScene* this_ptr, QStyle* style);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsScene_stickyFocus(const QGraphicsScene* this_ptr);
QT_WIDGETS_C_EXPORT QStyle* qt_widgets_c_QGraphicsScene_style(const QGraphicsScene* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_trUtf8_to_output(const char* s, const char* c, int n, QString* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_tr_to_output(const char* s, const char* c, int n, QString* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_update_no_args(QGraphicsScene* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_update_rect(QGraphicsScene* this_ptr, const QRectF* rect);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_update_x_y_w_h(QGraphicsScene* this_ptr, double x, double y, double w, double h);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsScene_views_to_output(const QGraphicsScene* this_ptr, QList< QGraphicsView* >* output);
QT_WIDGETS_C_EXPORT double qt_widgets_c_QGraphicsScene_width(const QGraphicsScene* this_ptr);

} // extern "C"

#endif // QT_WIDGETS_C_QGRAPHICSSCENE_H
