#ifndef QT_WIDGETS_C_QGRAPHICSSIMPLETEXTITEM_H
#define QT_WIDGETS_C_QGRAPHICSSIMPLETEXTITEM_H

#include "qt_widgets_c_global.h"

extern "C" {

QT_WIDGETS_C_EXPORT QGraphicsSimpleTextItem* qt_widgets_c_QGraphicsSimpleTextItem_G_dynamic_cast_QGraphicsSimpleTextItem_ptr_QAbstractGraphicsShapeItem(QAbstractGraphicsShapeItem* ptr);
QT_WIDGETS_C_EXPORT QGraphicsSimpleTextItem* qt_widgets_c_QGraphicsSimpleTextItem_G_dynamic_cast_QGraphicsSimpleTextItem_ptr_QGraphicsItem(QGraphicsItem* ptr);
QT_WIDGETS_C_EXPORT QAbstractGraphicsShapeItem* qt_widgets_c_QGraphicsSimpleTextItem_G_static_cast_QAbstractGraphicsShapeItem_ptr(QGraphicsSimpleTextItem* ptr);
QT_WIDGETS_C_EXPORT QGraphicsItem* qt_widgets_c_QGraphicsSimpleTextItem_G_static_cast_QGraphicsItem_ptr(QGraphicsSimpleTextItem* ptr);
QT_WIDGETS_C_EXPORT QGraphicsSimpleTextItem* qt_widgets_c_QGraphicsSimpleTextItem_G_static_cast_QGraphicsSimpleTextItem_ptr_QAbstractGraphicsShapeItem(QAbstractGraphicsShapeItem* ptr);
QT_WIDGETS_C_EXPORT QGraphicsSimpleTextItem* qt_widgets_c_QGraphicsSimpleTextItem_G_static_cast_QGraphicsSimpleTextItem_ptr_QGraphicsItem(QGraphicsItem* ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsSimpleTextItem_boundingRect_to_output(const QGraphicsSimpleTextItem* this_ptr, QRectF* output);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsSimpleTextItem_contains(const QGraphicsSimpleTextItem* this_ptr, const QPointF* point);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsSimpleTextItem_delete(QGraphicsSimpleTextItem* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsSimpleTextItem_font_to_output(const QGraphicsSimpleTextItem* this_ptr, QFont* output);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsSimpleTextItem_isObscuredBy(const QGraphicsSimpleTextItem* this_ptr, const QGraphicsItem* item);
QT_WIDGETS_C_EXPORT QGraphicsSimpleTextItem* qt_widgets_c_QGraphicsSimpleTextItem_new_no_args();
QT_WIDGETS_C_EXPORT QGraphicsSimpleTextItem* qt_widgets_c_QGraphicsSimpleTextItem_new_parent(QGraphicsItem* parent);
QT_WIDGETS_C_EXPORT QGraphicsSimpleTextItem* qt_widgets_c_QGraphicsSimpleTextItem_new_text(const QString* text);
QT_WIDGETS_C_EXPORT QGraphicsSimpleTextItem* qt_widgets_c_QGraphicsSimpleTextItem_new_text_parent(const QString* text, QGraphicsItem* parent);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsSimpleTextItem_opaqueArea_to_output(const QGraphicsSimpleTextItem* this_ptr, QPainterPath* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsSimpleTextItem_paint(QGraphicsSimpleTextItem* this_ptr, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsSimpleTextItem_setFont(QGraphicsSimpleTextItem* this_ptr, const QFont* font);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsSimpleTextItem_setText(QGraphicsSimpleTextItem* this_ptr, const QString* text);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsSimpleTextItem_shape_to_output(const QGraphicsSimpleTextItem* this_ptr, QPainterPath* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsSimpleTextItem_text_to_output(const QGraphicsSimpleTextItem* this_ptr, QString* output);
QT_WIDGETS_C_EXPORT int qt_widgets_c_QGraphicsSimpleTextItem_type(const QGraphicsSimpleTextItem* this_ptr);

} // extern "C"

#endif // QT_WIDGETS_C_QGRAPHICSSIMPLETEXTITEM_H
