#ifndef QT_WIDGETS_C_QCOMMANDLINKBUTTON_H
#define QT_WIDGETS_C_QCOMMANDLINKBUTTON_H

#include "qt_widgets_c_global.h"

extern "C" {

QT_WIDGETS_C_EXPORT QCommandLinkButton* qt_widgets_c_QCommandLinkButton_G_dynamic_cast_QCommandLinkButton_ptr_QAbstractButton(QAbstractButton* ptr);
QT_WIDGETS_C_EXPORT QCommandLinkButton* qt_widgets_c_QCommandLinkButton_G_dynamic_cast_QCommandLinkButton_ptr_QPushButton(QPushButton* ptr);
QT_WIDGETS_C_EXPORT QCommandLinkButton* qt_widgets_c_QCommandLinkButton_G_dynamic_cast_QCommandLinkButton_ptr_QWidget(QWidget* ptr);
QT_WIDGETS_C_EXPORT QAbstractButton* qt_widgets_c_QCommandLinkButton_G_static_cast_QAbstractButton_ptr(QCommandLinkButton* ptr);
QT_WIDGETS_C_EXPORT QCommandLinkButton* qt_widgets_c_QCommandLinkButton_G_static_cast_QCommandLinkButton_ptr_QAbstractButton(QAbstractButton* ptr);
QT_WIDGETS_C_EXPORT QCommandLinkButton* qt_widgets_c_QCommandLinkButton_G_static_cast_QCommandLinkButton_ptr_QObject(QObject* ptr);
QT_WIDGETS_C_EXPORT QCommandLinkButton* qt_widgets_c_QCommandLinkButton_G_static_cast_QCommandLinkButton_ptr_QPaintDevice(QPaintDevice* ptr);
QT_WIDGETS_C_EXPORT QCommandLinkButton* qt_widgets_c_QCommandLinkButton_G_static_cast_QCommandLinkButton_ptr_QPushButton(QPushButton* ptr);
QT_WIDGETS_C_EXPORT QCommandLinkButton* qt_widgets_c_QCommandLinkButton_G_static_cast_QCommandLinkButton_ptr_QWidget(QWidget* ptr);
QT_WIDGETS_C_EXPORT QObject* qt_widgets_c_QCommandLinkButton_G_static_cast_QObject_ptr(QCommandLinkButton* ptr);
QT_WIDGETS_C_EXPORT QPaintDevice* qt_widgets_c_QCommandLinkButton_G_static_cast_QPaintDevice_ptr(QCommandLinkButton* ptr);
QT_WIDGETS_C_EXPORT QPushButton* qt_widgets_c_QCommandLinkButton_G_static_cast_QPushButton_ptr(QCommandLinkButton* ptr);
QT_WIDGETS_C_EXPORT QWidget* qt_widgets_c_QCommandLinkButton_G_static_cast_QWidget_ptr(QCommandLinkButton* ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QCommandLinkButton_delete(QCommandLinkButton* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QCommandLinkButton_description_to_output(const QCommandLinkButton* this_ptr, QString* output);
QT_WIDGETS_C_EXPORT const QMetaObject* qt_widgets_c_QCommandLinkButton_metaObject(const QCommandLinkButton* this_ptr);
QT_WIDGETS_C_EXPORT QCommandLinkButton* qt_widgets_c_QCommandLinkButton_new_no_args();
QT_WIDGETS_C_EXPORT QCommandLinkButton* qt_widgets_c_QCommandLinkButton_new_parent(QWidget* parent);
QT_WIDGETS_C_EXPORT QCommandLinkButton* qt_widgets_c_QCommandLinkButton_new_text(const QString* text);
QT_WIDGETS_C_EXPORT QCommandLinkButton* qt_widgets_c_QCommandLinkButton_new_text_description(const QString* text, const QString* description);
QT_WIDGETS_C_EXPORT QCommandLinkButton* qt_widgets_c_QCommandLinkButton_new_text_description_parent(const QString* text, const QString* description, QWidget* parent);
QT_WIDGETS_C_EXPORT QCommandLinkButton* qt_widgets_c_QCommandLinkButton_new_text_parent(const QString* text, QWidget* parent);
QT_WIDGETS_C_EXPORT int qt_widgets_c_QCommandLinkButton_qt_metacall(QCommandLinkButton* this_ptr, const QMetaObject::Call* arg1, int arg2, void** arg3);
QT_WIDGETS_C_EXPORT void* qt_widgets_c_QCommandLinkButton_qt_metacast(QCommandLinkButton* this_ptr, const char* arg1);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QCommandLinkButton_setDescription(QCommandLinkButton* this_ptr, const QString* description);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QCommandLinkButton_trUtf8_to_output(const char* s, const char* c, int n, QString* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QCommandLinkButton_tr_to_output(const char* s, const char* c, int n, QString* output);

} // extern "C"

#endif // QT_WIDGETS_C_QCOMMANDLINKBUTTON_H
