#ifndef QT_WIDGETS_C_QGRAPHICSITEM_H
#define QT_WIDGETS_C_QGRAPHICSITEM_H

#include "qt_widgets_c_global.h"

extern "C" {

QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_G_operator_shl_to_output_QDebug_QGraphicsItem(const QDebug* debug, QGraphicsItem* item, QDebug* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_G_operator_shl_to_output_QDebug_QGraphicsItem_GraphicsItemChange(const QDebug* debug, const QGraphicsItem::GraphicsItemChange* change, QDebug* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_G_operator_shl_to_output_QDebug_QGraphicsItem_GraphicsItemFlag(const QDebug* debug, const QGraphicsItem::GraphicsItemFlag* flag, QDebug* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_G_operator_shl_to_output_QDebug_QGraphicsObject(const QDebug* debug, QGraphicsObject* item, QDebug* output);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsItem_acceptDrops(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsItem_acceptHoverEvents(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsItem_acceptTouchEvents(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_advance(QGraphicsItem* this_ptr, int phase);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_boundingRect_to_output(const QGraphicsItem* this_ptr, QRectF* output);
QT_WIDGETS_C_EXPORT double qt_widgets_c_QGraphicsItem_boundingRegionGranularity(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT QRegion* qt_widgets_c_QGraphicsItem_boundingRegion_as_ptr(const QGraphicsItem* this_ptr, const QTransform* itemToDeviceTransform);
QT_WIDGETS_C_EXPORT QGraphicsItem::CacheMode qt_widgets_c_QGraphicsItem_cacheMode(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_childItems_to_output(const QGraphicsItem* this_ptr, QList< QGraphicsItem* >* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_childrenBoundingRect_to_output(const QGraphicsItem* this_ptr, QRectF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_clearFocus(QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_clipPath_to_output(const QGraphicsItem* this_ptr, QPainterPath* output);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsItem_collidesWithItem_other(const QGraphicsItem* this_ptr, const QGraphicsItem* other);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsItem_collidesWithItem_other_mode(const QGraphicsItem* this_ptr, const QGraphicsItem* other, const Qt::ItemSelectionMode* mode);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsItem_collidesWithPath_path(const QGraphicsItem* this_ptr, const QPainterPath* path);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsItem_collidesWithPath_path_mode(const QGraphicsItem* this_ptr, const QPainterPath* path, const Qt::ItemSelectionMode* mode);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_collidingItems_to_output_mode(const QGraphicsItem* this_ptr, const Qt::ItemSelectionMode* mode, QList< QGraphicsItem* >* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_collidingItems_to_output_no_args(const QGraphicsItem* this_ptr, QList< QGraphicsItem* >* output);
QT_WIDGETS_C_EXPORT QGraphicsItem* qt_widgets_c_QGraphicsItem_commonAncestorItem(const QGraphicsItem* this_ptr, const QGraphicsItem* other);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsItem_contains(const QGraphicsItem* this_ptr, const QPointF* point);
QT_WIDGETS_C_EXPORT QCursor* qt_widgets_c_QGraphicsItem_cursor_as_ptr(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_data_to_output(const QGraphicsItem* this_ptr, int key, QVariant* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_delete(QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_deviceTransform_to_output(const QGraphicsItem* this_ptr, const QTransform* viewportTransform, QTransform* output);
QT_WIDGETS_C_EXPORT double qt_widgets_c_QGraphicsItem_effectiveOpacity(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_ensureVisible_no_args(QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_ensureVisible_rect(QGraphicsItem* this_ptr, const QRectF* rect);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_ensureVisible_rect_xmargin(QGraphicsItem* this_ptr, const QRectF* rect, int xmargin);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_ensureVisible_rect_xmargin_ymargin(QGraphicsItem* this_ptr, const QRectF* rect, int xmargin, int ymargin);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_ensureVisible_x_y_w_h(QGraphicsItem* this_ptr, double x, double y, double w, double h);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_ensureVisible_x_y_w_h_xmargin(QGraphicsItem* this_ptr, double x, double y, double w, double h, int xmargin);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_ensureVisible_x_y_w_h_xmargin_ymargin(QGraphicsItem* this_ptr, double x, double y, double w, double h, int xmargin, int ymargin);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsItem_filtersChildEvents(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT unsigned int qt_widgets_c_QGraphicsItem_flags(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT QGraphicsItem* qt_widgets_c_QGraphicsItem_focusItem(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT QGraphicsItem* qt_widgets_c_QGraphicsItem_focusProxy(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT QGraphicsItem* qt_widgets_c_QGraphicsItem_focusScopeItem(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_grabKeyboard(QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_grabMouse(QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT QGraphicsEffect* qt_widgets_c_QGraphicsItem_graphicsEffect(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT QGraphicsItemGroup* qt_widgets_c_QGraphicsItem_group(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsItem_handlesChildEvents(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsItem_hasCursor(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsItem_hasFocus(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_hide(QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_installSceneEventFilter(QGraphicsItem* this_ptr, QGraphicsItem* filterItem);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsItem_isActive(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsItem_isAncestorOf(const QGraphicsItem* this_ptr, const QGraphicsItem* child);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsItem_isBlockedByModalPanel_blockingPanel(const QGraphicsItem* this_ptr, QGraphicsItem** blockingPanel);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsItem_isBlockedByModalPanel_no_args(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsItem_isClipped(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsItem_isEnabled(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsItem_isObscuredBy(const QGraphicsItem* this_ptr, const QGraphicsItem* item);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsItem_isObscured_no_args(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsItem_isObscured_rect(const QGraphicsItem* this_ptr, const QRectF* rect);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsItem_isObscured_x_y_w_h(const QGraphicsItem* this_ptr, double x, double y, double w, double h);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsItem_isPanel(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsItem_isSelected(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsItem_isUnderMouse(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsItem_isVisible(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsItem_isVisibleTo(const QGraphicsItem* this_ptr, const QGraphicsItem* parent);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsItem_isWidget(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QGraphicsItem_isWindow(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_itemTransform_to_output_other(const QGraphicsItem* this_ptr, const QGraphicsItem* other, QTransform* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_itemTransform_to_output_other_ok(const QGraphicsItem* this_ptr, const QGraphicsItem* other, bool* ok, QTransform* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapFromItem_to_output_item_path(const QGraphicsItem* this_ptr, const QGraphicsItem* item, const QPainterPath* path, QPainterPath* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapFromItem_to_output_item_point(const QGraphicsItem* this_ptr, const QGraphicsItem* item, const QPointF* point, QPointF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapFromItem_to_output_item_polygon(const QGraphicsItem* this_ptr, const QGraphicsItem* item, const QPolygonF* polygon, QPolygonF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapFromItem_to_output_item_rect(const QGraphicsItem* this_ptr, const QGraphicsItem* item, const QRectF* rect, QPolygonF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapFromItem_to_output_item_x_y(const QGraphicsItem* this_ptr, const QGraphicsItem* item, double x, double y, QPointF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapFromItem_to_output_item_x_y_w_h(const QGraphicsItem* this_ptr, const QGraphicsItem* item, double x, double y, double w, double h, QPolygonF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapFromParent_to_output_path(const QGraphicsItem* this_ptr, const QPainterPath* path, QPainterPath* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapFromParent_to_output_point(const QGraphicsItem* this_ptr, const QPointF* point, QPointF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapFromParent_to_output_polygon(const QGraphicsItem* this_ptr, const QPolygonF* polygon, QPolygonF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapFromParent_to_output_rect(const QGraphicsItem* this_ptr, const QRectF* rect, QPolygonF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapFromParent_to_output_x_y(const QGraphicsItem* this_ptr, double x, double y, QPointF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapFromParent_to_output_x_y_w_h(const QGraphicsItem* this_ptr, double x, double y, double w, double h, QPolygonF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapFromScene_to_output_path(const QGraphicsItem* this_ptr, const QPainterPath* path, QPainterPath* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapFromScene_to_output_point(const QGraphicsItem* this_ptr, const QPointF* point, QPointF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapFromScene_to_output_polygon(const QGraphicsItem* this_ptr, const QPolygonF* polygon, QPolygonF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapFromScene_to_output_rect(const QGraphicsItem* this_ptr, const QRectF* rect, QPolygonF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapFromScene_to_output_x_y(const QGraphicsItem* this_ptr, double x, double y, QPointF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapFromScene_to_output_x_y_w_h(const QGraphicsItem* this_ptr, double x, double y, double w, double h, QPolygonF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapRectFromItem_to_output_item_rect(const QGraphicsItem* this_ptr, const QGraphicsItem* item, const QRectF* rect, QRectF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapRectFromItem_to_output_item_x_y_w_h(const QGraphicsItem* this_ptr, const QGraphicsItem* item, double x, double y, double w, double h, QRectF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapRectFromParent_to_output_rect(const QGraphicsItem* this_ptr, const QRectF* rect, QRectF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapRectFromParent_to_output_x_y_w_h(const QGraphicsItem* this_ptr, double x, double y, double w, double h, QRectF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapRectFromScene_to_output_rect(const QGraphicsItem* this_ptr, const QRectF* rect, QRectF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapRectFromScene_to_output_x_y_w_h(const QGraphicsItem* this_ptr, double x, double y, double w, double h, QRectF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapRectToItem_to_output_item_rect(const QGraphicsItem* this_ptr, const QGraphicsItem* item, const QRectF* rect, QRectF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapRectToItem_to_output_item_x_y_w_h(const QGraphicsItem* this_ptr, const QGraphicsItem* item, double x, double y, double w, double h, QRectF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapRectToParent_to_output_rect(const QGraphicsItem* this_ptr, const QRectF* rect, QRectF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapRectToParent_to_output_x_y_w_h(const QGraphicsItem* this_ptr, double x, double y, double w, double h, QRectF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapRectToScene_to_output_rect(const QGraphicsItem* this_ptr, const QRectF* rect, QRectF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapRectToScene_to_output_x_y_w_h(const QGraphicsItem* this_ptr, double x, double y, double w, double h, QRectF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapToItem_to_output_item_path(const QGraphicsItem* this_ptr, const QGraphicsItem* item, const QPainterPath* path, QPainterPath* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapToItem_to_output_item_point(const QGraphicsItem* this_ptr, const QGraphicsItem* item, const QPointF* point, QPointF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapToItem_to_output_item_polygon(const QGraphicsItem* this_ptr, const QGraphicsItem* item, const QPolygonF* polygon, QPolygonF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapToItem_to_output_item_rect(const QGraphicsItem* this_ptr, const QGraphicsItem* item, const QRectF* rect, QPolygonF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapToItem_to_output_item_x_y(const QGraphicsItem* this_ptr, const QGraphicsItem* item, double x, double y, QPointF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapToItem_to_output_item_x_y_w_h(const QGraphicsItem* this_ptr, const QGraphicsItem* item, double x, double y, double w, double h, QPolygonF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapToParent_to_output_path(const QGraphicsItem* this_ptr, const QPainterPath* path, QPainterPath* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapToParent_to_output_point(const QGraphicsItem* this_ptr, const QPointF* point, QPointF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapToParent_to_output_polygon(const QGraphicsItem* this_ptr, const QPolygonF* polygon, QPolygonF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapToParent_to_output_rect(const QGraphicsItem* this_ptr, const QRectF* rect, QPolygonF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapToParent_to_output_x_y(const QGraphicsItem* this_ptr, double x, double y, QPointF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapToParent_to_output_x_y_w_h(const QGraphicsItem* this_ptr, double x, double y, double w, double h, QPolygonF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapToScene_to_output_path(const QGraphicsItem* this_ptr, const QPainterPath* path, QPainterPath* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapToScene_to_output_point(const QGraphicsItem* this_ptr, const QPointF* point, QPointF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapToScene_to_output_polygon(const QGraphicsItem* this_ptr, const QPolygonF* polygon, QPolygonF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapToScene_to_output_rect(const QGraphicsItem* this_ptr, const QRectF* rect, QPolygonF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapToScene_to_output_x_y(const QGraphicsItem* this_ptr, double x, double y, QPointF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_mapToScene_to_output_x_y_w_h(const QGraphicsItem* this_ptr, double x, double y, double w, double h, QPolygonF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_matrix_to_output(const QGraphicsItem* this_ptr, QMatrix* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_moveBy(QGraphicsItem* this_ptr, double dx, double dy);
QT_WIDGETS_C_EXPORT double qt_widgets_c_QGraphicsItem_opacity(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_opaqueArea_to_output(const QGraphicsItem* this_ptr, QPainterPath* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_paint_painter_option(QGraphicsItem* this_ptr, QPainter* painter, const QStyleOptionGraphicsItem* option);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_paint_painter_option_widget(QGraphicsItem* this_ptr, QPainter* painter, const QStyleOptionGraphicsItem* option, QWidget* widget);
QT_WIDGETS_C_EXPORT QGraphicsItem* qt_widgets_c_QGraphicsItem_panel(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT QGraphicsItem::PanelModality qt_widgets_c_QGraphicsItem_panelModality(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT QGraphicsItem* qt_widgets_c_QGraphicsItem_parentItem(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT QGraphicsObject* qt_widgets_c_QGraphicsItem_parentObject(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT QGraphicsWidget* qt_widgets_c_QGraphicsItem_parentWidget(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_pos_to_output(const QGraphicsItem* this_ptr, QPointF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_removeSceneEventFilter(QGraphicsItem* this_ptr, QGraphicsItem* filterItem);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_resetMatrix(QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_resetTransform(QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT double qt_widgets_c_QGraphicsItem_rotation(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT double qt_widgets_c_QGraphicsItem_scale(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT QGraphicsScene* qt_widgets_c_QGraphicsItem_scene(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_sceneBoundingRect_to_output(const QGraphicsItem* this_ptr, QRectF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_sceneMatrix_to_output(const QGraphicsItem* this_ptr, QMatrix* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_scenePos_to_output(const QGraphicsItem* this_ptr, QPointF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_sceneTransform_to_output(const QGraphicsItem* this_ptr, QTransform* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_scroll_dx_dy(QGraphicsItem* this_ptr, double dx, double dy);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_scroll_dx_dy_rect(QGraphicsItem* this_ptr, double dx, double dy, const QRectF* rect);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setAcceptDrops(QGraphicsItem* this_ptr, bool on);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setAcceptHoverEvents(QGraphicsItem* this_ptr, bool enabled);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setAcceptTouchEvents(QGraphicsItem* this_ptr, bool enabled);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setActive(QGraphicsItem* this_ptr, bool active);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setBoundingRegionGranularity(QGraphicsItem* this_ptr, double granularity);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setCacheMode_mode(QGraphicsItem* this_ptr, QGraphicsItem::CacheMode mode);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setCacheMode_mode_cacheSize(QGraphicsItem* this_ptr, QGraphicsItem::CacheMode mode, const QSize* cacheSize);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setCursor(QGraphicsItem* this_ptr, const QCursor* cursor);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setData(QGraphicsItem* this_ptr, int key, const QVariant* value);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setEnabled(QGraphicsItem* this_ptr, bool enabled);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setFiltersChildEvents(QGraphicsItem* this_ptr, bool enabled);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setFlag_flag(QGraphicsItem* this_ptr, QGraphicsItem::GraphicsItemFlag flag);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setFlag_flag_enabled(QGraphicsItem* this_ptr, QGraphicsItem::GraphicsItemFlag flag, bool enabled);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setFlags(QGraphicsItem* this_ptr, unsigned int flags);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setFocusProxy(QGraphicsItem* this_ptr, QGraphicsItem* item);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setFocus_focusReason(QGraphicsItem* this_ptr, const Qt::FocusReason* focusReason);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setFocus_no_args(QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setGraphicsEffect(QGraphicsItem* this_ptr, QGraphicsEffect* effect);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setGroup(QGraphicsItem* this_ptr, QGraphicsItemGroup* group);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setHandlesChildEvents(QGraphicsItem* this_ptr, bool enabled);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setMatrix_matrix(QGraphicsItem* this_ptr, const QMatrix* matrix);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setMatrix_matrix_combine(QGraphicsItem* this_ptr, const QMatrix* matrix, bool combine);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setOpacity(QGraphicsItem* this_ptr, double opacity);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setPanelModality(QGraphicsItem* this_ptr, QGraphicsItem::PanelModality panelModality);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setParentItem(QGraphicsItem* this_ptr, QGraphicsItem* parent);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setPos_pos(QGraphicsItem* this_ptr, const QPointF* pos);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setPos_x_y(QGraphicsItem* this_ptr, double x, double y);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setRotation(QGraphicsItem* this_ptr, double angle);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setScale(QGraphicsItem* this_ptr, double scale);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setSelected(QGraphicsItem* this_ptr, bool selected);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setToolTip(QGraphicsItem* this_ptr, const QString* toolTip);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setTransformOriginPoint_ax_ay(QGraphicsItem* this_ptr, double ax, double ay);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setTransformOriginPoint_origin(QGraphicsItem* this_ptr, const QPointF* origin);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setTransform_matrix(QGraphicsItem* this_ptr, const QTransform* matrix);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setTransform_matrix_combine(QGraphicsItem* this_ptr, const QTransform* matrix, bool combine);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setTransformations(QGraphicsItem* this_ptr, const QList< QGraphicsTransform* >* transformations);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setVisible(QGraphicsItem* this_ptr, bool visible);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setX(QGraphicsItem* this_ptr, double x);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setY(QGraphicsItem* this_ptr, double y);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_setZValue(QGraphicsItem* this_ptr, double z);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_shape_to_output(const QGraphicsItem* this_ptr, QPainterPath* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_show(QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_stackBefore(QGraphicsItem* this_ptr, const QGraphicsItem* sibling);
QT_WIDGETS_C_EXPORT QGraphicsObject* qt_widgets_c_QGraphicsItem_toGraphicsObject(QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT const QGraphicsObject* qt_widgets_c_QGraphicsItem_toGraphicsObject_const(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_toolTip_to_output(const QGraphicsItem* this_ptr, QString* output);
QT_WIDGETS_C_EXPORT QGraphicsItem* qt_widgets_c_QGraphicsItem_topLevelItem(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT QGraphicsWidget* qt_widgets_c_QGraphicsItem_topLevelWidget(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_transformOriginPoint_to_output(const QGraphicsItem* this_ptr, QPointF* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_transform_to_output(const QGraphicsItem* this_ptr, QTransform* output);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_transformations_to_output(const QGraphicsItem* this_ptr, QList< QGraphicsTransform* >* output);
QT_WIDGETS_C_EXPORT int qt_widgets_c_QGraphicsItem_type(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_ungrabKeyboard(QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_ungrabMouse(QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_unsetCursor(QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_update_no_args(QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_update_rect(QGraphicsItem* this_ptr, const QRectF* rect);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QGraphicsItem_update_x_y_width_height(QGraphicsItem* this_ptr, double x, double y, double width, double height);
QT_WIDGETS_C_EXPORT QGraphicsWidget* qt_widgets_c_QGraphicsItem_window(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT double qt_widgets_c_QGraphicsItem_x(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT double qt_widgets_c_QGraphicsItem_y(const QGraphicsItem* this_ptr);
QT_WIDGETS_C_EXPORT double qt_widgets_c_QGraphicsItem_zValue(const QGraphicsItem* this_ptr);

} // extern "C"

#endif // QT_WIDGETS_C_QGRAPHICSITEM_H
