#ifndef QT_WIDGETS_C_QSTYLEOPTIONCOMBOBOX_H
#define QT_WIDGETS_C_QSTYLEOPTIONCOMBOBOX_H

#include "qt_widgets_c_global.h"

extern "C" {

QT_WIDGETS_C_EXPORT QStyleOptionComboBox* qt_widgets_c_QStyleOptionComboBox_G_static_cast_QStyleOptionComboBox_ptr_QStyleOption(QStyleOption* ptr);
QT_WIDGETS_C_EXPORT QStyleOptionComboBox* qt_widgets_c_QStyleOptionComboBox_G_static_cast_QStyleOptionComboBox_ptr_QStyleOptionComplex(QStyleOptionComplex* ptr);
QT_WIDGETS_C_EXPORT QStyleOptionComplex* qt_widgets_c_QStyleOptionComboBox_G_static_cast_QStyleOptionComplex_ptr(QStyleOptionComboBox* ptr);
QT_WIDGETS_C_EXPORT QStyleOption* qt_widgets_c_QStyleOptionComboBox_G_static_cast_QStyleOption_ptr(QStyleOptionComboBox* ptr);
QT_WIDGETS_C_EXPORT const QIcon* qt_widgets_c_QStyleOptionComboBox_currentIcon(const QStyleOptionComboBox* this_ptr);
QT_WIDGETS_C_EXPORT QIcon* qt_widgets_c_QStyleOptionComboBox_currentIcon_mut(QStyleOptionComboBox* this_ptr);
QT_WIDGETS_C_EXPORT const QString* qt_widgets_c_QStyleOptionComboBox_currentText(const QStyleOptionComboBox* this_ptr);
QT_WIDGETS_C_EXPORT QString* qt_widgets_c_QStyleOptionComboBox_currentText_mut(QStyleOptionComboBox* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QStyleOptionComboBox_delete(QStyleOptionComboBox* this_ptr);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QStyleOptionComboBox_editable(const QStyleOptionComboBox* this_ptr);
QT_WIDGETS_C_EXPORT bool qt_widgets_c_QStyleOptionComboBox_frame(const QStyleOptionComboBox* this_ptr);
QT_WIDGETS_C_EXPORT const QSize* qt_widgets_c_QStyleOptionComboBox_iconSize(const QStyleOptionComboBox* this_ptr);
QT_WIDGETS_C_EXPORT QSize* qt_widgets_c_QStyleOptionComboBox_iconSize_mut(QStyleOptionComboBox* this_ptr);
QT_WIDGETS_C_EXPORT QStyleOptionComboBox* qt_widgets_c_QStyleOptionComboBox_new_no_args();
QT_WIDGETS_C_EXPORT QStyleOptionComboBox* qt_widgets_c_QStyleOptionComboBox_new_other(const QStyleOptionComboBox* other);
QT_WIDGETS_C_EXPORT const QRect* qt_widgets_c_QStyleOptionComboBox_popupRect(const QStyleOptionComboBox* this_ptr);
QT_WIDGETS_C_EXPORT QRect* qt_widgets_c_QStyleOptionComboBox_popupRect_mut(QStyleOptionComboBox* this_ptr);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QStyleOptionComboBox_set_currentIcon(QStyleOptionComboBox* this_ptr, const QIcon* value);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QStyleOptionComboBox_set_currentText(QStyleOptionComboBox* this_ptr, const QString* value);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QStyleOptionComboBox_set_editable(QStyleOptionComboBox* this_ptr, bool value);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QStyleOptionComboBox_set_frame(QStyleOptionComboBox* this_ptr, bool value);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QStyleOptionComboBox_set_iconSize(QStyleOptionComboBox* this_ptr, const QSize* value);
QT_WIDGETS_C_EXPORT void qt_widgets_c_QStyleOptionComboBox_set_popupRect(QStyleOptionComboBox* this_ptr, const QRect* value);

} // extern "C"

#endif // QT_WIDGETS_C_QSTYLEOPTIONCOMBOBOX_H
