#ifndef QT_3D_EXTRAS_C_QFORWARDRENDERER_H
#define QT_3D_EXTRAS_C_QFORWARDRENDERER_H

#include "qt_3d_extras_c_global.h"

extern "C" {

QT_3D_EXTRAS_C_EXPORT QObject* qt_3d_extras_c_QForwardRenderer_G_static_cast_QObject_ptr(Qt3DExtras::QForwardRenderer* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DCore::QNode* qt_3d_extras_c_QForwardRenderer_G_static_cast_Qt3DCore_QNode_ptr(Qt3DExtras::QForwardRenderer* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QForwardRenderer* qt_3d_extras_c_QForwardRenderer_G_static_cast_Qt3DExtras_QForwardRenderer_ptr_QObject(QObject* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QForwardRenderer* qt_3d_extras_c_QForwardRenderer_G_static_cast_Qt3DExtras_QForwardRenderer_ptr_Qt3DCore_QNode(Qt3DCore::QNode* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QForwardRenderer* qt_3d_extras_c_QForwardRenderer_G_static_cast_Qt3DExtras_QForwardRenderer_ptr_Qt3DRender_QFrameGraphNode(Qt3DRender::QFrameGraphNode* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QForwardRenderer* qt_3d_extras_c_QForwardRenderer_G_static_cast_Qt3DExtras_QForwardRenderer_ptr_Qt3DRender_QTechniqueFilter(Qt3DRender::QTechniqueFilter* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DRender::QFrameGraphNode* qt_3d_extras_c_QForwardRenderer_G_static_cast_Qt3DRender_QFrameGraphNode_ptr(Qt3DExtras::QForwardRenderer* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DRender::QTechniqueFilter* qt_3d_extras_c_QForwardRenderer_G_static_cast_Qt3DRender_QTechniqueFilter_ptr(Qt3DExtras::QForwardRenderer* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DCore::QEntity* qt_3d_extras_c_Qt3DExtras_QForwardRenderer_camera(const Qt3DExtras::QForwardRenderer* this_ptr);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QForwardRenderer_clearColor_to_output(const Qt3DExtras::QForwardRenderer* this_ptr, QColor* output);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QForwardRenderer_delete(Qt3DExtras::QForwardRenderer* this_ptr);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QForwardRenderer_externalRenderTargetSize_to_output(const Qt3DExtras::QForwardRenderer* this_ptr, QSize* output);
QT_3D_EXTRAS_C_EXPORT float qt_3d_extras_c_Qt3DExtras_QForwardRenderer_gamma(const Qt3DExtras::QForwardRenderer* this_ptr);
QT_3D_EXTRAS_C_EXPORT bool qt_3d_extras_c_Qt3DExtras_QForwardRenderer_isFrustumCullingEnabled(const Qt3DExtras::QForwardRenderer* this_ptr);
QT_3D_EXTRAS_C_EXPORT const QMetaObject* qt_3d_extras_c_Qt3DExtras_QForwardRenderer_metaObject(const Qt3DExtras::QForwardRenderer* this_ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QForwardRenderer* qt_3d_extras_c_Qt3DExtras_QForwardRenderer_new_no_args();
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QForwardRenderer* qt_3d_extras_c_Qt3DExtras_QForwardRenderer_new_parent(Qt3DCore::QNode* parent);
QT_3D_EXTRAS_C_EXPORT int qt_3d_extras_c_Qt3DExtras_QForwardRenderer_qt_metacall(Qt3DExtras::QForwardRenderer* this_ptr, const QMetaObject::Call* arg1, int arg2, void** arg3);
QT_3D_EXTRAS_C_EXPORT void* qt_3d_extras_c_Qt3DExtras_QForwardRenderer_qt_metacast(Qt3DExtras::QForwardRenderer* this_ptr, const char* arg1);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QForwardRenderer_setCamera(Qt3DExtras::QForwardRenderer* this_ptr, Qt3DCore::QEntity* camera);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QForwardRenderer_setClearColor(Qt3DExtras::QForwardRenderer* this_ptr, const QColor* clearColor);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QForwardRenderer_setExternalRenderTargetSize(Qt3DExtras::QForwardRenderer* this_ptr, const QSize* size);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QForwardRenderer_setFrustumCullingEnabled(Qt3DExtras::QForwardRenderer* this_ptr, bool enabled);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QForwardRenderer_setGamma(Qt3DExtras::QForwardRenderer* this_ptr, float gamma);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QForwardRenderer_setSurface(Qt3DExtras::QForwardRenderer* this_ptr, QObject* surface);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QForwardRenderer_setViewportRect(Qt3DExtras::QForwardRenderer* this_ptr, const QRectF* viewportRect);
QT_3D_EXTRAS_C_EXPORT QObject* qt_3d_extras_c_Qt3DExtras_QForwardRenderer_surface(const Qt3DExtras::QForwardRenderer* this_ptr);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QForwardRenderer_trUtf8_to_output(const char* s, const char* c, int n, QString* output);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QForwardRenderer_tr_to_output(const char* s, const char* c, int n, QString* output);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QForwardRenderer_viewportRect_to_output(const Qt3DExtras::QForwardRenderer* this_ptr, QRectF* output);

} // extern "C"

#endif // QT_3D_EXTRAS_C_QFORWARDRENDERER_H
