#ifndef QT_3D_EXTRAS_C_QORBITCAMERACONTROLLER_H
#define QT_3D_EXTRAS_C_QORBITCAMERACONTROLLER_H

#include "qt_3d_extras_c_global.h"

extern "C" {

QT_3D_EXTRAS_C_EXPORT QObject* qt_3d_extras_c_QOrbitCameraController_G_static_cast_QObject_ptr(Qt3DExtras::QOrbitCameraController* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DCore::QEntity* qt_3d_extras_c_QOrbitCameraController_G_static_cast_Qt3DCore_QEntity_ptr(Qt3DExtras::QOrbitCameraController* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DCore::QNode* qt_3d_extras_c_QOrbitCameraController_G_static_cast_Qt3DCore_QNode_ptr(Qt3DExtras::QOrbitCameraController* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QOrbitCameraController* qt_3d_extras_c_QOrbitCameraController_G_static_cast_Qt3DExtras_QOrbitCameraController_ptr_QObject(QObject* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QOrbitCameraController* qt_3d_extras_c_QOrbitCameraController_G_static_cast_Qt3DExtras_QOrbitCameraController_ptr_Qt3DCore_QEntity(Qt3DCore::QEntity* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QOrbitCameraController* qt_3d_extras_c_QOrbitCameraController_G_static_cast_Qt3DExtras_QOrbitCameraController_ptr_Qt3DCore_QNode(Qt3DCore::QNode* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DRender::QCamera* qt_3d_extras_c_Qt3DExtras_QOrbitCameraController_camera(const Qt3DExtras::QOrbitCameraController* this_ptr);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QOrbitCameraController_delete(Qt3DExtras::QOrbitCameraController* this_ptr);
QT_3D_EXTRAS_C_EXPORT float qt_3d_extras_c_Qt3DExtras_QOrbitCameraController_linearSpeed(const Qt3DExtras::QOrbitCameraController* this_ptr);
QT_3D_EXTRAS_C_EXPORT float qt_3d_extras_c_Qt3DExtras_QOrbitCameraController_lookSpeed(const Qt3DExtras::QOrbitCameraController* this_ptr);
QT_3D_EXTRAS_C_EXPORT const QMetaObject* qt_3d_extras_c_Qt3DExtras_QOrbitCameraController_metaObject(const Qt3DExtras::QOrbitCameraController* this_ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QOrbitCameraController* qt_3d_extras_c_Qt3DExtras_QOrbitCameraController_new_no_args();
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QOrbitCameraController* qt_3d_extras_c_Qt3DExtras_QOrbitCameraController_new_parent(Qt3DCore::QNode* parent);
QT_3D_EXTRAS_C_EXPORT int qt_3d_extras_c_Qt3DExtras_QOrbitCameraController_qt_metacall(Qt3DExtras::QOrbitCameraController* this_ptr, const QMetaObject::Call* arg1, int arg2, void** arg3);
QT_3D_EXTRAS_C_EXPORT void* qt_3d_extras_c_Qt3DExtras_QOrbitCameraController_qt_metacast(Qt3DExtras::QOrbitCameraController* this_ptr, const char* arg1);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QOrbitCameraController_setCamera(Qt3DExtras::QOrbitCameraController* this_ptr, Qt3DRender::QCamera* camera);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QOrbitCameraController_setLinearSpeed(Qt3DExtras::QOrbitCameraController* this_ptr, float linearSpeed);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QOrbitCameraController_setLookSpeed(Qt3DExtras::QOrbitCameraController* this_ptr, float lookSpeed);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QOrbitCameraController_setZoomInLimit(Qt3DExtras::QOrbitCameraController* this_ptr, float zoomInLimit);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QOrbitCameraController_trUtf8_to_output(const char* s, const char* c, int n, QString* output);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QOrbitCameraController_tr_to_output(const char* s, const char* c, int n, QString* output);
QT_3D_EXTRAS_C_EXPORT float qt_3d_extras_c_Qt3DExtras_QOrbitCameraController_zoomInLimit(const Qt3DExtras::QOrbitCameraController* this_ptr);

} // extern "C"

#endif // QT_3D_EXTRAS_C_QORBITCAMERACONTROLLER_H
