#ifndef QT_3D_EXTRAS_C_QNORMALDIFFUSESPECULARMAPMATERIAL_H
#define QT_3D_EXTRAS_C_QNORMALDIFFUSESPECULARMAPMATERIAL_H

#include "qt_3d_extras_c_global.h"

extern "C" {

QT_3D_EXTRAS_C_EXPORT QObject* qt_3d_extras_c_QNormalDiffuseSpecularMapMaterial_G_static_cast_QObject_ptr(Qt3DExtras::QNormalDiffuseSpecularMapMaterial* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DCore::QComponent* qt_3d_extras_c_QNormalDiffuseSpecularMapMaterial_G_static_cast_Qt3DCore_QComponent_ptr(Qt3DExtras::QNormalDiffuseSpecularMapMaterial* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DCore::QNode* qt_3d_extras_c_QNormalDiffuseSpecularMapMaterial_G_static_cast_Qt3DCore_QNode_ptr(Qt3DExtras::QNormalDiffuseSpecularMapMaterial* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QNormalDiffuseSpecularMapMaterial* qt_3d_extras_c_QNormalDiffuseSpecularMapMaterial_G_static_cast_Qt3DExtras_QNormalDiffuseSpecularMapMaterial_ptr_QObject(QObject* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QNormalDiffuseSpecularMapMaterial* qt_3d_extras_c_QNormalDiffuseSpecularMapMaterial_G_static_cast_Qt3DExtras_QNormalDiffuseSpecularMapMaterial_ptr_Qt3DCore_QComponent(Qt3DCore::QComponent* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QNormalDiffuseSpecularMapMaterial* qt_3d_extras_c_QNormalDiffuseSpecularMapMaterial_G_static_cast_Qt3DExtras_QNormalDiffuseSpecularMapMaterial_ptr_Qt3DCore_QNode(Qt3DCore::QNode* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QNormalDiffuseSpecularMapMaterial* qt_3d_extras_c_QNormalDiffuseSpecularMapMaterial_G_static_cast_Qt3DExtras_QNormalDiffuseSpecularMapMaterial_ptr_Qt3DRender_QMaterial(Qt3DRender::QMaterial* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DRender::QMaterial* qt_3d_extras_c_QNormalDiffuseSpecularMapMaterial_G_static_cast_Qt3DRender_QMaterial_ptr(Qt3DExtras::QNormalDiffuseSpecularMapMaterial* ptr);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QNormalDiffuseSpecularMapMaterial_ambient_to_output(const Qt3DExtras::QNormalDiffuseSpecularMapMaterial* this_ptr, QColor* output);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QNormalDiffuseSpecularMapMaterial_delete(Qt3DExtras::QNormalDiffuseSpecularMapMaterial* this_ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DRender::QAbstractTexture* qt_3d_extras_c_Qt3DExtras_QNormalDiffuseSpecularMapMaterial_diffuse(const Qt3DExtras::QNormalDiffuseSpecularMapMaterial* this_ptr);
QT_3D_EXTRAS_C_EXPORT const QMetaObject* qt_3d_extras_c_Qt3DExtras_QNormalDiffuseSpecularMapMaterial_metaObject(const Qt3DExtras::QNormalDiffuseSpecularMapMaterial* this_ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QNormalDiffuseSpecularMapMaterial* qt_3d_extras_c_Qt3DExtras_QNormalDiffuseSpecularMapMaterial_new_no_args();
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QNormalDiffuseSpecularMapMaterial* qt_3d_extras_c_Qt3DExtras_QNormalDiffuseSpecularMapMaterial_new_parent(Qt3DCore::QNode* parent);
QT_3D_EXTRAS_C_EXPORT Qt3DRender::QAbstractTexture* qt_3d_extras_c_Qt3DExtras_QNormalDiffuseSpecularMapMaterial_normal(const Qt3DExtras::QNormalDiffuseSpecularMapMaterial* this_ptr);
QT_3D_EXTRAS_C_EXPORT int qt_3d_extras_c_Qt3DExtras_QNormalDiffuseSpecularMapMaterial_qt_metacall(Qt3DExtras::QNormalDiffuseSpecularMapMaterial* this_ptr, const QMetaObject::Call* arg1, int arg2, void** arg3);
QT_3D_EXTRAS_C_EXPORT void* qt_3d_extras_c_Qt3DExtras_QNormalDiffuseSpecularMapMaterial_qt_metacast(Qt3DExtras::QNormalDiffuseSpecularMapMaterial* this_ptr, const char* arg1);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QNormalDiffuseSpecularMapMaterial_setAmbient(Qt3DExtras::QNormalDiffuseSpecularMapMaterial* this_ptr, const QColor* ambient);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QNormalDiffuseSpecularMapMaterial_setDiffuse(Qt3DExtras::QNormalDiffuseSpecularMapMaterial* this_ptr, Qt3DRender::QAbstractTexture* diffuse);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QNormalDiffuseSpecularMapMaterial_setNormal(Qt3DExtras::QNormalDiffuseSpecularMapMaterial* this_ptr, Qt3DRender::QAbstractTexture* normal);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QNormalDiffuseSpecularMapMaterial_setShininess(Qt3DExtras::QNormalDiffuseSpecularMapMaterial* this_ptr, float shininess);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QNormalDiffuseSpecularMapMaterial_setSpecular(Qt3DExtras::QNormalDiffuseSpecularMapMaterial* this_ptr, Qt3DRender::QAbstractTexture* specular);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QNormalDiffuseSpecularMapMaterial_setTextureScale(Qt3DExtras::QNormalDiffuseSpecularMapMaterial* this_ptr, float textureScale);
QT_3D_EXTRAS_C_EXPORT float qt_3d_extras_c_Qt3DExtras_QNormalDiffuseSpecularMapMaterial_shininess(const Qt3DExtras::QNormalDiffuseSpecularMapMaterial* this_ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DRender::QAbstractTexture* qt_3d_extras_c_Qt3DExtras_QNormalDiffuseSpecularMapMaterial_specular(const Qt3DExtras::QNormalDiffuseSpecularMapMaterial* this_ptr);
QT_3D_EXTRAS_C_EXPORT float qt_3d_extras_c_Qt3DExtras_QNormalDiffuseSpecularMapMaterial_textureScale(const Qt3DExtras::QNormalDiffuseSpecularMapMaterial* this_ptr);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QNormalDiffuseSpecularMapMaterial_trUtf8_to_output(const char* s, const char* c, int n, QString* output);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QNormalDiffuseSpecularMapMaterial_tr_to_output(const char* s, const char* c, int n, QString* output);

} // extern "C"

#endif // QT_3D_EXTRAS_C_QNORMALDIFFUSESPECULARMAPMATERIAL_H
