#ifndef QT_3D_EXTRAS_C_QCYLINDERGEOMETRY_H
#define QT_3D_EXTRAS_C_QCYLINDERGEOMETRY_H

#include "qt_3d_extras_c_global.h"

extern "C" {

QT_3D_EXTRAS_C_EXPORT QObject* qt_3d_extras_c_QCylinderGeometry_G_static_cast_QObject_ptr(Qt3DExtras::QCylinderGeometry* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DCore::QNode* qt_3d_extras_c_QCylinderGeometry_G_static_cast_Qt3DCore_QNode_ptr(Qt3DExtras::QCylinderGeometry* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QCylinderGeometry* qt_3d_extras_c_QCylinderGeometry_G_static_cast_Qt3DExtras_QCylinderGeometry_ptr_QObject(QObject* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QCylinderGeometry* qt_3d_extras_c_QCylinderGeometry_G_static_cast_Qt3DExtras_QCylinderGeometry_ptr_Qt3DCore_QNode(Qt3DCore::QNode* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QCylinderGeometry* qt_3d_extras_c_QCylinderGeometry_G_static_cast_Qt3DExtras_QCylinderGeometry_ptr_Qt3DRender_QGeometry(Qt3DRender::QGeometry* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DRender::QGeometry* qt_3d_extras_c_QCylinderGeometry_G_static_cast_Qt3DRender_QGeometry_ptr(Qt3DExtras::QCylinderGeometry* ptr);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QCylinderGeometry_delete(Qt3DExtras::QCylinderGeometry* this_ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DRender::QAttribute* qt_3d_extras_c_Qt3DExtras_QCylinderGeometry_indexAttribute(const Qt3DExtras::QCylinderGeometry* this_ptr);
QT_3D_EXTRAS_C_EXPORT float qt_3d_extras_c_Qt3DExtras_QCylinderGeometry_length(const Qt3DExtras::QCylinderGeometry* this_ptr);
QT_3D_EXTRAS_C_EXPORT const QMetaObject* qt_3d_extras_c_Qt3DExtras_QCylinderGeometry_metaObject(const Qt3DExtras::QCylinderGeometry* this_ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QCylinderGeometry* qt_3d_extras_c_Qt3DExtras_QCylinderGeometry_new_no_args();
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QCylinderGeometry* qt_3d_extras_c_Qt3DExtras_QCylinderGeometry_new_parent(Qt3DCore::QNode* parent);
QT_3D_EXTRAS_C_EXPORT Qt3DRender::QAttribute* qt_3d_extras_c_Qt3DExtras_QCylinderGeometry_normalAttribute(const Qt3DExtras::QCylinderGeometry* this_ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DRender::QAttribute* qt_3d_extras_c_Qt3DExtras_QCylinderGeometry_positionAttribute(const Qt3DExtras::QCylinderGeometry* this_ptr);
QT_3D_EXTRAS_C_EXPORT int qt_3d_extras_c_Qt3DExtras_QCylinderGeometry_qt_metacall(Qt3DExtras::QCylinderGeometry* this_ptr, const QMetaObject::Call* arg1, int arg2, void** arg3);
QT_3D_EXTRAS_C_EXPORT void* qt_3d_extras_c_Qt3DExtras_QCylinderGeometry_qt_metacast(Qt3DExtras::QCylinderGeometry* this_ptr, const char* arg1);
QT_3D_EXTRAS_C_EXPORT float qt_3d_extras_c_Qt3DExtras_QCylinderGeometry_radius(const Qt3DExtras::QCylinderGeometry* this_ptr);
QT_3D_EXTRAS_C_EXPORT int qt_3d_extras_c_Qt3DExtras_QCylinderGeometry_rings(const Qt3DExtras::QCylinderGeometry* this_ptr);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QCylinderGeometry_setLength(Qt3DExtras::QCylinderGeometry* this_ptr, float length);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QCylinderGeometry_setRadius(Qt3DExtras::QCylinderGeometry* this_ptr, float radius);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QCylinderGeometry_setRings(Qt3DExtras::QCylinderGeometry* this_ptr, int rings);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QCylinderGeometry_setSlices(Qt3DExtras::QCylinderGeometry* this_ptr, int slices);
QT_3D_EXTRAS_C_EXPORT int qt_3d_extras_c_Qt3DExtras_QCylinderGeometry_slices(const Qt3DExtras::QCylinderGeometry* this_ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DRender::QAttribute* qt_3d_extras_c_Qt3DExtras_QCylinderGeometry_texCoordAttribute(const Qt3DExtras::QCylinderGeometry* this_ptr);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QCylinderGeometry_trUtf8_to_output(const char* s, const char* c, int n, QString* output);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QCylinderGeometry_tr_to_output(const char* s, const char* c, int n, QString* output);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QCylinderGeometry_updateIndices(Qt3DExtras::QCylinderGeometry* this_ptr);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QCylinderGeometry_updateVertices(Qt3DExtras::QCylinderGeometry* this_ptr);

} // extern "C"

#endif // QT_3D_EXTRAS_C_QCYLINDERGEOMETRY_H
