#ifndef QT_3D_EXTRAS_C_QPHONGALPHAMATERIAL_H
#define QT_3D_EXTRAS_C_QPHONGALPHAMATERIAL_H

#include "qt_3d_extras_c_global.h"

extern "C" {

QT_3D_EXTRAS_C_EXPORT QObject* qt_3d_extras_c_QPhongAlphaMaterial_G_static_cast_QObject_ptr(Qt3DExtras::QPhongAlphaMaterial* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DCore::QComponent* qt_3d_extras_c_QPhongAlphaMaterial_G_static_cast_Qt3DCore_QComponent_ptr(Qt3DExtras::QPhongAlphaMaterial* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DCore::QNode* qt_3d_extras_c_QPhongAlphaMaterial_G_static_cast_Qt3DCore_QNode_ptr(Qt3DExtras::QPhongAlphaMaterial* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QPhongAlphaMaterial* qt_3d_extras_c_QPhongAlphaMaterial_G_static_cast_Qt3DExtras_QPhongAlphaMaterial_ptr_QObject(QObject* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QPhongAlphaMaterial* qt_3d_extras_c_QPhongAlphaMaterial_G_static_cast_Qt3DExtras_QPhongAlphaMaterial_ptr_Qt3DCore_QComponent(Qt3DCore::QComponent* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QPhongAlphaMaterial* qt_3d_extras_c_QPhongAlphaMaterial_G_static_cast_Qt3DExtras_QPhongAlphaMaterial_ptr_Qt3DCore_QNode(Qt3DCore::QNode* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QPhongAlphaMaterial* qt_3d_extras_c_QPhongAlphaMaterial_G_static_cast_Qt3DExtras_QPhongAlphaMaterial_ptr_Qt3DRender_QMaterial(Qt3DRender::QMaterial* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DRender::QMaterial* qt_3d_extras_c_QPhongAlphaMaterial_G_static_cast_Qt3DRender_QMaterial_ptr(Qt3DExtras::QPhongAlphaMaterial* ptr);
QT_3D_EXTRAS_C_EXPORT float qt_3d_extras_c_Qt3DExtras_QPhongAlphaMaterial_alpha(const Qt3DExtras::QPhongAlphaMaterial* this_ptr);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QPhongAlphaMaterial_ambient_to_output(const Qt3DExtras::QPhongAlphaMaterial* this_ptr, QColor* output);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QPhongAlphaMaterial_delete(Qt3DExtras::QPhongAlphaMaterial* this_ptr);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QPhongAlphaMaterial_diffuse_to_output(const Qt3DExtras::QPhongAlphaMaterial* this_ptr, QColor* output);
QT_3D_EXTRAS_C_EXPORT const QMetaObject* qt_3d_extras_c_Qt3DExtras_QPhongAlphaMaterial_metaObject(const Qt3DExtras::QPhongAlphaMaterial* this_ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QPhongAlphaMaterial* qt_3d_extras_c_Qt3DExtras_QPhongAlphaMaterial_new_no_args();
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QPhongAlphaMaterial* qt_3d_extras_c_Qt3DExtras_QPhongAlphaMaterial_new_parent(Qt3DCore::QNode* parent);
QT_3D_EXTRAS_C_EXPORT int qt_3d_extras_c_Qt3DExtras_QPhongAlphaMaterial_qt_metacall(Qt3DExtras::QPhongAlphaMaterial* this_ptr, const QMetaObject::Call* arg1, int arg2, void** arg3);
QT_3D_EXTRAS_C_EXPORT void* qt_3d_extras_c_Qt3DExtras_QPhongAlphaMaterial_qt_metacast(Qt3DExtras::QPhongAlphaMaterial* this_ptr, const char* arg1);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QPhongAlphaMaterial_setAlpha(Qt3DExtras::QPhongAlphaMaterial* this_ptr, float alpha);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QPhongAlphaMaterial_setAmbient(Qt3DExtras::QPhongAlphaMaterial* this_ptr, const QColor* ambient);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QPhongAlphaMaterial_setBlendFunctionArg(Qt3DExtras::QPhongAlphaMaterial* this_ptr, const Qt3DRender::QBlendEquation::BlendFunction* blendFunctionArg);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QPhongAlphaMaterial_setDestinationAlphaArg(Qt3DExtras::QPhongAlphaMaterial* this_ptr, const Qt3DRender::QBlendEquationArguments::Blending* destinationAlphaArg);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QPhongAlphaMaterial_setDestinationRgbArg(Qt3DExtras::QPhongAlphaMaterial* this_ptr, const Qt3DRender::QBlendEquationArguments::Blending* destinationRgbArg);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QPhongAlphaMaterial_setDiffuse(Qt3DExtras::QPhongAlphaMaterial* this_ptr, const QColor* diffuse);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QPhongAlphaMaterial_setShininess(Qt3DExtras::QPhongAlphaMaterial* this_ptr, float shininess);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QPhongAlphaMaterial_setSourceAlphaArg(Qt3DExtras::QPhongAlphaMaterial* this_ptr, const Qt3DRender::QBlendEquationArguments::Blending* sourceAlphaArg);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QPhongAlphaMaterial_setSourceRgbArg(Qt3DExtras::QPhongAlphaMaterial* this_ptr, const Qt3DRender::QBlendEquationArguments::Blending* sourceRgbArg);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QPhongAlphaMaterial_setSpecular(Qt3DExtras::QPhongAlphaMaterial* this_ptr, const QColor* specular);
QT_3D_EXTRAS_C_EXPORT float qt_3d_extras_c_Qt3DExtras_QPhongAlphaMaterial_shininess(const Qt3DExtras::QPhongAlphaMaterial* this_ptr);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QPhongAlphaMaterial_specular_to_output(const Qt3DExtras::QPhongAlphaMaterial* this_ptr, QColor* output);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QPhongAlphaMaterial_trUtf8_to_output(const char* s, const char* c, int n, QString* output);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QPhongAlphaMaterial_tr_to_output(const char* s, const char* c, int n, QString* output);

} // extern "C"

#endif // QT_3D_EXTRAS_C_QPHONGALPHAMATERIAL_H
