#ifndef QT_3D_EXTRAS_C_QEXTRUDEDTEXTGEOMETRY_H
#define QT_3D_EXTRAS_C_QEXTRUDEDTEXTGEOMETRY_H

#include "qt_3d_extras_c_global.h"

extern "C" {

QT_3D_EXTRAS_C_EXPORT QObject* qt_3d_extras_c_QExtrudedTextGeometry_G_static_cast_QObject_ptr(Qt3DExtras::QExtrudedTextGeometry* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DCore::QNode* qt_3d_extras_c_QExtrudedTextGeometry_G_static_cast_Qt3DCore_QNode_ptr(Qt3DExtras::QExtrudedTextGeometry* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QExtrudedTextGeometry* qt_3d_extras_c_QExtrudedTextGeometry_G_static_cast_Qt3DExtras_QExtrudedTextGeometry_ptr_QObject(QObject* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QExtrudedTextGeometry* qt_3d_extras_c_QExtrudedTextGeometry_G_static_cast_Qt3DExtras_QExtrudedTextGeometry_ptr_Qt3DCore_QNode(Qt3DCore::QNode* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QExtrudedTextGeometry* qt_3d_extras_c_QExtrudedTextGeometry_G_static_cast_Qt3DExtras_QExtrudedTextGeometry_ptr_Qt3DRender_QGeometry(Qt3DRender::QGeometry* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DRender::QGeometry* qt_3d_extras_c_QExtrudedTextGeometry_G_static_cast_Qt3DRender_QGeometry_ptr(Qt3DExtras::QExtrudedTextGeometry* ptr);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QExtrudedTextGeometry_delete(Qt3DExtras::QExtrudedTextGeometry* this_ptr);
QT_3D_EXTRAS_C_EXPORT float qt_3d_extras_c_Qt3DExtras_QExtrudedTextGeometry_extrusionLength(const Qt3DExtras::QExtrudedTextGeometry* this_ptr);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QExtrudedTextGeometry_font_to_output(const Qt3DExtras::QExtrudedTextGeometry* this_ptr, QFont* output);
QT_3D_EXTRAS_C_EXPORT Qt3DRender::QAttribute* qt_3d_extras_c_Qt3DExtras_QExtrudedTextGeometry_indexAttribute(const Qt3DExtras::QExtrudedTextGeometry* this_ptr);
QT_3D_EXTRAS_C_EXPORT const QMetaObject* qt_3d_extras_c_Qt3DExtras_QExtrudedTextGeometry_metaObject(const Qt3DExtras::QExtrudedTextGeometry* this_ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QExtrudedTextGeometry* qt_3d_extras_c_Qt3DExtras_QExtrudedTextGeometry_new_no_args();
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QExtrudedTextGeometry* qt_3d_extras_c_Qt3DExtras_QExtrudedTextGeometry_new_parent(Qt3DCore::QNode* parent);
QT_3D_EXTRAS_C_EXPORT Qt3DRender::QAttribute* qt_3d_extras_c_Qt3DExtras_QExtrudedTextGeometry_normalAttribute(const Qt3DExtras::QExtrudedTextGeometry* this_ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DRender::QAttribute* qt_3d_extras_c_Qt3DExtras_QExtrudedTextGeometry_positionAttribute(const Qt3DExtras::QExtrudedTextGeometry* this_ptr);
QT_3D_EXTRAS_C_EXPORT int qt_3d_extras_c_Qt3DExtras_QExtrudedTextGeometry_qt_metacall(Qt3DExtras::QExtrudedTextGeometry* this_ptr, const QMetaObject::Call* arg1, int arg2, void** arg3);
QT_3D_EXTRAS_C_EXPORT void* qt_3d_extras_c_Qt3DExtras_QExtrudedTextGeometry_qt_metacast(Qt3DExtras::QExtrudedTextGeometry* this_ptr, const char* arg1);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QExtrudedTextGeometry_setDepth(Qt3DExtras::QExtrudedTextGeometry* this_ptr, float extrusionLength);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QExtrudedTextGeometry_setFont(Qt3DExtras::QExtrudedTextGeometry* this_ptr, const QFont* font);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QExtrudedTextGeometry_setText(Qt3DExtras::QExtrudedTextGeometry* this_ptr, const QString* text);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QExtrudedTextGeometry_text_to_output(const Qt3DExtras::QExtrudedTextGeometry* this_ptr, QString* output);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QExtrudedTextGeometry_trUtf8_to_output(const char* s, const char* c, int n, QString* output);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QExtrudedTextGeometry_tr_to_output(const char* s, const char* c, int n, QString* output);

} // extern "C"

#endif // QT_3D_EXTRAS_C_QEXTRUDEDTEXTGEOMETRY_H
