#ifndef QT_3D_EXTRAS_C_QTEXTUREDMETALROUGHMATERIAL_H
#define QT_3D_EXTRAS_C_QTEXTUREDMETALROUGHMATERIAL_H

#include "qt_3d_extras_c_global.h"

extern "C" {

QT_3D_EXTRAS_C_EXPORT QObject* qt_3d_extras_c_QTexturedMetalRoughMaterial_G_static_cast_QObject_ptr(Qt3DExtras::QTexturedMetalRoughMaterial* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DCore::QComponent* qt_3d_extras_c_QTexturedMetalRoughMaterial_G_static_cast_Qt3DCore_QComponent_ptr(Qt3DExtras::QTexturedMetalRoughMaterial* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DCore::QNode* qt_3d_extras_c_QTexturedMetalRoughMaterial_G_static_cast_Qt3DCore_QNode_ptr(Qt3DExtras::QTexturedMetalRoughMaterial* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QTexturedMetalRoughMaterial* qt_3d_extras_c_QTexturedMetalRoughMaterial_G_static_cast_Qt3DExtras_QTexturedMetalRoughMaterial_ptr_QObject(QObject* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QTexturedMetalRoughMaterial* qt_3d_extras_c_QTexturedMetalRoughMaterial_G_static_cast_Qt3DExtras_QTexturedMetalRoughMaterial_ptr_Qt3DCore_QComponent(Qt3DCore::QComponent* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QTexturedMetalRoughMaterial* qt_3d_extras_c_QTexturedMetalRoughMaterial_G_static_cast_Qt3DExtras_QTexturedMetalRoughMaterial_ptr_Qt3DCore_QNode(Qt3DCore::QNode* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QTexturedMetalRoughMaterial* qt_3d_extras_c_QTexturedMetalRoughMaterial_G_static_cast_Qt3DExtras_QTexturedMetalRoughMaterial_ptr_Qt3DRender_QMaterial(Qt3DRender::QMaterial* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DRender::QMaterial* qt_3d_extras_c_QTexturedMetalRoughMaterial_G_static_cast_Qt3DRender_QMaterial_ptr(Qt3DExtras::QTexturedMetalRoughMaterial* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DRender::QAbstractTexture* qt_3d_extras_c_Qt3DExtras_QTexturedMetalRoughMaterial_ambientOcclusion(const Qt3DExtras::QTexturedMetalRoughMaterial* this_ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DRender::QAbstractTexture* qt_3d_extras_c_Qt3DExtras_QTexturedMetalRoughMaterial_baseColor(const Qt3DExtras::QTexturedMetalRoughMaterial* this_ptr);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QTexturedMetalRoughMaterial_delete(Qt3DExtras::QTexturedMetalRoughMaterial* this_ptr);
QT_3D_EXTRAS_C_EXPORT const QMetaObject* qt_3d_extras_c_Qt3DExtras_QTexturedMetalRoughMaterial_metaObject(const Qt3DExtras::QTexturedMetalRoughMaterial* this_ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DRender::QAbstractTexture* qt_3d_extras_c_Qt3DExtras_QTexturedMetalRoughMaterial_metalness(const Qt3DExtras::QTexturedMetalRoughMaterial* this_ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QTexturedMetalRoughMaterial* qt_3d_extras_c_Qt3DExtras_QTexturedMetalRoughMaterial_new_no_args();
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QTexturedMetalRoughMaterial* qt_3d_extras_c_Qt3DExtras_QTexturedMetalRoughMaterial_new_parent(Qt3DCore::QNode* parent);
QT_3D_EXTRAS_C_EXPORT Qt3DRender::QAbstractTexture* qt_3d_extras_c_Qt3DExtras_QTexturedMetalRoughMaterial_normal(const Qt3DExtras::QTexturedMetalRoughMaterial* this_ptr);
QT_3D_EXTRAS_C_EXPORT int qt_3d_extras_c_Qt3DExtras_QTexturedMetalRoughMaterial_qt_metacall(Qt3DExtras::QTexturedMetalRoughMaterial* this_ptr, const QMetaObject::Call* arg1, int arg2, void** arg3);
QT_3D_EXTRAS_C_EXPORT void* qt_3d_extras_c_Qt3DExtras_QTexturedMetalRoughMaterial_qt_metacast(Qt3DExtras::QTexturedMetalRoughMaterial* this_ptr, const char* arg1);
QT_3D_EXTRAS_C_EXPORT Qt3DRender::QAbstractTexture* qt_3d_extras_c_Qt3DExtras_QTexturedMetalRoughMaterial_roughness(const Qt3DExtras::QTexturedMetalRoughMaterial* this_ptr);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QTexturedMetalRoughMaterial_setAmbientOcclusion(Qt3DExtras::QTexturedMetalRoughMaterial* this_ptr, Qt3DRender::QAbstractTexture* ambientOcclusion);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QTexturedMetalRoughMaterial_setBaseColor(Qt3DExtras::QTexturedMetalRoughMaterial* this_ptr, Qt3DRender::QAbstractTexture* baseColor);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QTexturedMetalRoughMaterial_setMetalness(Qt3DExtras::QTexturedMetalRoughMaterial* this_ptr, Qt3DRender::QAbstractTexture* metalness);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QTexturedMetalRoughMaterial_setNormal(Qt3DExtras::QTexturedMetalRoughMaterial* this_ptr, Qt3DRender::QAbstractTexture* normal);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QTexturedMetalRoughMaterial_setRoughness(Qt3DExtras::QTexturedMetalRoughMaterial* this_ptr, Qt3DRender::QAbstractTexture* roughness);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QTexturedMetalRoughMaterial_trUtf8_to_output(const char* s, const char* c, int n, QString* output);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QTexturedMetalRoughMaterial_tr_to_output(const char* s, const char* c, int n, QString* output);

} // extern "C"

#endif // QT_3D_EXTRAS_C_QTEXTUREDMETALROUGHMATERIAL_H
