#ifndef QT_3D_EXTRAS_C_QNORMALDIFFUSEMAPALPHAMATERIAL_H
#define QT_3D_EXTRAS_C_QNORMALDIFFUSEMAPALPHAMATERIAL_H

#include "qt_3d_extras_c_global.h"

extern "C" {

QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QNormalDiffuseMapAlphaMaterial* qt_3d_extras_c_QNormalDiffuseMapAlphaMaterial_G_dynamic_cast_Qt3DExtras_QNormalDiffuseMapAlphaMaterial_ptr(Qt3DExtras::QNormalDiffuseMapMaterial* ptr);
QT_3D_EXTRAS_C_EXPORT QObject* qt_3d_extras_c_QNormalDiffuseMapAlphaMaterial_G_static_cast_QObject_ptr(Qt3DExtras::QNormalDiffuseMapAlphaMaterial* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DCore::QComponent* qt_3d_extras_c_QNormalDiffuseMapAlphaMaterial_G_static_cast_Qt3DCore_QComponent_ptr(Qt3DExtras::QNormalDiffuseMapAlphaMaterial* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DCore::QNode* qt_3d_extras_c_QNormalDiffuseMapAlphaMaterial_G_static_cast_Qt3DCore_QNode_ptr(Qt3DExtras::QNormalDiffuseMapAlphaMaterial* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QNormalDiffuseMapAlphaMaterial* qt_3d_extras_c_QNormalDiffuseMapAlphaMaterial_G_static_cast_Qt3DExtras_QNormalDiffuseMapAlphaMaterial_ptr_QObject(QObject* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QNormalDiffuseMapAlphaMaterial* qt_3d_extras_c_QNormalDiffuseMapAlphaMaterial_G_static_cast_Qt3DExtras_QNormalDiffuseMapAlphaMaterial_ptr_Qt3DCore_QComponent(Qt3DCore::QComponent* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QNormalDiffuseMapAlphaMaterial* qt_3d_extras_c_QNormalDiffuseMapAlphaMaterial_G_static_cast_Qt3DExtras_QNormalDiffuseMapAlphaMaterial_ptr_Qt3DCore_QNode(Qt3DCore::QNode* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QNormalDiffuseMapAlphaMaterial* qt_3d_extras_c_QNormalDiffuseMapAlphaMaterial_G_static_cast_Qt3DExtras_QNormalDiffuseMapAlphaMaterial_ptr_Qt3DExtras_QNormalDiffuseMapMaterial(Qt3DExtras::QNormalDiffuseMapMaterial* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QNormalDiffuseMapAlphaMaterial* qt_3d_extras_c_QNormalDiffuseMapAlphaMaterial_G_static_cast_Qt3DExtras_QNormalDiffuseMapAlphaMaterial_ptr_Qt3DRender_QMaterial(Qt3DRender::QMaterial* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QNormalDiffuseMapMaterial* qt_3d_extras_c_QNormalDiffuseMapAlphaMaterial_G_static_cast_Qt3DExtras_QNormalDiffuseMapMaterial_ptr(Qt3DExtras::QNormalDiffuseMapAlphaMaterial* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DRender::QMaterial* qt_3d_extras_c_QNormalDiffuseMapAlphaMaterial_G_static_cast_Qt3DRender_QMaterial_ptr(Qt3DExtras::QNormalDiffuseMapAlphaMaterial* ptr);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QNormalDiffuseMapAlphaMaterial_delete(Qt3DExtras::QNormalDiffuseMapAlphaMaterial* this_ptr);
QT_3D_EXTRAS_C_EXPORT const QMetaObject* qt_3d_extras_c_Qt3DExtras_QNormalDiffuseMapAlphaMaterial_metaObject(const Qt3DExtras::QNormalDiffuseMapAlphaMaterial* this_ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QNormalDiffuseMapAlphaMaterial* qt_3d_extras_c_Qt3DExtras_QNormalDiffuseMapAlphaMaterial_new_no_args();
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QNormalDiffuseMapAlphaMaterial* qt_3d_extras_c_Qt3DExtras_QNormalDiffuseMapAlphaMaterial_new_parent(Qt3DCore::QNode* parent);
QT_3D_EXTRAS_C_EXPORT int qt_3d_extras_c_Qt3DExtras_QNormalDiffuseMapAlphaMaterial_qt_metacall(Qt3DExtras::QNormalDiffuseMapAlphaMaterial* this_ptr, const QMetaObject::Call* arg1, int arg2, void** arg3);
QT_3D_EXTRAS_C_EXPORT void* qt_3d_extras_c_Qt3DExtras_QNormalDiffuseMapAlphaMaterial_qt_metacast(Qt3DExtras::QNormalDiffuseMapAlphaMaterial* this_ptr, const char* arg1);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QNormalDiffuseMapAlphaMaterial_trUtf8_to_output(const char* s, const char* c, int n, QString* output);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QNormalDiffuseMapAlphaMaterial_tr_to_output(const char* s, const char* c, int n, QString* output);

} // extern "C"

#endif // QT_3D_EXTRAS_C_QNORMALDIFFUSEMAPALPHAMATERIAL_H
