#ifndef QT_3D_EXTRAS_C_QFIRSTPERSONCAMERACONTROLLER_H
#define QT_3D_EXTRAS_C_QFIRSTPERSONCAMERACONTROLLER_H

#include "qt_3d_extras_c_global.h"

extern "C" {

QT_3D_EXTRAS_C_EXPORT QObject* qt_3d_extras_c_QFirstPersonCameraController_G_static_cast_QObject_ptr(Qt3DExtras::QFirstPersonCameraController* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DCore::QEntity* qt_3d_extras_c_QFirstPersonCameraController_G_static_cast_Qt3DCore_QEntity_ptr(Qt3DExtras::QFirstPersonCameraController* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DCore::QNode* qt_3d_extras_c_QFirstPersonCameraController_G_static_cast_Qt3DCore_QNode_ptr(Qt3DExtras::QFirstPersonCameraController* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QFirstPersonCameraController* qt_3d_extras_c_QFirstPersonCameraController_G_static_cast_Qt3DExtras_QFirstPersonCameraController_ptr_QObject(QObject* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QFirstPersonCameraController* qt_3d_extras_c_QFirstPersonCameraController_G_static_cast_Qt3DExtras_QFirstPersonCameraController_ptr_Qt3DCore_QEntity(Qt3DCore::QEntity* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QFirstPersonCameraController* qt_3d_extras_c_QFirstPersonCameraController_G_static_cast_Qt3DExtras_QFirstPersonCameraController_ptr_Qt3DCore_QNode(Qt3DCore::QNode* ptr);
QT_3D_EXTRAS_C_EXPORT float qt_3d_extras_c_Qt3DExtras_QFirstPersonCameraController_acceleration(const Qt3DExtras::QFirstPersonCameraController* this_ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DRender::QCamera* qt_3d_extras_c_Qt3DExtras_QFirstPersonCameraController_camera(const Qt3DExtras::QFirstPersonCameraController* this_ptr);
QT_3D_EXTRAS_C_EXPORT float qt_3d_extras_c_Qt3DExtras_QFirstPersonCameraController_deceleration(const Qt3DExtras::QFirstPersonCameraController* this_ptr);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QFirstPersonCameraController_delete(Qt3DExtras::QFirstPersonCameraController* this_ptr);
QT_3D_EXTRAS_C_EXPORT float qt_3d_extras_c_Qt3DExtras_QFirstPersonCameraController_linearSpeed(const Qt3DExtras::QFirstPersonCameraController* this_ptr);
QT_3D_EXTRAS_C_EXPORT float qt_3d_extras_c_Qt3DExtras_QFirstPersonCameraController_lookSpeed(const Qt3DExtras::QFirstPersonCameraController* this_ptr);
QT_3D_EXTRAS_C_EXPORT const QMetaObject* qt_3d_extras_c_Qt3DExtras_QFirstPersonCameraController_metaObject(const Qt3DExtras::QFirstPersonCameraController* this_ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QFirstPersonCameraController* qt_3d_extras_c_Qt3DExtras_QFirstPersonCameraController_new_no_args();
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QFirstPersonCameraController* qt_3d_extras_c_Qt3DExtras_QFirstPersonCameraController_new_parent(Qt3DCore::QNode* parent);
QT_3D_EXTRAS_C_EXPORT int qt_3d_extras_c_Qt3DExtras_QFirstPersonCameraController_qt_metacall(Qt3DExtras::QFirstPersonCameraController* this_ptr, const QMetaObject::Call* arg1, int arg2, void** arg3);
QT_3D_EXTRAS_C_EXPORT void* qt_3d_extras_c_Qt3DExtras_QFirstPersonCameraController_qt_metacast(Qt3DExtras::QFirstPersonCameraController* this_ptr, const char* arg1);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QFirstPersonCameraController_setAcceleration(Qt3DExtras::QFirstPersonCameraController* this_ptr, float acceleration);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QFirstPersonCameraController_setCamera(Qt3DExtras::QFirstPersonCameraController* this_ptr, Qt3DRender::QCamera* camera);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QFirstPersonCameraController_setDeceleration(Qt3DExtras::QFirstPersonCameraController* this_ptr, float deceleration);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QFirstPersonCameraController_setLinearSpeed(Qt3DExtras::QFirstPersonCameraController* this_ptr, float linearSpeed);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QFirstPersonCameraController_setLookSpeed(Qt3DExtras::QFirstPersonCameraController* this_ptr, float lookSpeed);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QFirstPersonCameraController_trUtf8_to_output(const char* s, const char* c, int n, QString* output);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QFirstPersonCameraController_tr_to_output(const char* s, const char* c, int n, QString* output);

} // extern "C"

#endif // QT_3D_EXTRAS_C_QFIRSTPERSONCAMERACONTROLLER_H
