#ifndef QT_3D_EXTRAS_C_QMETALROUGHMATERIAL_H
#define QT_3D_EXTRAS_C_QMETALROUGHMATERIAL_H

#include "qt_3d_extras_c_global.h"

extern "C" {

QT_3D_EXTRAS_C_EXPORT QObject* qt_3d_extras_c_QMetalRoughMaterial_G_static_cast_QObject_ptr(Qt3DExtras::QMetalRoughMaterial* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DCore::QComponent* qt_3d_extras_c_QMetalRoughMaterial_G_static_cast_Qt3DCore_QComponent_ptr(Qt3DExtras::QMetalRoughMaterial* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DCore::QNode* qt_3d_extras_c_QMetalRoughMaterial_G_static_cast_Qt3DCore_QNode_ptr(Qt3DExtras::QMetalRoughMaterial* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QMetalRoughMaterial* qt_3d_extras_c_QMetalRoughMaterial_G_static_cast_Qt3DExtras_QMetalRoughMaterial_ptr_QObject(QObject* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QMetalRoughMaterial* qt_3d_extras_c_QMetalRoughMaterial_G_static_cast_Qt3DExtras_QMetalRoughMaterial_ptr_Qt3DCore_QComponent(Qt3DCore::QComponent* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QMetalRoughMaterial* qt_3d_extras_c_QMetalRoughMaterial_G_static_cast_Qt3DExtras_QMetalRoughMaterial_ptr_Qt3DCore_QNode(Qt3DCore::QNode* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QMetalRoughMaterial* qt_3d_extras_c_QMetalRoughMaterial_G_static_cast_Qt3DExtras_QMetalRoughMaterial_ptr_Qt3DRender_QMaterial(Qt3DRender::QMaterial* ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DRender::QMaterial* qt_3d_extras_c_QMetalRoughMaterial_G_static_cast_Qt3DRender_QMaterial_ptr(Qt3DExtras::QMetalRoughMaterial* ptr);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QMetalRoughMaterial_baseColor_to_output(const Qt3DExtras::QMetalRoughMaterial* this_ptr, QColor* output);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QMetalRoughMaterial_delete(Qt3DExtras::QMetalRoughMaterial* this_ptr);
QT_3D_EXTRAS_C_EXPORT const QMetaObject* qt_3d_extras_c_Qt3DExtras_QMetalRoughMaterial_metaObject(const Qt3DExtras::QMetalRoughMaterial* this_ptr);
QT_3D_EXTRAS_C_EXPORT float qt_3d_extras_c_Qt3DExtras_QMetalRoughMaterial_metalness(const Qt3DExtras::QMetalRoughMaterial* this_ptr);
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QMetalRoughMaterial* qt_3d_extras_c_Qt3DExtras_QMetalRoughMaterial_new_no_args();
QT_3D_EXTRAS_C_EXPORT Qt3DExtras::QMetalRoughMaterial* qt_3d_extras_c_Qt3DExtras_QMetalRoughMaterial_new_parent(Qt3DCore::QNode* parent);
QT_3D_EXTRAS_C_EXPORT int qt_3d_extras_c_Qt3DExtras_QMetalRoughMaterial_qt_metacall(Qt3DExtras::QMetalRoughMaterial* this_ptr, const QMetaObject::Call* arg1, int arg2, void** arg3);
QT_3D_EXTRAS_C_EXPORT void* qt_3d_extras_c_Qt3DExtras_QMetalRoughMaterial_qt_metacast(Qt3DExtras::QMetalRoughMaterial* this_ptr, const char* arg1);
QT_3D_EXTRAS_C_EXPORT float qt_3d_extras_c_Qt3DExtras_QMetalRoughMaterial_roughness(const Qt3DExtras::QMetalRoughMaterial* this_ptr);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QMetalRoughMaterial_setBaseColor(Qt3DExtras::QMetalRoughMaterial* this_ptr, const QColor* baseColor);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QMetalRoughMaterial_setMetalness(Qt3DExtras::QMetalRoughMaterial* this_ptr, float metalness);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QMetalRoughMaterial_setRoughness(Qt3DExtras::QMetalRoughMaterial* this_ptr, float roughness);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QMetalRoughMaterial_trUtf8_to_output(const char* s, const char* c, int n, QString* output);
QT_3D_EXTRAS_C_EXPORT void qt_3d_extras_c_Qt3DExtras_QMetalRoughMaterial_tr_to_output(const char* s, const char* c, int n, QString* output);

} // extern "C"

#endif // QT_3D_EXTRAS_C_QMETALROUGHMATERIAL_H
